### DISCUSSION TITLE
Multiple files with `spec: files` not supported in `conditions` of `kind:file`

### DISCUSSION THREAD

**Discussion by macedogm** [updatecli/updatecli#1013] [General]
Is there a reason why `spec:files > 1` isn't supported in `conditions` of `kind: file` but is supported in `targets`? See https://github.com/updatecli/updatecli/blob/1c37a46e5592eb0397bd5cfd96d95a7459da7d2f/pkg/plugins/resources/file/condition.go#L53-L58

My use case is to simplify detection of patterns, for example, instead of doing this multiple times with `kind: "dockerfile"`, one for each file:
```yaml
conditions:
  dockerfile-dapper:
    name: "Check if 'ARG GOLANG' is set in Dockerfile.dapper"
    kind: "dockerfile"
    scmid: "k3s"
    sourceid: "golang-alpine-docker-image"
    spec:
      file: "Dockerfile.dapper"
      instruction:
        keyword: "ARG"
        matcher: "GOLANG"
  dockerfile-test:
    name: "Check if 'ARG GOLANG' is set in Dockerfile.test"
    kind: "dockerfile"
    scmid: "k3s"
    sourceid: "golang-alpine-docker-image"
    spec:
      file: "Dockerfile.test"
      instruction:
        keyword: "ARG"
        matcher: "GOLANG"
```

We could simplify it with:
```yaml
conditions:
  dockerfiles:
    name: "Bump golang:alpine image version in Dockerfiles"
    kind: "file"
    scmid: "k3s"
    disablesourceinput: true
    spec:
      files:
        - "Dockerfile.dapper"
        - "Dockerfile.test"
        - "Dockerfile.manifest"
      matchpattern: 'ARG GOLANG=golang:v?\d+\.\d+\.\d+(-alpine\S+)?'
```

Because this functionality is already partially available in `kind: "file"`. Another option would be to add support to `spec: files` to `kind: "dockerfile"`, but this would require extra code. `kind: "file"` with `matchpattern` is really powerful IMO.
