### DISCUSSION TITLE
Rethink the shell expected result

### DISCUSSION THREAD

**Discussion by olblak** [updatecli/updatecli#1069] [Ideas]
I have been involved lately in different discussion about the shell resource. So I am putting here my thought looking for feedbacks.

At the moment, Updatecli shell resource return the following results

Source:
  - Success if command return code == 0
  - Error if command return code != 0 

Condition:
  - Success if command return code == 0
  - Error if command return code != 0 

Target:
 
  - Warning if command return code == 0 && output on the console
  - Success if command return code == 0 && no output on the console
  - Error if command return code != 0

While this behavior was a good idea to bootstrap the shell resource, I also need to regularly read to documentation each time I need to write a script for Updatecli
Now that the shell resource is used in many different scenarios, I start to have a better understanding of the problem

I can't find a solution that fit all my needs so I am wondering if it's not better to offer the ability to have different ways of mesure success
I propose to add a new key to define the kind of expected result

**Using file checksum**
```
targets:
  example:
    kind: shell
    spec:
      command: true
      result:
        kind: file/checksum
          spec:
           files:
            - file1.txt
            - file2.txt
            - file3.txt
```
=> If file checksum for listed files is the same before and after running the shell command then we return no changed

**Checking command return code**

```
targets:
  example:
    kind: shell
    spec:
      command: true
      result:
        kind: exitcode
        spec:
          failure: 1
          changed: 2
          success: 0
```

=> Result is defined based on command return code

**Checking if files exist**

```
targets:
  example:
    kind: shell
    spec:
      command: true
      result:
        kind: file/exist
        spec:
          files:
            - file1.txt
            - file2.txt
           - file3.txt
```
=> If some of the listed files are created before and after running the shell command then we return something changed.
If files are missing after a run then we assume an error
If the list of files already exist before the shell command then we skip

**Current behavior**
And the current mode for backward compatibility
## Current mode

```
targets:
  example:
    kind: shell
    spec:
      command: true
      result:
        kind: console/output
```

I guess we can still add result kind later based on the need.

The purpose of the result is to simplify so  we don't have to handle the different results

**Comment by olblak** [comment]
That being said, maybe I am just over engineering things :D

**Comment by olblak** [comment]
I think instead of "result" I would prefer "outcome" to express the expectaction of the shell resource

**Comment by dduportal** [comment]
I like the idea of using different exit code to ensure different outcomes. It reminds me of the [Terraform`-detailed-exitcode` flag](https://developer.hashicorp.com/terraform/cli/commands/plan#detailed-exitcode).

I can't remember exactly why I did the whole "output" stuff initially and I fear it was only "because it looked easy". 

Switching to an exit-code based behavior make sense to me:

- First version would print a "Warning depreciation" when a shell **target** would return an exit code 0 an output
- Next minor version would keep the warning but would change the behavior
- Then next minor version would change behavior

WDYT?

> Checking if files exist

and 

> Using file checksum

Both feels like over-engineered compared to a shell instruction `test -f filename.txt && exit 0 || exit 2` for instance.
I honestly do not see any added value (compared to the amount of YAML to write to specify this) for the "file exist".


----

While experimenting code changes for https://github.com/updatecli/updatecli/issues/465, I stumbled upon this behavior of the shell provider.

Updatecli has to `git add` the changed files. Removing the concept of SCM from resources to ensure that both `apply` and `diff` would have the same behavior, makes the shell target cumbersome.

I thought about a way to solve this differently: instead of asking the shell resource to determine which file was changed (e.g. the user 😅), what if updatecli could do it instead?
The idea was to use git to check the diff-ed file for all resources and let the pipeline processing to take care of it: less pain for the end user (their script would "only" take care of changing the file(s)) and less code complexity for plugins.

But this ain't a free meal to implement compared to the exit code solution you mention here.

**Reply by olblak** [reply]
I was also thinking to rely on Git but ideally I'd like continuing using Updatecli from none git repositories as well

**Comment by olblak** [comment]
Thanks a lot for your feedback.

The file checksum and file exist, are example where I envision have different kind of expected outcome to ultimately simply the scripting part.
And example is on the npm PR https://github.com/updatecli/updatecli/pull/1065

Where I have the following manifest 
```
targets:
    npm:
        name: Bump "@mdi/font" package version
        kind: json
        spec:
            file: package.json
            key: dependencies.@mdi/font
        scmid: default
        sourceid: npm
    package-lock.json:
        dependson:
            - npm
        name: Update NPM lockfile package-lock.json
        kind: shell
        spec:
            command: npm install --package-lock-only
        scmid: default
        disablesourceinput: true
```  

And I would like the shell target to detect if the package-lock.json was modified even if the file is not in a git repository
I could put all the logic in the script but I think something like 


```
targets:
    npm:
        name: Bump "@mdi/font" package version
        kind: json
        spec:
            file: package.json
            key: dependencies.@mdi/font
        scmid: default
        sourceid: npm
    package-lock.json:
        dependson:
            - npm
        name: Update NPM lockfile package-lock.json
        kind: shell
        spec:
            command: npm install --package-lock-only
            outcome:
              kind: file/checksum
              spec:
                files:
                  - "package-lock.json"
        scmid: default
        disablesourceinput: true
```

Would easily run on MacOSx/Windows/Linux assuming that everybody has npm installed
