### DISCUSSION TITLE
Replace string in file using matchpattern spec

### DISCUSSION THREAD

**Discussion by bngameni** [updatecli/updatecli#1530] [Q&A] [answered]
Greetings,

I encountered a minor issue with matchpatterns. Specifically, I'm attempting to replace every string that starts with "^something" with other text. However, it appears that the "^" character is being treated as a regular character rather than indicating the start of a line.

Here's a snippet of what I'm trying to achieve:

```yaml
sample_change:
    name: Update string
    kind: file
    scmid: gitlab
    sourceid: sample
    spec:
      file: "main.yml"
      matchpattern: "^something_"
      replacepattern: "others_"
```

Regrettably, I'm receiving an error message stating:

`no line matched in file \"main.yml\" for pattern \"^something_\`

Oddly enough, when I use the sed command in the command line, I get the desired results:
```console
sed -i.bcp -e "s|^something_|others|g" main.yml
``` 

I'd like to note that the "^" character is recognized by Go's regexp library (re2). Have I overlooked something? I've been troubleshooting this issue since yesterday.

**Comment by dduportal** [comment]
Could you try with the following and compare result?

```yaml
sample_change:
    name: Update string
    kind: file
    scmid: gitlab
    sourceid: sample
    spec:
      file: "main.yml"
      matchpattern: |-
        ^something_
      replacepattern: "others_"
```

which indicates a literal multiline with no newline at the end (https://yaml-multiline.info/) in YAML. The goal is to remove the YAML parser from the equation

**Reply by bngameni** [reply]
Unfortunately, I have the same error..

**Reply by dduportal** [reply]
Can you share a reproduction case that we could use to reproduce and  debug ?

**Reply by bngameni** [reply]
Yeah..
Here is my updatecli config

```yaml
---
name: Use guild's role instead of the internal role

# get repository
scms:
  gitlab:
    kind: gitlab
    spec:
      url: git.example.com
      owner: "projects/internal"
      repository: "config-mgt"
      branch: main
      username: '{{ requiredEnv "GITLAB_USERNAME" }}'
      token: '{{ requiredEnv "GITLAB_TOKEN" }}'
      user: 'Delibes Bechir'
      email: 'bngameni@example.com'

# defines how to get sources information
sources:
  mysql:
    name: Get mysql latest version
    kind: githubrelease
    spec:
      owner: "geerlingguy"
      repository: ansible-role-mysql
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      username: '{{ requiredEnv "GITHUB_USERNAME" }}'
      versionFilter:
        kind: latest

  role_requirements:
    name: Requirements file
    kind: file
    scmid: gitlab
    spec:
      file: "project/roles/requirements.yml"

  role_vars:
    name: Role vars file
    kind: file
    scmid: gitlab
    spec:
      files:
        - "inventory/group_vars/apache/main.yml"

# conditions
## pouet

# defines target which need to be update if different than source
targets:
  role_src_change:
    name: Update role src
    kind: file
    sourceid: role_requirements
    scmid: gitlab
    spec:
      file: "project/roles/requirements.yml"
      matchpattern: 'git@git\.example\.com:sample/projects/ansible/apache\.git'
      # example of replacement
      replacepattern: 'https://github.com/geerlingguy/ansible-role-apache.git'

  role_version_change:
    name: Update mysql release tag
    kind: yaml
    scmid: gitlab
    sourceid: mysql
    spec:
      file: "project/roles/requirements.yml"
      key: $.roles[0].version

  role_variables_change:
    name: Update role variables
    kind: file
    scmid: gitlab
    sourceid: role_vars
    spec:
      files:
        - "inventory/group_vars/apache/main.yml"
      matchpattern: |-
        ^apache2_
      replacepattern: "apache_"

# Create gitlab/mergerequest if a target is updated
actions:
  default:
    kind: gitlab/mergerequest
    scmid: gitlab
    title: "feat(core): use guilde role instead internal role"
    target:
      - role_version_change
      - role_src_change
      - role_variables_change
```

> requirements.yml in remote repository
```yaml
---
roles:
  - name: geerlingguy.mysql
    version: 1.0.0
 
  - name: apache
    src: git@git.example.com:sample/projects/ansible/apache.git
    scm: git
    version: 1.6.4
```
> main.yml

```
---
apache2_packages:
  - apache2
  - libapache2-mod-php7.3
  - php-fpm
  - python-passlib

apache2_vhosts_user: admin
apache2_vhosts_group: admin
```


I hope this will be enough to reproduce the scenario. 
Please feel free to provide suggestions to enhance the updatecli configuration. I'd be delighted to consider your recommendations

Regards,

**Reply by bngameni** [reply]
Re:

Hello,

I trust you received my previous message. 
Were you able to replicate the scenario and carry out debugging using the information I supplied?

**Reply by olblak** [reply]
Hello @bngameni I missed your previous example, I'll have a look

**Reply by olblak** [reply]
Hi I think initially misunderstood the problem, I thought you wanted to preserver the character "^" while you want to use a valid regex which shouldn't need character escape

I tested using :

```
targets:
  default:
    kind: file
    disablesourceinput: true
    spec:
      file: /tmp/data.yaml
      matchpattern: '^apache2_'
      replacepattern: "apache_"

  role_src_change:
    name: Update role src 
    kind: file
    disablesourceinput: true
    spec:
      file: "/tmp/data.yaml"
      matchpattern: 'git@git.example.com:sample/projects/ansible/apache.git'
      # example of replacement
      replacepattern: 'https://github.com/geerlingguy/ansible-role-apache.git'
```

on 

```
apache2_
myapache2_

git@git.example.com:sample/projects/ansible/apache.git
```

And it produced 

```
TARGETS
========

role_src_change
---------------
"/tmp/data.yaml" updated with content "https://github.com/geerlingguy/ansible-role-apache.git"

```
--- /tmp/data.yaml
+++ /tmp/data.yaml
@@ -1,5 +1,5 @@
 apache2_
 myapache2_
 
-git@git.example.com:sample/projects/ansible/apache.git
+https://github.com/geerlingguy/ansible-role-apache.git
 

```

⚠ - 1 file(s) updated with "https://github.com/geerlingguy/ansible-role-apache.git":
	* /tmp/data.yaml

default
-------
"/tmp/data.yaml" updated with content "apache_"

```
--- /tmp/data.yaml
+++ /tmp/data.yaml
@@ -1,4 +1,4 @@
-apache2_
+apache_
 myapache2_
 
 https://github.com/geerlingguy/ansible-role-apache.git

```

⚠ - 1 file(s) updated with "apache_":
	* /tmp/data.yaml

=============================

REPORTS:

```

Considering the "pouet" in your comment, you seem a french speaker from the other side of the border, so feel free to drop me an email on me@olblak.com so we can schedule a quick look call.

**Reply by bngameni** [reply, marked as answer]
Hello @olblak,

```yaml
  role_variables_change:
    name: Update role variables
    kind: file
    scmid: gitlab
    sourceid: role_vars
    spec:
      files:
        - "inventory/group_vars/apache/main.yml"
      matchpattern: "(?m)^apache2_"
      replacepattern: "apache_"
    
```

We applied the (?m) pattern to achieve multiline matching, and it effectively resolved the issue.

We realized that the "^apache2" pattern was only attempting to match the first line, which caused errors on our end.

After carefully studying the golang expression, we identified the correct regular expression to use.

**Comment by olblak** [comment]
Thanks for opening the issue. 
I managed to reproduced and resolve by escaping the "^" such as 

```
targets:
  sample_change:
      name: Update string
      kind: file
      spec:
        file: "/tmp/main.yaml"
        matchpattern: \^something_
        replacepattern: "others_"
```

I don't understand why because as far as I know "^" is not a special character interpreted by YAML or Go templates

**Reply by bngameni** [reply]
On my end, I'm encountering the same error, even after escaping the "^"..
You can find the information here: [link to the discussion](https://github.com/orgs/updatecli/discussions/1530#discussioncomment-6805100).

**Comment by olblak** [comment]
Also based on your example, the way you use the sourceid will not work,. probably better to use something like 

```
ources:
  sample:
      name: Get information
      kind: shell
      spec:
        command: "echo 1.2.3"

targets:
  sample_change:
      name: Update string
      kind: file
      disablesourceinput: true
      spec:
        file: "/tmp/main.yaml"
        matchpattern: \^something_
        replacepattern: 'others_{{ source "sample" }}'
```

Where you use the dynamic function `{{ source "sample" }}`
