### DISCUSSION TITLE
Retrieve appVersion from helm chart

### DISCUSSION THREAD

**Discussion by t3mi** [updatecli/updatecli#1619] [Q&A] [answered]
Is it possible to retrieve appVersion from remote helm chart and set appVersion value of the local chart to the retrieved one?

**Comment by olblak** [comment]
I am reopening this question as it was unanswered and already closed :D

**Comment by olblak** [comment, marked as answer]
So yes it is possible to retrieve the appVersion from a remote source, they are different ways to handle that

Using the https endpoint such as 

```
---
# PRO: Single http query
# CONS: Affect by API rate limit
#
name: Using http query

sources:
  default:
    name: Use yaml over https
    kind: yaml
    spec:
      file: https://raw.githubusercontent.com/epinio/helm-charts/main/chart/epinio/Chart.yaml
      key: $.appVersion

---
# PRO: Cloned once and then read file from local store
# CON: Not efficient when interacting with large git repositories
name: Using yaml from git 
scms:
  default:
    kind: git 
    spec:
      url: https://github.com/epinio/helm-charts.git
      branch: main
sources:
  default:
    name: Use yaml over https
    kind: yaml
    scmid: default
    spec:
      file: chart/epinio/Chart.yaml
      key: $.appVersion
```

and for updating your local chart you need to specify a target with your local file
