### DISCUSSION TITLE
Update policy Feedback

### DISCUSSION THREAD

**Discussion by olblak** [updatecli/updatecli#1878] [General]
I starting this discussion to gather all ideas around Updatecli policy and to identify missing steps for moving the feature out of experimental

## Context

The updatecli policy feature, provides the ability to publish any Updatecli to an registry and then to reuse them either with command line or via  the `update-compose.yaml` such as on the [updatelci/website](https://github.com/updatecli/website/blob/master/update-compose.yaml)

examples:

* `updatecli compose diff -f update-compose.yaml --experimental`
* `updatecli diff ghcr.io/updatecli/policies/nodejs/netlify:0.3.0`
* `updatecli diff ghcr.io/updatecli/policies/nodejs/netlify:0.3.0@sha256:41c2af6a10da1f4b4b91717ebaa4659332dd3d7107919c494c71f1f618aeaad8`

The goal is to be more DRY but not having to copy/paste the same policy over and over to multiple git repository.

**Comment by mcwarman** [comment]
I've been using within in a organisation where I manage multiple terraform repos.

## Policy releases

For releasing the policies I went down a slightly different approach to [updatecli/policies](https://github.com/updatecli/policies), relying on GitHub workflows to do the lifting as oppose to shell scripts. I also added tagging and releases similar to how a helm chart repo works: `name-version`.

<details><summary>GitHub Workflow</summary>
<p>

![image](https://github.com/updatecli/updatecli/assets/7236500/62eb2cf3-1b09-4725-8614-06f9d389e772)

```yaml
name: Policy Release

on:
  push:
    branches:
      - main
    paths:
      - "updatecli/policies/**"

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  changed-policies:
    name: Get changed policies
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          json: true
          quotepath: false
          files: "updatecli/policies/**/policy.yaml"
          dir_names: true

      - name: Set changed files as output
        id: set-matrix
        run: |
          matrix="{\"directory\":${{ steps.changed-files.outputs.all_changed_files }}}"
          echo "$matrix" | jq .
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    needs:
      - changed-policies
    strategy:
      matrix: ${{ fromJSON(needs.changed-policies.outputs.matrix) }}
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup updatecli
        uses: updatecli/updatecli-action@v2

      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set policy details
        id: policy
        env:
          POLICY_DIR: ${{ matrix.directory }}
        run: |
          name=$(realpath --relative-to=./updatecli/policies "${POLICY_DIR}")
          version=$(yq .version "${POLICY_DIR}/policy.yaml")
          {
            printf "name=$name\n"
            printf "version=$version\n"
            printf "release=$name-$version\n"
          } >>"${GITHUB_OUTPUT}"

      - name: Create github release
        id: github-release
        env:
          GH_TOKEN: ${{ github.token }}
          RELEASE: ${{ steps.policy.outputs.release }}
        run: |
          git tag "${RELEASE}"
          git push origin "${RELEASE}"
          gh release create "${RELEASE}" --verify-tag --latest

      - name: Push updatecli manifest
        working-directory: ${{ matrix.directory }}
        env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
          POLICY_NAME: ${{ steps.policy.outputs.name }}
        run: |
          updatecli manifest push \
            --config updatecli.d \
            --policy policy.yaml \
            --values values.yaml \
            --tag "ghcr.io/${GITHUB_REPOSITORY_OWNER}/${GITHUB_REPOSITORY_NAME}/${POLICY_NAME}" \
            .
```

</p>
</details> 

This is more a preference thing, but I thought i'd share the different approach.

I do think providing a standard approach (possibly a template/documentation similar to `scoop` bucket  ([Creating your own bucket](https://github.com/ScoopInstaller/Scoop/wiki/Buckets#creating-your-own-bucket)) and `brew` tap ([How to Create and Maintain a Tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap))) for policy repository bootstrapping would be helpful.

## `Policy.yaml` vs `policy.yaml`

Also for whatever reason I wasn't a fan `Policy.yaml` and have been using `policy.yaml` as it didn't make sense to me why the case had to be different, with most other things being lower, again its preference thing, but knowing the driver behind the decision might win me over. I had no issues with using a different approach.

## `latest` tag

It wasn't clear to me that the `latest` tag was _magic_ and I was using `oras tag` to create a latest tag. I only realised after debugging something, it turns out it was in the documentation and I just missed it (didn't read it). But its just worth mentioning it did throw me for a bit.

It even logs it as being ignored, but my brain didn't put two and two together for a while:

https://github.com/updatecli/updatecli/blob/794acb9fbb0ed77dfead3fee5fea73bd7728e966/pkg/core/registry/utils.go#L45

Possibly two enhancement options here:

* If latest is in the repo use it.
* If latest is in the repo the warning is clearer to the user that its not being used.

```
WARN: Ignoring tag latest ...
WARN: NOTE: When tag latest is used, updatecli will pull the lastest semantic version, and not use the latest tag.
```
