### DISCUSSION TITLE
Show changelogs of version info in the PR with file resource

### DISCUSSION THREAD

**Discussion by aaronspruit** [updatecli/updatecli#1895] [Q&A] [answered]
First of all, loving Updatecli!  I'm using it to keep various applications up to-date in a personal K8s cluster that are deployed via helm charts and/or kustomize deployments.  It provides a way better workflow than my previous attempts.

For all of my kustomize deployments, in the PR I get the nice info about the newTag being changed from version A to version B along with all the changelog info that is pulled from the github release resource.  This makes it nice to find any potentially breaking changes easily.

For the helm charts, I'm reliant on other repos and have helm install scripts with the specified version that are in a README.md file (see below).  In order to keep those up-to-date I'm using the File resource type as the target (Github release as the source, helmchart instead of dockerimage as the condition) with a match and replace pattern.  With that resource type as the Target, the only thing I get in the PR description is "1 file(s) updated with <replacePattern>: * README.md".

I'm curious as to a _better_ way of doing this that may pull in changelog info between releases for helm charts.  I'd like to _not_ host the helm charts in my personal repo (i.e. rely on the product's repo) while still maintaining traceability to what version is running in my cluster.

README.md example:
```bash
# Add Helm repo
helm repo add jetstack https://charts.jetstack.io

# Update Helm Repo
helm repo update

#Install cert-manager
helm upgrade cert-manager jetstack/cert-manager --version 1.13.3 \
    --namespace cert-manager \
    --set installCRDs=true \
    --create-namespace \
    -i --atomic
```

**Comment by olblak** [comment, marked as answer]
Thank you very much @aaronspruit for your support.
I turns out to be very challenging to have generic way to retrieve changelog information.

When I know in advance the pattern to retrieve what I am looking for, then  I use the parameter `description` in the `action` configuration ike in the following example:
 
(description is used as the first part of the pullrquest body )

``` 
actions:  
  kubernetes-marketplace:
    kind: "github/pullrequest"
    scmid: kubernetes-marketplace
    title: 'Bump Argocd Helm chart to {{ source "chart" }}'
    spec:
      description: For full list of changes please check ArtifactHub [changelog](https://artifacthub.io/packages/helm/argo/argo-cd?modal=changelog)
      usetitleforautomerge: true
      mergemethod: squash
      labels:
        - enhancement 
```
This example comes from [civo/kubernetes-marketplace](https://github.com/civo/kubernetes-marketplace/blob/master/.github/updatecli/updatecli.d/argocd.yaml#L102)

With a pullrequest example on https://github.com/civo/kubernetes-marketplace/pull/676


You could also leverage source information like 
```
description: changelog available on  https://www.updatecli.io/changelogs/updatecli/changelogs/{{ source "default" }}/
```

**Reply by aaronspruit** [reply]
Totally makes sense.  I see that in the example it's basically doing the same thing as I am - a secondary part of my question was to see if there's any different ways of doing this too.

**Comment by aaronspruit** [comment]
A bit similar to this as I ran into some issues with nginx-ingress helm chart versioning.  The helm chart is never taged as "latest" for the release, but the app is as they're both in the same repo.  They also backport older versions which means the newest helm chart listed is not the latest version. 

I now have 2 sources - the latest helm chart (no real changelog as part of the github release) and the latest actual app version (good changelog info on the release).  I then have a condition to verify if the Chart appVersion my source received is the same as the latest app version released in addition to ensuring the helm chart is available in the repo.

As part of that appVersion source lookup, I'm getting the changelog info that's on the github release information - shows in the logs.  Is there some way I can populate that into the description...in addition to the URL recommendation you give?  For example as part of my action below

```
sources:
  # Retrieve the "latest" Helm version using the Helm GitHub Release.
  helmRelease:
    name: Get latest release version
    kind: githubrelease
    spec:
      owner: kubernetes
      repository: ingress-nginx
      versionfilter:
        kind: regex
        pattern: helm-chart-(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)
    transformers:
      - trimprefix: helm-chart-
  appRelease:
    name: Get latest release version
    kind: githubrelease
    spec:
      owner: kubernetes
      repository: ingress-nginx
      typefilter:
        latest: true
    transformers:
      - trimprefix: controller-v

conditions:
  helmAppVersion:
    kind: yaml
    sourceid: appRelease
    spec:
      file: https://raw.githubusercontent.com/kubernetes/ingress-nginx/helm-chart-{{ source "helmRelease" }}/charts/ingress-nginx/Chart.yaml
      key: $.appVersion
  helmExists:
    kind: helmchart
    sourceid: helmRelease
    spec:
      url: https://kubernetes.github.io/ingress-nginx
      name: ingress-nginx

targets:
  updateReadme:
      name: Update Readme
      kind: file
      disablesourceinput: true
      scmid: default
      spec:
        file: "README.md"
        matchpattern: ingress-nginx/ingress-nginx --version (?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)
        replacepattern: ingress-nginx/ingress-nginx --version {{ source "helmRelease" }}

actions:
  checkin:
    kind: github/pullrequest
    scmid: default
    title: Bump nginx-ingress helm chart to {{ source "helmRelease" }}
    spec:
      usetitleforautomerge: true
      mergemethod: rebase
      labels:
        - "dependencies"
      description: |
        Changelog available at https://github.com/kubernetes/ingress-nginx/releases/tag/helm-chart-{{ source "helmRelease" }}
        ## would love something like the following
        ## {{ source appRelease.CHANGELOG }}
```
