### DISCUSSION TITLE
update an environment variable inside a kubernetes manifest

### DISCUSSION THREAD

**Discussion by till** [updatecli/updatecli#1949] [Q&A] [answered]
I have a Kubernetes manifest (Deployment) that looks like this:

```yaml
piVersion: apps/v1
kind: Deployment
metadata:
  name: ctr
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ctr
    spec:
      containers:
      - name: ctr-app
        image: r.example.org/ctr:local
        ports:
        - containerPort: 8080
          name: web
        env:
        - name: "ANOTHER_VARIABLE"
          value: "r.example.org/app:v1.2.3"
```

I would like to use `updatecli` to adjust the value of `ANOTHER_VARIABLE` whenever I cut a new release. Anyone have any thoughts on if this can be accomplished already? Or is this generally a bad idea? :D

**Comment by dduportal** [comment]
Hi @till , it is do-able and it makes sense.

You might want to use the `yaml` kind of resource. Something like this:

```yaml
# ... scm
# ...
# ... sources ...
target:
  updateDeploymentEnvVar:
    kind: yaml
    name: Update ANOTHER_VARIABLE env. var. in the Deployment manifest
    spec:
      file: ./path/to/deployment.yaml
      key: $.spec.template.spec.containers[0].env[0].value
```

**Reply by till** [reply]
@dduportal Thank you so much! I had totally overlooked `yaml` somehow. It works perfectly!

I guess, follow questions:

- I build a flow where I update multiple of these keys (when available), for the action, I open a pull_request, but it only mentions one of them (even though both got updated). Am I supposed to use multiple actions (e.g. 2 PRs) instead?
- Second question, I looked at the transformers for "quoting" the value. But there's nothing, I think — should I add prefix/suffix `"` instead?

**Reply by till** [reply]
I guess to answer this, my workflow failed when only one of them had chances. But I split them up and it seems to be working.

**Comment by olblak** [comment, marked as answer]
@till Another approach would be to use the yaml plugin with the yamlpath engine.

```
sources:
  default:
    kind: shell
    spec:
      command: echo "r.example.com/app:v2.0.0"

targets:
  solution-1:
    name: 'bump ANOTHER_VARIABLE to {{ source "default" }}'
    kind: yaml
    spec:
      engine: yamlpath
      file: /tmp/deployment.yaml
      key: "$.spec.template.spec.containers[*].env[?(@.name == 'ANOTHER_VARIABLE')].value"
    transformers:
      - addprefix: '"'
      - addsuffix: '"'

  solution-2:
    name: 'bump ANOTHER_VARIABLE to {{ source "default" }}'
    kind: yaml
    disablesourceinput: true
    spec:
      engine: yamlpath
      file: /tmp/deployment.yaml
      key: "$.spec.template.spec.containers[*].env[?(@.name == 'ANOTHER_VARIABLE')].value"
      value: '"{{ source "default" }}"'
```

solution 1 relies on transformers to add quotes while the second approach disable source input and use the templating syntax.
The yamlpath approach is more complex than @dduportal suggestion but it will be more robust over time as it will still work no matter how the env array is modified in your deployment file also it can be used to update multiple values in a yaml file like in the following example


```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctr 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ctr 
    spec:
      containers:
        - name: ctr-app
          image: r.example.org/ctr:local
          ports:
            - containerPort: 8080
              name: web 
          env:
            - name: "ANOTHER_VARIABLE"
              value: "\"r.example.com/app:v1.0.0\""
        - name: ctr-app2
          image: r.example.org/ctr:local
          ports:
            - containerPort: 8080
              name: web 
          env:
            - name: "ANOTHER_VARIABLE"
              value: "\"r.example.com/app:v1.2.0\""
```
