### DISCUSSION TITLE
Dynamic PR titles for argocd autodiscovery

### DISCUSSION THREAD

**Discussion by cloudoutloud** [updatecli/updatecli#2258] [Q&A] [answered]
If you're using autodiscovery for argocd https://www.updatecli.io/docs/plugins/autodiscovery/argocd/
Is there a way to include each helm chart name in the PR title, if crawler is set to groupby: individual ?

**Comment by olblak** [comment, marked as answer]
It should already be the case.

The following manifest 

```
name: Argocd Autodiscovery Example

autodiscovery:
  scmid: default
  actionid: default
  groupby: individual
  crawlers:
    argocd:

actions:
    default:
        kind: "github/pullrequest"
        spec:
            labels:
                - "dependencies"
            mergemethod: "squash"
        scmid: "default"
    
scms:
  default:
    kind: github
    spec:
      #user: redacted
      owner: kubefirst
      username: '{{ requiredEnv "GITHUB_ACTOR" }}'
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      repository: gitops-catalog
      branch: main
```

generates the manifest:
```
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+ DEPS(HELM): BUMP HELM CHART "VPA" IN ARGOCD MANIFEST "VERTICAL-POD-AUTOSCALER/COMPONENTS/VERTICAL-POD-AUTOSCALER/APPLICATION.YAML" +
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

name: 'deps(helm): bump Helm chart "vpa" in ArgoCD manifest "vertical-pod-autoscaler/components/vertical-pod-autoscaler/application.yaml"'
pipelineid: ed24c12c6875806e79217c8b9bf6467468b6576da4c436d1172c9f91784d5ee4
actions:
    default:
        kind: github/pullrequest
        spec:
            labels:
                - dependencies
            mergemethod: squash
        scmid: default
scms:
    default:
        kind: github
        spec:
            branch: main
            owner: kubefirst
            repository: gitops-catalog
            token: ghp_xxx
            username: xxx
        disabled: false
sources:
    vpa:
        name: Get latest "vpa" Helm chart version
        kind: helmchart
        spec:
            name: vpa
            url: https://charts.fairwinds.com/stable
            versionfilter:
                kind: semver
                pattern: '*'
conditions:
    vpa-name:
        name: Ensure Helm chart name vpa is specified
        kind: yaml
        spec:
            file: vertical-pod-autoscaler/components/vertical-pod-autoscaler/application.yaml
            key: $.spec.source.chart
            value: vpa
        scmid: default
        disablesourceinput: true
    vpa-repository:
        name: Ensure Helm chart repository https://charts.fairwinds.com/stable is specified
        kind: yaml
        spec:
            file: vertical-pod-autoscaler/components/vertical-pod-autoscaler/application.yaml
            key: $.spec.source.repoURL
            value: https://charts.fairwinds.com/stable
        scmid: default
        disablesourceinput: true
targets:
    vpa:
        name: 'deps(helm): bump Helm chart "vpa" in ArgoCD manifest "vertical-pod-autoscaler/components/vertical-pod-autoscaler/application.yaml"'
        kind: yaml
        spec:
            file: vertical-pod-autoscaler/components/vertical-pod-autoscaler/application.yaml
            key: $.spec.source.targetRevision
        scmid: default
        sourceid: vpa


+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+ DEPS(HELM): BUMP HELM CHART "YOURLS" IN ARGOCD MANIFEST "YOURLS/COMPONENTS/YOURLS/APPLICATION.YAML" +
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

name: 'deps(helm): bump Helm chart "yourls" in ArgoCD manifest "yourls/components/yourls/application.yaml"'
pipelineid: 7b42bc8f00ae406b39f531c93b2780088fb930676ffcd672f77bdc936c438c81
actions:
    default:
        kind: github/pullrequest
        spec:
            labels:
                - dependencies
            mergemethod: squash
        scmid: default
scms:
    default:
        kind: github
        spec:
            branch: main
            owner: kubefirst
            repository: gitops-catalog
            token: ghp_xxx
            username: xxx
        disabled: false
sources:
    yourls:
        name: Get latest "yourls" Helm chart version
        kind: helmchart
        spec:
            name: yourls
            url: https://charts.yourls.org
            versionfilter:
                kind: semver
                pattern: '*'
conditions:
    yourls-name:
        name: Ensure Helm chart name yourls is specified
        kind: yaml
        spec:
            file: yourls/components/yourls/application.yaml
            key: $.spec.source.chart
            value: yourls
        scmid: default
        disablesourceinput: true
    yourls-repository:
        name: Ensure Helm chart repository https://charts.yourls.org is specified
        kind: yaml
        spec:
            file: yourls/components/yourls/application.yaml
            key: $.spec.source.repoURL
            value: https://charts.yourls.org
        scmid: default
        disablesourceinput: true
targets:
    yourls:
        name: 'deps(helm): bump Helm chart "yourls" in ArgoCD manifest "yourls/components/yourls/application.yaml"'
        kind: yaml
        spec:
            file: yourls/components/yourls/application.yaml
            key: $.spec.source.targetRevision
        scmid: default
        sourceid: yourls
```

The generated pipelines have different `pipelineid` and manifest `name`

**Reply by cloudoutloud** [reply]
Thank you understand now

**Comment by olblak** [comment]
you just need to be sure that you action spec doesn't specify a title otherwise it will be applied to all generated manifests

```
actions:
  helm-charts:
    kind: "github"
    scmid: "website"
    spec:
      automerge: true
      description: "Prepend description"
      draft: false
      labels:
        - "dependencies"
        - "epinio"
      title: "Pull Request Title"
```
