### DISCUSSION TITLE
How to tell JSON source it's OK for a key not to be found

### DISCUSSION THREAD

**Discussion by jsok** [updatecli/updatecli#2568] [Q&A]
Hi there,

My build tool emits a JSON file containing the name and image of the release container images, and I'm trying to hook this up to updatecli to then propaget the image to a set of Dockerfiles.

My issue is that the JSON file won't always contain the specific key(s) I'm interested in, e.g. if the image wasn't built as part of that release.

I can't work out how to tell updatecli that it's fine and it should just skip the target.

For context, the JSON file is a [skaffold build output file](https://pkg.go.dev/github.com/GoogleContainerTools/skaffold/v2/cmd/skaffold/app/flags#BuildOutput), e.g.:

```json
{
  "builds": [
    {
      "imageName": "example",
      "tag": "example:latest@sha256:f3df2f00b9bbc305120f2153411bbc149ce7d9708f429c64fb072d34f2810142"
    }
  ]
}
```

My updatecli YAML looks like:

```yaml
sources:
  example:
    name: Example image
    kind: json
    spec:
      file: artifacts.json
      key: "builds.(imageName=example).tag"
targets:
  dockerfile:
    name: Dockerfile to update
    kind: dockerfile
    sourceid: example
    spec:
      file: Dockerfile
      instruction:
        keyword: "ARG"
        matcher: "EXAMPLE"
```

When the `example` key is present it all works as expected, but when it's not it gives the obvious error:

```
SOURCES
=======

example
-------
ERROR: ✗ ✗ cannot find value for path "builds.(imageName=example).tag" from file "artifacts.json"
ERROR: ✗ ✗ cannot find value for path "builds.(imageName=example).tag" from file "artifacts.json"
Pipeline "EXAMPLE.YAML" failed
Skipping due to:
        sources stage:  "✗ cannot find value for path \"builds.(imageName=example).tag\" from file \"artifacts.json\""
```

How do I just turn this into a no-op. Having updatecli fail means any other configs or targets won't get updated and makes the CI config complicated.
