### DISCUSSION TITLE
Copying an array element (which contains an object) and updating a value on that copied object

### DISCUSSION THREAD

**Discussion by jcmcken** [updatecli/updatecli#2942] [Q&A]
I'm evaluating some different tooling to automate some gitops-type operations. The specific action I need can be accomplished with ``yq`` with an expression like the following (probably not optimal, but it works):

```
select(document_index == 1).foo as $foo |
select(document_index == 1).foo |= . + [$foo[0]] |
select(document_index == 1).foo[1].bar = "baz2"
```

(In this case, the YAML file has multiple documents, which is why I'm selecting the document at index 1)

Example input YAML:

```yaml
fizz: buzz
---
foo:
- bar: baz
```

Output:

```yaml
fizz: buzz
---
foo:
- bar: baz1
- bar: baz2
```

Is there a way to accomplish something like this with ``updatecli`` ?
