### DISCUSSION TITLE
versionincrement: "patch" seems to want to bump Major/Minors also ?

### DISCUSSION THREAD

**Discussion by SnappyLarry** [updatecli/updatecli#2973] [Q&A] [answered]
### I currently have this configuration:
```
sources:
  traefik:
    kind: helmchart
    spec:
      url: "https://traefik.github.io/charts/"
      name: "traefik"
      
conditions: {}

targets:
  traefik:
    sourceid: traefik
    name: Bump traefik Chart dependencies
    kind: helmchart
    spec:
      Name: "charts/cluster-addons"
      file: "values.yaml"
      key: "$.traefik.chart.version"
      versionincrement: "patch"
```
### when i run an `updatecli diff` i get the following behavior:

target: target#traefik
--------------

**Dry Run enabled**

⚠ - change detected:
        * key "$.traefik.chart.version" should be updated from "32.1.1" to "33.0.0", in file "charts/cluster-addons/values.yaml"
change detected:
        * key "$.version" should be updated from "0.1.0" to "0.1.1", in file "charts/cluster-addons/Chart.yaml"
        

is there something i'm missing?

**Comment by olblak** [comment]
The `versioncincrement` affects the appVersion of your Helmchart.
In this case 
```
 * key "$.version" should be updated from "0.1.0" to "0.1.1", in file "charts/cluster-addons/Chart.yaml"
```

While the value in `key: "$.traefik.chart.version` is defined by your source result.
In your case, it's the "latest" version of the traefik chart.
so if you want to retrieve the latest patch version, you could do something like

```
sources:
  traefik:
    kind: helmchart
    spec:
      url: "https://traefik.github.io/charts/"
      name: "traefik"
      versionfilter:
        kind: semver
        pattern: "32.1.x"
```

**Comment by olblak** [comment, marked as answer]
If you don't know in advance "32.1.x" then you can build a more advance update scenario by:
* chaining two sources, one to retrieve the current version, and a second one to get the latest version
* you can use a transformers to modify the currently used version
* you need to specify a different sourceid

So something like this 

```
sources:
  currentTraefikVersion:
    kind: yaml
    spec:
      file: "/tmp/values.yaml"
      key: "$.traefik.chart.version"
    transformers:
      - semverinc: minor

  traefik:
    kind: helmchart
    dependson:
      - "currentTraefikVersion"
    spec:
      url: "https://traefik.github.io/charts/"
      name: "traefik"
      versionfilter:
        kind: semver
        pattern: '<{{ source "currentTraefikVersion" }}'

targets:
  traefik:
    kind: shell
    sourceid: traefik
    spec:
      command: "echo "
```
