### DISCUSSION TITLE
Is It Possible to Template a Pull Request and Commit Body?

### DISCUSSION THREAD

**Discussion by ryancurrah** [updatecli/updatecli#5428] [Q&A] [answered]
I want to get a list of commit messages between tags in git and add them to the pull request body. Here is what I have. It works but doesn't use the body I specified when creating the pull request. Leading me to believe that it might not be possible.

```
name: acme-cli

scms:
  acme-kustomize-repo:
    kind: stash
    spec:
      url: '{{ .bitbucket.url }}'
      owner: '{{ .bitbucket.acme_project }}' 
      branch: '{{ .bitbucket.branch }}'
      username: '{{ requiredEnv "BITBUCKET_USER" }}'
      token: '{{ requiredEnv "BITBUCKET_TOKEN" }}'
      email: '{{ requiredEnv "BITBUCKET_EMAIL" }}'
      user: '{{ requiredEnv "BITBUCKET_NAME" }}'
      repository: kustomize

  acme-cli-repo:
    kind: stash
    spec:
      url: '{{ .bitbucket.url }}'
      branch: '{{ .bitbucket.branch }}'
      username: '{{ requiredEnv "BITBUCKET_USER" }}'
      token: '{{ requiredEnv "BITBUCKET_TOKEN" }}'
      email: '{{ requiredEnv "BITBUCKET_EMAIL" }}'
      user: '{{ requiredEnv "BITBUCKET_NAME" }}'
      owner: go-acme
      repository: acme-cli

sources:
  acme-cli-version:
    kind: gittag
    scmid: acme-cli-repo
    spec:
      versionfilter:
        kind: regex
        pattern: '^v[0-9]+\.[0-9]+\.[0-9]+$'
        strict: true
    transformers:
      - trimprefix: v

  acme-cli-previous-version:
    kind: shell
    scmid: acme-cli-repo
    spec:
      command: |
        new="{{ source "acme-cli-version" }}"
        series=$(echo "$new" | awk -F. '{print $1"."$2}')
        git tag -l "v${series}.*" --sort=-v:refname \
          | sed -n '2p' \
          | sed 's/^v//'

  acme-cli-changelog:
    kind: shell
    scmid: acme-cli-repo
    dependson:
      - source#acme-cli-version
      - source#acme-cli-previous-version
    spec:
      command: |
        git log --pretty=format:"* %h - %s" \
          "v{{ source "acme-cli-previous-version" }}..v{{ source "acme-cli-version" }}"

targets:
  production-version-kustomize:
    name: Production Version Kustomize
    kind: yaml
    scmid: acme-kustomize-repo
    sourceid: acme-cli-version
    spec:
      file: clusters/eng-acme-argo-prod/namespaces/acme-workflows/values.yaml
      key: $.values.acmeDev.version

actions:
  pr-acme-kustomize-repo:
    kind: stash/pullrequest
    scmid: acme-kustomize-repo
    title: 'chore: bump acme-cli to v{{ source "acme-cli-version" }} ACME-3325'
    body: |
      ### acme-cli {{ source "acme-cli-version" }}

      Commits since {{ source "acme-cli-previous-version" }}:

      {{ source "acme-cli-changelog" }}

      _Generated automatically by Updatecli_
```

**Comment by olblak** [comment]
`body` is not an exposed configuration, but you can use `description`  to prepend information to your pullrequest description.

* https://www.updatecli.io/docs/plugins/actions/github/

**Comment by olblak** [comment]
Updatecli stores the state of your pipeline in pull request description using html tags.
You can see them if you try to edit the pull request description.

So it's important to only use `description` to customize the pullrequest body

**Comment by ryancurrah** [comment]
Hey thanks for the response. I dont see description as a valid field in the docs https://www.updatecli.io/docs/plugins/actions/stash/.

**Comment by olblak** [comment]
Ho sorry

I missed that you are using stash
You are missing the `spec`

Something like this should work:

```
actions:
  pr-acme-kustomize-repo:
    kind: stash/pullrequest
    scmid: acme-kustomize-repo
    title: 'chore: bump acme-cli to v{{ source "acme-cli-version" }} ACME-3325'
    spec:
      body: |
        ### acme-cli {{ source "acme-cli-version" }}

        Commits since {{ source "acme-cli-previous-version" }}:

        {{ source "acme-cli-changelog" }}

        _Generated automatically by Updatecli_
````

**Comment by olblak** [comment]
Please note that currently, Updatecli won't try to update an existing pull request.
@mcwarman recently made some improvement for bitbucket so maybe the code can be reused for stash as well

**Reply by ryancurrah** [reply]
I've noticed that, the version will change but the description will be the old one. Interesting. Maybe if I have time I can create a PR.

**Comment by ryancurrah** [comment]
Ok I am so close now. The only issue now is it does not like new lines in the source `acme-cli-changelog`.

This is the error I'm getting. 

```
ERROR: something went wrong in "target#production-version-kustomize" : update pipeline: yaml: line 13: did not find expected alphabetic or numeric character

Pipeline "acme-cli" failed
Skipping due to:
	something went wrong during target execution
```

If I append ` | tr -d '\n'` to the `acme-cli-changelog` shell it works. So the pull request message renderer does not like the new lines for some reason. Is there any work around?

```
name: acme-cli

scms:
  acme-services-repo:
    kind: stash
    spec:
      url: '{{ .bitbucket.url }}'
      owner: '{{ .bitbucket.acme_project }}' 
      branch: '{{ .bitbucket.branch }}'
      username: '{{ requiredEnv "BITBUCKET_USER" }}'
      token: '{{ requiredEnv "BITBUCKET_TOKEN" }}'
      email: '{{ requiredEnv "BITBUCKET_EMAIL" }}'
      user: '{{ requiredEnv "BITBUCKET_NAME" }}'
      repository: services

  acme-cli-repo:
    kind: stash
    spec:
      url: '{{ .bitbucket.url }}'
      branch: '{{ .bitbucket.branch }}'
      username: '{{ requiredEnv "BITBUCKET_USER" }}'
      token: '{{ requiredEnv "BITBUCKET_TOKEN" }}'
      email: '{{ requiredEnv "BITBUCKET_EMAIL" }}'
      user: '{{ requiredEnv "BITBUCKET_NAME" }}'
      owner: go-acme
      repository: acme-cli

sources:
  acme-cli-version:
    kind: gittag
    scmid: acme-cli-repo
    spec:
      versionfilter:
        kind: regex
        pattern: '^v[0-9]+\.[0-9]+\.[0-9]+$'
        strict: true
    transformers:
      - trimprefix: v

  acme-cli-previous-version:
    kind: yaml
    scmid: acme-services-repo
    spec:
      engine: yamlpath
      file: clusters/eng-acme-argo-prod/namespaces/acme-workflows/values.yaml
      key: '$.values.crwdDev.version'

  acme-cli-changelog:
    kind: shell
    scmid: acme-cli-repo
    dependson:
      - source#acme-cli-version
      - source#acme-cli-previous-version
    spec:
      command: |
        git log --pretty=format:"* %h - %s" "v{{ source "acme-cli-previous-version" }}..v{{ source "acme-cli-version" }}"

targets:
  production-version-kustomize:
    name: Production Version Kustomize
    kind: yaml
    scmid: acme-services-repo
    sourceid: acme-cli-version
    spec:
      engine: yamlpath
      file: clusters/eng-acme-argo-prod/namespaces/acme-workflows/values.yaml
      key: '$.values.crwdDev.version'

actions:
  pr-acme-services-repo:
    kind: stash/pullrequest
    scmid: acme-services-repo
    spec:
      title: 'chore: bump acme-cli to v{{ source "acme-cli-version" }} ACME-3325'
      body: |
        ### acme-cli {{ source "acme-cli-version" }}

        Commits since {{ source "acme-cli-previous-version" }}:

        {{ source "acme-cli-changelog" }}

        _Generated automatically by Updatecli_
```
