### DISCUSSION TITLE
"Freeze until" functionnality?

### DISCUSSION THREAD

**Discussion by lemeurherve** [updatecli/updatecli#698] [Ideas]
In the "nice to have" category, WDYT of a new feature allowing to "freeze" a PR until a certain version is published, like [Maven 3.8.6](https://github.com/jenkins-infra/jenkins-infra/pull/2165)?

This could for example preventing updatecli to push new commits on a PR, and/or comment on the PR to announce the desired version is finally available.

**Comment by olblak** [comment]
I am not sure to understand what you mean. 
Something I have been considering is condition on target so I could have something like, only bump target if minor version change but to be honest I couldn't a nice way to express that.

**Reply by lemeurherve** [reply]
> I am not sure to understand what you mean.

For the Maven example, the version 3.8.5 is broken, so we're waiting for the 3.8.6 one, but updatecli constantly create or bump PRs with the 3.8.5

Is it more clear?

**Reply by olblak** [reply]
Yes it is maybe a list of ignore string would be better like 

```
targets:
  default:
    name: 'Update updatecli version to {{ source "default" }}'
    kind: yaml
    ignore:
        - semver: patch
        - pattern: 3.8.5
    spec:
```

Something similar to transformers but for validating target changes.
We could have something like `ignore` and `only`

**Comment by olblak** [comment]
Probably something like 

```
targets:
  default:
    name: 'Update updatecli version to {{ source "default" }}'
    kind: yaml
    when:
        - semver: major
    spec:
      file: .github/workflows/go.yaml
      key: jobs.build.steps[6].with.version
    scmid: default
    # Required: the version of golangci-lint is required
    # and must be specified without patch version:
    # we always use the latest patch version.
    transformers:
      - findSubMatch:
          pattern: 'v(\d*)\.(\d*)'
```
