### DISCUSSION TITLE
`extractpattern` for `sources`?

### DISCUSSION THREAD

**Discussion by lemeurherve** [updatecli/updatecli#722] [Ideas]
Instead of [matchpattern + transformer.findsubmatch](https://github.com/jenkins-infra/shared-tools/blob/main/updatecli/updatecli.d/hashicorp-tools.yml#L29-L33), wouldn't it be nice to be able to combine these 2 in `extractpattern` for simple cases with only one capture group?

This:
```
sources:
  terraformHashicorpToolsVersion:
    kind: file
    spec:
      file: 'https://raw.githubusercontent.com/jenkins-infra/docker-hashicorp-tools/{{ source `dockerHashicorpToolsImageVersion` }}/Dockerfile'
      matchpattern: 'ARG TERRAFORM_VERSION=(.*)'
    transformers:
      - findsubmatch:
          pattern: 'ARG TERRAFORM_VERSION=(.*)'
          captureindex: 1
```

would become:
```
sources:
  terraformHashicorpToolsVersion:
    kind: file
    spec:
      file: 'https://raw.githubusercontent.com/jenkins-infra/docker-hashicorp-tools/{{ source `dockerHashicorpToolsImageVersion` }}/Dockerfile'
      extractpattern: 'ARG TERRAFORM_VERSION=(.*)'
```
