### DISCUSSION TITLE
Automatically handle "standard" workflows

### DISCUSSION THREAD

**Discussion by olblak** [updatecli/updatecli#755] [Ideas]
# Automatically handle "standard" workflows

Writing custom manifest is great to have tailored upgrade scenario but in many cases we could automatically detect what needs to be done. 
The different scenarios that I would need and that I could already handle with "little" effort are:

* Automate Helm Chart dependency update
* Automate Dockerfile "FROM" image
* Automate Github Action Workflows

My idea would be to add a new "stage" named "default" that could generate pipeline configuration.
Configuration would looks like this

```
scms:
  default:
    kind: github
    spec:
      ... 
defaults:
  helm:
    kind: helm
    scmid: default
    # `ignore` and `only` are mutually exclusive.  
    # Ignore allows to specify pipeline name/rule that we want to ignore
    ignore:
      - certmanager
    # Only allows to restrict the number of pipeline name/rule that we want to execute
    only:
      - certmanager
    spec:
      versionFilter:
        kind: semver
        pattern: "~0"
      workdir: "charts"
       
```

The purpose of that new stage would be to generate pipeline configuration to execute.
The core engine would looks like 

.1 Prepare Stage: Ensure git repositories are cloned locally
.2 Default Stage: Browse local files to generate pipelines based on rules # This is the new stage proposed
.3 Sources Stage: Retrieve source information
.4 Condition Stage: Ensure condition pass
.5 Target Stage: Update files if needed

Please note that I am not fully convinced by the new stage named "default"
