### ISSUE TITLE
Feature Request: Get Helm Chart version from local index.yaml instead of remote URL

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#1022]
### Is your feature request related to a problem?

I am looking for a way to retrieve the latest Helm chart version from a local index.yaml

### Solution you'd like

I would like to be able to retrieve Helm Chart version from a local file instead of a remote URL.
Such as 

```
sources:
  chart:
    name: Load chart version
    kind: helmchart
    spec:
      url: "charts/{{ requiredEnv .chart  }}"
      name: jenkins
```

```
sources:
  chart:
    name: Load chart version
    kind: helmchart
    spec:
      url: "file://./charts/{{ requiredEnv .chart  }}"
      name: jenkins
```
