### ISSUE TITLE
Feature Request: Support multiple files with `spec: files` in `conditions` of `kind:file`

### ISSUE THREAD

**Issue by macedogm** [updatecli/updatecli#1026]
### Is your feature request related to a problem?

As discussed in https://github.com/updatecli/updatecli/discussions/1013, Updatecli already has the logic to support multiple files with `spec: files` in `conditions` of `kind:file`. However, this functionality is not allowed due to a check of the number of files:

https://github.com/updatecli/updatecli/blob/1c37a46e5592eb0397bd5cfd96d95a7459da7d2f/pkg/plugins/resources/file/condition.go#L53-L58

### Solution you'd like

Would be nice to have this feature so we can write more concise pipelines. Example:

```yaml
conditions:
  dockerfiles:
    name: "Bump golang:alpine image version in Dockerfiles"
    kind: "file"
    scmid: "k3s"
    disablesourceinput: true
    spec:
      files:
        - "Dockerfile.dapper"
        - "Dockerfile.test"
        - "Dockerfile.manifest"
      matchpattern: 'ARG GOLANG=golang:v?\d+\.\d+\.\d+(-alpine\S+)?'
```

### Alternatives you've considered

To work around such limitation, the user needs to write a verbose and repetitive pipelines. Example:

```yaml
conditions:
  dockerfile-dapper:
    name: "Check if 'ARG GOLANG' is set in Dockerfile.dapper"
    kind: "dockerfile"
    scmid: "k3s"
    sourceid: "golang-alpine-docker-image"
    spec:
      file: "Dockerfile.dapper"
      instruction:
        keyword: "ARG"
        matcher: "GOLANG"
  dockerfile-test:
    name: "Check if 'ARG GOLANG' is set in Dockerfile.test"
    kind: "dockerfile"
    scmid: "k3s"
    sourceid: "golang-alpine-docker-image"
    spec:
      file: "Dockerfile.test"
      instruction:
        keyword: "ARG"
        matcher: "GOLANG"
```

Another option would be to add support to `spec: files` to `kind: "dockerfile"`, but this would require extra code.
