### ISSUE TITLE
updatecli removes the YAML document indicator (---) when updating a YAML file

### ISSUE THREAD

**Issue by rszumlakowski** [updatecli/updatecli#1036]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`updatecli` removes the YAML document indicator (`---`) when updating a value in a YAML file.

### Expected Behavior

`updatecli` retains the YAML document indicator (`---`) when updating a value in a YAML file.

### Steps To Reproduce

On Linux or macOS:

# Using test file:

```
# something important
---
base_image: my-repository/my-image:latest
```

# Run updatecli with the following configuration:

```
name: Update base_image in build jobs

sources:
 lastDockerDigest:
   kind: dockerdigest
   spec:
     image: "my-repository/my-image"
     tag: "latest"

targets:
 varsYamlFile:
   name: Bump base_image latest digest
   kind: yaml
   transformers:
   - addprefix: my-repository/my-image@
   spec:
     key: base_image
     file: ci/config/vars.yaml
```

# This output is produced:

```
#! something important
base_image: my-repository/my-image@sha256:xxxxxxxx
```

# But this output is expected:

```
#! something important
---
base_image: my-repository/my-image@sha256:xxxxxxxx
```

### Environment

```markdown
- OS: macOS Monterey v12.6.1, also Linux Photon OS
- updatecli: v0.40.0
```

### Anything else?

My intent was to use this YAML file as a `ytt` data values file.  `ytt` expected the YAML document indicator to be in the file.  Since updatecli removed the YAML document indicator then `ytt` fails to load the YAML data values file.
