### ISSUE TITLE
Feature Request: Allow to define expected Condition result

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#1053]
### Is your feature request related to a problem?

Sometimes I would like my condition to return `false` as the expected result instead of checking for a result to be `true`

### Solution you'd like

I would like to use the key "false" such as 

```
conditions:
    dockerTag:
        name: Is docker image golang:{{ source "latestGoVersion" }} published
        kind: dockerimage
        spec:
            image: golang
            tag: '{{ source "latestGoVersion" }}'
        scmid: default
        sourceid: latestGoVersion
        false: true
```

### Anything else?

I also would like to be able to combine condition result but I don't we could express with the current syntax
