### ISSUE TITLE
Feature Request: update multiple yaml keys with one target

### ISSUE THREAD

**Issue by jvanz** [updatecli/updatecli#1056]
### Is your feature request related to a problem?

I need to update two different yaml keys with the same value.  I need to have two targets to do that.

### Solution you'd like

It would be nice if the `key` field in the target yaml accept a list of keys. Therefore, there is no need to define multiple target to change multiple yaml keys with the same value.

**Comment by lemeurherve** [comment]
Would be fixed by https://github.com/updatecli/updatecli/pull/650
I need to merge the upstream changes.

**Comment by lemeurherve** [comment]
That was easier than I though.

**Comment by olblak** [comment]
I think @jvanz request is to update multiple key in one target, like the json/csv/toml plugin

**Comment by lemeurherve** [comment]
Oh you're right!
This issue is a duplicate of https://github.com/updatecli/updatecli/issues/464 then 🙂

**Comment by olblak** [comment]
In fact it's related to the yaml refactoring needed.
Both Dasel and yq would supported multi query.

The plugins json,csv, and toml rely on Dasel but Dasel used with yaml has different limitation than the current Updatecli implementations. I would like to take some time to look at yq

**Comment by dduportal** [comment]
> In fact it's related to the yaml refactoring needed. Both Dasel and yq would supported multi query.
> 
> The plugins json,csv, and toml rely on Dasel but Dasel used with yaml has different limitation than the current Updatecli implementations. I would like to take some time to look at yq

Be careful: the author of this issue is asking for multiple files to target (e.g. "1 query for N files"). 
It's slighltly different than "multiple queries" (e.g. "N queries for N files").

**Comment by jvanz** [comment]
Let me give and example of what I would like to do:
```yaml
sources:                                                                                                                                                                                                                                     
  controllerChart:                                                                                                                                                                                                                           
    name: Load chart version                                                                                                                                                                                                                 
    kind: yaml                                                                                                                                                                                                                               
    spec:                                                                                                                                                                                                                                    
      file: "file://charts/kubewarden-controller/Chart.yaml"                                                                                                                                                                                 
      key: "version" 
targets:
  chartPatchVersionUpdate:
    name: Bump chart patch version
    kind: yaml
    sourceid: controllerChart
    scmid: "default"
    transformers:
      - semverinc: "patch"
    spec:
      file: "file://charts/kubewarden-controller/Chart.yaml"
      key: 
        - "version"
        - 'annotations.catalog\.cattle\.io/upstream-version'
```

Instead of:

```yaml
sources:                                                                                                                                                                                                                                     
  controllerChart:                                                                                                                                                                                                                           
    name: Load chart version                                                                                                                                                                                                                 
    kind: yaml                                                                                                                                                                                                                               
    spec:                                                                                                                                                                                                                                    
      file: "file://charts/kubewarden-controller/Chart.yaml"                                                                                                                                                                                 
      key: "version" 
targets:
  chartPatchVersionUpdate:
    name: Bump chart patch version
    kind: yaml
    sourceid: controllerChart
    scmid: "default"
    transformers:
      - semverinc: "patch"
    spec:
      file: "file://charts/kubewarden-controller/Chart.yaml"
      key: "version"
  chartPatchVersionUpdate2:
    name: Bump chart patch version in annotations
    kind: yaml
    sourceid: controllerChart
    scmid: "default"
    transformers:
      - semverinc: "patch"
    spec:
      file: "file://charts/kubewarden-controller/Chart.yaml"
      key: 'annotations.catalog\.cattle\.io/upstream-version'

```
