### ISSUE TITLE
Feature Request: github source spec without token

### ISSUE THREAD

**Issue by johanvdw** [updatecli/updatecli#1060]
I'm testing updatecli, and I did not find a way to fetch a source version without a token. As we do not use github but gitea for our own repo, it seems a bit strange to have need a token to fetch eg the latest version of an open source package. The example below works fine with token, but it would be nicer if this would work without it.

```
sources:
  pgadminVersion:
    name: get latest version pgadmin
    kind: githubrelease
    spec:
      owner: pgadmin-org
        #      token: "xxxxx"
      repository: pgadmin4
    transformers:
    - trimprefix: "REL-"
    - replacer:
        from: "_"
        to: "."
conditions:
  pgadminimage:
    name: latest pgadmin published in 6 series
    kind: dockerimage
    spec:
      image: dpage/pgadmin4
targets:
  pgadmin:
    name: bump pgadmin version
    kind: yaml
    scmid: gitea
    spec:
...
```

**Comment by dduportal** [comment]
Hello @johanvdw , the `githubrelease` source uses the GitHub API (paginated, sorting, etc.).

This API requires an authentication (mainly because of Rate limit) so that is why authentication is required.

Be aware that, you can run `curl` request without authentication on some cases but too much requests will rate-limit (or block) your public egress IP on GitHub websites if they are too much.

Alowing unauthenticated requests on updatecli would mean dropping the whole implementation (which uses a github API golang native  client under the hood) and to re-implement all requests with REST instead of GraphQL: that would be quite a change with no real interest.

Does it clarify the reason for you? I'm asking because documentation could benefit from a note for this, what do you think?

**Comment by johanvdw** [comment]
This is clear for me - it may be worth mentioning it, this way people would also know that they need a classic personal access token and not a limited one.

**Comment by dduportal** [comment]
> 

Good point! May I ask you to propose a draft by editing the source file at https://github.com/updatecli/website/blob/master/content/en/docs/plugins/resource/github_release.adoc ?

I'm asking for help because as the adage says: "you know what you don't know", e.g. right now you are right now the best person to set this note in the place you would have expected to help you (as we, maintainers, have our biases that makes it hard for us to know the "correct" way to help users).

**Comment by olblak** [comment]
Hi @johanvdw 

As @dduportal explained it very well, many GitHub api endpoints requires a token hence why we requires it.
That being said you could use the following workaround, which use the json resource instead of the githubrelease

```
sources:
  semverVersion:
    kind: json
    name: Get latest Updatecli version
    spec:
      file: https://api.github.com/repos/updatecli/updatecli/releases
      query: ".[*].tag_name"
      versionfilter:
        kind: semver
        pattern: "v0.35"
```

Also please note that https://github.com/pgadmin-org/pgadmin4 do not publish releases but Git Tag
So a manifest like the following one will be better. Even though I now realize that this repository is quite heavy... 

```
scms:
  pgadmin4:
    kind: git 
    spec:
      url: https://github.com/pgadmin-org/pgadmin4.git
      branch: master

sources:
  pgadmin4:
    kind: gittag
    scmid: pgadmin4
    transformers:
      - trimprefix: "REL-"
      - replacer:
          from: "_" 
          to: "." 
```
