### ISSUE TITLE
support labels in updatecli values

### ISSUE THREAD

**Issue by jetersen** [updatecli/updatecli#108]
For GitHub it would be nice to add labels on a pull request on creation.

```yaml
github:
  user: "GitHub Action"
  email: "41898282+github-actions[bot]@users.noreply.github.com"
  username: "github-actions"
  token: "UPDATECLI_GITHUB_TOKEN"
  branch: "master"
  owner: "owner"
  repository: "repo"
  labels:
    - dependency
```

If you like the idea, I would be open to working on the issue.
If not feel free to close the issue.
