### ISSUE TITLE
Feature Request: condition to check if a Github release  to a given tag exists

### ISSUE THREAD

**Issue by jvanz** [updatecli/updatecli#1084]
### Is your feature request related to a problem?

I'm trying to sync the release of 3 different repositories. For that, I want to run the updatecli script when all the 3 repositories have a release to a given tag. If there are such releases, do whatever I want to do. 

### Solution you'd like

I would like to have a condition that checks if a given github repository has a release for a given tag. 

### Alternatives you've considered

I'm using the condition to check if the tag exists in a git repository. But this does not guarantee that the github release exists. This is a problem for me because I need to download an asset from the release of one of the repositories. Therefore, I need to check if the release is there using other tools.

**Comment by olblak** [comment]
Thanks for opening this issue
I just did a quick check and I think you spot a UX issue and I am open to suggestion

Currently the githubrelease condition compares the value from the `spec.tag` (default to source output), and the versionfilter. I think versionfilter should only be used in source at least that's what we do for the other resources
So the Github release should check that a tag exist and only that

I tried the following manifest 

<details><summary>Manifest</summary>

```
name: Test checking that both github release and gittag exist

scms:
  default:
    kind: github
    spec:
      owner: updatecli
      repository: updatecli
      branch: main
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'

sources:
  shell:
    name: Get version from shell command output
    kind: shell
    spec:
      command: echo v0.40.1
conditions:
  gittag:
    name: Test that gittag exist based on source output
    sourceid: shell
    kind: gittag
    scmid: default
  githubrelease:
    name: Test that github release tag exist based on source output
    kind: githubrelease
    sourceid: shell
    spec:
      owner: updatecli
      repository: updatecli
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      versionfilter:
        kind: regex
        pattern: "v0.40.1"
targets:
  version:
    name: Only run if conditions succeeded
    kind: shell
    spec:
      command: echo release 

```

</details>

<details><summary>Output</summary>

```
 ~  updatecli diff --config /tmp/test.yaml                                                                                                     ✔ │ took 13s 


+++++++++++
+ PREPARE +
+++++++++++

Loading Pipeline "/tmp/test.yaml"

SCM repository retrieved: 1


++++++++++++++++++
+ AUTO DISCOVERY +
++++++++++++++++++



++++++++++++
+ PIPELINE +
++++++++++++



###########################################################
# TEST CHECKING THAT BOTH GITHUB RELEASE AND GITTAG EXIST #
###########################################################


SOURCES
=======

shell
-----
The shell 🐚 command "echo v0.40.1" ran successfully with the following output:
----
v0.40.1
----


CONDITIONS:
===========

githubrelease
-------------
Searching for version matching pattern "v0.40.1"
✔ Github Release version "v0.40.1" found

gittag
------
Source input value detected: using it as spec.versionfilter.pattern
Searching for version matching pattern "v0.40.1"
✔ Git tag "v0.40.1" matching


TARGETS
========

version
-------

**Dry Run enabled**

The shell 🐚 command "echo release v0.40.1" ran successfully with the following output:
----
release v0.40.1
----

=============================

REPORTS:


⚠ Test checking that both github release and gittag exist:
	Source:
		✔ [shell] Get version from shell command output (kind: shell)
	Condition:
		✔ [githubrelease] Test that github release tag exist based on source output (kind: githubrelease)
		✔ [gittag] Test that gittag exist based on source output (kind: gittag)
	Target:
		⚠ [version] Only run if conditions succeeded (kind: shell)


Run Summary
===========
Pipeline(s) run:
  * Changed:	1
  * Failed:	0
  * Skipped:	0
  * Succeeded:	0
  * Total:	1

```

</details>

**Comment by olblak** [comment]
@jvanz If it's good for you 

If I understand correctly you would expected the following snippet to work

```
conditions:
  test:
    kind: githubrelease
    spec:
       owner: updatecli
       repository: updatecli
       tag: 1.0.0
```
