### ISSUE TITLE
Feature Request: Add Golang package support

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#1088]
### Is your feature request related to a problem?

I would like to be able to use Go package version from source and condition.
There is an API documented on https://go.dev/ref/mod#goproxy-protocol

The following endpoint can be used 

List all versions for a specific package
`curl https://proxy.golang.org/github.com/updatecli/updatecli/@v/list`

Get package version information
`curl https://proxy.golang.org/github.com/updatecli/updatecli/@v/v0.40.1.info`

### Solution you'd like

I would like to use the following manifest

```
sources:
  example1:
    name: Get github.com/updatecli/updatecli package version
    kind: gopackage
    spec:
      package: github.com/updatecli/updatecli
      versionfilter:
        kind: semver
        pattern: "~0"

conditions:
  example1:
    name: Get github.com/updatecli/updatecli package version
    kind: gopackage
    disablesourceinput
    spec:
      package: github.com/updatecli/updatecli
      version: 0.30.0
      url: <differentProxy than proxy.golang.org>
```

### Alternatives you've considered

Instead of `package` we could use `name` such as 

I am expecting the following manifest to work

```
sources:
  example1:
    name: Get github.com/updatecli/updatecli package version
    kind: gopackage
    spec:
      name: github.com/updatecli/updatecli
      versionfilter:
        kind: semver
        pattern: "~0"

conditions:
  example1:
    name: Get github.com/updatecli/updatecli package version
    kind: gopackage
    disablesourceinput
    spec:
      name: github.com/updatecli/updatecli
      version: 0.30.0
```

### Anything else?

A similar pullrequest that can be used for inspiration https://github.com/updatecli/updatecli/pull/1081
