### ISSUE TITLE
Feature Request: Support upstream GitHub pullrequest

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#1096]
### Is your feature request related to a problem?

The two following use case triggered then need for working on a "fork" repository and then opening the pullrequest to the upstream repository

1. For security reason, I don't want to give write permission to updatecli. Instead I would like to allow the tool to work on a fork repository and then publish upstream

2. To update third party repositories, project such as homebrew, or jsonschemastore requires to open a pullrequest to submit the change. I would like to do it automatically using Updatecli

### Solution you'd like

I would like to add to add a new parameter for the  action resource `github/pullrequest`.
I am thinking of a boolean named `upstream` by default set to false

<details><summary>Manifest</summary>

```
actions:
    default:
        title: '[updatecli] Bump golangci-lint version to {{ source "default" }}'
        kind: github/pullrequest
        spec:
            automerge: true
            labels:
                - chore
                - dependencies
                - skip-changelog
        scmid: default
        upstream: true
scms:
    default:
        kind: github
        spec:
            branch: main
            email: me@olblak.com
            owner: updatecli
            repository: updatecli
            token: '{{ requiredEnv "UPDATECLI_GITHUB_TOKEN" }}'
            user: updatecli
            username: '{{ requiredEnv "UPDATECLI_GITHUB_ACTOR" }}'
        disabled: false

```

</details>

The logic would need to be implemented in the pullrequest codebase

1. Check if current repository is fork, probably by extending [codebase](https://github.com/updatecli/updatecli/blob/0e74b32c5a6e581272caad2c1eadbec6bcde971d/pkg/plugins/scms/github/main.go#L229)
2. If yes then retrieves the upstream repository information
3. Use that information when opening the pullrequest [codebase](https://github.com/updatecli/updatecli/blob/0e74b32c5a6e581272caad2c1eadbec6bcde971d/pkg/plugins/scms/github/pullrequest.go#L352)
