### ISSUE TITLE
Gittag spec.path is not working

### ISSUE THREAD

**Issue by enrichman** [updatecli/updatecli#1101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the `spec.path` is specified the current working directory is still used.

```yaml
sources:
  gitExample1:
    name: "Get Latest updatecli test"
    kind: gittag
    spec:
      path: "./git_repository_path/"
```

### Expected Behavior

The tags of the specified repository should be used.

### Environment

```markdown
- OS:
- updatecli:
```
