### ISSUE TITLE
Target resource designed to not update files always fail

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#1126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When Updatecli executes a target which modify a git repositories, It monitors files returned by the target to identify if it should proceed or return  no change.
Instead, Updatecli should rely on git to identify if changes are need which is not supported at the moment.

The code that checks is https://github.com/updatecli/updatecli/blob/main/pkg/core/pipeline/target/main.go#L141L144

Due to this behavior, target resource such as gitbranch or gittag always fails as they do not modify files.
The workaround for now is to return `[]string{""}` instead of `[]string{}`

### Expected Behavior

Updatecli should rely on git to identify if changes are need which is not supported at the moment.
Snippet shouldn't be needed

```
		if len(files) == 0 {
			t.Result = result.FAILURE
			return fmt.Errorf("no changed file to commit")
		**}**
```

### Steps To Reproduce

Manifest used to reproduce 

<details><summary>Example</summary>

```
scms:
  default:
    kind: github
    spec:
      branch: master
      email: me@olblak.com
      owner: olblak
      repository: nocode
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      user: updatecli
      username: '{{ requiredEnv "GITHUB_ACTOR" }}'
    disabled: false

sources:
  default:
    name: Get Latest committed branch
    kind: gitbranch
    scmid: default

conditions:
  default:
    name: Get Latest committed branch
    kind: gitbranch
    scmid: default
    sourceid: default
  master:
    name: Get Latest committed branch
    kind: gitbranch
    scmid: default
    disablesourceinput: true
    spec:
      branch: master

targets:
  default:
    name: Create the branch v2 if needed
    kind: gitbranch
    scmid: default
    disablesourceinput: true
    spec:
      branch: v2
  alreadyexist:
    name: Test that the branch already exist.
    kind: gitbranch
    scmid: default
    spec:
      branch: master

```

</details>

### Environment

```markdown
- OS:
- updatecli: 0.43.0
```
