### ISSUE TITLE
Feature Request: negation for the file kind condition

### ISSUE THREAD

**Issue by v1v** [updatecli/updatecli#1137]
### Is your feature request related to a problem?

I'd like to use a flag/action for supporting negation for finding a string within a `condition`, then it will be possible to declare those condition within the `yml` rather than using a shell script or similar.

### Solution you'd like

if `notfind` look for the given value in the given file, then something like the below snippet could work:

```bash
...
conditions:
  goDefaultVersion-check:
    kind: file
    sourceid: latestGoVersion
    spec:
      file: .go-version
      notfind: '{{ source "latestGoVersion" }}'
```

### Alternatives you've considered

As today I can get a similar behaviour by using the `shell` with a script call, something like:

```bash
#!/usr/bin/env bash
if grep -q "$1" .go-version ; then
  echo "found $1. No need to do nothing"
  # return false
  exit 1
fi
echo "not found $1. Need to update the file"
# return true
exit 0
```

```yaml
...
conditions:
  goDefaultVersion-check:
    name: Check if defined golang version differs
    kind: shell
    sourceid: latestGoVersion
    spec:
      command: bash test-golang-version.sh
```

or use a trick too like the below one:

```yaml
...
conditions:
  goDefaultVersion-check:
    name: Check if defined golang version differs
    kind: shell
    sourceid: latestGoVersion
    spec:
      command: 'grep -v -q {{ source "latestGoVersion" }} .go-version #'
```

`#` helps to use the grep with the right arguments

```
----------
The shell 🐚 command "grep -v -q 1.19.5 .go-version # 1.19.5" ran successfully with the following output:
----
```

### Anything else?

I tried with `matchpattern` but there is no support for negation in https://pkg.go.dev/regexp/syntax

**Comment by olblak** [comment]
The condition accepts the boolean `failwhen` which allows to revert the expected result as in the following examples

```
conditions:
  jenkinsexist:
    kind: jenkins
    spec:
      version: '2.235'
      release: weekly
    failwhen: false
  jenkindonotexist:
    kind: jenkins
    spec:
      version: '2.235'
      release: weekly
    failwhen: true
  wrongjenkinsexist:
    kind: jenkins
    spec:
      version: '2.999'
      release: weekly
    failwhen: false
  wrongjenkindonotexist:
    kind: jenkins
    spec:
      version: '2.999'
      release: weekly
    failwhen: true
```
