### ISSUE TITLE
Feature Request: Missing feature parity with github/gitea and git SCMs 

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#1139]
### Is your feature request related to a problem?

There is a different behavior between the git scm and the github/gitea scm.

The `git` scm always push changes to the targeted branch defined in the manifest while the gitea/github, creates a temporary working branch.

 

### Solution you'd like

I would like to be able to use one of the two workflow no matter the scm

```
scms:
  scenario-source:
    kind: git
    spec:
      username: "git username used for authentication"
      password: 'git password used for authentication'
      url: "https://github.com/updatecli/experiment.git"
      branch: "main"
      targetbranch: "main"
```

### Alternatives you've considered

We could have a new action type 

```
actions:
  default:
    kind: git
    spec:
      sourcebranch: xxx
      targetbranch: yyy
```

**Comment by olblak** [comment]
I initially attempt for solving this https://github.com/updatecli/updatecli/issues/738

**Comment by mcwarman** [comment]
I like the idea of `targetbranch` property as with the changes in #1132, in my head it enables:

```yaml
scms:
  scenario-source:
    kind: git
    spec:
      username: "git username used for authentication"
      password: 'git password used for authentication'
      url: "https://github.com/updatecli/experiment.git"
      branch: "main"
      targetbranch: 'updatecli/my-update/{{ source "default" }}'
```

**Comment by dduportal** [comment]
> I like the idea of `targetbranch` property as with the changes in #1132, in my head it enables:
> 
> ```yaml
> scms:
>   scenario-source:
>     kind: git
>     spec:
>       username: "git username used for authentication"
>       password: 'git password used for authentication'
>       url: "https://github.com/updatecli/experiment.git"
>       branch: "main"
>       targetbranch: 'updatecli/my-update/{{ source "default" }}'
> ```

WDYT about the "action" of type `git/push` that would had its `spec.targetbranch`?

The reason I'm asking is because the `scms` section looks really bloated in term concepts: it holds both local and remote setups, in a way that tries to be "generic" to fit all cases.

Using an "action" would help in term of concept:

- `scms` would be a configuration placeholder with no user intent
- `actions` would help user expressing what they want to do with the changes done by the updatecli targets

For instance:

```yaml
scms:
  local:
    kind: git
    spec:
      username: "luke"
      password: 'SuperSecret!'
      url: "https://github.com/updatecli/experiment.git"

sources:
# ...
conditions:
# ...
targets:
# ...

actions:
  push_to_git_remote:
    kind: git/push
    spec:
      sourcebranch: main
      ## Uncomment below to specify your own static branch name, otherwise Updatecli generates one
      # targetbranch: updatecli_dependency_foo
```

**Comment by mcwarman** [comment]
That makes sense from usability point of view, and readability of the config.

But as user I think I would also expect `github` and `gitea` to work the same way with equivalent actions and control. 

There's obviously a trade off with the implementation from a backwards capability point of view. Possibly the push actions would have to be assumed how they currently work even if not configured.

**Comment by mcwarman** [comment]
I think `branch` also make sense to stay in `scms`, because of what it means to `source` and `conditions`. And that is then used for the action.

```yaml
scms:
  local:
    kind: git
    spec:
      username: "luke"
      password: 'SuperSecret!'
      url: "https://github.com/updatecli/experiment.git"
      branch: main

sources:
# ...
conditions:
# ...
targets:
# ...

actions:
  push_to_git_remote:
    kind: git/push
    ## Uncomment below to specify your own static branch name, otherwise Updatecli generates one
    # spec:
    #   targetbranch: updatecli_dependency_foo
```

**Comment by dduportal** [comment]
> But as user I think I would also expect github and gitea to work the same way with equivalent actions and control.

Absolutely! what you say make perfect sense.

I was thinking about updating the current `github/pullrequest` and `gitea/pullrequest` actions with the same behavior:

```
actions:
  default:
    kind: github/pullrequest
    scmid: default
    title: Bump Jenkins LTS docker image version to {{ source "latestRelease" }}
    targetbranch: updatecli/jenkins-core
    spec:
      labels:
        - dependencies
        - jenkins-lts
```

> There's obviously a trade off with the implementation from a backwards capability point of view. Possibly the push actions would have to be assumed how they currently work even if not configured.

True. But the (code) path to add a new feature in actions, which are quite new in updatecli is easier than changing the `scms` code base that has a lot of implications. That's not the reason why I proposed this, but it would be a side benefit \o/

> Another suggestion is for branch to stay in scms, because of what it means to source and conditions. And the value of branch is then used for the actions.

That is an excellent proposal (I really like it)

- That would ensure backward compatibility with current users
- This not exclusive of using an `actions.*.spec.sourcetarget` for new manifests/users (and we could had a warning message telling the user that their `sourcebranch` is set to scm's `branch value if both are present).

**Comment by olblak** [comment]
I've been thinking about this issue lately and I am considering a different approach. 
I would introduce a new key named `ephemeralbranch` or `workingbranch`  that would accept true, false or nil.

To stay backward compatible the git scm would be false by default and all others would be true when the parameter is nil.

So something like :

```
scms:
  local:
    kind: git
    spec:
      username: "luke"
      password: 'SuperSecret!'
      url: "https://github.com/updatecli/experiment.git"
      branch: main
      workingbranch: true
```

If set to true, Updatecli would create a "working branch" like we have today `updatecli_xxx` based on the branch value which would be main in the current example.

We could also imagine different behavior based on the associated action but I am bit concerned by the confusion that it may introduce to end users.

ps: We could also introduce a new parameter `workingbranchprefix` that would allow overriding the default `updatecli_`
