### ISSUE TITLE
Feature Request: Allow to specify versioncontraint for target

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#1150]
### Is your feature request related to a problem?

I would like to have different update strategies depending the version bump, such as 

In the context of semver:
* Using github/pullrequest with flag auto merge for patch version bump
* Using specific labels for minor or major version bump

In the context of a regex:
* Only bump to version using the string "-team-highlander"

### Solution you'd like

I would like to have a new spec next to versionfilter such as 

```
targets:
  kind: yaml
  spec:
    file: updatecli.yaml
    key: version
    versionconstraint:
      kind: semver
      spec:
        only:
          patch: true
          minor: true
        # ignore:
        #   patch: true
        #   minor: true
        #   major: true
```

### Alternatives you've considered

Instead I considered adding a new condition of type "semver" such as 

## New conditoin of type "semver"

```
conditions:
  semver:
    kind: semver
    spec:
      versions:
        - 1.0.0
        - 2.0.0
      ignore:
        major: 
```

The problem is the resource would requires at least two input from two differents sources.
The second problem is we only know at "target" time to what version we're gonna update to. 

## Add versionconstraint at the resource lever

Not every plugin needs this
