### ISSUE TITLE
Checking out the same branch in the git-checkout targeting a different branch in the Git

### ISSUE THREAD

**Issue by v1v** [updatecli/updatecli#1159]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Given the `BRANCH` env variable
And
```yaml
...
scms:
  default:
    kind: github
    spec:
      user: '{{ requiredEnv "GIT_USER" }}'
      email: '{{ requiredEnv "GIT_EMAIL" }}'
      owner: elastic
      repository: fleet-server
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      username: '{{ requiredEnv "GIT_USER" }}'
      branch: '{{ requiredEnv "BRANCH" }}'
```

When I run `BRANCH=main updatecli diff --config .ci/bump-elastic-stack-snapshot.yml  --debug` or `BRANCH=8.6 updatecli diff --config .ci/bump-elastic-stack-snapshot.yml  --debug`

Then for both cases it uses the same checkout branch

```
DEBUG: checkout branch "updatecli_761abaa52598c50f90bcfdf4a7059e949e992bbb5532726bc682cf114db69843", based on "main" to directory "/var/folders/hn/j6gds1qx1f5bysfn0qp0t03c0000gn/T/updatecli/github/elastic/fleet-server"
```

```
checkout branch "updatecli_761abaa52598c50f90bcfdf4a7059e949e992bbb5532726bc682cf114db69843", based on "8.6" to directory "/var/folders/hn/j6gds1qx1f5bysfn0qp0t03c0000gn/T/updatecli/github/elastic/fleet-server"
```

### Expected Behavior

checkout branch "updatecli_***` will be a different one each time

### Steps To Reproduce

1. Locally and GitHub actions
2. updatecli diff -

### Environment

```markdown
- OS: Ubuntu 22 GitHub runners and MacOS
- updatecli: 0.40.2
```

### Anything else?

https://github.com/elastic/beats/commits/updatecli_53ebe810f7782bf7e7c14b060c30f04f8a06667843a6dfb9b2c31e3f74dcd82b was created with two commits for two different versions, while I would not expected the same branch with two commits but just one

https://github.com/elastic/beats/actions/runs/4171866100/jobs/7222276576 is the workflow we have in place:
- https://github.com/elastic/beats/actions/runs/4171866100/workflow#L23-L42

Then it runs `updatecli` for different active branches in parallel, so the bump can happen for any active branches.

**Comment by v1v** [comment]
As far as I see, the pipelineID is the one reused:
- https://github.com/updatecli/updatecli/blob/3535c64acd1f607ffd14d18250c817086a01b93e/pkg/plugins/scms/github/main.go#L93

I wonder whether that could be changed to be dynamic in a way it's resolved when running the `updatecli`

**Comment by olblak** [comment]
I am interested by the use case here. Something to keep in mind is Updatecli do not have access to state management.
So if you generate a different working branch each time your run Updatecli then you'll end with a lot of pullrequest for the same change.

At the moment, we support two scenarios:

1) You specify the pipelineid such as https://github.com/updatecli/updatecli/blob/3535c64acd1f607ffd14d18250c817086a01b93e/updatecli/updatecli.d/updatecli.yaml#L2 so no matter what you'll always have the same working branch. The same pipelineID can be reused accross manifest so they'll all work from the same temporary branch.

2) You don't specify pipelineid, then Updatecli generate a checksum based on the manifest. If you change the manifest then you have a differrent pipelineid



At the moment, either you specify the `pipelineid` then we

**Comment by olblak** [comment]
A workaround would to have something like 

```
pipelineid: '{{ requiredEnv "BRANCH" }}' 
scms:
  default:
    kind: github
    spec:
      user: '{{ requiredEnv "GIT_USER" }}'
      email: '{{ requiredEnv "GIT_EMAIL" }}'
      owner: elastic
      repository: fleet-server
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      username: '{{ requiredEnv "GIT_USER" }}'
      branch: '{{ requiredEnv "BRANCH" }}'
```
