### ISSUE TITLE
No changelog in the PR request

### ISSUE THREAD

**Issue by alexagriffith** [updatecli/updatecli#1190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

(redacting some stuff with xx since private) 
Right now, when I run updatecli it prints out the changes that need to be made with a changelog like 

```
################################
# ROLES-XX-BASE-QA.TPL #
################################


SOURCES
=======

roles-xx
----------------
Searching for version matching pattern "latest"
✔ Github Release version "1.22.16.7" found matching pattern "latest"


CHANGELOG:
----------

Release published on the 2023-02-15 00:13:43 +0000 UTC at the url https://github.com/xx/roles-xx/releases/tag/1.22.16.7

View the [build log on Jenkins](https://xx-build.jaas.dev.xx.com/job/xxx).
## Changelog since 1.22.16.6

- [`acd41c6`](https:/github.com/xx): [ENG3DISRE-2672] update configs (#1087) (#1089) by xx[bot] (20983+xx[bot]@users.github)


---

*The above changelog was generated automatically by [Jaazy-Jeff](https://github.com/ds/jaazy-jeff).*


TARGETS
========

roles-kubernetes-qa
-------------------
✔ Content from file "/var/folders/gl/9dxcv29j0f781mb8dmjhjg2h0000gn/T/updatecli/github/qa_base/xx.yaml" already up to date
✔ All contents from 'file' and 'files' combined already up to date


ACTIONS
========


Pull Request available at:

        https://github.com/xx/pull/277
```

so I expect to see this changelog in the changelog field

but instead every PR has a changelog that is empty like 

![Screen Shot 2023-02-28 at 1 00 43 PM](https://user-images.githubusercontent.com/43711982/221941133-ed39afcd-6388-47f4-bdbe-8abc311bdeeb.png)

### Expected Behavior

changelog populated in the auto PR 

### Steps To Reproduce

my action setup is like 

```
actions:
  default:
    title: Bump {{$name}} to {{ source $name }} on QA
    kind: github/pullrequest
    spec:
      automerge: false
      draft: false
      mergemethod: squash
      labels:
        - "chore"
    scmid: default
 ```

### Environment

```markdown
- OS:
- updatecli: v0.36.0
```
