### ISSUE TITLE
Feature Request: Allow versionfilter on target 

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#1203]
### Is your feature request related to a problem?

I would like to have different update strategies based on the type of version bump. 

### Solution you'd like

If the updatecli version bump is:
Other situation would be to ignore patch version update
* A patch version change, then I would like to open a GitHub pullrequest with the automerge flag enabled
* A minor version change, then I would like to open a Github pullrequest with   
* A major version change, then I would like to open a GitHub pullrequest with a specific label

```
sources:
  updatecli:
    kind: githubrelease
    spec: 
      owner: updatecli
      repository: updatecli
      token: xxx
targets:
  updatecli:
    kind: yaml
    spec:
      file: action.yaml
      key: version
    versionfilter:
      kind: semver
      spec:
        minor: true
        patch: true
```

## Condition

I considered adding a new condition of type semver but we have the two following constraint:
.1 Between a source and a target, the information could be transformed using the "transformers"
.2 We only know at the target stage the version used

## Source

I considered handling this at the source level with the current `versionfilter` implementation, but we don't know yet what the target value would be.

## Pipeline refactoring 

I considered changing the core pipeline to go from 
.1 Get sources 
.2 Check condition
.3 Update target

to 
.1 Get target value
.2 Get source 
.3 Check condition
.4 Update target

But I don't think, the time spent of this type of refactoring is worthwhile
