### ISSUE TITLE
XML target fail to find file when using scmid

### ISSUE THREAD

**Issue by pgmillon** [updatecli/updatecli#1210]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```yaml
---
name: Bump Datadog Java agent

scms:
  default:
    kind: github
    spec:
      user: {{ requiredEnv "GIT_AUTHOR_USERNAME" }}
      email: {{ requiredEnv "GIT_AUTHOR_EMAIL" }}
      token: {{ requiredEnv "UPDATECLI_GITHUB_TOKEN" }}
      owner: xxx
      repository: xxx
      branch: master
      username: xxx

sources:
  default:
    name: Get latest dd-java-agent release
    kind: maven
    scmid: default
    spec:
      repository: "https://repo1.maven.org/maven2"
      groupid: "com.datadoghq"
      artifactid: "dd-java-agent"

targets:
  default:
    name: Update dd-java-agent to {{ source "default" }}
    kind: xml
    scmid: default
    spec:
      file: datadog-java-agent-build/pom.xml
      path: "/project/version"
      
actions:
  default:
    kind: github/pullrequest
    scmid: default
    title: Update dd-java-agent to {{ source "default" }}
```

```$ GIT_AUTHOR_USERNAME=pgmillon GIT_AUTHOR_EMAIL=pierre-gildas.millon@hyland.com  updatecli apply --config ./updatecli/updatecli.d/
...

TARGETS
========

default
-------
⚠ Key '/project/version', from file '/tmp/updatecli/github/<owner>/<repository>/datadog-java-agent-build/pom.xml', was updated from '0.75.0' to '1.10.0'

ERROR: something went wrong in target "default" : "open /tmp/updatecli/github/<owner>/<repository>/tmp/updatecli/github/<owner>/<repository>/datadog-java-agent-build/pom.xml: no such file or
directory"

Pipeline "Bump Datadog Java agent" failed
Skipping due to:
        targets stage:  "something went wrong during target execution"
```

### Expected Behavior

PR should be created with file datadog-java-agent-build/pom.xml modified.

### Environment

```markdown
- OS:Ubuntu 22.04.2 LTS
- updatecli: 0.46.0
```
