### ISSUE TITLE
Feature Request: Extend changelog when using `github/pullrequest`

### ISSUE THREAD

**Issue by v1v** [updatecli/updatecli#1217]
### Is your feature request related to a problem?

If the `changelog` is empty when using `githubrelease`, I'd like to support some kind of extension so I could synthetically modify the `changelog` within the pipeline definition.

To illustrate the above:

https://github.com/updatecli/updatecli/pull/1214 is the one that used 

```yaml
sources:
  latestGoVersion:
    name: Get Latest Go Release
    kind: githubrelease
    transformers:
      - trimprefix: go
    spec:
      owner: golang
      repository: go
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      username: '{{ requiredEnv "GIT_USER" }}'
      versionfilter:
        kind: regex
        pattern: go1\.(\d*)\.(\d*)$
...
```

But its changelog is empty:

<img width="978" alt="image" src="https://user-images.githubusercontent.com/2871786/224306547-ece8c396-b531-4321-8060-3a66b4084c65.png">

### Solution you'd like

I'd like to somehow being able to modify the changelog as part of the kind `github/pullrequest`

```
actions:
  chart:
    kind: github/pullrequest
    scmid: githubConfig
    spec:
      extchangelog:  https://github.com/golang/go/issues?q=milestone%3AGo{{ source "latestGoVersion" }}'+label%3ACherryPickApproved

```

### Alternatives you've considered

https://github.com/updatecli/updatecli/issues/1125 could be the new way?

**Comment by olblak** [comment]
Thanks for bringing back this topic on the table, handling Changelog correctly is a large and not so easy topic :D that I didn't have to dig into yet...

So the short answer, I usually use the field "description" for github pullrequest to provide additional information such as [civo/kubernetes-marketplace:/.github/updatecli.d/argocd.yaml](https://github.com/civo/kubernetes-marketplace/blob/5a204bf233163a82cc91b63f7b56f13678cce310/.github/updatecli/updatecli.d/argocd.yaml#L102)  that generate **https://github.com/civo/kubernetes-marketplace/pull/394**

**Comment by olblak** [comment]
The challenge for https://github.com/updatecli/updatecli/issues/1125 is to be able to have more than one changelog in the PR body while having constant data across Updatecli pipeline run.

I already have prototype working which I need to fine some time to finalize

**Comment by v1v** [comment]
Thanks Olivier, I've been using the description and works quite well. Just found the `changelog` being empty somehow a bit misleading. That's a bit of edge-case as the release notes for Golang is somewhere elsse.

Probably this can be closed as `description` is a good workaround, while https://github.com/updatecli/updatecli/issues/1125 can be the solution

Thanks again!

**Comment by olblak** [comment]
I always wanted to work on the changelog but lack of time and the current status quo is enough for my needs.
I have been considering having something like 

```
sources:
  elastic:
    # Get latest elasticsearch version
changelogs
   elastic:
     kind: githubrelease
targets:
   action:
     kind: file
     sourceid: elastic
     changelogid: elastic
    # provide 
``` 

based on the source and target we would be able to build a dif
