### ISSUE TITLE
Feature Request: new source type to download a subset of GitHub repository

### ISSUE THREAD

**Issue by v1v** [updatecli/updatecli#1218]
### Is your feature request related to a problem?

I wonder whether a new kind called `kind: github-repo-subdir` to extend the functionality of `kind: file` with targeting a github url 

`kind: file` allows to use an https URL:

```
  cgroup_parsing.json:
    kind: file
    spec:
      file: https://raw.githubusercontent.com/elastic/apm/main/tests/agents/json-specs/cgroup_parsing.json
```

But the `source` can be quite long if it contains a bunch of `kind:file` entries

### Solution you'd like

I'd like to support a new kind to fetch the files for a given sub-folder of a GitHub repository. 

Something like the below can help to illustrate how it might work

```
sources:
  github-sub-repo:
    kind: github-sub-repo
    spec:
      repo: https://github.com/elastic/apm/main/tests/agents/json-specs

targets:
  cgroup_parsing.json:
    scmid: default
    sourceid: github-sub-repo
    kind: file
    spec:
      file: test/fixtures/json-specs/cgroup_parsing.json
      content: {{ source "github-sub-repo.cgroup_parsing.json" }}
```

### Anything else?

https://github.com/elastic/apm-agent-nodejs/pull/3197 contains more details about how we are using it at the moment

**Comment by olblak** [comment]
Hi @v1v , 
I think adding a new plugin for this specific use-case seems overkill considering the time need to maintain it versus the different options available at the moment.

**Option 1** 

You could use a value file such as 

values.yaml
```
url:  https://github.com/elastic/apm/main/tests/agents/json-specs
``` 

and then 

manifest.yaml
```
sources:
  default:
    kind: file
    spec:
      file: '{{ .url }}/cgroup_parsing.json'
```

and then execute `updatecli apply --config manifest.yaml --values values.yaml`

**Option 2** 
 
You could define a golang template variable in your manifest

**Option 3**

You could use a source combined with a scm such as 

```
scms:
  apm:
    kind: git
    spec:
      url: https://github.com/elastic/apm.git
      branch: main

sources:
  apm:
    kind: file
    scmid: apm
    spec:
      file: tests/agents/json-specs/cgroup_parsing.json
```

Personally I would prefer the third option, you clone the repository locally and then read the file locally, which reduce the risk of network issues or Github Api rate limit
