### ISSUE TITLE
Source "dockerimage" returns wrong version for "latest"

### ISSUE THREAD

**Issue by CrystalMethod** [updatecli/updatecli#1321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I've added a simple debug statement to print out the found tags. This list is sorted alphanumerical, whats wrong in this case. Because `1.0.0-10 ... 1.0.0-14 > 1.0.0-9`.

```
DEBUG: Searching tags for the image "xxxx.azurecr.io/yyy"
DEBUG: Tags found: [1.0.0-1 1.0.0-10 1.0.0-11 1.0.0-12 1.0.0-13 1.0.0-14 1.0.0-2 1.0.0-3 1.0.0-4 1.0.0-5 1.0.0-6 1.0.0-7 1.0.0-8 1.0.0-9]
DEBUG: 14 Docker image tag(s) found
Searching for version matching pattern "latest"
DEBUG: Searching for latest version
✔ Docker Image Tag "1.0.0-9" found matching pattern "latest"
```

### Expected Behavior

`1.0.0-14` should be returned as "latest".

```
✔ Docker Image Tag "1.0.0-14" found matching pattern "latest"
```

### Steps To Reproduce

```
name: Bump yyy version

sources:
  latestVersion:
    name: Get latest version from image registry
    kind: dockerimage
    spec:
      image: xxx.azurecr.io/yyy
```

### Environment

```markdown
- OS: ArchLinux
- updatecli: 0.49.2
```

**Comment by CrystalMethod** [comment]
I can absolutely agree with your comments regarding the semantics of Docker image tags. According to your recommendation we are now using the "semver" versionfilter.  This additionally allows us to define a version range.

Example:
```
sources:
  latestVersion:
    name: Get latest version from image registry
    kind: dockerimage
    spec:
      image: xxx.azurecr.io/yyy
      versionfilter:
        kind: semver
        pattern: "~1.0.0-0"
```
