### ISSUE TITLE
Yaml Anchors cause upcatecli to fail

### ISSUE THREAD

**Issue by jamiezieziula** [updatecli/updatecli#1332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I have a yaml anchor defined in my target yaml file:
```yaml
definitions:  
  docker:
    - docker: &docker
        push: true
        requires: prefect-docker==0.2.2
        tag: latest
```
when I run updatecli, it produces the following error:
```
ERROR: something went wrong in target "deployment_yaml" : "✗ cannot find key 'definitions.docker[0].docker.requires' from file 'deployment.yaml'"

Pipeline "MANIFEST.YAML" failed
Skipping due to:
        targets stage:  "something went wrong during target execution"
```

If i remove the anchor, updatecli works as expected

manifest.yaml:
```yaml
targets:
  deployment_yaml:
    name: bump prefect-docker version
    kind: yaml
    spec:
      file: deployment.yaml
      key: definitions.docker[0].docker.requires
    sourceid: prefect_docker
    transformers:
      - addprefix: "prefect-docker=="
```

### Expected Behavior

Updatecli would execute normally, even with anchors & aliases inline

### Steps To Reproduce

updatecli manifest.yaml
```yaml
sources:
  prefect_docker:
    kind: githubrelease
    spec:
      owner: PrefectHQ
      repository: prefect-docker
      token: YOUR_TOKEN_HERE
      versionFilter:
        kind: semver
        pattern: v0.x.x
    transformers:
      - trimprefix: v
conditions: {}
targets:
  deployment_yaml:
    name: bump prefect-docker version
    kind: yaml
    spec:
      file: deployment.yaml
      key: definitions.docker[0].docker.requires
    sourceid: prefect_docker
    transformers:
      - addprefix: "prefect-docker=="
```

and a target yaml of `deployment.yaml`
```yaml
definitions:  
  docker:
    - docker: &docker
        push: true
        requires: prefect-docker==0.2.2
        tag: latest
```

run `updatecli diff --config .github/updatecli/manifest.yaml`

### Environment

```markdown
- OS: Mac OS
- updatecli: 0.49.2
```

**Comment by jamiezieziula** [comment]
thank you @olblak !!!

**Comment by dduportal** [comment]
Note: I believe this issue can be closed. Anchor are supported with the `yamlpath` engine:

```
updateDockerComposeFile:
    name: "Update Hugo version in docker image name in docker-compose.yaml"
    transformers:
      - addprefix: "hugomods/hugo:ci-"
    kind: yaml
    spec:
      engine: yamlpath
      file: docker-compose.yaml
      key: $.x-base.image
```


with

```
x-base: &base
  image: hugomods/hugo:ci-0.128.0
  volumes:
    - .:/src

services:
  status:
    <<: *base
    ports:
      - 1313:1313
    command: "hugo serve --bind 0.0.0.0 --cleanDestinationDir --disableFastRender --printPathWarnings --printMemoryUsage --noHTTPCache"
  build:
    <<: *base
    profiles:
      - donotstart
```
