### ISSUE TITLE
YAML: Comments seemingly randomly chosen for removal

### ISSUE THREAD

**Issue by jimid27** [updatecli/updatecli#1351]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently, updatecli is removing some comments that we have in place in our YAML definitions.  Specifically those comments that are at the beginning of a file.  Feels similar-ish to https://github.com/updatecli/updatecli/issues/903
Seems to ignore most if not all comments that are inline w/ code fine but removes most comments that are on their own line. 

![Screenshot 2023-05-30 at 11 19 32 AM](https://github.com/updatecli/updatecli/assets/12978862/daee08cb-9d21-4cd5-86f7-83817c2f5d64)
![Screenshot 2023-05-30 at 11 26 19 AM](https://github.com/updatecli/updatecli/assets/12978862/43d2f523-a7b7-41f4-96cd-8f6f8196ceb7)

### Expected Behavior

Comments are ignored by UpdateCLI for YAML unless specifically included in the manifest definition.

### Steps To Reproduce

Manifest (excerpt related to above):
```
---
sources:
  istio_gateway:
    kind: helmchart
    spec:
      url: https://istio-release.storage.googleapis.com/charts
      name: gateway
      version: 1.*.*
  prometheus_postgres:
    kind: helmchart
    spec:
      url: https://prometheus-community.github.io/helm-charts
      name: prometheus-postgres-exporter
      version: 4.*.*
conditions: {}
targets:
  istio_gateway:
    name: bump chart dependencies
    kind: yaml
    spec:
      file: apps/istio/dataplane/gateway-helmrelease.yaml
      key: spec.chart.spec.version
    sourceid: istio_gateway
  istio_gateway_label:
    name: bump chart dependencies
    kind: yaml
    spec:
      file: apps/istio/dataplane/gateway-helmrelease.yaml
      key: 'spec.values.labels.service\.istio\.io/canonical-revision'
    sourceid: istio_gateway
  prometheus_exporter:
    name: bump chart dependencies
    kind: yaml
    spec:
      file: apps/monitoring/prometheus/metrics/postgres-exporter.yaml
      key: spec.chart.spec.version
    sourceid: prometheus_postgres
```

### Environment

```markdown
- OS: Ubuntu 22.04 (ubuntu-latest GHA)
- updatecli: v0.52.0
```
