### ISSUE TITLE
[condition][dockerfile] It's not possible to define a condition on a Dockerfile arg with a default value

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#136]
**Describe the bug**
```
conditions:
  isARGTINIVERSIONSet:
    name: Is ENV TINI_VERSION set 
    kind: dockerfile
    spec:
      file: Dockerfile
      Instruction: ARG[1][0]
      Value: "tini_version"
```

for the Dockerfile instruction `ARG tini_version=v0.19.0`, like for ENV, I expect  ARG[1][0] to be 'tini_version' but it is 'tini_version=v0.19.0'

**Version (please complete the following information):**
 - OS: linux
 - Version: v0.30.0

**Comment by dduportal** [comment]
Proposal for a syntax adaptation for the dockerfile's kind (UX), to help solving this issue:

The idea is to:
* Not using the array syntax `[]`
* Delegate the "research" of the expected instruction to `updateCLI`

```
conditions:
  isENVSet:
    name: Is ENV HELM_VERSION set
    kind: dockerfile
    spec:
      ## Search for the presence of an `ENV HELM_VERSION=.*` instruction.
      ## Condition is true if it fins 1 or more occurrences in the Dockerfile
      file: docker/Dockerfile
      Instruction: 
        env: "HELM_VERSION"
targets:
  updateENVHELMVERSION:
    name: Update HELM_VERSION
    kind: dockerfile
    spec:
      ## Update all the occurrences of `ENV HELM_VERSION=.*`
      file: docker/Dockerfile
      Instruction: 
        env: "HELM_VERSION"
```

Same could be applied for ARGS and FROM:

```
targets:
  updateARGHELMVERSION:
    name: Update HELM_VERSION
    kind: dockerfile
    spec:
      ## Update all the occurrences of `ARG HELM_VERSION=.*`, but do not update `ARG HELM_VERSION` with no value
      file: docker/Dockerfile
      Instruction: 
        arg: "HELM_VERSION"
```

```
targets:
  updateFROMGOVERSION:
    name: Update GO_VERSION
    kind: dockerfile
    spec:
      ## Update all the occurrences of `FROM golang.*` 
      file: docker/Dockerfile
      Instruction: 
        from: "golang" # or "golang:alpine" for tag strict matching
```

Additionnaly:

* A new keyword `onlyFirst` could be added, with a default value set to `false`, valid for the 3 instructions (for `ENV` and `arg` it is straightforward. For the `FROM` it would cover cases with multistage builds)

```
targets:
  updateENVHELMVERSION:
    name: Update HELM_VERSION
    kind: dockerfile
    spec:
      ## Update only the first occurrence of `ENV HELM_VERSION=.*`
      file: docker/Dockerfile
      Instruction: 
        env:
          key: "HELM_VERSION"
          onlyFirst: true
```

* A new keyword `onlyDefaultValues` (default to `true`) could be added but only for the `ARG` instruction, to only replace the instruction holding a (default) value (e.g. `ARG TERRAFORM_VERSION=0.14.5`), and not the unvalued declarations (e.g. `ARG TERRAFORM_VERSION`):

```
targets:
  updateARGTERRAFORMVERSION:
    name: Update TERRAFORMVERSION
    kind: dockerfile
    spec:
      ## Update all the occurrences of `ARG TERRAFORMVERSION=.*` and `ARG TERRAFORMVERSION`
      file: docker/Dockerfile
      Instruction: 
        env:
          key: "TERRAFORMVERSION"
          onlyDefaultValues: false
```
