### ISSUE TITLE
Proxy implementation in golang/gomod missing

### ISSUE THREAD

**Issue by dginther** [updatecli/updatecli#1370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using the crawler golang/gomod, updatecli does not seem to respect the env vars GOPROXY or GOPRIVATE when they are set in the environment, and there is no way to set them in the plugin options.

### Expected Behavior

Expected either the env vars to be respected OR have a way to set the proxy and private settings.

### Steps To Reproduce

In private enterprise environment, set GOPROXY and GOPRIVATE variable appropriately
use:
```
  autodiscovery:
    scmid: name of repo here
    actionid: default
    groupby: all
    crawlers:
      golang/gomod:
        versionfilter:
          kind: semver
          pattern: patch
```

GOPROXY var is not respected, the updatecli execution still results in: 
```
github.com/spf13/cobra: github.com/spf13/cobra@v1.0.0: Get "https://proxy.golang.org/github.com/spf13/cobra/@v/v1.0.0.zip": dial tcp 142.251.40.113:443: i/o timeout
```

### Environment

```markdown
- OS: Ubuntu 20.04
- updatecli: 0.52.0
```
