### ISSUE TITLE
Feature Request: Support Docker Bake variables update

### ISSUE THREAD

**Issue by dduportal** [updatecli/updatecli#1378]
### Is your feature request related to a problem?

Docker [Buildx](https://docs.docker.com/build/) allows using a file to define a set of container images to build to improve maintainers life.

This ["bake"](https://docs.docker.com/build/bake/) sub-command supports JSON, Yaml but also HCL files as per https://docs.docker.com/build/bake/reference/#file-format.

HCL is the default as it provides a rich feature set including custom functions (making usage of docker compose yaml or json not possible).

The Docker bake file using HCL have `variable` top-level keyword with default values (https://docs.docker.com/build/bake/reference/#variable) that I would like to track using `updatecli`.

Example on the official Jenkins controller image: https://github.com/jenkinsci/docker/blob/master/docker-bake.hcl.

### Solution you'd like

A native support for, at least the `variable` of docker bake file could make our life easier:

Something looking like:

```
targets:
  updateDockerBake:
    name: "Update the value of the base image (ARG ALPINE_TAG) in the docker-bake.hcl"
    kind: dockerBake
    sourceid: alpineVersion
    spec:
      file: docker-bake.hcl
      variable: ALPINE_FULL_TAG
      # Default value come from the source
      # value: <whatever>
    scmid: default
```

### Alternatives you've considered

- Today, we are using the `file` provider with a tedious regex. It works, but it is really hard to write and maintain
- An eventual HCL resource could help (same as for https://github.com/updatecli/updatecli/issues/534) instead if there is a "generic" way to request HCL files like we do with yaml
