### ISSUE TITLE
updatecli can't cope with Ruby releases

### ISSUE THREAD

**Issue by gounthar** [updatecli/updatecli#1391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The latest Ruby version is `3.2.2`.
I would like `updatecli` to retrieve `3.2.2` and not `3.0.6`.

```
SOURCES
=======

rubyLatestVersionByLatest
-------------------------
DEBUG: GitHub Api credit used used 1, remaining 4977 (reset at 2023-06-21T15:50:08Z)
DEBUG: 8 releases found
Searching for version matching pattern "latest"
✔ Github Release version "v3_0_6" found matching pattern "latest"

rubyLatestVersionByRegex
------------------------
DEBUG: GitHub Api credit used used 1, remaining 4975 (reset at 2023-06-21T15:50:08Z)
DEBUG: 8 releases found
Searching for version matching pattern "v3_(\\d+)_(\\d+)$"
✔ Github Release version "v3_0_6" found matching pattern "v3_(\\d+)_(\\d+)$"

rubyDockerImageLatestVersion
----------------------------
DEBUG: Searching tags for the image "index.docker.io/library/ruby"
DEBUG: 1130 Docker image tag(s) found

Searching for version matching pattern "\\d\\.\\d\\.\\d$"
✔ Docker Image Tag "3.2.2" found matching pattern "\\d\\.\\d\\.\\d$"
```

### Expected Behavior

The latest Ruby version is `3.2.2`.
I would like `updatecli` to retrieve `3.2.2` and not `3.0.6`.

### Steps To Reproduce

```
---
name: Bump the various docker images versions for the Ruby version

scms:
  default:
    kind: github
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: "{{ .github.owner }}"
      repository: "{{ .github.repository }}"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      branch: "{{ .github.branch }}"

sources:
  rubyLatestVersionByRegex:
    name: "Get the latest Ruby version by regex"
    kind: githubrelease
    spec:
      owner: "ruby"
      repository: "ruby"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      versionfilter:
        kind: regex
        pattern: 'v3_(\d+)_(\d+)$'
    transformers:
      - trimprefix: "v"
      - replacer:
         from: "_"
         to: "."
  rubyLatestVersionByLatest:
    name: "Get the latest Ruby version"
    kind: githubrelease
    spec:
      owner: "ruby"
      repository: "ruby"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      versionfilter:
        kind: latest
    transformers:
      - trimprefix: "v"
      - replacer:
          from: "_"
          to: "."
  rubyDockerImageLatestVersion:
    kind: dockerimage
    name: "Get the latest Ruby version"
    spec:
      image: "ruby"
      tagFilter: >-
        \d\.\d\.\d$
      versionfilter:
        kind: regex
        pattern: >-
          \d\.\d\.\d$

conditions:
  testRubyAlpineImagePublished:
    name: "Test ruby:3.x.x-alpine-3.xx docker image tag"
    kind: dockerimage
    sourceid: rubyLatestVersionByLatest
    spec:
      image: "ruby"
      tag: '{{ source "rubyLatestVersionByLatest" }}'
```

On WSL2/Debian, I run the following command:
`updatecli diff --debug --config updatecli/updatecli.d/ruby-github-release.yaml --values updatecli/values.github-action.yaml`

gives:

```
+++++++++++
+ PREPARE +
+++++++++++

Loading Pipeline "updatecli/updatecli.d/ruby-github-release.yaml"
DEBUG: stage: git-clone


SCM repository retrieved: 1
DEBUG: cloning git repository: https://github.com/jenkins-infra/jenkins.io.git in /tmp/updatecli/github/jenkins-infra/jenkins.io
DEBUG:
DEBUG: fetching remote branches
DEBUG: stage: git-checkout

DEBUG: checkout branch "updatecli_c2baf2798f194cd1a3151fa722802086999a172ee2c3a46012a6f1942f7b49ec", based on "master" to directory "/tmp/updatecli/github/jenkins-infra/jenkins.io"
DEBUG:
DEBUG: branch 'updatecli_c2baf2798f194cd1a3151fa722802086999a172ee2c3a46012a6f1942f7b49ec' doesn't exist, creating it from branch 'master'
DEBUG: branch "updatecli_c2baf2798f194cd1a3151fa722802086999a172ee2c3a46012a6f1942f7b49ec" successfully created


++++++++++++++++++
+ AUTO DISCOVERY +
++++++++++++++++++



++++++++++++
+ PIPELINE +
++++++++++++



################################################################
# BUMP THE VARIOUS DOCKER IMAGES VERSIONS FOR THE RUBY VERSION #
################################################################


SOURCES
=======

rubyLatestVersionByLatest
-------------------------
DEBUG: GitHub Api credit used used 1, remaining 4977 (reset at 2023-06-21T15:50:08Z)
DEBUG: 8 releases found
Searching for version matching pattern "latest"
✔ Github Release version "v3_0_6" found matching pattern "latest"


CHANGELOG:
----------

Release published on the 2023-03-30 13:13:37 +0000 UTC at the url https://github.com/ruby/ruby/releases/tag/v3_0_6

## Security Fixes

* [CVE-2023-28755: ReDoS vulnerability in URI](https://www.ruby-lang.org/en/news/2023/03/28/redos-in-uri-cve-2023-28755/)
* [CVE-2023-28756: ReDoS vulnerability in Time](https://www.ruby-lang.org/en/news/2023/03/30/redos-in-time-cve-2023-28756/)


## What's Changed

* [Bug #19187: Ruby 3.1.3 testsuite fails after timezone 2022g update is applied](https://bugs.ruby-lang.org/issues/19187)
* [Rename --jit to --mjit by k0kubun · Pull Request #5248](https://github.com/ruby/ruby/pull/5248)
* [Merge URI-0.10.2 for Ruby 3.0 by hsbt · Pull Request #7607](https://github.com/ruby/ruby/pull/7607)
* [Bug #19161: Cannot compile 3.0.5 or 3.1.3 on Red Hat Enterprise Linux 7](https://bugs.ruby-lang.org/issues/19161)

Note: This list is automatically generated by tool/gen-github-release.rb. Because of this, some commits may be missing.

## Full Changelog

https://github.com/ruby/ruby/compare/v3_0_5...v3_0_6



rubyLatestVersionByRegex
------------------------
DEBUG: GitHub Api credit used used 1, remaining 4975 (reset at 2023-06-21T15:50:08Z)
DEBUG: 8 releases found
Searching for version matching pattern "v3_(\\d+)_(\\d+)$"
✔ Github Release version "v3_0_6" found matching pattern "v3_(\\d+)_(\\d+)$"


CHANGELOG:
----------

Release published on the 2023-03-30 13:13:37 +0000 UTC at the url https://github.com/ruby/ruby/releases/tag/v3_0_6

## Security Fixes

* [CVE-2023-28755: ReDoS vulnerability in URI](https://www.ruby-lang.org/en/news/2023/03/28/redos-in-uri-cve-2023-28755/)
* [CVE-2023-28756: ReDoS vulnerability in Time](https://www.ruby-lang.org/en/news/2023/03/30/redos-in-time-cve-2023-28756/)


## What's Changed

* [Bug #19187: Ruby 3.1.3 testsuite fails after timezone 2022g update is applied](https://bugs.ruby-lang.org/issues/19187)
* [Rename --jit to --mjit by k0kubun · Pull Request #5248](https://github.com/ruby/ruby/pull/5248)
* [Merge URI-0.10.2 for Ruby 3.0 by hsbt · Pull Request #7607](https://github.com/ruby/ruby/pull/7607)
* [Bug #19161: Cannot compile 3.0.5 or 3.1.3 on Red Hat Enterprise Linux 7](https://bugs.ruby-lang.org/issues/19161)

Note: This list is automatically generated by tool/gen-github-release.rb. Because of this, some commits may be missing.

## Full Changelog

https://github.com/ruby/ruby/compare/v3_0_5...v3_0_6



rubyDockerImageLatestVersion
----------------------------
DEBUG: Searching tags for the image "index.docker.io/library/ruby"
DEBUG: 1130 Docker image tag(s) found

Searching for version matching pattern "\\d\\.\\d\\.\\d$"
✔ Docker Image Tag "3.2.2" found matching pattern "\\d\\.\\d\\.\\d$"
DEBUG: empty changelog found for the source


CONDITIONS:
===========

testRubyAlpineImagePublished
----------------------------
✔ The Docker image index.docker.io/library/ruby:3.0.6 (amd64) exists and is available.

=============================

REPORTS:


- Bump the various docker images versions for the Ruby version:
        Source:
                ✔ [rubyDockerImageLatestVersion] Get the latest Ruby version (kind: dockerimage)
                ✔ [rubyLatestVersionByLatest] Get the latest Ruby version (kind: githubrelease)
                ✔ [rubyLatestVersionByRegex] Get the latest Ruby version by regex (kind: githubrelease)
        Condition:
                ✔ [testRubyAlpineImagePublished] Test ruby:3.x.x-alpine-3.xx docker image tag (kind: dockerimage)

Run Summary
===========
Pipeline(s) run:
  * Changed:    0
  * Failed:     0
  * Skipped:    1
  * Succeeded:  0
  * Total:      1
```

### Environment

```markdown
- OS: WSL2/Debian
- updatecli: 0.49.2
```

**Comment by olblak** [comment]
The problem here is the we have different interpretation of "latest"

According the log `v3_0_6`  was released on `2023-03-30 21:41:03 +0900`
* `git log -1 --format=%ai v3_0_6`

While v3_2_2 was released on `2023-03-30 20:06:29 +0900`
* `git log -1 --format=%ai v3_2_2` 

This means that v3_0_6 is more recent than `v3_2_2` 

They are different ways to sort a list of tag but the challenge is to express the meaning we are looking for

**Comment by gounthar** [comment]
Hopefully, the next `ruby` release will sort everything out... or make things even worse. 🤣

**Comment by olblak** [comment]
Using the github release seems to be what you are looking for 

```
sources
  rubyLatestVersionGithubRelease:
    name: "Get the latest Ruby version"
    kind: githubrelease
    spec:
      owner: ruby
      repository: ruby
      token: '{{ requiredEnv "UPDATECLI_GITHUB_TOKEN" }}'
      username: '{{ requiredEnv "UPDATECLI_GITHUB_ACTOR" }}'
      typefilter:
        latest: true

```
