### ISSUE TITLE
Feature Request: gittag plugin is missing the parameter tag

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#1394]
### Is your feature request related to a problem?

while writing gittag e2e tests, I noticed the `gittag` plugin wasn't consistence with the plugins `gitea/tag`, `gitlab/tag`, `stash/tag` 

The condition is missing the parameter `tag` such as 

```
conditions:
  master:
    name: Get Latest committed branch
    kind: gittag
    scmid: default
    disablesourceinput: true
    spec:
      tag: 0.7.2
```

### Solution you'd like

We need a new parameter `tag`
