### ISSUE TITLE
Feature Request: Allow configuration of commit branch

### ISSUE THREAD

**Issue by JohnniDi** [updatecli/updatecli#1399]
### Is your feature request related to a problem?

Currently opencli will push a new branch with changes that is named opencli_\<some long hash\>
This will not work with our internal processes and especially not with our remaining jenkins automation.

### Solution you'd like

It would be great if the scm  definitions allow a configuration to give the working branch a specific name.

### Anything else?

This seems to be already somewhat prepared:
git
```
func (g *Git) GetBranches() (sourceBranch, workingBranch, targetBranch string) {
	sourceBranch = g.spec.Branch
	workingBranch = g.spec.Branch
	targetBranch = g.spec.Branch
```
stash
```
func (s *Stash) GetBranches() (sourceBranch, workingBranch, targetBranch string) {
	sourceBranch = s.Spec.Branch
	workingBranch = s.nativeGitHandler.SanitizeBranchName(fmt.Sprintf("updatecli_%v", s.pipelineID))
	targetBranch = s.Spec.Branch
```

**Comment by olblak** [comment]
Hi @JohnniDi,

Indeed we can easily expose a setting to customize `updatecli_`.
The second part of the working branch can already be customize with the pipelineid

@dduportal What would you think of adding the parameter `workingbranchprefix` for all scm excepted the `git` which do not handle.

So something like 

```
scms:
    default:
        kind: github
        spec:
            branch: main
            workingbranchprefix: "customPrefix/"
            email: me@olblak.com
            owner: updatecli
            repository: updatecli
            token: '{{ requiredEnv "UPDATECLI_GITHUB_TOKEN" }}'
            user: updatecli
            username: '{{ requiredEnv "UPDATECLI_GITHUB_ACTOR" }}'

```

**Comment by JohnniDi** [comment]
So for my specific use case example would be:

```scms:
    release:
        kind: stash
        spec:
            branch: master
            workingbranchprefix: "release/v"
            pipelineid: '{{ dynamicEnv form source }}'
            email: him@olblak.com
            owner: updatecli
            repository: updatecli
            token: '{{ requiredEnv "UPDATECLI_GITHUB_TOKEN" }}'
            user: updatecli
            username: '{{ requiredEnv "UPDATECLI_GITHUB_ACTOR" }}'`
            commitmessage:
                type: '<Jenkins Parameter>'
                body: '{{ dynamicEnv from source }}'
```

I'm just realizing this might not even be possible, there are not dynamic Envs right?
And the checkout and branch naming happens before the source step...
I could work around this by running updatecli twice, 1st to source the needed value into a temporary file and 2nd to write it to the correct branch.

**Comment by olblak** [comment]
> @olblak could the "workingbranchprefix" be templatized (with `{{ ... }}`) ?
> 
> Haven't looked closely at that part in the source but I guess it is not possible since the branch name must be determined (and used) before executing the sources.

Without looking at the code, I don't see why it wouldn't, the information is used the first time when we do a `git checkout` let say in the target.

> I'm just realizing this might not even be possible, there are not dynamic Envs right?

Yes you have, you can reuse source output value using "{{ source "sourceID" }}" such as 

```
pipelineid:
sources:
  default:
    kind: jenkins

  shell:
    kind: shell
    dependson:
      - default
    spec:
      command: 'echo {{ source "default" }}'
```

`dependson` is needed to enforce order

That's being said, your usecase is something that I never thought about, it may or may not work and you may also see side effects
