### ISSUE TITLE
Feature Request: Source to retrieve GitHub release artifacts

### ISSUE THREAD

**Issue by cedws** [updatecli/updatecli#1400]
### Is your feature request related to a problem?

I'm giving updatecli a try and I'd like to use it to update the download link to the latest release artifact when a new one becomes available. The [GitHub Release](https://www.updatecli.io/docs/plugins/resource/github_release/) source appears to just get the latest released tag.

### Solution you'd like

Potentially, a "GitHub Release Artifact" source that behaves similarly to the GitHub Release source, but retrieves a link to one of the release artifacts based on a set of filters. For instance, you may want to only grab a release artifact that contains "amd64" and "windows" in the name.

### Alternatives you've considered

In some cases it may be possible to use transformers to build a download link from the release name, but in mine it isn't. The artifacts have the release date in their names.

**Comment by olblak** [comment]
Thanks for your interest. 
Usually as a fallback I rely on the json plugin to fetch the information I am looking for.

for example:

```
sources:
  single:
    kind: json
    name: Get latest rpm package download link
    spec:
      file: https://api.github.com/repos/updatecli/updatecli/releases
      key: ".[0].assets.(name=updatecli_amd64.rpm).browser_download_url"
```

You could replace updatecli with your repository

The json plugin uses Dasel to query json data 
-> https://daseldocs.tomwright.me 

You could also combine information from different sources as well
