### ISSUE TITLE
Fail cloning git repository

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#1408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For some reason, the following manifest won't work 

```
scms:
  git:
    kind: git
    spec:
      #url: "https://github.com/epinio/epinio.git"
      url: "git@github.com:epinio/epinio.git"
      branch: main
  github:
    kind: github
    spec:
      owner: epinio
      repository: epinio
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      branch: main
```

When running that pipeline, it just creates an empty directory.

### Steps To Reproduce

1. updatecli diff --config /tmp/epinio.yaml --debug

### Environment

```markdown
- OS:linux
- updatecli: v0.54.0
```

### Anything else?

Worth mentioning, that repository uses git submodule and I am aware of a few issues related to git submodule in the go-git library

Could be related to https://github.com/updatecli/updatecli/issues/1098
