### ISSUE TITLE
Feature Request: allow defining target YAML type (or always use string)

### ISSUE THREAD

**Issue by jawnsy** [updatecli/updatecli#1416]
### Is your feature request related to a problem?

Some images (e.g. `docker.io/debezium/server`) use tags like `2.4`, which are parseable as floating point numbers. When using `target` to update a field, `updatecli` currently always writes a bare number (i.e. `2.0.4` or `2.4`), which means the behavior is inconsistent depending on whether the version number is a full semver (major.minor.patch) or just a two-part semver (major.minor only). In the former case, YAML parsers will detect that the bare `2.0.4` is a string, since there's multiple dots. In the latter case, YAML parsers will sometimes use a schema to force the type, or otherwise interpret it as a floating-point number, since there's only one dot.

### Solution you'd like

There's a few possible solutions that would resolve this issue:

* Always write these versions as strings
* Allow the output type to be configured (i.e. tell `updatecli` that the YAML path is an integer literal, float literal, etc)
* Use the prior field value to detect the type (i.e. if the current value is a string, then write the updated value as a string, too)

### Alternatives you've considered

A workaround is to use something like this:

```
sources:
  debezium_server:
    kind: dockerimage
    spec:
      image: docker.io/debezium/server
      versionFilter:
        kind: semver
    transformers:
      # this hack is necessary because Debezium uses versions like "2.4",
      # which are detected as a float, but must be a string for Flux
      - addprefix: "'"
      - addsuffix: "'"
conditions: {}
targets:
  debezium_server:
    name: bump image version
    kind: yaml
    spec:
      files:
        - debezium.yaml
      key: $.spec.postBuild.substitute.debezium_server_version
    sourceid: debezium_server
```

Another option is to collaborate with upstream to get the versions published as `2.4.0` instead, but this is a general problem with different images.

**Comment by olblak** [comment]
Thanks for the opening this issue. This usecase seems legit to me and I would even go one step further, we may need to enforce other type like bool, int, etc.  

```
targets:
  debezium_server:
    name: bump image version
    kind: yaml
    spec:
      files:
        - debezium.yaml
      key: $.spec.postBuild.substitute.debezium_server_version
      valuetype: string
    sourceid: debezium_server
```

**Comment by olblak** [comment]
I am sure which key should be used here, neither if it's really worth using the transformer on the target does the work 

```
sources:
  default:
    kind: jenkins

targets:
  default:
    kind: yaml
    spec:
      file: /tmp/data.yaml
      key: $.version
    transformers:
      - addprefix: '"'
        addsuffix: '"' 
```

worth reminding, a transformer defined on a target only apply to the default input for the target, so it won't work if `disablesourceinput` is used

but we could also use 

```
sources:
  default:
    kind: jenkins

targets:
  default:
    kind: yaml
    spec:
      file: /tmp/data.yaml
      disablesourceinput: true
      key: $.version
      value: '"{{ source "default" }}"'
```
