### ISSUE TITLE
helm resource reorders yaml

### ISSUE THREAD

**Issue by mcwarman** [updatecli/updatecli#1442]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behaviour

When using helm target the outputted yaml gets reordered, which although isn't "important" is annoying.

### Expected Behaviour

Order is preserved.

### Steps To Reproduce

`Chart.yaml`

```yaml
apiVersion: v2
name: webapp
version: 0.3.0
appVersion: 0.1.0
dependencies:
  - name: db
    version: 1.0.0
```

`updatecli.yml`

```yaml
targets:
  chart:
    kind: helmchart
    spec:
      name: "testdata"
      file: "Chart.yaml"
      key: "dependencies[0].version"
      versionincrement: none
```

### Environment

```markdown
- OS: Ubuntu 20.04
- updatecli: v0.55.2
```

### Anything else?

After looking into the code [`(c *Chart) MetadataUpdate(chartPath string, dryRun bool) error`](https://github.com/updatecli/updatecli/blob/main/pkg/plugins/resources/helm/utils.go#L161C5-L161C5) is what's doing it.

Looking at the other parts of the resources, maybe it should it be refactored to use `yaml.Source` and `yaml.Target` similar to the version itself, and move away from roundtripping the yaml.

#693 could possibly be tacked as a part of this refactor passing in `scm` correctly, or at the very least create a foundation for it.

**Comment by mcwarman** [comment]
If the suggested solution makes sense, happy to take a crack at it.

**Comment by olblak** [comment]
Interesting I am heavily using this plugin for various projects and outside of the initial reformatting done by go-yaml, I am not aware of additional reformatting.

I don't even know if it's possible to avoid the first formatting, feel free to contribute an improvement if you find a way to reproduce in the UT

Worth mentioning that the helm plugin relies on the yaml plugin.

```
targets:
  chart:
    kind: helmchart
    spec:
      name: "testdata"
      file: "Chart.yaml"
      key: "dependencies[0].version"
      versionincrement: none
```

On my projects, I migrated all helm dependencies update using a similar manifest you show to the helm autodiscovery which works great in my usecase, like 

<details>

```
name: Default Autodiscovery
actions:
    default:
        kind: github/pullrequest
        spec:
            automerge: false
            labels:
                - chore
                - dependencies
        scmid: default
scms:
    default:
        kind: github
        spec:
            branch: main
            email: me@olblak.com
            owner: updatecli
            repository: charts
            token: '{{ requiredEnv "UPDATECLI_GITHUB_TOKEN" }}'
            user: updatecli
            username: '{{ requiredEnv "UPDATECLI_GITHUB_ACTOR" }}'

autodiscovery:
  groupby: all 
  scmid: default
  actionid: default
  crawlers:
    helm:
      versionfilter:
        kind: semver
```
</details 

The only drawback is the manifest generated by the helm autodiscovery can't disable the chart default `versionincrement` which I would need for some project that I am maintaining like on [epinio](https://github.com/epinio/helm-charts/tree/main/updatecli/updatecli.d/autodiscovery).
