### ISSUE TITLE
Feature Request: Allow to use file pattern in the file/files key

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#1453]
### Is your feature request related to a problem?

In the current situation, we only specifies file/files that already exist, such as

```
targets:
  download-url:
    name: 'Update Epinio Installation URL'
    kind: file
    spec:
      files: 
        - docs/tutorials/single-dev-workflow.md
        - docs/howtos/install_epinio_on_rancher_desktop.md
      matchpattern: 'https://github.com/cert-manager/cert-manager/releases/download/(.*)/'
      replacepattern: 'https://github.com/cert-manager/cert-manager/releases/download/{{ source "cert-manager" }}/'
    scmid: default
    disablesourceinput: true
```

The problem is we need to update the updatecli manifest each time we add additional files in the future.

### Solution you'd like

I like to be able to use file path such as:

```
targets:
  download-url:
    name: 'Update Epinio Installation URL'
    kind: file
    spec:
      files: 
        - docs/*
        - .github/workflows/*
      matchpattern: 'https://github.com/cert-manager/cert-manager/releases/download/(.*)/'
      replacepattern: 'https://github.com/cert-manager/cert-manager/releases/download/{{ source "cert-manager" }}/'
    scmid: default
    disablesourceinput: true

```
