### ISSUE TITLE
cargopackage: Conditions error on non existing package

### ISSUE THREAD

**Issue by loispostula** [updatecli/updatecli#1459]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently, if using condition with `kind: cargopackage` for a non existing package, the condition errors. 

### Expected Behavior

When the package does not exist the condition should not errored.

### Steps To Reproduce

Given the following config:
```yaml
name: Retrieve the latest Cargo Package Version

scms:
  private-registry:
    kind: git
    spec:
      url: "https://github.com/updatecli-test/fake-cargo-registry.git"
      branch: "main"

conditions:
  existing-package-private-reg:
    name: Test if test-crate-2 0.1.0 exists on private registry
    kind: cargopackage
    scmid: private-registry
    spec:
      package: test-crate-2
      version: 0.1.0
  existing-package-not-existing-version-private-reg:
    name: Test if test-crate-2 0.6.0 does not exists on private registry
    kind: cargopackage
    scmid: private-registry
    failwhen: true
    spec:
      package: test-crate-2
      version: 0.6.0
  non-existing-package-private-reg:
    name: Test if non-existing-test-crate 0.1.0 does not exists on private registry
    kind: cargopackage
    scmid: private-registry
    failwhen: true
    spec:
      package: non-existing-test-crate
      version: 0.1.0
  existing-package-public-reg:
    name: Test if rand version exists on public reg
    kind: cargopackage
    spec:
      package: rand
      version: 0.7.2
  existing-package-p-not-existing-version-public-reg:
    name: Test if rand version 99.99.99 does not exists on public reg
    kind: cargopackage
    failwhen: true
    spec:
      package: rand
      version: 99.99.99
  non-existing-package-public-reg:
    name: Test if non-existing-package-to-be-sure-123456 does exists on public reg
    kind: cargopackage
    failwhen: true
    spec:
      package: non-existing-package-to-be-sure-123456
      version: 0.7.2
```

All condition should be met. But this errors

### Environment

```markdown
- OS:
- updatecli:
```
