### ISSUE TITLE
Add string matcher

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#152]
**Is your feature request related to a problem? Please describe.**
I am looking for a way to extract sub information from a string manipulated by a stage where
* source would extract sub information based on a string
* a condition would test that the match works
* a target would only use the value returned by the regex

**Describe the solution you'd like**
I am looking to provide a regex expression to the key match, as in the following example.
- > https://golang.org/pkg/regexp/#Match
```
source:
  name: "Retrieve latest jenkins weekly version"
  kind: githubRelease
  match: <regex> 
  spec:
    owner: "jenkinsci"
    repository: "jenkins"
    token: "{{ requiredEnv .github.token }}"
    username: "{{ .github.username }}"
    version: "latest"
```

**Describe alternatives you've considered**
/

**Additional context**
A typical scenario would be to retrieve package checksum for a specific version to run some validation like from 
https://releases.hashicorp.com/terraform/0.14.5/terraform_0.14.5_SHA256SUMS
