### ISSUE TITLE
Using rootdir without scm with helm autodiscovery triggers a failure

### ISSUE THREAD

**Issue by gionn** [updatecli/updatecli#1529]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

feels like updatecli internally it's referencing the Chart.yaml currently selected using a path relative to the dir specified in `rootdir`, but actually the PWD could be another directory (the directory from which I am running updatecli)

Errors are like:

```
alfresco-common
---------------
ERROR: reading yaml file: ✗ The specified file "alfresco-content-services/Chart.yaml" does not exist

✗ condition not met, skipping pipeline
```

### Expected Behavior

Charts dependencies should be processed correctly in the same way they are when not using `rootdir`

### Steps To Reproduce

I have a local [repository](https://github.com/Alfresco/acs-deployment) checked out which contains an `helm` folder, so I tried initially with this config:

```
name: "Helm autodiscovery for charts dependencies"
autodiscovery:
  crawlers:
    helm:
      rootdir: helm
      ignorecontainer: true
```

but running `updatecli apply --experimental` lead to multiple errors (one for each declared dependency of the `alfresco-content-services` chart) as reported above.

### Environment

```markdown
- OS: macOS Ventura 13.5.1 
- updatecli: v0.57.0
```
