### ISSUE TITLE
Feature Request: Update helmchart targets to wildcards from autodiscovery

### ISSUE THREAD

**Issue by klagroix** [updatecli/updatecli#1539]
### Is your feature request related to a problem?

I'm trying to setup helm autodiscovery to automatically create GitHub PRs when chart dependency updates are available.

Here is a simplified directory with multiple helm charts which each have their own dependencies:
```
├── README.md
├── apps
│   ├── external-dns
│   │   └── Chart.yaml
│   └── external-secrets
│       └── Chart.yaml
└── manifest.yaml
```

I initially tried with the following manifest but I get the note (from `--debug`) that a target is needed in order for an action to be run: `DEBUG: no target found, skipping action`

<details>
<summary>Autodiscovery manifest with no target</summary>

```
scms:
  default:
    kind: "github"
    spec:
      user: "GitHub Actions"
      email: "41898282+github-actions[bot]@users.noreply.github.com"
      username: "github-actions"
      branch: "main"
      owner: "foo"
      repository: "bar"
      token: "token"

autodiscovery:
  scmid: "default"
  crawlers:
    helm:
      versionincrement: "none"

actions:
  default:
    kind: github/pullrequest
    scmid: "default"
    spec:
      automerge: false
      draft: true
      labels:
        - "dependencies"
```

</details>

I then tried to add a target but it seems that the helmchart `spec.name` is required and doesn't allow wildcards. This means I need to specify each path as a target which seems to defeat some of the purpose of autodiscovery.

For example, this fails:

<details>
<summary>Autodiscovery manifest with wildard target (failing)</summary>

```
scms:
  default:
    kind: "github"
    spec:
      user: "GitHub Actions"
      email: "41898282+github-actions[bot]@users.noreply.github.com"
      username: "github-actions"
      branch: "main"
      owner: "foo"
      repository: "bar"
      token: "token"

autodiscovery:
  scmid: "default"
  crawlers:
    helm:
      versionincrement: "none"

targets:
  test:
    name: Generic target
    kind: helmchart
    spec:
      name: "apps/*"
      file: Chart.yaml
      key: "$.dependencies[0].version"
    scmid: default

# PR
actions:
  default:
    kind: github/pullrequest
    scmid: "default"
    spec:
      automerge: false
      draft: true
      labels:
        - "dependencies"
```

</details>

In order to get this to work, I need to specify the full path to the chart. Example:

```
targets:
  test:
    name: Generic target
    kind: helmchart
    spec:
      name: "apps/external-dns"
      file: Chart.yaml
      key: "$.dependencies[0].version"
    scmid: default
```

### Solution you'd like

I'd like to avoid having to add a target for each chart directory. 
It would be ideal if we could provide a wildcard path in the target that can match multiple charts in a repository.

### Alternatives you've considered

Currently my workaround is to not use autodiscover at all and instead wrap `updatecli` in a script that iterates over each directory in `apps/` then creates a custom values.yaml file which is fed into `updatecli`. While this works, it's more cumbersome than I'd like.

**Comment by olblak** [comment]
Thanks for opening the issue, I am wondering what's wrong with your attempt to do the autodiscovery manifest because your example is almost good and you shouldn't need to specify target.

Your are just missing the `actionid` in the autodiscovery section such as 
```
autodiscovery:
  scmid: "default"
  actionid: "default"
  crawlers:
    helm:
      versionincrement: "none"
``` 

The `scmid` specifies which git repository to use for fetching the helm files and the `actionID` specifies which action config to use when opening the pullrequest. 

I am wondering if you didn't forget the `--experimental` flag such as `updatecli diff --config manifest.yaml --experimental`

The "autodiscovery" analyzes directories/files to generate "common" manifest, you can: 
* see what would be generated by Updatecli by running `updatecli manifest show --experimental` or `updatecli manifest show --experimental --config manifest.yaml`
* see what would be changed by running `updatecli diff --experimental`
* apply the changes by running `updatecli apply --experimental --config yourManifest.yaml`

You can find working examples on https://github.com/epinio/helm-charts/tree/main/updatecli/updatecli.d/autodiscovery
And the github action workflow https://github.com/epinio/helm-charts/blob/main/.github/workflows/updatecli.yml

One of the challenges when it comes to dependency management with change validation is to handle the load of change request.

I am experimentation with three main different approaches that work differently depending on the project 

<details><summary>One pullrequest with all dependencies</summary>

```
---
name: "Autodiscovery"

autodiscovery:
  scmid: default
  actionid: default
  crawlers:
    helm:

scms:
  default:
    kind: "github"
    spec:
      user: "{{ .github.epinio.user }}"
      email: "{{ .github.epinio.email }}"
      owner: "{{ .github.epinio.owner }}"
      repository: "{{ .github.epinio.repository }}"
      token: '{{ requiredEnv .github.epinio.token }}'
      username: "{{ .github.epinio.username }}"
      branch: "{{ .github.epinio.branch }}"

actions:
  default:
    kind: "github/pullrequest"
    scmid: "default"
    spec:
      title: Bump all chart dependencies
      labels:
        - "dependencies"
        - "helm"
```

</details>


<details><summary>One pullrequest per dependencies</summary>

Only `groupby: individual` is changed here

```
---
name: "Autodiscovery"

autodiscovery:
  groupby: individual
  scmid: default
  actionid: default
  crawlers:
    helm:
scms:
  default:
    kind: "github"
    spec:
      user: "{{ .github.epinio.user }}"
      email: "{{ .github.epinio.email }}"
      owner: "{{ .github.epinio.owner }}"
      repository: "{{ .github.epinio.repository }}"
      token: '{{ requiredEnv .github.epinio.token }}'
      username: "{{ .github.epinio.username }}"
      branch: "{{ .github.epinio.branch }}"

actions:
  default:
    kind: "github/pullrequest"
    scmid: "default"
    spec:
      labels:
        - "dependencies"
        - "helm"
```

</details>


<details><summary>One pullrequest with all dependencies per chart</summary>

By using `only` we can filter down to a specific chart

```
---
name: "Autodiscovery"

autodiscovery:
  groupby: all
  scmid: default
  actionid: default
  crawlers:
    helm:
      versionfilter:
        kind: semver
      only:
        - path: "chart/epinio/*"

scms:
  default:
    kind: "github"
    spec:
      user: "{{ .github.epinio.user }}"
      email: "{{ .github.epinio.email }}"
      owner: "{{ .github.epinio.owner }}"
      repository: "{{ .github.epinio.repository }}"
      token: '{{ requiredEnv .github.epinio.token }}'
      username: "{{ .github.epinio.username }}"
      branch: "{{ .github.epinio.branch }}"

actions:
  default:
    kind: "github/pullrequest"
    scmid: "default"
    spec:
      title: Bump Epinio chart dependencies
      labels:
        - "dependencies"
        - "helm"
```

</details>
