### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#1573]
### Is your feature request related to a problem?

Today we can't contribute a new file **and** a new Updatecli manifest at the same time in the same pullrequest.
The reason is:

When a manifest relies on a git repository, Updatecli clone that repository in a temporary location **then** do all the changes there instead of doing the change in the local directory.

This UX experience is annoying because we need first to submit the change and in a second interation submit the Updatecli manifest.

### Solution you'd like

I would like that if I run `updatecli apply` from a git directory then I would like to use that directory instead of the one in "/tmp"

### Alternatives you've considered

At the moment, we usually "comment" all annoying scmid such as:

```
targets:
  default:
    name: Bump my target
    # scmid: default
   kind: yaml
   spec:
     file: data.yaml
```
