### ISSUE TITLE
Allow to define and use multiple sources 

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#158]
**Is your feature request related to a problem? Please describe.**

In the current state, we can only define one source per configuration file. 
Sometimes to update a target, the information need to come from multiple sources, as example is 
to fetch both the latest version of a package and its checksum from a different file. 
Combined with #156 this would also drastically simplify pull request as every changes related to one thing would be grouped in the same pull request.

Obviously having multiple sources would also mean that every condition/target should be able to either specify the source or fetch a default source value

**Describe the solution you'd like**
The sources would accept a map source identified by a sourceID
Conditions and and targets would accept the key "from" to define which source value to use by default

```
sources:
  source1:
    name: Fetch value from 
    kind: file
    spec:
      file: "http://example.com/checksum.txt"
  source2:
    name: Fetch package version
    kind: githubRelease
    spec:
      owner: owner
      repository: repositry
      username: username
      email: email
      token: token
conditions:
  condition1:
    from: source2
    name: Test Docker image publish
    kind: dockerImage
    spec:
     image: docker_image 
  condition2:
    from: source1
    name: Test content
    kind: file
    spec:
     file: "http://example.com/checksum.txt"
targets:
  targetID1:
    from: source1
    name: Test Docker image publish
    kind: dockerfile
    spec:
     file: Dockerfile
     instruction: ARG[0][0]
  targetID2:
    from: source2
    name: Test Docker image publish
    kind: dockerfile
    spec:
     file: Dockerfile
     instruction: ARG[1][0]

```

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by dduportal** [comment]
Adding proposal regarding sources inter-dependences (use case: update both terraform version and checksum)

```
---
sources:
  - name: Get Latest Terraform Release Version
    id: terraform_version
    kind: githubRelease
    spec:
      owner: "hashicorp"
      repository: "terraform"
      # token: "{{ requiredEnv "GITHUB_TOKEN" }}"
      # username: "dduportal"
      # version: "Match"
      # replaces:
      #   - from: "v"
      #     to: ""
  - name: Get Latest Terraform SHA Hash
    id: terraform_hash
    kind: file
    spec:
      file: https://terraform.io/downloads/${terraform_version}/checksum
      #file: https://terraform.io/downloads/{{ source "terraform_version" }}/checksum
      #file: https://terraform.io/downloads/{{ sources.id "terraform_version" }}/checksum
targets:
  - name: Update TERRAFORM_VERSION
    kind: yaml
    source: terraform_version
    spec:
      file: ".build-args.yml"
      key: "args.TERRAFORM_VERSION"
  - name: Update TERRAFORM_SHAS256
    kind: yaml
    source: terraform_hash
    spec:
      file: ".build-args.yml"
      key: "args.TERRAFORM_SHAS256"
...

```
