### ISSUE TITLE
[Docker Image] Condition does not honour the architecture filter

### ISSUE THREAD

**Issue by dduportal** [updatecli/updatecli#1582]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Conditions of kind `dockerimage` are ignoring the architecture filter.

It leads to production deployment issues (ref. https://github.com/jenkins-infra/kubernetes-management/pull/4338) as the container images versions are published even if the target architecture is not available.

### Expected Behavior

I expect conditions of kind `dockerimage` to fail when the provided architecture is invalid and/or does not have a corresponding manifest.

### Steps To Reproduce

Any manifest with the following conditions:

```
conditions:
  checkDockerImagePublishedList:
    name: "Test jenkinsciinfra/wiki:<latest_version> docker image tag"
    kind: dockerimage
    sourceid: latestRelease
    spec:
      image: "jenkinsciinfra/wiki"
      architectures:
        - tttt
        - aaaa
  checkDockerImagePublishedString:
    name: "Test jenkinsciinfra/wiki:<latest_version> docker image tag"
    kind: dockerimage
    sourceid: latestRelease
    spec:
      image: "jenkinsciinfra/wiki"
      architecture: bbb
```

must fail as these architecture do no exist

### Environment

```markdown
- OS: Ubuntu, macOS
- updatecli: v0.59.0
```

### Anything else?

This might be a broader issue (to the whole `dockerimage `resource 😱 )

**Comment by olblak** [comment]
I confirmed the bug.
I just tested the following manifest 

```
sources:
  latestRelease:
    kind: dockerimage
    spec:
      image: "jenkinsciinfra/wiki"
      versionfilter:
        kind: semver
        pattern: '0.1.6'
      architecture: arm64

conditions:
  checkDockerImagePublishedList:
    name: "Test jenkinsciinfra/wiki:<latest_version> docker image tag"
    kind: dockerimage
    sourceid: latestRelease
    spec:
      image: "jenkinsciinfra/wiki"
      architectures: 
        - arm64
```
