### ISSUE TITLE
Allow to configuration changelog

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#159]
**Is your feature request related to a problem? Please describe.**
Right now the way to retrieve a changelog depends on the source resource. 
It would be nice to allow to parameterized it.

**Describe the solution you'd like**

```
sources:
  source1:
    name: Fetch value from 
    kind: file
    spec:
      file: "http://example.com/checksum.txt"
    changelog:
        kind:
        spec:
            github:
                owner:
                ....
```

**Describe alternatives you've considered**

**Additional context**
