### ISSUE TITLE
JSON target does not update values

### ISSUE THREAD

**Issue by kuisathaverat** [updatecli/updatecli#1590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you configure a target of kind `json`, the values from the source will be ignored.

### Expected Behavior

The target should set the values from the source configured.

### Steps To Reproduce

1. Create the following pipeline
```
# yaml-language-server: $schema=https://www.updatecli.io/schema/latest/config.json
title: Test JSON file
name: Test JSON file
scms:
  githubConfig:
    kind: "github"
    spec:
      owner: "octocat"
      repository: "octocat.github.io"
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      branch: "master"
actions:
  elasticStack:
    kind: github/pullrequest
    scmid: githubConfig
    spec:
      mergemethod: squash
      title: '[updatecli] Test JSON file'
      description: 'Test modification of JSON files.'

sources:
  local:
    kind: shell
    spec:
      command: echo foo
      environments:
        - name: PATH
targets:
  localWithSource:
    name: "Test JSON file"
    scmid: githubConfig
    sourceid: local
    kind: json
    spec:
      file: "params.json"
      key: "name"
  localWithoutSource:
    name: "Test JSON file"
    scmid: githubConfig
    disablesourceinput: true
    kind: json
    spec:
      file: "params.json"
      key: "name"
      value: '{{ source `local` }}'
```
2. Run  `GITHUB_TOKEN=$(gh auth token) updatecli diff --config test-json.yml`
3. Check the logs
```
+++++++++++
+ PREPARE +
+++++++++++

Loading Pipeline "test-json.yml"

SCM repository retrieved: 1


++++++++++++++++++
+ AUTO DISCOVERY +
++++++++++++++++++



++++++++++++
+ PIPELINE +
++++++++++++



##################
# TEST JSON FILE #
##################


SOURCES
=======

local
-----
The shell 🐚 command "/bin/sh /var/folders/rd/4lpsq9tn2h35ty0nkl9g4hlh0000gn/T/updatecli/bin/560a70ed288bdcf100ccdaa3482cd087fb4542c36582d101147e5f0c8673bfee.sh" ran successfully with the following output:
----
foo
----
✔ shell command executed successfully


TARGETS
========

localWithoutSource
------------------

**Dry Run enabled**


key "name", from file "should be ", /var/folders/rd/4lpsq9tn2h35ty0nkl9g4hlh0000gn/T/updatecli/github/octocat/octocat.github.io/params.jsonupdated from "Octocat.github.io" to ""
⚠ - 

localWithSource
---------------

**Dry Run enabled**


key "name", from file "should be ", /var/folders/rd/4lpsq9tn2h35ty0nkl9g4hlh0000gn/T/updatecli/github/octocat/octocat.github.io/params.jsonupdated from "Octocat.github.io" to ""
⚠ - 


ACTIONS
========

[Dry Run] An action of kind "github/pullrequest" is expected.

=============================

REPORTS:



⚠ Test JSON file:
        Source:
                ✔ [local] 
        Target:
                ⚠ [localWithSource] Test JSON file
                ⚠ [localWithoutSource] Test JSON file


Run Summary
===========
Pipeline(s) run:
  * Changed:    1
  * Failed:     0
  * Skipped:    0
  * Succeeded:  0
  * Total:      1
```
the value provided by the source `local` is ignored.

### Environment

```markdown
- OS: macOS 13.5.2
- updatecli: 0.59.0
```

**Comment by olblak** [comment]
Thanks for opening, I had a quick look and the problem is the output message because the file is correctly updated.

I'll open a PR later today to fix the console message.

I'll also fix the file path in the message to show `params.json` instead of the full path on the local system

**Comment by csc-piscopo** [comment]
I am still experiencing this issue with v0.71.0. While the console messaging has changed the target fails:

```
key "version", from file "/tmp/updatecli/path/to/file/spec.json",  updated from "1.3.0" to "1.3.1"
DEBUG: fileInfo for /tmp/updatecli/path/to/file/spec.json mode=-rw-r--r--
DEBUG: user: username=updatecli, uid=1000, gid=1000
⚠ - 
DEBUG: Checking if local changes have been done that should be published

ERROR: something went wrong in target "updateApiValidatorSpecJson" : "target has no change message"

Pipeline "Bump imageVersion in values.yaml" failed
Skipping due to:
        targets stage:  "something went wrong during target execution"
```

My target configuration seems straight forward enough and the value does seem to be updating:

```
  updateApiValidatorSpecJson:
    name: "Update the value of spec.json"
    scmid: git-something-something
    sourceid: validatorSpec
    kind: json
    spec:
      file: path/to/file/spec.json
      key: version
```
