### ISSUE TITLE
Feature Request: Automated and controllable version increments for semver

### ISSUE THREAD

**Issue by jawnsy** [updatecli/updatecli#1598]
### Is your feature request related to a problem?

I'm unsure whether this feature request is for documentation for an example (in case I'm not using the settings correctly) or indeed a new feature.

**Problem statement**: to reduce risk and churn, we want to assess "major" upgrades on a different cadence from "patch" upgrades.

For example, if upgrading from version 4.x.x to 5.x.x, we want to review on a monthly cycle so that we can ensure there are no breaking changes and test accordingly. Additionally, some services, like Istio or Kubernetes, have significant changes in "minor" releases (e.g. 1.17.0 to 1.18.0) so we would like to update the minor releases monthly, and update patch releases otherwise.

For minor releases (e.g. Istio 1.17.1 to 1.17.2), we would like to review and apply patches on a weekly basis, since the risk should be low and we would pick up security patches and bug fixes as part of this.

### Solution you'd like

Ideally (and perhaps `versionIncrement` already does this), we would have a way to specify that we are willing to accept minor updates or patch updates for a given source. Then, if the current version is 1.17.1, and upstream available versions are 1.17.2 and 1.18.0, updatecli should choose 1.17.2.

Alternatively, some way to support inheritance between two updatecli configs (similar to [Docker Compose's `extends` syntax](https://docs.docker.com/compose/multiple-compose-files/extends/)) would be useful. In this case, we could reduce duplication by having our minor update config extend our major update config.

### Alternatives you've considered

We are currently using two separate configuration files.

In the config file that we run monthly, we use:

```yaml
sources:
  cert_manager:
    kind: helmchart
    spec:
      url: https://charts.jetstack.io
      name: cert-manager
      versionFilter:
        kind: semver

targets:
  cert_manager:
    name: bump chart dependencies
    kind: yaml
    spec:
      file: apps/cert-manager/helmrelease/cert-manager.yaml
      key: $.spec.chart.spec.version
    sourceid: cert_manager
    transformers:
      - trimprefix: v
```

Note that we are not using `kind: helmchart` for the target because we are updating a file containing a HelmRelease (a Custom Resource Definition provided by Flux CD)

In the config file that we run weekly, we instead add a version filtering pattern:

```yaml
sources:
  cert_manager:
    kind: helmchart
    spec:
      url: https://charts.jetstack.io
      name: cert-manager
      versionFilter:
        kind: semver
        pattern: 1.*.* # this is the only difference

targets:
  cert_manager:
    name: bump chart dependencies
    kind: yaml
    spec:
      file: apps/cert-manager/helmrelease/cert-manager.yaml
      key: $.spec.chart.spec.version
    sourceid: cert_manager
    transformers:
      - trimprefix: v
```

This works well, but requires us to keep these two files in sync and there is significant duplication otherwise.

### Anything else?

I've tried using `versionIncrement: minor,patch` in both `source` and `target` blocks, but have not been able to achieve the desired behavior. This may be a misunderstanding on my part about what this feature does and how it works.

I've tried examining the source code but was unable to determine whether there was a way to get updatecli to exhibit the desired behavior: https://github.com/updatecli/updatecli/blob/4fa6b0e9dc8c8a1f65dc9ac3161692640567ceb5/pkg/plugins/utils/version/filter.go#L114-L125

**Comment by dduportal** [comment]
There are multiple things, I'll try to treat them separately to give you actionnables (I believe @olblak might also have ideas and feedbacks eventually).

----

First of all, you should change `versionFilter` to `versionfilter`. The documentation / example might not up to date about this.

I recommend you to use the JSON schema validation when editing your manifests (it is out of the box in VSCode) to point such syntax changes to the end users.
The output of `updatecli` most probably warns you when executing a `diff` or an `apply`.

I'm pointing this out as some features might be deprecated and disabled with the older syntax.

----

About the `pattern` for version filters of type `semver` are documented here: https://www.updatecli.io/docs/plugins/_versionfilter/ but lacks examples and/or link to the library we use under the hood: https://github.com/Masterminds/semver.
This library does not allow a direct syntax to "only" request a patch or minor without writing a specialized pattern (https://github.com/Masterminds/semver#tilde-range-comparisons-patch). But you can express some elements such as:

```yaml
# Only update to latest patch of the 1.17 line (don't update to 1.18.x)
# ref. https://github.com/Masterminds/semver#tilde-range-comparisons-patch
versionFilter:
  kind: semver
  pattern: '~1.17'

# Only update to latest patch of the 1.x line (don't update to 2.0.0)
# ref. https://github.com/Masterminds/semver#caret-range-comparisons-major
versionFilter:
  kind: semver
  pattern: '^1.x'
```

But you must have some prior knowledge to update (in these case you must keep the values `1.17` and `1` updated). Note that you can use the second manifest (the one trackin the major version monthly) to update the first ;)

--- 

Then, about the `versionIncrement`:

The documentation at https://www.updatecli.io/docs/plugins/autodiscovery/helm/ (check the list of parameters, last item of the array) mentions that it is only when using a `target` of kind `helm`. It's used to auto-increment a chart version when the chart is updated by `updatecli`.
The documentation is being updated since a few weeks so this might not have been easy to catch, no worries. But I'm pointing it to you to avoid having you wasting your time on this attribute for your use case, since your targets are CRDs (e.g. yaml file).

----

About the "code duplication":

There are a lot of discussion and back and forth work about this in updatecli and your testimony here really helps to provide real life use cases thanks!
I remember ideas (long ago) of @olblak about multi-valued sources (but only sources). 

There are multiple tools to help you already:

- [YAML anchors](https://support.atlassian.com/bitbucket-cloud/docs/yaml-anchors/) if you choose to have a single manifest
  -  Involves expressing 2 sources (one for patch and one for major for instance) and 2 actions of type pull requests (one for each). But with an anchor, that could help you to reduce the duplication:
  
  ```yaml
  ---
  name: Bump Cert-Manager Version
  
  scms:
    cert_manager_patch: &scmSpec
      kind: github
      spec:
        user: "{{ .github.user }}"
        email: "{{ .github.email }}"
        owner: "{{ .github.owner }}"
        repository: "{{ .github.repository }}"
        token: "{{ requiredEnv .github.token }}"
        username: "{{ .github.username }}"
        branch: "{{ .github.branch }}"
    # Exactly the same
    cert_manager_minor: *scmSpec
  
  sources:
    cert_manager_patch: &sourcePatch
      kind: helmchart
      spec: &patch
        url: https://charts.jetstack.io
        name: cert-manager
        versionfilter:
          kind: semver
          pattern: '~1.12'
    cert_manager_minor:
      kind: helmchart
      spec:
        <<: *patch
        versionfilter:
          pattern: '^1.x'
  
  targets:
    cert_manager_patch: &targetPatch
      name: Bump Cert Manager Patch Version
      kind: yaml
      sourceid: cert_manager_patch
      spec:
        file: .github/workflows/updatecli.yaml
        key: $.name
      transformers:
        - trimprefix: v
      scmid: cert_manager_patch
    cert_manager_minor:
      <<: *targetPatch
      name: Bump Cert Manager Minor Version
      sourceid: cert_manager_minor
      scmid: cert_manager_minor
  
  actions:
    cert_manager_patch:
      kind: github/pullrequest
      scmid: cert_manager_patch
      spec:
        title: Bump Cert Manager Patch Version to {{ source `cert_manager_patch` }}
        labels:
          - cert-manager
          - patch
    cert_manager_minor:
      kind: github/pullrequest
      scmid: cert_manager_minor
      spec:
        title: Bump Cert Manager Patch Version to {{ source `cert_manager_minor` }}
        labels:
          - cert-manager
          - minor
  ```

**Comment by dduportal** [comment]
I believe we could discuss this feature in the long term under the following scope:

- Only for source,
- a collection of `versionFilter` could be defined
- Each one of these filters could be referenced later

Something like this:

```yaml
sources:
  cert_manager:
    kind: helmchart
    spec:
      url: https://charts.jetstack.io
      name: cert-manager
      versionfilters:
        patchFilter: # User-specified name
          kind: semver
          pattern: '~1.12'
        cert_manager_minor:
          kind: semver
          pattern: '^1.x'
    transformers:
      - trimprefix: v

targets:
  cert_manager_patch:
    name: Bump Cert Manager Patch Version
    kind: yaml
    sourceid: cert_manager.patchFilter
    spec:
      file: .github/workflows/updatecli.yaml
      key: $.name
```

WDYT @olblak ?


----

Side-tracking: Specifying 2 different PRs from 2 different targets looked really cumbersome in my previous message @olblak: do you think we could have a way to link actions and targets other than using the `scmid`? I have vague memory of playing with this in the past but can't remember if it is possible today

**Comment by olblak** [comment]
That's a lot of information to process, so I'll try answer them one by one

## Version Increment

Writing a policy that would do what you ask has been puzzling me for a while :) .

To know the "latest" version, we need to know the current version, the update pattern from that version, to finally retrieve the "latest" upstream version

### Transformers

One of my first attempt to solve this was by introducing transformers of type `semverinc` such as in the following example

<details><summary>Example</summary>

```
sources:
  default:
    kind: yaml
    spec:
      file: /tmp/data.yaml
      key: $.version

conditions:
  default:
    kind: dockerimage
    spec:
      image: ghcr.io/updatecli/updatecli
    transformers:
      - semverinc: minor
      ## semver drops v prefix
      - addprefix: v

targets:
  default:
    kind: yaml
    spec:
      file: /tmp/data.yaml
      key: $.version
```

</details>

Two major drawbacks:

1. We probably want to update to the latest version and not one version at a time.
2. The pipeline fails if there is no new version, which is quite confusing :(.

But `semverinc` ended up being useful in some situation so I kept it and regularly use it.

### Autodiscovery

In the autodiscovery context, it was easier because we analyze the files we want to update and then all we need to do is to generate the right semver pattern.

An example [here](https://github.com/epinio/helm-charts/blob/6b08026a4d0b002f4d5fe9a22c343a73611b57e7/updatecli/updatecli.d/autodiscovery/epinio.yaml#L10C7-L10C23)

Once again they are drawbacks

.1 We could have two similar pullrequests opened at a time, one bumping the patch version and another one bumping the minor version.
-> It's mitigated in your case because the minor bump happened once a month while the patch bump happened every day
-> In my scenarii, I automerge patch update or dependencies that I trust and specifically don't automerge those that I don't trust.
.2 More autodiscovery plugins means more code to maintain. :(

While I am considering adding more autodiscovery plugin, it's not my current priority

### Multiple manifests

Another attempt was to maintain multiple manifest, one for patch update, minor,etc..
with different CI jobs, like weekly, daily,etc.
This doesnt' scale very well as the number of manifest grow.

Quickly I gave up **but** I recently realized that using OCI registry, it could be a good way to publish and reuse policies
cfr https://github.com/updatecli/updatecli/issues/1600

so something like

<details><summary>Single</summary>

```
sources:
  default:
    kind: yaml
    spec:
      file: /tmp/data.yaml
      key: $.version
    transformers:
      - trimprefix: v
      - findsubmatch:
          # uncomment if we want patch version update
          #pattern: '^(\d*).(\d*)'
          pattern: '^(\d*)'
          captureindex: 0

  updatecli:
    kind: githubrelease
    dependson:
      - default
    spec:
      owner: updatecli
      repository: updatecli
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      versionfilter:
        kind: semver
        pattern: '{{ source "default" }}.x'

conditions:
  default:
    kind: dockerimage
    sourceid: updatecli
    spec:
      image: ghcr.io/updatecli/updatecli

targets:
  default:
    kind: yaml
    sourceid: updatecli
    spec:
      file: /tmp/data.yaml
      key: $.version
```

</details>

could be made more generic by leveraging go template "range"
and then we would just have to provide the values file.

Support for OCI registry is very promising and will come soon.

I'll keep the follow up later today
