### ISSUE TITLE
Add transformers parameter

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#160]
**Is your feature request related to a problem? Please describe.**

A major benefits of updatecli is to retrieve information from a third location then apply string manipulation to it by 
adding prefix, postfix, or replacer. More ways of modifying string is needed and we'll quickly need to specify the order of string manipulation 

**Describe the solution you'd like**

It would be simpler and better to add a new key for every stage that would accept a list of transformer, so we could control the order  of transformations

```
targets:
    targetID:
       kind: yaml
       transformers:
           - prefix: 
           - postfix:
           - replacer:
           - ...
```

**Describe alternatives you've considered**
We could use "modifiers" instead of "transformers"

**Additional context**
The current way of specifying prefix/postfix should remain but with a deprecation warning
