### ISSUE TITLE
Add support for OS on dockerimage resource

### ISSUE THREAD

**Issue by mcwarman** [updatecli/updatecli#1606]
### Is your feature request related to a problem?

Since #1589 fixed architecture queries failures have occured when checking images as the default is `linux`

### Solution you'd like

```yaml
  checkTemurinNanoserver2019DockerImage:
    kind: dockerimage
    name: Check if the container image "eclipse-temurin:<lastVersion>-jdk-nanoserver-1809" is available
    disablesourceinput: true
    spec:
      architecture: amd64
      operatingsystem: windows
      image: eclipse-temurin
      tag: '{{source "lastVersion" }}-jdk-nanoserver-1809'
```

**Comment by mcwarman** [comment]
Instead of adding new field does it make more sense to support in single string:

```yaml
  checkTemurinNanoserver2019DockerImage:
    kind: dockerimage
    name: Check if the container image "eclipse-temurin:<lastVersion>-jdk-nanoserver-1809" is available
    disablesourceinput: true
    spec:
      architectures:
        - windows/amd64
      image: eclipse-temurin
      tag: '{{source "lastVersion" }}-jdk-nanoserver-1809'
```
