### ISSUE TITLE
Feature Request: Action title Conventional Commit prefix

### ISSUE THREAD

**Issue by mcwarman** [updatecli/updatecli#1608]
### Is your feature request related to a problem?

Recently switched to using helm auto discovery for repos.

One thing I've lost in doing this is a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) title for the GitHub PRs, which means when I use Squash merges with title as commit message, I loose `build(deps): Bump dependency...`

### Solution you'd like

I'm not sure whether a `titleprefix` or a bool `addprefix` makes more sense.

I think it could be more complicated to gate it by bool , but probably more usable.

```yaml
actions:
  default:
    kind: github/pullrequest
    titleprefix: 'build(deps): '
    # addprefix: true
    spec:
      mergemethod: squash
      labels:
        - dependencies
    scmid: default
```

### Alternatives you've considered

I was thinking about whether target format made sense for auto discovery configuration, which would then be used for the PR title.

```yaml
autodiscovery:
  scmid: default
  actionid: default
  targetformat: build(deps): bump depedency {target} to {version}
  crawlers:
    helm: {}
```
