### ISSUE TITLE
dockerdigest + hidetag still leaves leading `@` 

### ISSUE THREAD

**Issue by parkedwards** [updatecli/updatecli#1618]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

if we define a source like this:

```
sources:
  busybox:
    kind: dockerdigest
    spec:
      architecture: amd64
      image: cgr.dev/chainguard/busybox
      tag: latest
      hidetag: true
```

the resulting digest value looks like this:

```
@sha256:815800c4e637e74b8850a14febe28d491890e953e53946f7199a8d79e8929a70
```

### Expected Behavior

i would expect `hidetag: true` would also remove the first `@`

```
sha256:815800c4e637e74b8850a14febe28d491890e953e53946f7199a8d79e8929a70
```

### Steps To Reproduce

1. create a `dockerdigest` source, with any repository
2. target the `latest` tag
3. inspect the generated digest value

### Environment

```markdown
Application:	0.61.0
Golang     :	1.21.1 linux/amd64
Build Time :	2023-09-18T20:45:38Z
```
