### ISSUE TITLE
Feature Request: Allow to compose Updatecli policies

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#1622]
### Is your feature request related to a problem?

I would like to easily define update policies for a specific git repository without having to duplicate Updatecli manifest.

### Solution you'd like

I would like to be able to run one of the following command 

* `updatecli compose show`: show all policies defined in `update-compose.yaml` similarly to `updatecli manifest show`
* `updatecli compose diff`: to show what would change for policies defined in `update-compose.yaml` similarly to `updatecli diff` 
* * `updatecli compose apply`: to enforce policies defined in `update-compose.yaml` similarly to `updatecli diff` 

I am envisioning to have file such as 

<details>

```
# Policies defines a list policies to enforce when running 
# `updatecli compose apply`
# `updatecli compose diff`
# `updatelci compose show`

policies:
  default:
    policy: ghcr.io/updatecli/policies/updatecli:latest
    ## Allow to override default policy configuration
    config:
      - default
    # Allow to load environment from file
    env_file:
      - values.d/scm.yaml
      - values.d/golang.yaml
    # environments allows to specify a map of environment variable
    environments:
      # if a value is omitted then we fetch from the global environments.
      UPDATECLI_GITHUB_TOKEN: ''
      UPDATECLI_GITHUB_ACTOR: 'olblak'

configs:
  default:
    config:
      - updatecli.d
    values:
      - values.yaml
    secrets:
      - secrets.yaml

---

# Example with local manifest
#
config:
  default:
    config:
      - updatecli.d
    values:
      - values.yaml

policies:
  default:
    config:
      - default

---
# Example of oci policy only
#
policies:
  default:
    policy: ghcr.io/updatecli/policies/default:latest
    environments:
      UPDATECLI_GITHUB_TOKEN: ''
      UPDATECLI_GITHUB_ACTOR: ''

  golang:
    policy: ghcr.io/updatecli/policies/golang:latest
    environments:
      UPDATECLI_GITHUB_TOKEN: ''
      UPDATECLI_GITHUB_ACTOR: ''
~                                                             
```

</details>

### Anything else?

This feature would require https://github.com/updatecli/updatecli/issues/1600
