### ISSUE TITLE
yaml parser fails when file contains directive

### ISSUE THREAD

**Issue by mteodori** [updatecli/updatecli#1649]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

terraform-version-source
------------------------
ERROR: ✗ searching in yaml file: invalid query:
    github.com/goccy/go-yaml.init
        /home/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.11.2/decode.go:807
ERROR: {Terraform version used in PaaS ✗   { {  } }   ERROR: ✗ searching in yaml file: invalid query:
    github.com/goccy/go-yaml.init
        /home/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.11.2/decode.go:807
} searching in yaml file: invalid query:
    github.com/goccy/go-yaml.init
        /home/runner/go/pkg/mod/github.com/goccy/go-yaml@v1.11.2/decode.go:807

### Expected Behavior

SOURCES
=======

terraform-version-source
------------------------
✔ value "1.4.6" found for key "$.terraform.version" in the yaml file "test.yaml"

### Steps To Reproduce

1. create a file `test.yaml` with content
```yaml
%YAML 1.2
---
terraform:
  version: 1.4.6
```
and a `updatecli.yaml` config
```yaml
title: bump version
sources:
  terraform-version-source:
    name: Terraform version used
    kind: yaml
    spec:
      file: test.yaml
      key: $.terraform.version
```
3. run `updatecli diff` and see reported error
5. remove or comment directive `%YAML 1.2` in `test.yaml`
6. run `updatecli diff` and source is parsed correctly

### Environment

```markdown
- OS: MacOS 13.6
- updatecli: 0.62.0
```
