### ISSUE TITLE
Config not being picked up in updatecli.d or updatecli.yaml

### ISSUE THREAD

**Issue by mcwarman** [updatecli/updatecli#1694]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

From version `v0.63.0` configuration are not loaded from `updatecli.d` directory or file `updatelci.yaml`.

### Expected Behavior

Configuration files in `updatecli.d` directory  or file `updatelci.yaml` should be loaded

### Steps To Reproduce

From the updatecli repository

1. `mkdir updatecli.d`
2. Create a pipeline `updatecli.d/test.yaml`
3. `updatecli diff`

```yaml
# updatecli.d/test.yaml
sources:
  JenkinsOldestSupportedWeekly:
    name: Get the oldest supported Jenkins weekly version
    kind: json
    spec:
      file: https://updates.jenkins.io/tiers.json
      key: "weeklyCores.[0]"
```

NOTE: This still works: `updatecli diff --config ./updatecli.d/test.yaml`

### Environment

```markdown
- OS: Ubuntu 20.04
- updatecli: v0.63.0
```

### Anything else?

Tested in v0.62.0 and works as expected
