### ISSUE TITLE
[regresion] 0.64 ask to enable experimental flag

### ISSUE THREAD

**Issue by kuisathaverat** [updatecli/updatecli#1706]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We use an env var to allow pass flags to a makefile. This usually is empty, this behavior works with 0.62 (and all CLI we have tested). After the update to 0.64 the program exists with a warning.

```
WARNING: The 'oci registry' feature requires the flag --experimental to be set
```

### Expected Behavior

The pipeline must run as it does with <=0.62

### Steps To Reproduce

* create a pipeline test.yml

```yaml
---
# yaml-language-server: $schema=https://www.updatecli.io/schema/latest/config.json
name: test
pipelineid: test

sources:
  one:
    name: 'Check {{ $updateChannel }} channel'
    kind: shell
    spec:
      command: echo 1
targets:
  one:
    name: 'Check {{ $updateChannel }} channel'
    kind: shell
    spec:
      command: echo 1
```

* run the commands

```shell
UPDATECLI_OPTS=""
updatecli apply $(UPDATECLI_OPTS) --config config.yml
```
or
```shell
updatecli apply "" --config config.yml
```

* the program exist with code 1 and a warning

```
WARNING: The 'oci registry' feature requires the flag --experimental to be set
```

### Environment

```markdown
- OS: linux/macOS
- updatecli: 0.64
```

### Anything else?

The workaround is to set a flag in the env var to no pass `""`

```shell
UPDATECLI_OPTS="--clean"
updatecli apply $(UPDATECLI_OPTS) --config config.yml
```
