### ISSUE TITLE
Autodiscovery with multiple ignore paths failes (dockerfile)

### ISSUE THREAD

**Issue by hans-d** [updatecli/updatecli#1716]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
autodiscovery:
  crawlers:
    dockerfile:
      ignore:
        - path: dir1/*
        - path: dir2/*
```
When having both ignores, all is included. When having only one ignore, it works fine

### Expected Behavior

filter out all paths specified

### Steps To Reproduce

config see above.

### Environment

```markdown
- OS: Linux / Debian
- updatecli:
    Application:	0.64.1
    Golang     :	1.21.3 linux/amd64
```
