### ISSUE TITLE
dockerimage condition fails when docker image does not exist

### ISSUE THREAD

**Issue by treezio** [updatecli/updatecli#1728]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After upgrading `updatecli` from `v0.64.1` to `v0.65.0` the condition for `dockerimage` fails instead of being skipped, leading to a failure output (exit 1).

### Expected Behavior

The pipeline is skipped as the image does not exists meaning the condition is not met.

### Steps To Reproduce

On github actions use latest action version `v2.47.0` which runs on `updatecli v0.65.0`

Set a condition for a docker image tag that does not exist.

Scenario: The latest tag/release in the source repository is `v1.47.2` . There is no `v1.47.2` tag for the Docker Image in DockerHub

```
sources:
  latestVersion:
    kind: githubrelease
    name: Get the latest stable version
    spec:
      owner: "treezio"
      repository: "test-releases-notifications"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      versionfilter:
        kind: semver

conditions:
  IsDockerImagePublished:
    name: Check application {{ source "latestVersion" }} docker image tag is released
    kind: dockerimage
    spec:
      image: "treezio/test-notification-releases"
      architecture: amd64
```

The output:

```
SOURCES
=======

latestVersion
-------------
Searching for version matching pattern "*"
✔ GitHub release version "v1.47.2" found matching pattern "*" of kind "semver"


CHANGELOG:
----------

Release published on the 2023-10-25 16:04:57 +0000 UTC at the url https://github.com/treezio/test-releases-notifications/releases/tag/v1.47.2




CONDITIONS:
===========

IsDockerImagePublished
----------------------
ERROR: GET https://index.docker.io/v2/treezio/test-notification-releases/manifests/v1.[47](https://github.com/sequra/jenkins-test/actions/runs/6655061707/job/18084462981#step:4:48).2: MANIFEST_UNKNOWN: manifest unknown; unknown tag=v1.47.2

✗ condition not met, skipping pipeline

=============================

REPORTS:



✗ Bump app-update image version:
	Source:
		✔ [latestVersion] Get the latest stable app-update version
	Condition:
		✗ [IsDockerImagePublished] Check app-update v1.47.2 docker image tag is released
	Target:
		- [imageTag] 


Run Summary
===========
Pipeline(s) run:
  * Changed:	0
  * Failed:	1
  * Skipped:	0
  * Succeeded:	0
  * Total:	1
ERROR: ✗ 1 over 1 pipeline failed
ERROR: command failed: 1 over 1 pipeline failed
Error: Process completed with exit code 1.
```

### Environment

```markdown
- Location: GitHub Runner
- OS: ubuntu-22.04
- updatecli: v0.65.0
```

**Comment by olblak** [comment]
Thanks for opening this issue, indeed you are right to highlight a scenario I forgot about.

> The pipeline is skipped as the image does not exists meaning the condition is not met., 

The purpose of the fix introduced in 0.65.0 was to detect broken pipeline if the condition failed.

I now realize that "skipped" is different than "failed" and we need both.
So we probably need an additional setting on condition

```
conditions:
  IsDockerImagePublished:
    name: Check application {{ source "latestVersion" }} docker image tag is released
    kind: dockerimage
    skiponfail: true
    spec:
      image: "treezio/test-notification-releases"
      architecture: amd64
```

https://github.com/updatecli/updatecli/blob/5758ea9e3125d4bc9ad62f22c7d408ac49b434a0/pkg/core/pipeline/conditions.go#L46C12-L46C12 

Yes `skiponfail` is not perfect but it's the first name that come out of my mind now
I am also wondering if we should skip on fail by default or report an error
