### ISSUE TITLE
PipelineID causing duplicate branch name usages

### ISSUE THREAD

**Issue by YuhanunCitgez** [updatecli/updatecli#1731]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you create a PR using the following workflow;

```
name: Bump project1 helm version

scms:
  default:
    kind: github
    spec:
      user: "cicd"
      email: "cicd@example.com"
      owner: "example"
      repository: "artifacts"
      token: "{{ requiredEnv .github.token }}"
      username: "cicd"
      branch: "main"

sources:
  lastReleaseVersion:
    name: Get the latest release version for project1
    kind: githubrelease
    spec:
      owner: "example"
      repository: "project1"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      versionfilter:
        kind: semver
    transformers:
    - trimprefix: "v"

targets:
  helmFiles:
    name: Update the `project1` chart version
    kind: file
    scmid: default
    spec:
      files:
      - "clusters/stage.yaml"
      matchpattern: 'chart: example/project1((\r\n|\r|\n)(\s+))version: .*'
      replacepattern: 'chart: example/project1${1}version: {{ source "lastReleaseVersion" }}'


actions:
  default:
    kind: github/pullrequest
    scmid: default
    title: '[Stage] Bump `project1` helm chart version to {{ source "lastReleaseVersion" }}'
    spec:
      automerge: true
      mergemethod: squash
      labels:
      - project1
      - application
```

This cuases merge conflicts in the PR. 

### Expected Behavior

I'd expect each run individually to have a unique branch name, so we don't get a merge conflict because the branch "already existed" and hence an old version was used (not up to date with main)

### Steps To Reproduce

1. Apply to workflow to a repo
2. Create a release tag in project1
3. Merge the PR
4. Create another release tag in project1
5. A merge conflict exists now

### Environment

```markdown
- OS: ubuntu 22.04 (running in EKS k8s)
- updatecli: 0.64.0
```
