### ISSUE TITLE
Error Cloning repository using GitHub SCM Plugin

### ISSUE THREAD

**Issue by treezio** [updatecli/updatecli#1732]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This scenario is kind of weird.
I'm currently setting up the updatecli pipeline for a "big" repository based on GitHub Actions, using the `GITHUB_TOKEN` as authentication.
Even though I have been able to clone many private repositories, I'm facing errors when attempting to clone this GitHub private repository using the `GitHub` SCM Plugin. 
I have recreated the errors in my local using an Ubuntu docker Image.

The main issue is that although I'm setting the `GITHUB_TOKEN` environment variable, it seems like it is trying to clone the repository using the SSH protocol, and it is complaining about not being able to create an SSH Agent.

```
+++++++++++
+ PREPARE +
+++++++++++

Loading Pipeline "./path/to/app/updatecli.yaml"

SCM repository retrieved: 1
ERROR: failed cloning GitHub repository "https://github.com/organization/repository.git"
ERROR: err - error creating SSH agent: "SSH agent requested but SSH_AUTH_SOCK not-specified"
```

I've tried to dive a bit in the `go-git` library but I have no clue why this is actually happening.

Maybe I'm missing something but I think this is not related to authentication errors, as I have been able to clone the repository using the `git` cli and the `GITHUB_TOKEN` via `https://` URL 

Pipeline Config:

```
---
name: Bump aplication chart version

scms:
  default:
    kind: github
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: "{{ .github.owner }}"
      repository: "{{ .github.repository }}"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      branch: "{{ .github.branch }}"
```

Config values:
```
github:
  user: "SomeUser"
  email: "mail@organization.es"
  username: "treezio"
  token: "GITHUB_TOKEN"
  branch: "master"
  owner: "organization"
  repository: "repository"
```

I've tried this very same configuration just changing the `repository` value and it works.

### Expected Behavior

The repository is cloned via API using the authentication token `GITHUB_TOKEN`  

### Steps To Reproduce

- Run ubuntu 22.04 docker image in repository directory
- `docker run -ti -v $(pwd):/opt ubuntu:22.04`
- Install updatecli
- export `GITHUB_TOKEN` 
- Run `updatecli diff`

As this is happening with a private repository I haven't been able to recreate it with a public repository so far 😢 

### Environment

```markdown
- OS: ubuntu 22.04
- updatecli: 0.65.1
```

### Anything else?

As I said this is a private repository and kind of big, so I don't know if that might have something to do with this issue
