### ISSUE TITLE
YAML target replaces `~` for `null` 

### ISSUE THREAD

**Issue by v1v** [updatecli/updatecli#1735]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="417" alt="image" src="https://github.com/updatecli/updatecli/assets/2871786/c6163af1-415a-41e5-8db5-9ecde538273e">

### Expected Behavior

Only changes in the env key

```
env:
  SCORECARD_VERSION: "4.13.1"
```

Rather than replacing `~` for `null` or change the identation/lines

### Steps To Reproduce

**Given**

```yaml
---
name: action

env:
  SCORECARD_VERSION: "4.13.0"

jobs:
  inspect:
```

**And**

```yaml
...
targets:
  workflow:
    name: Update GitHub workflow
    kind: yaml
    scmid: default
    spec:
      file: .github/workflows/ci.yml
      key: 'env.SCORECARD_VERSION'
      value: '4.13.1'

```

**When** running `updatecli apply --config ./updatecli.d/bump-scorecard.yml`

### Environment

```markdown
- OS: GitHub actions
- updatecli: https://github.com/elastic/apm-pipeline-library/blob/5800f4a0e2c6b29ff642b29279cb4b6eb9095cbc/.github/actions/updatecli/action.yml#L64. `v0.65.1`
```
