### ISSUE TITLE
Feature Request: Allow to ignore File content pattern not found

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#1765]
### Is your feature request related to a problem?

I am trying to write an updatecli policy that could update all files from a specific location for a specific regular expression.
This was my intend in https://github.com/updatecli/updatecli/pull/1738

For example update all GitHub action workflows located in `.github/workflows/*` where the strings `NODEJS_VERSION` is defined...

In the current state my policy will fails as it found files not containing  `NODEJS_VERSION`

I would like to ignore errors when the file doesn't contain `NODEJS_VERSION`

### Solution you'd like

I would like to ignore errors when the file doesn't contain `NODEJS_VERSION`

I propose to add a new key `ignorenotfound` as in the following example

```
targets:
    githubaction:
        name: 'deps: update Node used by Github Action to {{ source "node" }}'
        kind: file
        disablesourceinput: true
        spec:
            files:
             - .github/workflows/*.yaml
             - .github/workflows/*.yml
            ignorenotfound: true
            searchpattern: true
            matchpattern: 'node-version: (.*)'
            replacepattern: 'node-version: {{ source "majornodeversion" }}'
```

### Alternatives you've considered

* Not introducing a new key and just don't report error when match pattern returned nothing
* using `ignoresearchpatternnotfound` instead of `ignorenotfound`
