### ISSUE TITLE
Ignore path failing for Helm autodiscovery

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#1769]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The Helm autodiscovery plugin used to rely on the Helm chart metadata file path to identify if a ignore/only rule is matching but instead now rely on the Chart root directory.
This has some consequence on the matching rule of kind path

Here is an example of what should be updated.

```
autodiscovery:
  groupby: all 
  scmid: default
  actionid: default
  crawlers:
    helm:
      versionfilter:
        kind: semver
      # The following helm chart already have specific updatecli manifest
       ignore:
-        - path: "chart/application-stateful/*"
+        - path: "chart/application-stateful"
```

### Environment

```markdown
- OS:
- updatecli:0.66.0
```

### Anything else?

I am opening this issue for visibility but I will probably just update the release note to reflect the new behavior.
This change is part of one of the last change needed to promote autodiscovery out of experimental.

And being autodiscovery is still behind the experimental flag, I don't consider having to revert to the previous behavior
