### ISSUE TITLE
Github Release doesn't return a release

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#182]
**Describe the bug**
In some situation, the Github release doesn't return a valid list of release as for 
-> https://github.com/kubernetes/kubectl/releases

**Comment by olblak** [comment]
Basically it just show git tags.

A potential solution would be to create a new resource that would works for source and conditions as in the following example.
It would works for both github and git repository as we wouldn't rely on github api

```
    name: "Get jenkins tags"
    kind: gitTags
    spec:
      value: <matching pattern similar to semver>
    scm:
      github:
        user: "{{ .github.user }}" 
        email: "{{ .github.email }}" 
        owner: "{{ .github.owner }}" 
        repository: "{{ .github.repository }}" 
        token: "{{ requiredEnv .github.token }}" 
        username: "{{ .github.username }}" 
        branch: "{{ .github.branch }}" 

```
