### ISSUE TITLE
transformers do not work on file targets with matchpattern/replacepattern

### ISSUE THREAD

**Issue by oderayi** [updatecli/updatecli#1848]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a target like so:

```
targetID:
    name: bump  version
    sourceid: sourceID
    kind: file
    spec:
      file: path/to/file.txt
      matchpattern: '(packagename)-([\d\.]+)(-snapshot(\.\d+)?)?'
      replacepattern: '$1-{{ source "sourceID" }}'
    transformers:
      - trimprefix: 'v'
```

Say the source returns `v15.2.0` and I wish to trim off the "v" part so that "15.2.0" is used in the replacement operation. This does not seem to work. 

However, if I use `line: n` instead of `matchpattern/replacepattern`, the transformer works.

### Expected Behavior

I expect the source value without the trimmed prefix to be returned and not the whole source value.

### Environment

```markdown
- OS: Ubuntu 22.04.1
- updatecli: 0.68.0
```

**Comment by olblak** [comment]
Hi @oderayi,

The problem you highlight is something I couldn't find a good way to solve because it's hard to identify at the target level that you want to use the syntax `{{ source "sourceid" }}`

So I usually disable the default sourceinput using `disablesourceinput` set to `true`  and move the transformer rule at the source level such as: 

```
sources:
  sourceID:
    name: Get source information
    kind: xxx
    spec:
      ...
    transformers:
      - trimprefix: v

targets:
  targetID:
    name: bump  version
    disablesourceinput: true
    kind: file
    spec:
      file: path/to/file.txt
        matchpattern: '(packagename)-([\d\.]+)(-snapshot(\.\d+)?)?'
        replacepattern: '$1-{{ source "sourceID" }}'
```
