### ISSUE TITLE
failwhen is not honoured when using the file condition

### ISSUE THREAD

**Issue by v1v** [updatecli/updatecli#1849]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using 

```yaml
conditions:
  is:
    spec:
      file: go.mod
      matchpattern: pattern
    failwhen: true
```

I get the same output if I use the `failwhen: false` 

### Expected Behavior

I'd expect the condition to be one of the or other while using the `failwhen`

### Steps To Reproduce

```yaml
conditions:
  is:
    kind: file
    disablesourceinput: true
    scmid: default
    spec:
      file: go.mod
      matchpattern: 'github\.com/elastic/beats.*'
    failwhen: false
```

then it behaves as similar as using `failwhen: true`

### Environment

```markdown
- OS: Ubuntu and MacOS M11
- updatecli: `0.70.0`, `0.67.1`
```

### Anything else?

https://github.com/elastic/apm-server/blob/29076053edb9328049d999bd264fa60bb90577e8/.ci/update-beats.yml is the pipeline we use.
