### ISSUE TITLE
Feature Request: add dockerimage autodiscovery.

### ISSUE THREAD

**Issue by pismute** [updatecli/updatecli#1856]
### Is your feature request related to a problem?

I would like to automatically update dockerimage in arbitrary files, specifically in Jenkinsfiles and Kustomizations:

```yaml
    spec:
      containers:
      - image: updatecli/updatecli:0.70.0
```

### Solution you'd like

I want to look for all file except for files matched by other crawlers:

includes:
- dockerimage's filematch: default `*`

excludes if defined:
- dockercompose's filematch
- dockerfiles' filematch

I would like to narrow matching pattern in file contents:

```
  matchpattern: `image:.*`
```

I want to look for `imagename:semver` in matched string. looking for `updatecli/updatecli:0.70.0` in `image: updatecli/updatecli:0.70.0`

I would like to filter messy tags out with tagfilter. tagfilter is a useful parameter for development.

It generates manifest in memory like:

```
sources:
  'updatecli/updatecli':
    kind: dockerimage
    spec:
      image: updatecli/updatecli
      tagfilter: ...
      versionfilter:
        kind: semver

targets:
    sourceid: 'updatecli/updatecli'
    kind: file
    spec:
      file: ...
      matchpattern:  'image:(\s*)updatecli/updatecli:[0-9].*(\s*)'
      searchpattern: 'image:$1updatecli/updatecli:{{ source "updatecli/updatecli" }}$2'
```

**Comment by olblak** [comment]
Looking at this issue,
It's already possible to look for file path matching pattern.
The key is to use the parameter `searchpattern: true`

with something like 

```
name: "deps: update Updatecli docker image"
sources:
  updatecli:
    name: Get latest Updatecli docker image
    kind: dockerimage
    spec:
      image: ghcr.io/updatecli/updatecli
      versionfilter:
        kind: semver

targets:
  updatecli:
    name: Update Updatecli docker image in all files {{ source "updatecli" }}
    kind: file
    disablesourceinput: true
    spec:
      files:
        - "*.yaml"
        - "Jenkinsfile"
      matchpattern: 'image:(\s*)updatecli/updatecli:[0-9].*(\s*)'
      searchpattern: true
      replacepattern: 'image:$1updatecli/updatecli:{{ source "updatecli" }}$2'
```

We use this technique in many places where we need to update all GitHub workflow using a specific action such as [here](https://github.com/updatecli/policies/blob/main/updatecli/policies/nodejs/githubaction/updatecli.d/manifest.yaml) using the file plugin  or [here](https://github.com/updatecli/policies/blob/56adcf89531949a13c4be39da7c4c383ab596a85/updatecli/policies/golangci-lint/githubaction/updatecli.d/default.yaml#L62) using the yaml plugin


Closing as your issue is solved from my perspective but feel free to reopen if you want to continue the discussion or have additionnal question
