### ISSUE TITLE
Inconsistent behaviour of file target

### ISSUE THREAD

**Issue by pismute** [updatecli/updatecli#1860]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`file target` fails(exit non-zero) if pattern isn't matched:

```yaml
targets:
  a-target:
    ...
    kind: file
    spec:
      file: 'myfile'
      matchpattern:  'mypattern*'
```

`file target` deosn't fail(exit 0) if pattern isn't matched in multiple files:

```yaml
targets:
  a-target:
    ...
    kind: file
    spec:
      file: 'myfile*'
      matchpattern:  'mypattern*'
      searchpattern: true
```

### Expected Behavior

I think updatecli should fail in unmatched cases, even though `searchpattern` is true.

### Environment

```markdown
- OS: Mac sonoma
- updatecli: v0.70.0
```

**Comment by olblak** [comment]
Thanks for the opening this issues, I think it's duplicated with https://github.com/updatecli/updatecli/issues/1849
Which is on my list to fix https://github.com/updatecli/updatecli/issues/1849

**Comment by olblak** [comment]
What would you think about adding new setting `matchatleast` such as 

```
targets:
    githubaction:
        name: 'deps: update Node used by Github Action to {{ source "node" }}'
        kind: file
        disablesourceinput: true
        spec:
            files:
             - .github/workflows/*.yaml
             - .github/workflows/*.yml
            searchpattern: true
            matchpattern: 'node-version: (.*)'
            matchatleast: 1 
            replacepattern: 'node-version: {{ source "majornodeversion" }}'
```

Where `matchatleast` specifies the required number of matching files where accepted values are 

* `*` match all
* `<an integer>`

With default value to`1`

I need to think about it but it could also replace `searchpattern`
