### ISSUE TITLE
Panic error with `dockerimage` source with `tagfilter`

### ISSUE THREAD

**Issue by lemeurherve** [updatecli/updatecli#1888]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Got a panic error when running this simple manifest:

```
name: "Bump Jenkins Weekly docker image version on infra.ci.jenkins.io"

scms:
  default:
    kind: github
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: "{{ .github.owner }}"
      repository: "{{ .github.repository }}"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      branch: "{{ .github.branch }}"

sources:
  latestRelease:
    name: Get latest jenkinsciinfra/jenkins-weekly image tag
    kind: dockerimage
    spec:
      image: "jenkinsciinfra/jenkins-weekly"
      tagfilter: .*-\d+$
```

<details><summary>Panic error log</summary>

> ###################################################################
> 
> # BUMP JENKINS WEEKLY DOCKER IMAGE VERSION ON INFRA.CI.JENKINS.IO
> 
> ###################################################################
> 
> # SOURCES
> 
> ## latestRelease
> 
> Searching for version matching pattern "latest"
> panic: runtime error: index out of range \[-1\]
> 
> goroutine 1 \[running\]:
> github.com/updatecli/updatecli/pkg/plugins/utils/version.(\*Filter).Search(0x140006ff088, {0x0?, 0x0, 0x0})
> /home/runner/work/updatecli/updatecli/pkg/plugins/utils/version/filter.go:86 +0x480
> github.com/updatecli/updatecli/pkg/plugins/resources/dockerimage.(\*DockerImage).Source(0x140006fefc0, {0x0?, 0x0?}, 0x140002b4a90)
> /home/runner/work/updatecli/updatecli/pkg/plugins/resources/dockerimage/source.go:36 +0x280
> github.com/updatecli/updatecli/pkg/core/pipeline/source.(\*Source).Run(0x140002b4a80)
> /home/runner/work/updatecli/updatecli/pkg/core/pipeline/source/main.go:90 +0x5c0
> github.com/updatecli/updatecli/pkg/core/pipeline.(\*Pipeline).RunSources(0x14000720540)
> /home/runner/work/updatecli/updatecli/pkg/core/pipeline/sources.go:49 +0x3a8
> github.com/updatecli/updatecli/pkg/core/pipeline.(\*Pipeline).Run(0x14000720540)
> /home/runner/work/updatecli/updatecli/pkg/core/pipeline/main.go:204 +0x150
> github.com/updatecli/updatecli/pkg/core/engine.(\*Engine).Run(0x10959be60)
> /home/runner/work/updatecli/updatecli/pkg/core/engine/run.go:16 +0xd4
> github.com/updatecli/updatecli/cmd.run({0x106b9f6d2?, 0x0?})
> /home/runner/work/updatecli/updatecli/cmd/root.go:122 +0x4e4
> github.com/updatecli/updatecli/cmd.glob..func5(0x14000503000?, {0x140008f5840?, 0x0?, 0x4?})
> /home/runner/work/updatecli/updatecli/cmd/diff.go:38 +0x228
> github.com/spf13/cobra.(\*Command).execute(0x1095588e0, {0x140008f5800, 0x4, 0x4})
> /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x640
> github.com/spf13/cobra.(\*Command).ExecuteC(0x1095571e0)
> /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320
> github.com/spf13/cobra.(\*Command).Execute(...)
> /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
> github.com/updatecli/updatecli/cmd.Execute()
> /home/runner/work/updatecli/updatecli/cmd/root.go:49 +0x68
> main.main()
> /home/runner/work/updatecli/updatecli/main.go:8 +0x1c

</details>

### Expected Behavior

No panic error.

### Steps To Reproduce

- Run updatecli diff on this manifest

### Environment

```markdown
- OS: MacOS
- updatecli: 0.68.0
```
