### ISSUE TITLE
Not possible anymore to only use Golang autodiscovery plugin for only go version`

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#1896]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

As explained on https://www.updatecli.io/docs/plugins/autodiscovery/golang/

It was possible to use the Golang autodiscovery plugin to only update go version and ignoring go modules
But apparently with the last matchingrule refactoring, we can't ignore all go modules.

### Steps To Reproduce

The following autodiscovery manifest should only bump Golang version

```
autodiscovery:
    golang/gomod:
      versionfilter:
        kind: semver
        pattern: minor
      only:
        - goversion: "*" 
```

### Environment

```markdown
- OS:Linux
- updatecli: 0.72.0
```
