### ISSUE TITLE
Feature Request: Automated signed commits for GitHub Actions if a github-bot

### ISSUE THREAD

**Issue by v1v** [updatecli/updatecli#1914]
### Is your feature request related to a problem?

Signed commits can be done within the existing environment or by the CI if a bot exists.

### Solution you'd like

If running for GitHub actions, then I'd like to enable new settings to do the magic 

https://gist.github.com/swinton/03e84635b45c78353b1f71e41007fc7c is an example of using the existing GITHUB_TOKEN 

```yaml
actions:
  pull-request:
    kind: "github"
    scmid: default
    spec:
      autogithubbotsign: true
```

The if `autogithubbotsign` and `CI=true` and GitHub actions, then use signing with the Rest API

### Alternatives you've considered

Configure the local environment with the GPG as explained in https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits
