### ISSUE TITLE
Unexpected trailing contents with file target and content targeting a specific line

### ISSUE THREAD

**Issue by gionn** [updatecli/updatecli#1915]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When defining a target with `kind: file`, using `line` together with `content` referencing a variable, the line is properly updated but some cruft is added at the end of the file, which seems the trailing text present in `content` after the `{{ variable }}` is being used.

### Expected Behavior

Since I am targeting a specific line, I expect that only that line should be modified, and the entire line should be overwritten completely with the `content` provided, independently from the pre-existing text on that line.

### Steps To Reproduce

Have a pipeline with the following targets:

```
targets:
  updateSyncServiceVersion:
    name: Bump Sync Service version
    kind: file
    scmid: securityTestingRepo
    sourceid: syncServiceVersion
    spec:
      file: configs/Sync Service/urls_to_upload_and_scan.txt
      line: 1
      content: org.alfresco.services.sync:service-sync:${ARTIFACT_VERSION:-{{ source `syncServiceVersion` }}}:jar
  updateDeviceSyncRepoVersion:
    name: Bump Device Sync Repo version
    kind: file
    scmid: securityTestingRepo
    sourceid: syncServiceVersion
    spec:
      file: configs/Sync Service/urls_to_upload_and_scan.txt
      line: 2
      content: org.alfresco.services.sync:alfresco-device-sync-repo:${ARTIFACT_VERSION:-{{ source `syncServiceVersion` }}}:amp
```

the target file contents are:

```
org.alfresco.services.sync:service-sync:${ARTIFACT_VERSION:-5.0.1-SNAPSHOT}:jar
org.alfresco.services.sync:alfresco-device-sync-repo:${ARTIFACT_VERSION:-5.0.1-SNAPSHOT}:amp
```

### Environment

```markdown
- OS: Ubuntu 22.04
- updatecli: v0.71.0
```

### Anything else?

First commit (after first target update):
<img width="817" alt="Screenshot 2024-02-06 at 09 56 00" src="https://github.com/updatecli/updatecli/assets/71768/aabde725-3310-429d-80b4-c6dd3769f0f3">

Second commit (after second target update):
<img width="824" alt="Screenshot 2024-02-06 at 09 56 07" src="https://github.com/updatecli/updatecli/assets/71768/ba5cce06-8ad2-4423-a47e-21f9ccb95d25">
