### ISSUE TITLE
Feature Request or Bug: source githubrelease version: latest, return latest by date but not latest from github label

### ISSUE THREAD

**Issue by smerle33** [updatecli/updatecli#1951]
### Is your feature request related to a problem?

if we take ruby github releases : https://github.com/ruby/ruby/releases
we got the `v3_2_3` on the january 18, 2024 so last one on date sorting
but the `v3_3_0` on january 5, 2024 so release before BUT with the Latest label 

<img width="665" alt="Capture d’écran 2024-02-22 à 10 21 17" src="https://github.com/updatecli/updatecli/assets/95630726/2e7fb23d-0429-4a53-a3dd-5f54ffe16c32">
 

### Solution you'd like

```
sources:
  rubyLastestRelease:
    kind: githubRelease
    name: "Get the latest Ruby version"
    spec:
      owner: "ruby"
      repository: "ruby"
      token: "{{ requiredEnv .github.token }}"
      versionFilter:
        kind: latest
```

I feel like this should return v3_3_0 as it has the label `Latest`

### Alternatives you've considered

I did try some server filter with 
```
    versionFilter:
        kind: semver
        pattern: "~3"
 ```
 with no luck
 
 I was trying to find ways to solve this by "kind of" mixing semver and replace ... 
 for example, I would : 

1.  filter out release candidate and preview (with a regexp saying something like v(\d).(\d).(\d)$
2. tell updatecli to use "_" instead of "." as a semver separator

so I would get 3.3.0 (or v3_3_0)
 

### Anything else?

this would probably help also on the temurin problem referred here : https://github.com/jenkins-infra/kubernetes-management/issues/4630 (and kind of here https://github.com/updatecli/updatecli/issues/1733)

What do you think ?

**Comment by olblak** [comment]
@smerle33 you could use the `typefilter` for doing that:
That parameter is specific to the githubrelease plugin and allow you to filter per "draft", prerelease, "release", or "latest" 
where "latest" is the one specified by the project maintainer as "latest"

```
sources:
  rubyLastestRelease:
    kind: githubRelease
    name: "Get the latest Ruby version"
    spec:
      owner: "ruby"
      repository: "ruby"
      token: '{{ requiredEnv "UPDATECLI_GITHUB_TOKEN" }}'
      ## cfr https://www.updatecli.io/docs/plugins/resource/github_release/
      typefilter:
        latest: true
```
