### ISSUE TITLE
Preserve whitespace in yaml files

### ISSUE THREAD

**Issue by till** [updatecli/updatecli#1954]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Whitespace in yaml files is not preserved when updatecli updates the file.

### Expected Behavior

No extra whitespace changes.

### Steps To Reproduce

I omitted parts of this manifest, but imagine a k8s manifest like:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service
spec:
  selector:
    matchLabels:
      app: service
  replicas: 1
  template:
    metadata:
      labels:
        app: service
    spec:
      containers:
      - name: service
        image: r.example.org/project/service:local
        ports:
        - containerPort: 3000
        env:
        - name: "DEBUG"
          value: "1"
        - name: "IMAGE"
          value: "r.example.org/project/image:v0.3.1"
```

Then I am running `updatecli` to update the value of `IMAGE` (in `env`). The update itself works, but the whitespace on the file is also changed.

My "target" configuration looks like this:

```yaml
# updatecli/updatecli.d/update.yml

targets:
  update-buildpack:
    kind: yaml
    name: IMAGE
    scmid: default
    sourceid: buildpack
    spec:
      engine: yamlpath
      file: ./k8s/base/deployment.yml
      key: "$.spec.template.spec.containers[*].env[?(@.name == 'IMAGE')].value"
```

Anyway, the result is that my manifest now looks like this:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service
spec:
  selector:
    matchLabels:
      app: service
  replicas: 1
  template:
    metadata:
      labels:
        app: service
    spec:
      containers:
        - name: service
          image: r.example.org/project/service:local
          ports:
            - containerPort: 3000
          env:
            - name: "DEBUG"
              value: "1"
            - name: "IMAGE"
              value: "r.example.org/project/image:v0.3.2"
```

So this is a matter of how lists in yaml are spaced. I searched the docs and code for a "preserve whitespace" option, but came up short. It's also not a huge issue, just means that all manifests will go through this and I have to adjust my editor (somehow).

### Environment

```markdown
- OS: OSX
- updatecli: 0.73


VERSION

Application:	0.73.0
Golang     :	1.22.0 linux/amd64
Build Time :	2024-02-17T18:30:26Z
```
```


### Anything else?

_No response_
