### ISSUE TITLE
dockerdigest w/ and w/o arch fetches different digests.

### ISSUE THREAD

**Issue by pismute** [updatecli/updatecli#1977]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Default architecture is amd64 in documentation, I think updatecli should behave in the same way.

```yaml
 sources:
   bookworm-slim-amd64:
     kind: dockerdigest
     spec:
       image: debian
       architecture: "amd64"
       tag: "bookworm-slim"

   bookworm-slim:
     kind: dockerdigest
     spec:
       image: debian
       tag: "bookworm-slim"
```

Results:

```
bookworm-slim
-------------
✔ Docker Image Tag debian:bookworm-slim resolved to digest index.docker.io/library/debian:bookworm-slim@sha256:d02c76d82364cedca16ba3ed6f9102406fa9fa8833076a609cabf14270f43dfc
DEBUG: empty changelog found for the source

bookworm-slim-amd64
-------------------
✔ Docker Image Tag debian:bookworm-slim resolved to digest index.docker.io/library/debian:bookworm-slim@sha256:6bdbd579ba71f6855deecf57e64524921aed6b97ff1e5195436f244d2cb42b12
DEBUG: empty changelog found for the source
```

Even I cannot find `d02c76d82364cedca16ba3ed6f9102406fa9fa8833076a609cabf14270f43dfc` on dockerhub for any arch. I do not know where is comming from.

### Environment

```markdown
- OS: mac Sonoma 14.2.1
- updatecli: v0.73.0
```

**Comment by olblak** [comment]
More context on https://github.com/updatecli/updatecli/issues/1603

If an architecture is undefined, Updatecli retrieves the digest of the image index which can be used regardless of the architecture but if an architecture is specified then Updatecli retrieves a specific image digest.

You could try with the following manifest 

```
name: Get digest
sources:
  all:
    kind: dockerdigest
    spec:
      image: ghcr.io/updatecli/updatecli
      tag: v0.73.0
  amd64:
    kind: dockerdigest
    spec:
      architecture: amd64
      image: ghcr.io/updatecli/updatecli
      tag: v0.73.0
  arm64:
    kind: dockerdigest
    spec:
      architecture: arm64
      image: ghcr.io/updatecli/updatecli
      tag: v0.73.0
```
