### ISSUE TITLE
tagger field is required from gittag target

### ISSUE THREAD

**Issue by cedws** [updatecli/updatecli#1993]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using the gittag target to create a git tag for an SCM, an error is produced. Strangely I'm not able to reproduce this locally, only in GitHub Actions, despite running the same version of updatecli.

```
tag
---
WARNING: No specified message for gittag target. Using default value "Generated by updatecli"
Searching for version matching pattern "11.0.1"
ERROR: create git tag error: tagger field is required

ERROR: something went wrong in target "tag" : "tagger field is required"

Pipeline "UPDATECLI.YAML" failed
Skipping due to:
	targets stage:	"something went wrong during target execution"
```

### Expected Behavior

gittag target succeeds.

### Steps To Reproduce

1. Create the following updatecli.yaml 
2. Use the updatecli-action to install updatecli in GitHub Actions
3. Attempt to run use this manifest inside a workflow

```yaml
scms:
  github:
    kind: git
    spec:
      username: oauth2
      password: "{{ requiredEnv "PAT" }}"
      url: https://github.com/cedws/docker-ghidraserver
      branch: master
      user: github-actions[bot]
      email: 41898282+github-actions[bot]@users.noreply.github.com

sources:
  ghidraTag:
    kind: json
    transformers:
      - trimprefix: "Ghidra "
    spec:
      file: releases.json
      key: '.[0].name'
  ghidraDownload:
    kind: json
    spec:
      file: releases.json
      key: '.[0].assets.[0].browser_download_url'

targets:
  dockerfile:
    name: Update Dockerfile with latest Ghidra artifact
    kind: dockerfile
    sourceid: ghidraDownload
    scmid: github
    spec:
      file: Dockerfile
      instruction:
        keyword: ARG
        matcher: GHIDRA_ARCHIVE
  tag:
    name: Create tag
    kind: gittag
    sourceid: ghidraTag
    scmid: github
    dependsonchange: true
    dependson:
      - dockerfile
```

### Environment

```markdown
- OS: Ubuntu (GitHub Actions)
- updatecli: 0.74.0
```

### Anything else?

You can see the GitHub Actions run yourself here: https://github.com/cedws/docker-ghidraserver/actions/runs/8217964706/job/22474239648
