### ISSUE TITLE
Maven plugin encoding support

### ISSUE THREAD

**Issue by mcwarman** [updatecli/updatecli#2146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to access maven repositories and the XML encodings is not `UTF-8` for example: `US-ASCII` we get an error.

```xml
<?xml version='1.0' encoding='US-ASCII'?>
```

```text
ERROR: ✗ getting latest version: xml: encoding "US-ASCII" declared but Decoder.CharsetReader is nil
```

### Expected Behavior

Support for other types of XML encoding

### Steps To Reproduce

```yaml
sources:
  latest:
    kind: maven
    spec:
      repository: "https://plugins.gradle.org/m2/"
      groupid: "io.freefair.gradle"
      artifactid: "lombok-plugin"
```

### Environment

```markdown
- OS: WSL (Debian - Bookworm)
- updatecli: 0.76.1
```

### Anything else?

This is probably the answer (PR incoming): https://dzhg.dev/posts/2020/08/how-to-parse-xml-with-non-utf8-encoding-in-go/
