### ISSUE TITLE
dependsonchange doesn't work when some dependees are changed.

### ISSUE THREAD

**Issue by pismute** [updatecli/updatecli#2148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am not sure it is a bug, maybe expected. dependsonchange's behaviour doesn't seem intuitive to me at least.

```
targets:
     dependee1:
        ...
     dependee2:
        ...
    depender:
        dependson:
            - dependee1
            - dependee2
        dependsonchange: true
```

`depender` works only if all dependees are changed.

### Expected Behavior

I think `depender` should be triggered If any changes happens.

### Environment

```markdown
- OS: macos
- updatecli: 0.76.1
```

**Comment by olblak** [comment]
Well I thought your request is already the default behavior but I may be wrong 
I think we could easily support both scenario with something like 

```
targets:
     dependee1:
        ...
     dependee2:
        ...
    depender:
        dependson:
            - 'dependee1:required'
            - 'dependee2:required'
            - 'dependee3:optional'
            - 'dependee4'
        dependsonchange: true
```

Where default would be required to not introduce a breaking change and then we switch the default to "optional" in a later iteration
