### ISSUE TITLE
When using `--experimental` for `commitusingapi`, then I see errors related to udash but no failures

### ISSUE THREAD

**Issue by v1v** [updatecli/updatecli#2181]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using the `--experimental` flag then I see

```
REPORT
=======
ERROR: publishing to Udash:
errors occurred while publishing to Udash:
	* Bump bump-version to latest minor versionretrieving service access token: stat /home/runner/.config/updatecli/udash.json: no such file or directory
	*
```

### Expected Behavior

No errors in the report or a way to disable udash when using `--experimental`

### Steps To Reproduce

1. In linux
2. Given the configuration

```yaml
Given

```yaml
---
name: Bump golang-version to latest version

scms:
  githubConfig:
    kind: github
    spec:
      user: '{{ requiredEnv "GITHUB_ACTOR" }}'
      owner: elastic
      repository: golang-crossbuild
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      branch: main
      commitusingapi: true

actions:
  default:
    title: '[Automation] Bump Golang version to {{ source "go-version" }}'
    kind: github/pullrequest
    scmid: githubConfig
    spec:
      description: |
        See [changelog](https://github.com/golang/go/issues?q=milestone%3AGo{{ source "go-version" }}+label%3ACherryPickApproved) for {{ source "go-version" }}

sources:
  go-version:
    kind: githubrelease
    transformers:
      - trimprefix: go
    spec:
      owner: golang
      repository: go
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      username: '{{ requiredEnv "GIT_USER" }}'

targets:
  update-go-version:
    name: "Update .go-version"
    sourceid: go-version
    scmid: githubConfig
    kind: file
    spec:
      content: '{{ source "go-version" }}'
      file: .go-version
      matchpattern: '\d+.\d+.\d+'
```

3. When I run `GITHUB_TOKEN=$(gh auth token) GITHUB_ACTOR=your-actor updatecli --experimental diff --config  updatecli.d/bump.yml --debug`
4. I see

```
ACTIONS
========
REPORT
=======
ERROR: publishing to Udash:
errors occurred while publishing to Udash:
```

### Environment

```markdown
- OS: Linux Ubuntu (Github action runner)
- updatecli: 0.76.1
```
