### ISSUE TITLE
Running parallel pipelines with different parameters some are skipped

### ISSUE THREAD

**Issue by kuisathaverat** [updatecli/updatecli#2211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a pipeline that receives a parameter to choose what to update. This pipeline affects several files and is dynamic; it does not always process the same files. We detected that, at some point, this pipeline stopped working as expected. When we execute multiple pipelines in parallel with different parameters, only one creates the PR. The rest show a message like this one.

```
WARNING: GitHub pull request creation skipped as branch "updatecli_main_2e4738258883e65e74efa81cba52f74fdcf5e5c76cee53c658e2587e6175f113" diverged from "main"
```

### Expected Behavior

All the parallel pipeline execution with different parameters should create all the PRs needed.

### Steps To Reproduce

1. Create a pipeline like the following
```yaml
---
# yaml-language-server: $schema=https://www.updatecli.io/schema/latest/config.json
# {{ $updateChannel := requiredEnv "UPDATE_CHANNEL" }}
name: Update update channels {{ $updateChannel }}
scms:
  githubConfig:
    kind: "github"
    spec:
      user: '{{ requiredEnv "GIT_USER" }}'
      email: '{{ requiredEnv "GIT_EMAIL" }}'
      owner: '{{ requiredEnv "GITHUB_OWNER" }}'
      repository: '{{ requiredEnv "GITHUB_REPO" }}'
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      username: '{{ requiredEnv "GIT_USER" }}'
      branch: "main"
      force: true
actions:
  createpr:
    kind: github/pullrequest
    scmid: githubConfig
    spec:
      mergemethod: squash
      title: '[updatecli] Update channels {{ $updateChannel }}'
      description: 'Update channels new versions.'
      labels:
        - "update-channels"
        - "{{ $updateChannel }}"
sources:
  version:
    name: 'Check {{ $updateChannel }} channel'
    kind: shell
    spec:
      command: sleep 30; echo "3.${RANDOM}"
      environments:
        - name: RANDOM
targets:
  update-channel:
    name: "Updating {{ $updateChannel }} version"
    sourceid: version
    scmid: githubConfig
    kind: file
    spec:
      file: ".python-version"
      forcecreate: true
```
2. Create a PR change changing the `.python-version` file to anything
2. Run the following Script and merge the previous PR when the first pipeline execution pass
```shell
for i in one two three; 
do 
    GIT_USER="my-user" \
    GIT_EMAIL="my-user@example.com" \
    GITHUB_OWNER="my-user" \
    GITHUB_REPO="my-repo" \
    GITHUB_TOKEN="$(gh auth token)" \
    UPDATE_CHANNEL="$i" \
    RANDOM="${RANDOM}" \
    updatecli apply --config .ci/update-versions/test.yml; 
done
```

### Environment

```markdown
- OS: Ubuntu 22.04
- updatecli: v0.78.0
```

### Anything else?

I think is related to the changes at https://github.com/updatecli/updatecli/issues/2039

**Comment by olblak** [comment]
Mmmh interesting bug, that area of code is not easy to test.
Can you confirm that:

1. you are not running Updatecli in experimental mode
2. Each Updatecli execution within the loop, create a different working branch
3. Working branches are correctly created but it failed open a pullrequest

**Comment by kuisathaverat** [comment]
>you are not running Updatecli in experimental mode

nop

>Each Updatecli execution within the loop, create a different working branch

it happens running in the same shell like the example or running in different workflows and runners.

>Working branches are correctly created but it failed open a pullrequest

the only message is the one related to the diverge

```
WARNING: GitHub pull request creation skipped as branch "updatecli_main_2e4738258883e65e74efa81cba52f74fdcf5e5c76cee53c658e2587e6175f113" diverged from "main"
```

Is there a way to disable the diverge checking and create the PR always? that's fixes the issue for me.

**Comment by olblak** [comment]
> Is there a way to disable the diverge checking and create the PR always? that's fixes the issue for me.

Yes if you set `force` to `false`, it won't try to update the base branch

like 
```
scms:
  githubConfig:
    kind: "github"
    spec:
      user: '{{ requiredEnv "GIT_USER" }}'
      email: '{{ requiredEnv "GIT_EMAIL" }}'
      owner: '{{ requiredEnv "GITHUB_OWNER" }}'
      repository: '{{ requiredEnv "GITHUB_REPO" }}'
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      username: '{{ requiredEnv "GIT_USER" }}'
      branch: "main"
      force: false
```


> it happens running in the same shell like the example or running in different workflows and runners.

Base on your manifest, each updatecli execution within your shell loop should open a different pullrequest from a different branch like `updatecli_main_xxx`
If I understand correctly those pipelines only contain one target per pullrequest
