### ISSUE TITLE
Add a new resource of type "AMI" (Amazon Machine Image)

### ISSUE THREAD

**Issue by dduportal** [updatecli/updatecli#222]
**Is your feature request related to a problem? Please describe.**

I would like to use to keep up-to-date the AMI references of some of my projects:

- Jenkins CasC YAML (EC2 Cloud setup)
- Terraform project throug variables written in a [`.tfvars`](https://www.terraform.io/docs/language/values/variables.html#variable-definitions-tfvars-files`) file
- Packer project (chaining AMI builds) through a file

**Describe the solution you'd like**

A new resource of kind `ami`:

* Source: allow to filter AMI on my AWS account to retrieve the latest version
* Condition: ensure that an AMI exists, given a set of filters
* Target: none (I don't see any use case immediatly)

**Describe alternatives you've considered**

Terraform and Packer have AMI filters that could do the job (almost) but using an updatecli process allows to force a static version and delegate the update process.

**Additional context**

- Command `describe-images` of the CLI `aws ec2`, to have an idea of what the AWS API allows: <https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-images.html>
- Data source `aws_ami` used in terraform to retrieve an AMI: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ami

Configuration example proposal:

```yml
---
title: "Bump ubuntu1804 arm Jenkins ec2 agent AMI"
sources:
  getLatestUbuntu1804ArmAMI:
    ## Only the latest ami should be returned (e.g. only 1 value)
    ## If multiple results are returned, then only the latest is kept but a warning is issued in the stoud with the returned values
    kind: ami
    name: Get the latest AMI ID
    spec:
      owners:
        - self # Default value
        - amazon # String value (common name of the publisher in the AWS Marketplace)
        - 12234567 # Int value (ID of the publisher in the AWS Marketplace)
      executable_users:
        - self # Default value
        - cloudbees@infra-admin # String of IAM user allowed to start an instance with the returned AMI
      filters: # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Filtering.html#Filtering_Resources_CLI
        # Single value (easy case)
        - name: "root-device-type"
          values: "ebs"
        # Multiple values: string with comma as a separator
        - name: "instance-type"
          values: "m5.large,m5d.large"
        # Patterns
        - name: "name"
          values: "*ubuntu*1804*arm*"
      region: "us-east-1" # Region to use for the research. Can be used if different from the current AWS config
conditions:
  checkLatestUbuntu1804ArmAMI:
    ## Returns true if at least 1 AMI is returned by the research
    kind: ami
    name: Check if there is an ubuntu 1804 ARM image
    spec:
      owners:
        - self # Default value
        - amazon # String value (common name of the publisher in the AWS Marketplace)
        - 12234567 # Int value (ID of the publisher in the AWS Marketplace)
      executable_users:
        - self # Default value
        - cloudbees@infra-admin # String of IAM user allowed to start an instance with the returned AMI
      filters: # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Filtering.html#Filtering_Resources_CLI
        # Single value (easy case)
        - name: "root-device-type"
          values: "ebs"
        # Multiple values: string with comma as a separator
        - name: "instance-type"
          values: "m5.large,m5d.large"
        # Patterns
        - name: "name"
          values: "*ubuntu*1804*amd*"
      region: "us-east-1" # Region to use for the research. Can be used if different from the current AWS config
...
```
