### ISSUE TITLE
Feature Request: Possiblity to run shell-commands as actions

### ISSUE THREAD

**Issue by argoyle** [updatecli/updatecli#2257]
### Is your feature request related to a problem?

I have a case where I want to run kubectl kustomize after updating some values using updatecli but before creating a pull request.

### Solution you'd like

Either a way to run shell-commands as actions or a way to run everything except the actions (so I can run another shell-script and then run the full pipeline)

**Comment by olblak** [comment]
Thanks for suggesting this feature request. It's  problem I stumble a while ago, Updatecli being declarative vs imperative.

The way we resolved this is by chaining targets together for example in the following snippet

```
name: example issue 2257
  
sources:
  chart:
    kind: helmchart
    name: Get latest Rancher Helm Chart version
    spec:
      url: https://releases.rancher.com/server-charts/latest
      name: rancher

targets:
  manifest:
    kind: yaml
    name: Update rancher/manifest.yaml
    spec:
      file: rancher/manifest.yaml
      key: $.version
    sourceid: chart

  kubectl:
    name: run kubectl when manifest.yaml changed
    kind: shell
    dependson:
      - manifest
    dependsonchange: true
    disablesourceinput: true
    spec:
      command: "kubectl apply -f rancher/manifest.yaml"
```

We use `dependson` + `dependsonchange` in the second target to only execute the command `kubectl` if `rancher/manifest.yaml` changed.

I still have a lot to document for the shell plugin.
