### ISSUE TITLE
Feature Request: add source for `dockerfile` resource

### ISSUE THREAD

**Issue by dduportal** [updatecli/updatecli#2275]
### Is your feature request related to a problem?

I need to retrieve the value of a `FROM` instruction in a `Dockerfile` to use its value in my manifest, but the resource kind `dockerfile` does not have source support.

My manifest is there: https://github.com/jenkins-infra/docker-packaging/blob/048f979f954e8851db6f6c8abb0d6532ccc64186/updatecli/updatecli.d/jdk-build.yml#L38-L47

It tries to read the following instruction: https://github.com/jenkins-infra/docker-packaging/blob/048f979f954e8851db6f6c8abb0d6532ccc64186/Dockerfile#L6

### Solution you'd like

With the following `Dockerfile`:

```
FROM eclipse-temurin:${JAVA_VERSION}-jdk-jammy AS jdk
FROM --platform=linux/amd64 eclipse-mosquitto:2.0
```

I would expect:

- Snippet below to return `eclipse-temurin:${JAVA_VERSION}-jdk-jammy`:

```
sources:
  getImageName:
    name: Get the Image name
    kind: dockerfile
    spec:
      file: Dockerfile      
      instruction:
        keyword: "FROM"
        matcher: "eclipse-temurin"
```

- Snippet below to return `eclipse-mosquitto:2.0`:

```
sources:
  getImageName:
    name: Get the Image name
    kind: dockerfile
    spec:
      file: Dockerfile      
      instruction:
        keyword: "FROM"
        matcher: "mosquitto"
```

- Snippet below to return (multiline string)

```
eclipse-temurin:${JAVA_VERSION}-jdk-jammy
eclipse-mosquitto:2.0`:
```

```
sources:
  getImageName:
    name: Get the Image name
    kind: dockerfile
    spec:
      file: Dockerfile      
      instruction:
        keyword: "FROM"
        matcher: "eclipse-"
```

### Alternatives you've considered

For now, we are using a `file` resource with a `matchpattern`: it works but it is tedious.
