### ISSUE TITLE
Feature Request: with `dockerfile` resource, support `FROM <...> AS <...>` form

### ISSUE THREAD

**Issue by dduportal** [updatecli/updatecli#2276]
### Is your feature request related to a problem?

I would like  `updatecli` to manage the parent image alias, e.g. the `AS` secondary keyword  in the `FROM` instruction from dockerfile resource.

### Solution you'd like

With the following `Dockerfile`:

```
FROM eclipse-temurin:${JAVA_VERSION}-jdk-jammy AS jdk
FROM --platform=linux/amd64 eclipse-mosquitto:2.0
```

The following manifest should change the `Dockerfile` to 

```
FROM eclipse-temurin:${JAVA_VERSION}-jdk-jammy AS hello
FROM --platform=linux/amd64 eclipse-mosquitto:2.0 AS world
```

```
sources:
  sayHello:
    kind: shell
    spec:
      command: echo hello
  sayWorld:
    kind: shell
    spec:
      command: echo world

targets:
  setFromAliasToHello:
    sourceID: sayHello
    kind: dockerfile
    spec:
      file: Dockerfile
      instruction:
        keyword: "FROM-AS" # New keyword
        matcher: "eclipse-temurin"
  setFromAliasToWorld:
    sourceID: sayWorld
    kind: dockerfile
    spec:
      file: Dockerfile
      instruction:
        keyword: "FROM-AS" # New keyword
        matcher: "eclipse-mosquitto"
```

### Alternatives you've considered

Using file matcher works but is tedious
