### ISSUE TITLE
Feature Request: support partial content for the resource "file"

### ISSUE THREAD

**Issue by dduportal** [updatecli/updatecli#231]
## Is your feature request related to a problem? Please describe.

updatecli is used for https://github.com/asciidoctor/docker-asciidoctor , to update the dependencies of the Docker image.
There are 3 locations where the list of dependencies, and their versions, are defined:
* Dockerfile => works fine with the resource "Dockerfile" of updateCLI ✅ 
* Test harness => using bats/shell, an "environment file" is needed. As YAML is supported by updatecli to selectively update values, we use a simple YAML file to support the list of key/values, and a [`sed` instruction](https://github.com/asciidoctor/docker-asciidoctor/blob/main/tests/test_suite.bats#L11) is used to transform the YAML to a temporary env-file, which is sourced ⚠️ 
* README => the readme holds the list of dependencies and versions thanks to [asciidoctor's attributes](https://docs.asciidoctor.org/asciidoc/latest/attributes/document-attributes/). We had to [update the README](https://github.com/asciidoctor/docker-asciidoctor/pull/204/files) to be generated from a template, with a `sed` operation to parse to YAML into asciidoctor's attribute's syntax ⚠️ 

This issue targets the described used case, as we would want to be able to define files to be changed in their own syntaxes (shell env file, asciidoctor's file) using a kind of search & replace pattern.

## Describe the solution you'd like

As for today, the resource "File" targets the whole content of a file. The proposal is to support partial content from a file as an additional behavior:

#### For a source of kind `file`:
 
* Select content per line by giving a line number as a strictly positive integer

```yaml
# Source holds the complete line #2 of README.adoc
sources:
  kind: file
  spec:
    file: README.adoc
    line: 2
```

* Select content per pattern matching (regex? simple pattern ?)
 
```yaml
# Source holds the aggregation of all the lines of README.adoc matching the pattern 
sources:
  kind: file
  spec:
    file: README.adoc
    content:
      pattern: "^:asciidoctor_pdf_version:.*$"
```

* The source could be "transformed" like the "githubRelease" resource:

```yaml
# Source holds the aggregation of all the lines of README.adoc matching the pattern 
sources:
  kind: file
  spec:
    file: README.adoc
    content:
      pattern: "^:asciidoctor_pdf_version:.*$"
  transformers:
      - trimPrefix: ":asciidoctor_pdf_version:"
```

#### For a condition of kind `file`:
 
* Check that the file content matches a pattern

```yaml
# Fails if the file README.adoc does not have a line starting with ":asciidoctor_pdf_version:"
conditions:
  kind: file
  spec:
    file: README.adoc
    content:
      pattern: "^:asciidoctor_pdf_version:"
```

#### For a target of kind `file`:
 
* Replace the line 5 of README.adoc by the content of the source

```yaml
# Sets the line 5 of README.adoc to the value from the source
targets:
  kind: file
  sourceID: "asciidoctorPDFVersion"
  spec:
    file: README.adoc
    line: 5 
```

* Replace the line using a standard golang regex replaceAll pattern

```yaml
# 
targets:
  kind: file
  sourceID: "asciidoctorPDFVersion"
  spec:
    file: README.adoc
    content:
      pattern: ":asciidoctor_pdf_version: (\d*).(\d*).(\d*)"
      replace: ":asciidoctor_pdf_version: $SOURCE" # $SOURCE maps to the source's content
```

**Comment by dduportal** [comment]
That's a good point! #167 is almost there. The only issue is the "target" part which replace all the target file (and not only the line specified):

```
---
title: "Bump maven version"
sources:
  getMavenVersion:
    kind: githubRelease
    name: Get the latest Maven version
    spec:
      owner: "apache"
      repository: "maven"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      versionFilter:
        kind: regex
        pattern: 'maven-3.(\d*).(\d*)'
    transformers:
      - trimPrefix: "maven-"
      - addPrefix: 'maven_version = "'
      - addSuffix: '"'
targets:
  updateMavenVersion:
    name: "Update the value of maven_version in Packer's Variables File"
    sourceID: getMavenVersion
    kind: file
    spec:
      file: .auto.pkrvars.hcl
      line:
        includes:
          - "maven_version"
```

gives:

```
DIFF


+++++++++++
+ PREPARE +
+++++++++++



+++++++
+ RUN +
+++++++



######################
# BUMP MAVEN VERSION #
######################



SOURCE:
=======

⚠ No GitHub Release found. As fallback Looking at published git tags
Searching for version matching pattern "maven-3.(\\d*).(\\d*)"
✔ Github Release version "maven-3.8.1" found matching pattern "maven-3.(\\d*).(\\d*)"


CHANGELOG:
==========
No Github Release found for maven-3.8.1 on https://github.com/apache/maven


TARGETS:
========


**Dry Run enabled**
✔ File content for '.auto.pkrvars.hcl', updated. 
< maven_version               = "3.8.1"
< git_version                 = "2.29.2"
< jdk11_version               = "11.0.9+11"
< jdk8_version                = "8u272-b10"
< git_lfs_version             = "2.12.1"
< compose_version             = "1.25.4"
< openssh_version             = "v8.1.0.0p1-Beta"
< openssh_authorized_keys_url = "https://raw.githubusercontent.com/jenkins-infra/aws/main/ec2_agents_authorized_keys"
< 
---
> maven_version = "3.8.1"
> 

=============================

REPORTS:


⚠ MAVEN.YML
        Sources:
                ✔  Get the latest Maven version(githubRelease)
        Target:
                ⚠  Update the value of maven_version in Packer's Variables File(file)



Run Summary
===========
1 job run
0 job succeed
0 job failed
1 job applied changes
```
