### ISSUE TITLE
semver filtering affect changelog output

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#244]
**Describe the bug**
It seems that when we filter a version retrieved from a githubRelease, using the filter "semver" retrieve the "v" in front of the version and so we can't retrieve the changelog anymore

**To Reproduce**
```
  helmfile:
    kind: githubRelease
    name: Get the latest helmfile version
    spec:
      owner: "gohugoio"
      repository: "hugo"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      #versionFilter:
      #  kind: semver
      #  pattern: "~0"
    # TrimPrefix so we can retrieve the changelog
    transformers:
      - trimPrefix: "v" 
```

**Expected behavior**
We should keep track of the real version retrieved from a github release

```
  helmfile:
    kind: githubRelease
    name: Get the latest helmfile version
    spec:
      owner: "gohugoio"
      repository: "hugo"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      #versionFilter:
      #  kind: semver
      #  pattern: "~0"
```

**Version (please complete the following information):**
 - OS: linux
 - Version: v0.4.0

**Additional context**
