### ISSUE TITLE
Using versionfilter in Argocd auto discovery

### ISSUE THREAD

**Issue by cloudoutloud** [updatecli/updatecli#2467]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I don't know if this is an issue or if my understanding may be wrong.

Using Argocd autodiscovery when setting the below

```
versionfilter:
   kind: semver
   pattern: major
   strict: true
```

It still raises pull requests for non-major upgrades such as the below 

![Screenshot 2024-08-06 at 20 25 43](https://github.com/user-attachments/assets/a20b110c-78c6-4a9b-b091-7722ca218931)

in logs 
```
Searching for version matching pattern ">=1"
```
So it just matches all greater?

### Expected Behavior

I would have thought it only created a PR if the major version had changed and ignored minor and patch updates.
based of docs https://www.updatecli.io/docs/plugins/autodiscovery/argocd/
major - major only update major versions

### Steps To Reproduce

**1. Config used** 

```
# updatecli.d/default.yaml
name: Argocd Autodiscovery Example

autodiscovery:
  # 1 PR per a chart
  groupby: individual
  # scmid is applied to all crawlers
  scmid: default
  # actionid is applied to all crawlers
  actionid: default
  crawlers:
    argocd:
      # Only update on major versions
      versionfilter:
        kind: semver
        pattern: major
        strict: true

scms:
  default:
    kind: github
    spec:
      user: 'github-actions[bot]'
      username: 'github-actions[bot]'
      email: 'github-actions[bot]@users.noreply.github.com'
      owner: 'cloudoutloud'
      repository: 'test-updatecli'
      token: '{{ requiredEnv "UPDATECLI_GITHUB_TOKEN" }}'
      branch: 'main'
      commitusingapi: true

actions:
  default:
    kind: "github/pullrequest"
    spec:
      mergemethod: "squash"
    scmid: "default"
```
**2. On Manifest**
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: groundcover
  namespace: argocd
spec:
  project: default
  source:
    chart: groundcover
    repoURL: https://helm.groundcover.com
    targetRevision: 1.8.61
    helm:
      releaseName: groundcover
  destination:
    server: "https://kubernetes.default.svc"
    namespace: groundcover
```

### Environment

```markdown
- OS: Ubuntu 22.04.4
- updatecli: v0.82.0
- Golang: 1.22.5 linux/amd64
```

### Anything else?

I am running this in a github action.
