### ISSUE TITLE
Golang go.mod Autodiscovery: latest versionfilter selects old version

### ISSUE THREAD

**Issue by in0rdr** [updatecli/updatecli#2528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I run updatecli v0.82 on a [golang project](https://code.in0rdr.ch/hivedav/file/go.mod.html) with following config file for autodiscovery using the [gomod crawler](https://www.updatecli.io/docs/plugins/autodiscovery/golang):

```yaml
# updatecli.d/default.yaml
name: Update go dependencies
# use jenkins $BUILD_NUMBER env var
pipelineid: {{ requiredEnv "BUILD_NUMBER" }}
scms:
  default:
    # https://www.updatecli.io/docs/core/scm
    kind: git
    spec:
      url: "https://git.in0rdr.ch/hivedav.git"
      # read git credentials from jenkins secret
      username: {{ requiredEnv "GIT_USERNAME" }}
      password: {{ requiredEnv "GIT_PASSWORD" }}
      user: {{ requiredEnv "GIT_AUTHOR_NAME" }}
      email: {{ requiredEnv "GIT_AUTHOR_EMAIL" }}
      # source branch
      branch: master
      # create remote target branch updatecli_master_$PIPELINEID to push changes
      workingbranch: true
      # reuse existing target branch updatecli_master_$PIPELINEID
      force: true

# no targets, use autodiscovery
# - https://www.updatecli.io/docs/guides/npm
# - https://www.updatecli.io/docs/core/autodiscovery
autodiscovery:
  scmid: default
  crawlers:
    # https://www.updatecli.io/docs/plugins/autodiscovery/golang
    golang/gomod:
      versionfilter:
        kind: latest
      ignore:
        - modules:
            # Skip modules that don't have "latest" version
            github.com/jordan-wright/email:
            github.com/emersion/go-ical:
            gopkg.in/robfig/cron.v2:
            github.com/pquerna/termchalk:

actions:
  default:
    kind: git
    scmid: default
```

`updatecli diff` shows me that the module `github.com/spf13/viper` would be downgraded from v1.18.2 to v1.9.0:

```
⚠ - go.mod should update Module path "github.com/spf13/viper" version from "v1.18.2" to "v1.9.0"
```

### Expected Behavior

I expected updatecli to bump the version to the actual latest module release [v1.19.0](https://github.com/spf13/viper/releases/tag/v1.19.0).

### Steps To Reproduce

```bash
# download source code
git clone https://in0rdr@git.in0rdr.ch/hivedav.git
cd hivedav

# fake the pipeline env
export BUILD_NUMBER=123
export PIPELINEID=123
export GIT_USERNAME="foo"
export GIT_PASSWORD="bar"
export GIT_AUTHOR_NAME="foo"
export GIT_AUTHOR_EMAIL="bar"

# run updatecli
updatecli version

VERSION

Application:    0.82.2
Golang     :    1.22.6 linux/amd64
Build Time :    2024-08-13T14:51:57Z

updatecli diff
```

### Environment

```markdown
- OS: NixOS 24.05 (Uakari)
- updatecli: 0.82.2
```

**Comment by in0rdr** [comment]
I have one more observation which might help to debug the issue with the `latest` versionfilter here. The `semver` filter works as expected:

```yaml
# updatecli.d/default.yaml
...
      versionfilter:
        kind: semver
        pattern: major
```

This reports the correct upgrade path:

```
⚠ - go.mod should update Module path "github.com/spf13/viper" version from "v1.18.2" to "v1.19.0"
```

I'll stick to the semver filter for now to select the correct version (1.19).
