### ISSUE TITLE
Feature Request: allow scm directive at top-level

### ISSUE THREAD

**Issue by dduportal** [updatecli/updatecli#260]
**Is your feature request related to a problem? Please describe.**
The directive `scm` is quite always a copy and paste and repeated on a given pipeline file. For instance, look at https://github.com/jenkins-infra/jenkins-infra/pull/1834/files#diff-e75ea1a6ba30a7ab01ebebc5cfb7ed693f4895d862f01db823c6058c6db979a1 .

This creates uneeded verbosity and risks of diverging configurations when changing a repository parameter (token/etc).

**Describe the solution you'd like**

I would like to be able to define the `scm` block one time as a top level directive, so it could be reused by default by all my sources/conditions/target without repeating.

Then I would have to define an empty key `scm` (either `scm:` or `scm {}`, I don't mind) to specify that I want to use scm, and that it would inherit from the top-level key (hence avoid repeating)

```yaml
---
title: Bump ci.jenkins.io agent templates
# Top level default setting to be reused everywhere
scm:
  github:
    user: "{{ .github.user }}"
    email: "{{ .github.email }}"
    owner: "{{ .github.owner }}"
    repository: "{{ .github.repository }}"
    token: "{{ requiredEnv .github.token }}"
    username: "{{ .github.username }}"
    branch: "{{ .github.branch }}"

sources:
  getAzureGalleryLatestVersion:
    kind: githubRelease
    spec:
      owner: "jenkins-infra"
      repository: "packer-images"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
    scm: # Empty
  getLatestInboundAlpineContainerImage:
    kind: dockerDigest
    spec:
      image: "jenkins/inbound-agent"
      tag: "alpine"
    scm: {} # empty
targets:
  setAzureGalleryImageVersion:
    sourceID: getAzureGalleryLatestVersion
    name: "Bump Azure Gallery Image Version"
    kind: yaml
    spec:
      file: hieradata/common.yaml
      key: "profile::buildmaster::agents_azure_vms_gallery_image_version"
    scm: # Empty
  setInboundAlpineContainerImage:
    sourceID: getLatestInboundAlpineContainerImage
    name: "Bump ci.jenkins.io container agent image jenkins/inbound-agent (Alpine)"
    kind: yaml
    spec:
      file: hieradata/clients/azure.ci.jenkins.io.yaml
      key: "profile::buildmaster::container_agents[4].image"
    transformers:
      - addPrefix: "jenkins/inbound-agent@sha256:"
    scm: {} # Empty
```

Of course, I might want to be able to override locally one of the settings (for instance changing the repository only for one target).

```yaml
---
title: Bump ci.jenkins.io agent templates

scm:
  github:
    user: "{{ .github.user }}"
    email: "{{ .github.email }}"
    owner: "{{ .github.owner }}"
    repository: "{{ .github.repository }}"
    token: "{{ requiredEnv .github.token }}"
    username: "{{ .github.username }}"
    branch: "{{ .github.branch }}"

sources:
  getLatestInboundAlpineContainerImage:
    kind: dockerDigest
    spec:
      image: "jenkins/inbound-agent"
      tag: "alpine"
    scm: {} # empty
targets:
  setInboundAlpineContainerImage:
    sourceID: getLatestInboundAlpineContainerImage
    name: "Bump ci.jenkins.io container agent image jenkins/inbound-agent (Alpine)"
    kind: yaml
    spec:
      file: hieradata/clients/azure.ci.jenkins.io.yaml
      key: "profile::buildmaster::container_agents[4].image"
    transformers:
      - addPrefix: "jenkins/inbound-agent@sha256:"
    scm:
      github:
        owner: "another-github-org" # Overrides default 
        repository: "another-github-repo" # Overrides default 
```

This feature implies that there are 3 possible scopes for the `scm` object (and it content):

- Object level directive: that is the actual `scm:`, which is defined for each object. This one should be kept, and should always takes precedence (overrides existing values)
- Top level directive `scm` which scope is ALL categories (sources, conditions and targets) and ALL objects (if they define an `scm` directive) - see previous examples 
- Category level directive: defining a set of scm options scoped to either sources, conditions or targets.
  - Not sure where to define this one: cannot be under the `sources:`, `conditions:` or `targets` because it would be confusing and confused with the real objects (sources,conditions, targets).
  - @olblak you mentioned the idea of defining scope at the top level directive (such as `category-scope: targets, sources` for instances). This would implies we that the scm top level would be a list:

```yaml
scm:
  - scopes: # All scopes (e.g. default)
     - sources
     - conditions
     - targets
    github:
       user: "dduportal"
       username: "dduportal"
       email: "dduportal@nowhere.org"
       token: "{{ requiredEnv .github.token }}"
       owner: "dduportal-gh-org"
       repository: "awesome-repo"
       branch: "main"
  - scopes: # Only on targets
       - targets
     github:
       owner: "corporate-gh-org" # e.g. github.com/corporate-gh-org/awesome-repo
       branch: "master"
```

**Describe alternatives you've considered**

- Tried YAML anchors: it does not work (fails to be parsed as the library go-yaml library does not support it out of the box)
- Templating only changes the values, but it does not decrease verbosity

**Additional context**
N.A.

**Comment by olblak** [comment]
What would you think to have something like 
```
scm:
    scm1:
        kind: github
        spec:
            ...
sources:
    source1:
         kind: yaml
         scmID: scm1
```
Using a key referencing a SCM id could be usefull in this [context](https://github.com/updatecli/updatecli/issues/261) as well.
We could use a different name than "scm"
