### ISSUE TITLE
Improve `github` 's `scm` block to fully support pull requests uses cases

### ISSUE THREAD

**Issue by dduportal** [updatecli/updatecli#261]
**Is your feature request related to a problem? Please describe.**

- When looking at an SCM directive block, it's not really explicit that updatecli should open a PR:

```yaml
scm:
  github:
    user: "{{ .github.user }}"
    email: "{{ .github.email }}"
    owner: "{{ .github.owner }}"
    repository: "{{ .github.repository }}"
    token: "{{ requiredEnv .github.token }}"
    username: "{{ .github.username }}"
    branch: "{{ .github.branch }}" # Is it a PR targeted to that branch, a commit to this branch, should it be created if not existing?
```

- It's not possible to define PR attributes or policies such as labels, approvers, or auto-merge

**Describe the solution you'd like**

WDYT about defining a "pull_request" block?

* Default uses the principal branch of the current defined repository:

```yaml
targets:
  myCustomTarget:
    # Target stuff here ...
    scm:
      github:
        # usual directives such as user, token, etc.
        pull_request:
```

* You can define a custom target repository (use cases of forks) and branch (when not using the default):

```yaml
targets:
  myCustomTarget:
    # Target stuff here ...
    scm:
      github:
        owner: "dduportal"
        repository: "jenkins-infra-charts"
        branch: "production"
        pull_request: 
          target_owner: "jenkins-infra"
          target_repository: "charts"
          target_repository: "master"
# Should open a PR from github.com/dduportal/jenkins-infra-charts/tree/production to github.com/jenkins-infra/charts/tree/master
```

* Define custom PR attributes (at least labels).
The "labels" are tracked in #108 .

```yaml
targets:
  myCustomTarget:
    # Target stuff here ...
    scm:
      github:
        # usual directives such as user, token, etc.
        pull_request:
          labels:
            - "bypass-review"
            - "hotfix"
          auto_merge: true
```

**Describe alternatives you've considered**

- Define a custom bot for merging PRs outside updatecli: not really a solution

**Additional context**

N.A.

**Comment by olblak** [comment]
Now that I spent more time dealing with different pullRequest scenarios, I am thinking about having an additional "stage" after target where I could define which and how to open pullrequest. 
This would be an example (not yet implemented) 

```
sources:
    ...
conditions:
    ...
targets:
    target1:
    target2: 
pullRequest:
    title: this is a pull request title with default to pipeline title
    dependsOnTarget:
         -  target1 # A target key
         -  target2 # The second target key
     kind: github # At this stage we only support github pullrequest
     spec:
         labels:
             - documentation
             - enhancement
         draft: true
```
Being able to specify a list of target as dependency mean that the body of the pull request would not changed between updatecli run
