### ISSUE TITLE
 Improve `scm` block to support "local" pull requests

### ISSUE THREAD

**Issue by dduportal** [updatecli/updatecli#262]
**Is your feature request related to a problem? Please describe.**

In the PR https://github.com/jenkins-infra/charts/pull/1389, a new code component had been introduced.
I wanted to add (and enable) the associated updatecli configuration so once merged, no need to open a 2 PR for updatecli and it's already automated.

However the presence of the `scm` directive made the PR's check to fail initially: the code had to be present on the `master` branch priro to opening a PR with the updatecli configuration.

We ended up in adding the updatecli config disabled, and delay to a second PR, at the risk to forget it.

**Describe the solution you'd like**

I would like to be able to define updatecli policy that would use the "local" repository for the sources/conditions/targets content so that any change in the code would be associated to the current updatecli configuration.

For instance, when the command `updatecli apply #...` is run, would open a PR on {{ .github.owner }}/{{ .github.repository }} from the actual local content (not from the code from the remote branch):

```
title: Bump autoscaler helm chart version
sources:
  default:
    kind: helmChart
    spec:
      url: https://kubernetes.github.io/autoscaler
      name: cluster-autoscaler
conditions:
  exist:
    name: "Autoscaler helm chart available on Registry"
    kind: helmChart
    spec:
      url: https://kubernetes.github.io/autoscaler
      name: cluster-autoscaler
  helmfileRelease:
    name: "autoscaler/cluster-autoscaler Helm Chart"
    kind: yaml
    spec:
      file: "helmfile.d/autoscaler.yaml"
      key: "releases[0].name"
      value: "autoscaler"
targets:
  chartVersion:
    name: "autoscaler/cluster-autoscaler Helm Chart"
    kind: yaml
    spec:
      file: "helmfile.d/autoscaler.yaml"
      key: "releases[0].version"
    scm:
      github:
        user: "{{ .github.user }}"
        email: "{{ .github.email }}"
        owner: "{{ .github.owner }}"
        repository: "{{ .github.repository }}"
        token: "{{ requiredEnv .github.token }}"
        username: "{{ .github.username }}"
        branch: "{{ .github.branch }}"
```

**Describe alternatives you've considered**

- Open 2 PRs for each new config
- Comment out the whole `scm` block to test the updatecli config, and NOT forget to uncomment

**Additional context**

N.A.
