### ISSUE TITLE
 Add a new resource of type "shell"

### ISSUE THREAD

**Issue by dduportal** [updatecli/updatecli#263]
**Is your feature request related to a problem? Please describe.**

Sometime, I would want to execute a custom shell script to retrieve a "source" for updatecli when it does not support it (for instance: until #222 is implemented, I would use a `get_latest_ami.sh` script instead to retrieve the string I expec, or any unsupported system.

**Describe the solution you'd like**

A new provider `shell`that would:

- for sources, uses the stdout of the command as value for the source, if and only if the exit code is 0, otherwise updatecli fails, and the stderr of the command would be shown as the updatecli CLI output

- for conditions, pass the provided source as argument to the command, and uses the exit code to validate the condition

- for target, pass the provided source as argument to the command, uses the exit code to see if it changes something, or not, or failed (code 0 = success with nothing changed, code 2 means success with the change printed on the stdout, other ocdes means failure)

```yaml
title: Do something
sources:
  default:
    kind: shell
    spec:
      command: "bash -x get_latest_ami.sh {{ .aws.account_name }}"
      name: get latest AMI
conditions:
  exist:
    name: Check that the AMI has the tag "cb-ready" present
    kind: shell
    spec:
      sourceID: default
      # Script check_tag_on_ami expectes $1 to be the provided template value, and $2 to be the value from "default"
      command: "bash -x check_tag_on_ami.sh {{ .aws.account_name }}"
      name: cluster-autoscaler
targets:
  copyAmi:
    name: Copy the AMI from us-east-1 to the region eu-west-2
    kind: shell
    spec:
      sourceID: default
      # the command expects a $1 argument set to the value of the source
      command: "aws ec2 copy-image --region-from=us-east-1 --region-to=eu-west-2"
```

**Describe alternatives you've considered**
N.A.

**Additional context**

This "generic" provider:

- Could allow supporting non native existing providers, hence limiting the amount of work
- Should be able to (nice to have) customize the command prompt: `sh`, `zsh` or even... `powershell` on windows :)
