### ISSUE TITLE
Feature Request: support for github issue creation/commenting

### ISSUE THREAD

**Issue by smerle33** [updatecli/updatecli#2641]
### Is your feature request related to a problem?

While working on https://github.com/jenkins-infra/docker-openvpn/pull/354 I decided to automate the issue generation for CRL cert renewal.
Which lead me to use GH, but this could have been embedded within updatecli as a target (not action as for this example there is no target to provide, and target is mandatory to use action)		

### Solution you'd like

```yaml
targets:
  createIssue:
    kind: github/issue
  scmid: default
  title: Bump CRL cert as will expire soon {{ source "previousendate" }}
    body: |
      "follow https://github.com/jenkins-infra/docker-openvpn?tab=readme-ov-file#howto-renew-certificate-revocation-list \
        See https://github.com/jenkins-infra/helpdesk/issues/4266 for details."
  spec:
    labels:
      - crl
      - updatecli
```

### Alternatives you've considered

using gh but then I needed to check on already openned issue
