### ISSUE TITLE
Allow to automatically sign commits

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#274]
**Is your feature request related to a problem? Please describe.**
It's not possible to use updatecli in environment that enforce signed commits

**Describe the solution you'd like**
I would to be able to provide a gpg key to signed commits created by updatecli such as

```
    scm:
      github:
        user: updatecli
        email: info@example.com
        owner: updatecli
        repository: updatecli
        token: ...
        username: ...
        branch: main
        gpg: 
          sign: true
          signingKey: xxxx
```

**Describe alternatives you've considered**

**Additional context**
Example of fail commit https://github.com/updatecli/updatecli/pull/272

**Comment by dduportal** [comment]
That would be a great feature!

Minor improvement proposal: I would shrink the setup to a single key such as `gpgSigningKey`. The rationale is that there are no reason (unless I miss it: please le me know) to set `sign` to false, which meanse either you provide a signingkey hence you enable the gpg signing, or you do not.

e.g.

```
    scm:
      github:
        user: updatecli
        email: info@example.com
        owner: updatecli
        repository: updatecli
        token: ...
        username: ...
        branch: main
        gpgSigningKey: xxxx # Sign commits if defined (and valid)
```
