### ISSUE TITLE
Not possible to refer to the output of one source within another source?

### ISSUE THREAD

**Issue by dnwe** [updatecli/updatecli#278]
**Describe the bug**
Unless I'm missing something, it doesn't appear to be possible to refer to the output of one source within a templating of another. In this case I'd like to lookup the latest prometheus version and then also fetch the content of the shasums file to write out:

**To Reproduce**
```yaml
sources:
  latestPromVersion:
    name: Get latest prometheus release version
    kind: githubRelease
    spec:
      owner: "prometheus"
      repository: "prometheus"
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
  latestPromChecksum:
    name: Get latest prometheus release checksum
    kind: file
    spec:
      file: 'https://github.com/prometheus/prometheus/releases/download/v{{ source "latestPromVersion" }}/sha256sums.txt'
    transformers:
      - find: '(.*)  prometheus-{{ source "latestPromVersion" }}.linux-arm64.tar.gz'
      - trimSuffix: '  prometheus-{{ source "latestPromVersion" }}.linux-arm64.tar.gz'
```

**Expected behavior**
I hoped to be able to use the output of latestPromVersion to template the file spec of latestPromChecksum

**Screenshots**
N/A

**Version (please complete the following information):**
 - OS: [e.g. linux] darwin/amd64
 - Version [e.g. v0.0.15] v0.7.1
