### ISSUE TITLE
No error return when sourceID doesn't exist

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#281]
**Describe the bug**
We don't trigger an error if we reference a sourceID which doesn't exist such as in the following example.

```
sources:
  getLatestVersion:
    kind: shell
    spec:
      command: echo ami-XXXXX
conditions:
  checkIfAmiExist:
    name: Test if ami1 exist
    sourceID: doNotExist
    kind: shell
    spec:
      command: echo OK
```

**To Reproduce**
Just specific a sourceID which doesn't exist in any configuration

**Expected behavior**
I would expect an early error message

**Screenshots**
-

**Version (please complete the following information):**
 - OS: linux
 - Version: V0.7.1

**Additional context**
An early validation could be done when we load the configuration [here](https://github.com/updatecli/updatecli/blob/90e37f8ec93a945097b767762957aad746c9e022/pkg/core/config/main.go#L124)
