### ISSUE TITLE
XML: Unable to reference Attribute instead of Value.

### ISSUE THREAD

**Issue by zonorti** [updatecli/updatecli#2825]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am trying to read or write an XML Attribute using updatecli.
But not finding the value. According to XPath it's a valid query.
Error:

```
SOURCES
=======

xml
---
ERROR: ✗ cannot find value for path "/a/b/@MyVal" from file "test.xml"
ERROR: ✗ cannot find value for path "/a/b/@MyVal" from file "test.xml"
Pipeline "Test XML" failed
Skipping due to:
	sources stage:	"cannot find value for path \"/a/b/@MyVal\" from file \"test.xml\""
```

 See further for example files.

### Expected Behavior

Source: reads 1 from XML
Target: writes 1 into MyVal of /a/c

### Steps To Reproduce

test.xml
```
<a>
  <b MyVal="1">1</b>
  <c MyVal="2">2</c>
</a>
```
updatecli.yaml
```
name: Test XML

sources:
  xml:
    name: Read Attribute from XML
    kind: xml
    spec:
      file: test.xml
      path: "/a/b/@MyVal"

targets:
  xml:
    name: Change Attribute in XML
    kind: xml
    spec:
      file: test.xml
      path: "/a/c/@MyVal"
```

run `updatecli diff`

### Environment

```markdown
- OS: macOS Sonoma 14.4.1
- updatecli: 0.85.0
```
