### ISSUE TITLE
Bug: source executed while their parent source failed

### ISSUE THREAD

**Issue by dduportal** [updatecli/updatecli#285]
**Describe the bug**

In a scenario with sources depending on each other explictly (e.g. using the directive `depends_on`),

if the upstream source failed then the downtsream sources are still executed.
It leads to pipelines trying to execute with empty values, which is hard to catch at first sight.

**To Reproduce**

With this file:

```yml
# updateCli.yaml
sources:
  parentSource:
    kind: shell
    spec:
      command: /nonexistingcommandtofail
  childSource:
    kind: shell
    depends_on:
      - parentSource
    spec:
      command: echo CHILD-{{ source "parentSource" }}
target:
  printResult:
    kind: shell
    sourceID: childSource
    spec:
      command: echo
```

The command `updatecli diff` reports 1 job failure as expected, BUT the source `childSource` had been executed depsite the source `parentSource` failing:

```shell
SOURCE:
=======

ERROR: ✗ fork/exec /nonexistingcommandtofail: no such file or directory


SOURCE:
=======

✔ The shell 🐚 command "echo CHILD-{{ source \"parentSource\" }}" ran successfully and retrieved the following source value: "CHILD-{{ source \"parentSource\" }}"
```

**Expected behavior**

The source `childSource` should not be executed and the command line output should show it as "error because upstream".

**Additional context**
N.A.
