### ISSUE TITLE
Feature Request [Resource "shell"] Allow disabling adding the source as line argument

### ISSUE THREAD

**Issue by dduportal** [updatecli/updatecli#288]
**Is your feature request related to a problem? Please describe.**

The resource "shell", when used for condition or target, execute a command with the associated source output appended by default.

But sometimes, when the source is not needed (when using templating for instance), this "last argument" makes the command harder to read/write, or forces the user to create a separated shell script.

Consider this example:

```yaml
sources:
  mavenVersion:
    kind: githubRelease
    name: Get the latest Maven version
    spec:
      owner: "apache"
      repository: "maven"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      versionFilter:
        kind: latest
    transformers:
      - trimPrefix: "maven-"
 
conditions:
  checkIfMavenReleaseIsAvailable:
    kind: shell
    name: check if the found release is available for download
    sourceID: mavenVersion
    depends_on:
      - mavenVersion
    spec:
      command: curl --connect-timeout 5 --location --head --fail --silent --show-error https://archive.apache.org/dist/maven/maven-3/{{ source "mavenVersion" }}/binaries/apache-maven-{{ source "mavenVersion" }}-bin.tar.gz 

targets:
  showMavenVersion:
    name: Prints the latest Maven available version
    sourceID: mavenVersion
    kind: shell
    spec:
      command: echo
```

which results in the following output (truncated):

```text
SOURCE:
=======

⚠ No GitHub Release found. As fallback Looking at published git tags
Searching for version matching pattern "latest"
✔ Github Release version "maven-3.8.3" found matching pattern "latest"


CHANGELOG:
==========
No Github Release found for maven-3.8.3 on https://github.com/apache/maven


CONDITIONS:
===========

The shell 🐚 command "curl --connect-timeout 5 --location --head --fail --silent --show-error https://archive.apache.org/dist/maven/maven-3/3.8.3/binaries/apache-maven-3.8.3-bin.tar.gz 3.8.3" failed with an exit code of 28 and the following messages: 
stderr=

stdout=
curl: (22) The requested URL returned error: 404 Not Found
curl: (28) Connection timed out after 5004 milliseconds


✗ condition not met, skipping pipeline

=============================

REPORTS:


✗ UPDATECLI.YAML
        Sources:
                ✔  Get the latest Maven version(githubRelease)
        Condition:
                ✗  check if the found release is available for download(shell)
        Target:
                  ()



ERROR: ✗ 1/1 job(s) failed
ERROR: command failed
```

**Describe the solution you'd like**

I would like to be able to specify an optional attribute `appendSource` on the condition or the target.
By default, this attributes should be set to "true" to keep the current behavior.
When set to false, then the source should not be appended.

**Describe alternatives you've considered**

- Create a shell script to use the source's value instead of using templating
- Do not set the a condition 😅

**Additional context**
N.A.
