### ISSUE TITLE
 Feature Request [Resource "File"] allow condition to only check for existence of a file (and not the value)

### ISSUE THREAD

**Issue by dduportal** [updatecli/updatecli#290]
**Is your feature request related to a problem? Please describe.**

In the spirit of #289, with the same use case as #288 below:

```yaml
sources:
  mavenVersion:
    kind: githubRelease
    name: Get the latest Maven version
    spec:
      owner: "apache"
      repository: "maven"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      versionFilter:
        kind: latest
    transformers:
      - trimPrefix: "maven-"
 
conditions:
  checkIfMavenReleaseIsAvailable:
    kind: shell
    name: check if the found release is available for download
    sourceID: mavenVersion
    depends_on:
      - mavenVersion
    spec:
      command: curl --connect-timeout 5 --location --head --fail --silent --show-error https://archive.apache.org/dist/maven/maven-3/{{ source "mavenVersion" }}/binaries/apache-maven-{{ source "mavenVersion" }}-bin.tar.gz 

targets:
  showMavenVersion:
    name: Prints the latest Maven available version
    sourceID: mavenVersion
    kind: shell
    spec:
      command: echo
```

I would like to check for the existence of the remote file at the provided URL, or on my filesystem.

**Describe the solution you'd like**

Adding a new attribute `existenceOnly` only available on the condition of kind "file", that would ignore the value and only check for the existence of the file.

**Describe alternatives you've considered**

- Using a shell condition with a curl/wget command (or test -f)
- Implements #268 to check for a remote (URL) file

**Additional context**
N.A.
