### ISSUE TITLE
Feature Request: Temurin conditions

### ISSUE THREAD

**Issue by dduportal** [updatecli/updatecli#2915]
### Is your feature request related to a problem?

In https://github.com/updatecli/updatecli/issues/2839, the author tried to use a condition of type `temurin` which is not implemented as per https://www.updatecli.io/docs/plugins/resource/temurin/

<img width="1158" alt="Capture d’écran 2024-10-27 à 09 02 38" src="https://github.com/user-attachments/assets/0689d76d-9827-478f-8137-db3ed70b4e6e">

### Solution you'd like

Support of a condition to check if a given version, installer_url, checksum_url or signature_url exists or not.

Please note that using a source of type `temurin` and then checking its existence with a condition makes no sense (since both should use the same API endpoints and code).

The added value would be in specifying a collection of platform to check all at once.

Let's check the following use case as an example (inspired from the attempt at):

```
sources:
  # The source is expected to show a version to be passed to a Dockerfile build arg
  # example of expected source result: '17.0.13+11`
  lastTemurin21Version:
    kind: temurin
    name: Get the latest Adoptium JDK21 version via the API
    spec:
      featureversion: 21
    transformers:
      - trimprefix: "jdk-"
      - replacer:
          from: +
          to: _

# Check if the "latest version", which is implicitly for x64 Linux, exists for all provided architectures
conditions:
  checkTemurinAlpineRelease:
    name: Check if the "<lastTemurin21Version>" is available for all custom Linux architectures
    kind: temurin
    sourceid: lastTemurin21Version
    spec:
      featureversion: 21
      architectures:
        - x64
        - s390x
```

I wonder about the pertinence of the `architectures` (plural form) as we'll quickly need to specify `os` and other filter soon, creating a matrix hard to maintain.

WDYT about adding a specify use case around the word "platform" which maps to usual Docker specifier but to **none** of the Temurin API keywords: less risk of confusion then.

Example (condition only!):

```yaml
# Check if the "latest version", which is implicitly for x64 Linux, exists for all provided architectures
conditions:
  checkTemurinAlpineRelease:
    name: Check if the "<lastTemurin21Version>" is available for all custom Linux architectures
    kind: temurin
    sourceid: lastTemurin21Version
    spec:
      featureversion: 21
      platforms:
        - linux/x64
        - windows/x64
        - alpine/arm64
```
