### ISSUE TITLE
Wrong changelog retrieve from the helmchart plugin

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#2975]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The following manifest return the latest changelog instead of the one specified by the version filter rule

```
sources:
  traefik:
    kind: helmchart
    spec:
      url: "https://traefik.github.io/charts/"
      name: "traefik"
      versionfilter:
        kind: semver
        pattern: '30.0.x'

targets:
  traefik:
    kind: shell
    spec:
      command: "echo "
```

```
##################
# UPDATECLI.YAML #
##################


SOURCES
=======

traefik
-------
Searching for version matching pattern "30.0.x"
✔ Helm Chart "traefik" version "30.0.2" is found from repository "https://traefik.github.io/charts/"

Remark: We couldn't identify a way to automatically retrieve changelog information.
Please use following information to take informed decision

Helm Chart: traefik
A Traefik based Kubernetes ingress controller
Project Home: https://traefik.io/
Require Kubernetes Version: &gt;=1.22.0-0
Version created on the 2024-10-30 13:17:10.352848336 &#43;0000 UTC

Sources:

* https://github.com/traefik/traefik

* https://github.com/traefik/traefik-helm-chart



URL:

* https://traefik.github.io/charts/traefik/traefik-33.0.0.tgz




CHANGELOG:
----------

Remark: We couldn't identify a way to automatically retrieve changelog information.
Please use following information to take informed decision

Helm Chart: traefik
A Traefik based Kubernetes ingress controller
Project Home: https://traefik.io/
Require Kubernetes Version: &gt;=1.22.0-0
Version created on the 2024-10-30 13:17:10.352848336 &#43;0000 UTC

Sources:

* https://github.com/traefik/traefik

* https://github.com/traefik/traefik-helm-chart



URL:

* https://traefik.github.io/charts/traefik/traefik-33.0.0.tgz





TARGETS
========

traefik
-------

**Dry Run enabled**

The shell 🐚 command "/bin/sh /tmp/updatecli/bin/658bb4d226330d51c13b2688ef4ed15b17c9c454f94ddd31e0725c946f4e7cf2.sh" ran successfully with the following output:
----
30.0.2
----
⚠ - ran shell command "echo  30.0.2"

```

### Expected Behavior

Well it should show the changelog for 30.0.2

### Environment

```markdown
- OS: Linux
- updatecli: 0.85.0
```
