### ISSUE TITLE
[autodiscovery/terragrunt] empty terraform block breaks updatecli

### ISSUE THREAD

**Issue by loispostula** [updatecli/updatecli#2976]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you have a terragrunt file specifying a terraform block without setting source in it, it segfault updatecli

### Expected Behavior

Updatecli should just ignore the manifest

### Steps To Reproduce

A project with the following kind of terragrunt manifest
```hcl
terraform {}

locals {}

generate "main" {
  path      = "main.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<EOF
variable "tags" {
  type = map(string)
  default = {}
}
EOF
}
```

And the following compose policy
```yaml
policies:
  - name: Terragrunt autodiscovery
    policy: ghcr.io/updatecli/policies/autodiscovery/terragrunt:0.3.0@sha256:976dc3ac101e19962e4c6941dfd145ccdbd40b8f6c87ac697cd1d422607e6072

```

Would yield
```
TERRAGRUNT
===========
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x6d414ae]

```

### Environment

```markdown
- OS:
- updatecli:
```
