### ISSUE TITLE
Feature Request: stop inputing the source on conditions

### ISSUE THREAD

**Issue by dduportal** [updatecli/updatecli#305]
Follow up of the issue #288 that was scoped to the shell resource only, there was a comment on the implementation PR #304 by @olblak about a possibility to disable input source on a condition with a flag that would be common to ALL sources:

> I am facing the same issue on other "resources" such as "aws/ami" and I am wondering if it wouldn't be better to have > something generic at the condition and at target level such as (not at the spec level like you are suggesting).
> 
> I am thinking of something like:
>
> ```
> conditions:
>    condition:
>        disableSourceInput: true (default to false)
>        kind: shell
>       spec:
>            command: xxx
> ```
> And we could just have a condition that test if disableSourceInput is set to true then we set the source to an empty string
here

Alternative proposal: since we can use the form `{{ source "<sourceID>" }}`, the idea would be to purely remove the concept of "input source" from the "Conditon" interface contract. That mean a refactoring, but that would remove some unused code and would avoid an implicit behavior that is confusing usages: instead, user defines in a more precise way.

WDYT?

**Comment by dduportal** [comment]
Counter proposal:

- For a given condition
- If the attribute "sourceId" is set, then the condition needs the source to exist AND uses the source output value string
- Otherwise, an "INFO" message is printed (letting the user know that the condition has no source attached) and the source input value is not used (empty)

e.g.

With 

```yaml
source:
  printName:
    kind: shell
    spec:
      command: echo Damien

conditions:
  withSourceId:
    kind: shell
    sourceID: printName
    spec:
      command: echo
```

then I expected something like

```text
$ updatecli apply
# ...
###### Condition
+ echo Damien
Damien
```

and with

```yaml
source:
  printName:
    kind: shell
    spec:
      command: echo Damien

conditions:
  withoutSourceId:
    kind: shell
    spec:
      command: echo
```

I expect

```text
$ updatecli apply
# ...
###### Condition
INFO: Condition 'withoutSourceId' does not have an associated source (sourceId not specified).
+ echo

```



  

It would be simple, would not break any usages.
