### ISSUE TITLE
Feature Request: Support mirrors in maven autodiscovery

### ISSUE THREAD

**Issue by AidanDelaney** [updatecli/updatecli#3053]
### Is your feature request related to a problem?

In many environments it is preferable to use an internal mirror of maven central.  Support autodiscovery against an internal mirror.

### Solution you'd like

It would be great if the mirror could be configured at the crawler level

```
autodiscovery:
  scmid: default
  crawlers:
    maven:
      mirror: https://my.internal.repo/central
```

### Alternatives you've considered

I have considered adding a `--mirror` flag to `updatecli`, but this seems inappropriate for a single crawler.
