### ISSUE TITLE
Target using a source and `dependsonchange:true` should only take target dep into account

### ISSUE THREAD

**Issue by loispostula** [updatecli/updatecli#3159]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Given the following pipeline
```yaml
name: Should Source impact dependsonchange
pipelineid: e2e/dependsonchangeor

sources:
  source_1:
    name: Should be succeeding
    kind: shell
    spec:
      command: "echo 1.2.3"
conditions:
  condition_1:
    disablesourceinput: true
    name: Should be succeeding
    kind: shell
    spec:
      command: "true"
targets:
  target_1:
    disablesourceinput: true
    name: Should be succeeding
    kind: shell
    spec:
      command: "true"
  target_2:
    disablesourceinput: true
    name: Should be succeeding
    kind: shell
    spec:
      command: "true"

  target_3:
    name: Should be skipped
    kind: shell
    dependson:
      - "target_1:or"
      - "target_2:or"
    dependsonchange: true
    disableconditions: true
    spec:
      command: 'echo {{ source "source_1" }}'
```

We would expect the following results:
```golang
{
  expectedSourcesResult: map[string]string{
    "source_1": "✔",
  },
  expectedConditionsResult: map[string]string{
    "condition_1": "✔",
  },
  expectedTargetsResult: map[string]string{
    "target_1": "✔",
    "target_2": "✔",
    "target_3": "-",
  },
  expectedPipelineResult: "✔",
}
```

But this is not the case, as the target `3` will get executed. 

It's executed because the fact that it does use a `source` an implicit `source#1:and` is added to it's dependson, which is a success and thus the target is not skipped.

### Expected Behavior

The target should be skipped.

### Environment

```markdown
- OS:
- updatecli:
```
