### ISSUE TITLE
Helm Chart Autodiscovery OOM on large folders

### ISSUE THREAD

**Issue by kuisathaverat** [updatecli/updatecli#3204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We have a large folder with 27 Helm Charts, each with about 2-10 dependencies, and about 1-3 containers in the k8s resources. Everything goes fine most of the time, but sometimes, the process runs out of memory and kills the GitHub runner. The last time was when two helm chart changes (10 and 1 dependency) and one Docker container in another helm chart.

### Expected Behavior

The updates succeded without issues.

### Steps To Reproduce

1- create a folder with 27 Helm charts with ten dependencies each and 2 Docker containers in k8s resources, use old version for everything to force an update.
2- run updatecli

```yaml
---
# yaml-language-server: $schema=https://www.updatecli.io/schema/latest/config.json
name: "Helm autodiscovery"
scms:
  githubConfig:
    kind: "github"
    spec:
      user: '{{ requiredEnv "GIT_USER" }}'
      email: '{{ requiredEnv "GIT_EMAIL" }}'
      owner: "owner"
      repository: "repo"
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      username: '{{ requiredEnv "GIT_USER" }}'
      branch: "main"
actions:
  updateCharts:
    kind: github/pullrequest
    scmid: githubConfig
    spec:
      mergemethod: "squash"
      automerge: true
      labels:
        - "dependencies"
        - "automerge"

autodiscovery:
  scmid: githubConfig
  actionid: updateCharts
  crawlers:
    helm:
      rootdir: helm-charts
```

### Environment

```markdown
- OS: Ubuntu 22.04
- updatecli: 0.88.0
```

### Pipeline Graph

```mermaid
```

### Anything else?

There is a workaround that splits the update in Helm Dependencies and Docker containers, in that way, the update succeeded

```yaml
---
# yaml-language-server: $schema=https://www.updatecli.io/schema/latest/config.json
name: "Helm autodiscovery chart dependencies"
scms:
  githubConfig:
    kind: "github"
    spec:
      user: '{{ requiredEnv "GIT_USER" }}'
      email: '{{ requiredEnv "GIT_EMAIL" }}'
      owner: "owner"
      repository: "repo"
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      username: '{{ requiredEnv "GIT_USER" }}'
      branch: "main"
actions:
  updateCharts:
    kind: github/pullrequest
    scmid: githubConfig
    spec:
      mergemethod: "squash"
      automerge: true
      labels:
        - "dependencies"
        - "automerge"

autodiscovery:
  scmid: githubConfig
  actionid: updateCharts
  crawlers:
    helm:
      rootdir: helm-charts
      ignorecontainer: true
      skippackaging: true
      versionincrement: patch
```

```yaml
---
# yaml-language-server: $schema=https://www.updatecli.io/schema/latest/config.json
name: "Helm autodiscovery Docker containers"
scms:
  githubConfig:
    kind: "github"
    spec:
      user: '{{ requiredEnv "GIT_USER" }}'
      email: '{{ requiredEnv "GIT_EMAIL" }}'
      owner: "owner"
      repository: "repo"
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      username: '{{ requiredEnv "GIT_USER" }}'
      branch: "main"
actions:
  updateCharts:
    kind: github/pullrequest
    scmid: githubConfig
    spec:
      mergemethod: "squash"
      automerge: true
      labels:
        - "dependencies"
        - "automerge"

autodiscovery:
  scmid: githubConfig
  actionid: updateCharts
  crawlers:
    helm:
      rootdir: helm-charts
      ignorechartdependency: true
      skippackaging: true
      versionincrement: patch
```
