### ISSUE TITLE
Feature Request: add kubernetes cron-job support

### ISSUE THREAD

**Issue by qianlongzt** [updatecli/updatecli#3345]
https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/

```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
```
