### ISSUE TITLE
helm autodiscover crash when you set ignores

### ISSUE THREAD

**Issue by kuisathaverat** [updatecli/updatecli#3367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you set any ignore setting updatecli crash

### Expected Behavior

process the ignore settings

### Steps To Reproduce

1. Create a GitHub repo with a folder with Helm Charts
2. create the following manifest
```yaml
---
# yaml-language-server: $schema=https://www.updatecli.io/schema/latest/config.json
name: "Helm autodiscovery Docker containers"
scms:
  githubConfig:
    kind: "github"
    spec:
      user: '{{ requiredEnv "GIT_USER" }}'
      email: '{{ requiredEnv "GIT_EMAIL" }}'
      owner: "{{ requiredEnv "GITHUB_OWNER" }}"
      repository: "{{ requiredEnv "GITHUB_REPO" }}"
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      username: '{{ requiredEnv "GIT_USER" }}'
      branch: "main"
actions:
  updateCharts:
    kind: github/pullrequest
    scmid: githubConfig
    spec:
      mergemethod: "squash"
      automerge: true
      labels:
        - "dependencies"

autodiscovery:
  scmid: githubConfig
  actionid: updateCharts
  crawlers:
    helm:
      rootdir: helm-charts
      digest: true
      ignorechartdependency: true
      skippackaging: true
      versionincrement: patch
      ignore:
        - path: "helm-charts/hello"
# I tested also these configs
#        - containers:
#            "my-helm-chart": ">0.0.1"
#        - dependencies:
#           "my-helm-chart": ""
``` 

3. run updatecli

```shell
 updatecli diff --config autodiscover.yml
```

```log
HELM
=====
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xf0d143c]

goroutine 1 [running]:
github.com/updatecli/updatecli/pkg/plugins/autodiscovery/helm.Helm.discoverHelmContainerManifests({0x1, {0x0, 0xc000e1e5d8, 0x0, 0x1, {0xc000e0e760, 0x1, 0x1}, {0xc000baf3a0, 0xb}, ...}, ...})
        /home/runner/work/updatecli/updatecli/pkg/plugins/autodiscovery/helm/container.go:176 +0xb9c
github.com/updatecli/updatecli/pkg/plugins/autodiscovery/helm.Helm.DiscoverManifests({0x1, {0x0, 0xc000e1e5d8, 0x0, 0x1, {0xc000e0e760, 0x1, 0x1}, {0xc000baf3a0, 0xb}, ...}, ...})
        /home/runner/work/updatecli/updatecli/pkg/plugins/autodiscovery/helm/main.go:140 +0x219
github.com/updatecli/updatecli/pkg/core/pipeline/autodiscovery.(*AutoDiscovery).Run(0xc00091a8a0?)
        /home/runner/work/updatecli/updatecli/pkg/core/pipeline/autodiscovery/main.go:363 +0x76
github.com/updatecli/updatecli/pkg/core/engine.(*Engine).LoadAutoDiscovery(0x136416e0, 0x0?)
        /home/runner/work/updatecli/updatecli/pkg/core/engine/autodiscovery.go:109 +0x653
github.com/updatecli/updatecli/pkg/core/engine.(*Engine).Prepare(0x136416e0)
        /home/runner/work/updatecli/updatecli/pkg/core/engine/prepare.go:41 +0x15f
github.com/updatecli/updatecli/cmd.run({0x10734d9a?, 0x0?})
        /home/runner/work/updatecli/updatecli/cmd/root.go:126 +0x494
github.com/updatecli/updatecli/cmd.init.func9(0x135f4e20?, {0xc000bbe500?, 0x0?, 0x2?})
        /home/runner/work/updatecli/updatecli/cmd/diff.go:38 +0x247
github.com/spf13/cobra.(*Command).execute(0x135f4e20, {0xc000bbe4e0, 0x2, 0x2})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989 +0xa91
github.com/spf13/cobra.(*Command).ExecuteC(0x135f3720)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/updatecli/updatecli/cmd.Execute()
        /home/runner/work/updatecli/updatecli/cmd/root.go:50 +0x5b
main.main()
        /home/runner/work/updatecli/updatecli/main.go:8 +0xf
```

### Environment

```markdown
- OS: Ubuntu 22.04 (GitHub runner) / macOS 15
- updatecli: 0.91.0
```

### Pipeline Graph

```mermaid
```

**Comment by kuisathaverat** [comment]
It is caused by one of our Helm Charts https://github.com/kuisathaverat/updatecli-issues/tree/main/issue-3367/helm-charts/otelcol-github-actions
https://github.com/kuisathaverat/updatecli-issues/actions/runs/12514955811/job/34911791508

**Comment by olblak** [comment]
Thanks for the sharing the example, I need to add at test if tag is empty.
I had a look to the other autodiscovery plugins using the same approach and they are not affected but I spot a few minor issues

**Comment by olblak** [comment]
Could I ask you to validate your use case with https://github.com/updatecli/updatecli/pull/3501
I had to slightly change your pullrequest has otherwise only/ignore rules would be ignored if a docker image had a tag like "latest"

**Comment by olblak** [comment]
Also worth mentioning, while investigating this issue, I noticed that the helm autodiscovery plugin allows to ignore image based on tags like 

```
ignores:
   - containers:
       "nginx": "1.20"
```

while all other plugins only support image name like 

```
ignore:
  - containers:
     - "nginx"  
```

I am wondering if having the granularity at the tag level is worth the effort

**Comment by kuisathaverat** [comment]
I have tested with the example, it does not crash

```shell
gh repo clone https://github.com/kuisathaverat/updatecli-issues.git
gh repo clone https://github.com/updatecli/updatecli.git
cd updatecli
gh co https://github.com/updatecli/updatecli/pull/3501
export GITHUB_TOKEN=$(gh auth token)
go run . diff --config ../updatecli-issues/issue-3367/test.yml 
```

This is the configuration evaluated

```
image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""
```

it does not apply the digest and create a new PR

```
################################################################
# DEPS(HELM): BUMP IMAGE "NGINX" DIGEST FOR CHART "TESTDATA-5" #
################################################################

condition: condition#nginx-repository
--------------------------
✔ key "$.image.repository" is correctly set to "nginx"

source: source#nginx-digest
-------------------
✔ Docker Image Tag nginx:latest resolved to digest index.docker.io/library/nginx:latest@sha256:42e917aaa1b5bb40dd0f6f7f4f857490ac7747d7ef73b391c774a41a8b994f15

target: target#nginx
------------
✔ - no change detected:
	* key "$.image.tag" already set to "latest@sha256:42e917aaa1b5bb40dd0f6f7f4f857490ac7747d7ef73b391c774a41a8b994f15", from file "issue-3367/helm-charts/testdata-5/values.yaml"
```
