### ISSUE TITLE
ArgoCD autodiscovery does not work with OCI registry

### ISSUE THREAD

**Issue by dshmelev** [updatecli/updatecli#3459]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

ArgoCD application manifest should have repoURL without oci:// syntax (https://argo-cd.readthedocs.io/en/latest/user-guide/helm/):
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
spec:
  project: default
  source:
    chart: nginx
    repoURL: registry-1.docker.io/bitnamicharts  # note: the oci:// syntax is not included.
    targetRevision: 15.9.0
  destination:
    name: "in-cluster"
    namespace: nginx
```
Autodiscovery generates the following source manifest:
```
sources:
    nginx:
        name: Get latest "nginx" Helm chart version
        kind: helmchart
        spec:
            name: nginx
            url: registry-1.docker.io/bitnamicharts
            versionfilter:
                kind: semver
                pattern: '>=15.9.0'
```
And then fails with error:
```
source: source#nginx
------------
ERROR: ✗ getting repo index from file: open <hidden_directory_path>/registry-1.docker.io/bitnamicharts/index.yaml: no such file or directory
```

### Expected Behavior

`sources.nginx.spec.url` should have `oci://` syntax to work correctly:
```
sources:
    nginx:
        name: Get latest "nginx" Helm chart version
        kind: helmchart
        spec:
            name: nginx
            url: oci://registry-1.docker.io/bitnamicharts
            versionfilter:
                kind: semver
                pattern: '>=15.9.0'
```

### Environment

```markdown
- OS: MacOS 14.3.1 
- updatecli: 0.91.0
```

### Pipeline Graph

```mermaid
```
