### ISSUE TITLE
Blank lines are removed from YAML target after apply with yamlpath engine

### ISSUE THREAD

**Issue by thiagowfx** [updatecli/updatecli#3525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Exactly the same issue as https://github.com/updatecli/updatecli/issues/794. This issue was fixed for the `go-yaml` engine, but it remains with `yamlpath`.

When declaring a yaml file as target, after a successful apply, every blank line in that yaml file gets removed.

### Expected Behavior

No changes to the formatting of existing yaml files. Blank lines should be preserved.

### Steps To Reproduce

`python.yaml`:

```
# yaml-language-server: $schema=https://www.updatecli.io/schema/latest/policy/manifest/config.json
name: python

sources:
  python:
    # FIXME: githubtag: WARNING: ⚠ No GitHub Release found, we fallback to published git tags
    kind: githubrelease
    spec:
      owner: python
      repository: cpython
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      versionfilter:
        kind: semver
        pattern: "~3"
    transformers:
      - trimprefix: "v"

targets:
  actions-setup-python:
    name: update python from actions/setup-python in pre-commit-autoupdate.yml
    kind: yaml
    spec:
      file: pre-commit-autoupdate.yml
      key: "$.jobs.pre-commit-auto-update.steps[?(@.name == 'Set up Python')].with.python-version"
      # FIXME: do not remove blank lines
      engine: yamlpath
```

`pre-commit-autoupdate.yml` (redacted, [minimal example](https://www.sscce.org/)):

```
jobs:
  pre-commit-auto-update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: "3.12"
```

To reproduce, run `updatecli apply --config python.yaml`.

### Environment

```markdown
- OS: macOS Sonoma 14.7.2
- updatecli:


% updatecli version

VERSION

Application:    0.91.0
Golang     :    1.23.4 linux/amd64
Build Time :    2024-12-24T06:53:18Z
```
```


### Pipeline Graph

```mermaid
graph TD
    target#actions-setup-python("update python from actions/setup-python in pre-commit-autoupdate.yml (yaml)")
    source#python(["python (githubrelease)"])
    source#python --> target#actions-setup-python
```
