### ISSUE TITLE
Feature request: ability to target one release amongs many in a single helmfile

### ISSUE THREAD

**Issue by lemeurherve** [updatecli/updatecli#353]
**Is your feature request related to a problem? Please describe.**
I don't see how I can update one of the releases in the same helmfile without keeping an index of the charts order.

For now, with `kind: yaml` I can only specify a specific release by its index.

For example, in the context of [this PR](https://github.com/jenkins-infra/charts/pull/1683), [here](https://github.com/jenkins-infra/charts/blob/main/updatecli/updatecli.d/charts/accountapp.yaml#L15) instead of
```
targets:
  updateChartVersion:
    name: "Update the chart version for accountapp"
    kind: yaml
    spec:
      file: helmfile.d/accountapp.yaml
      key: releases[0].version
```
I would like to be able to specify something like that:
```
targets:
  updateChartVersion:
    name: "Update the chart version for accountapp"
    kind: yaml
    spec:
      file: clusters/publick8s.yaml
      key: releases[].version
      where:
		field: release.name
		eq: accountapp
```

**Describe alternatives you've considered**
As a workaround, I can target with a multiline regexp, but it would need (I think) to require a strict order of release fields (`version` just after `name` for example)

**Comment by olblak** [comment]
> As a workaround, I can target with a multiline regexp, but it would need (I think) to require a strict order of release fields (version just after name for example)

Indeed which is why I am using a condition to verify that the associated key is correct like [here](https://github.com/jenkins-infra/jenkins-infra/blob/production/updatecli/weekly.d/openvpn.yaml#L15L18)

**Comment by dduportal** [comment]
> > As a workaround, I can target with a multiline regexp, but it would need (I think) to require a strict order of release fields (version just after name for example)
> 
> Indeed which is why I am using a condition to verify that the associated key is correct like [here](https://github.com/jenkins-infra/jenkins-infra/blob/production/updatecli/weekly.d/openvpn.yaml#L15L18)

This workaround is not always working as expected because we often cannot determine the value of the key in advance (#289might solve this difficulty though).

But the initial need from @lemeurherve is because maintaining the updatecli manifest over time will be really painful (each time you add an element in the array, you have to update all manifests if it's not added at the end of the list). Hence the feature request :)

**Comment by olblak** [comment]
I am currently migrating the yaml plugin to an awesome library which has this limitation https://github.com/goccy/go-yaml/issues/290

**Comment by olblak** [comment]
Bumping @hervelemeur and @dduportal  here as I think the coming Updatecli 0.66.0 introduces two different approaches to solve this problem.

1. Yamlpath
2. Helmfile Autodiscovery

**Yamlpath**

More advanced yamlpath queries are introduced by https://github.com/updatecli/updatecli/pull/1741

```
sources:
  default:
    name: Get acme version
    kind: yaml
    spec:
      engine: yamlpath
      file: clusters/privatek8s.yaml
      key: "$.releases[?(@.name=='acme')].version"
```

tested on https://github.com/jenkins-infra/kubernetes-management

**helmfile autodiscovery**

Introduced in https://github.com/updatecli/updatecli/pull/1754

Allows to use only/ignore rule per release such as 

```
autodiscovery:
  crawlers:
    helmfile:
      only:
        - path: clusters/privatek8s.yaml
          repositories:
            - "https://jenkins-infra.github.io/helm-charts"
          charts:
            "acme": ""
```
