### ISSUE TITLE
Bug in a target when using multi yaml matches

### ISSUE THREAD

**Issue by smerle33** [updatecli/updatecli#3548]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

the target says no change while the detail show change

```
✔ - no change detected:
        * key "$.releases[?(@.name == \"jenkins-agents\" || @.name == \"jenkins-agents-bom\")].version" should be updated from "1.0.0" to "1.1.0", in file "clusters/cijioagents1.yaml"
        * key "$.releases[?(@.name == \"jenkins-agents\" || @.name == \"jenkins-agents-bom\")].version" already set to "1.1.0", from file "clusters/cijioagents2.yaml", 
        * key "$.releases[?(@.name == \"jenkins-agents\" || @.name == \"jenkins-agents-bom\")].version" already set to "1.1.0", from file "clusters/cijioagents2.yaml",
```

### Expected Behavior

to have a change detected: 

```
⚠ - change detected:
        * key "$.releases[?(@.name == \"jenkins-agents\" || @.name == \"jenkins-agents-bom\")].version" should be updated from "1.0.0" to "1.1.0", in file "clusters/cijioagents1.yaml"
        * key "$.releases[?(@.name == \"jenkins-agents\" || @.name == \"jenkins-agents-bom\")].version" should be updated from "1.0.0" to "1.1.0", in file "clusters/cijioagents1.yaml"
        * key "$.releases[?(@.name == \"jenkins-agents\" || @.name == \"jenkins-agents-bom\")].version" already set to "1.1.0", from file "clusters/cijioagents2.yaml", 
        * key "$.releases[?(@.name == \"jenkins-agents\" || @.name == \"jenkins-agents-bom\")].version" already set to "1.1.0", from file "clusters/cijioagents2.yaml",
```

### Steps To Reproduce

updatecli manifest extract: 
```
targets:
  updateChartVersionCIjioAgents:
    name: "Update the chart version for jenkins kubernetes agent for CI"
    kind: yaml
    spec:
      files:
        - clusters/cijioagents1.yaml
        - clusters/cijioagents2.yaml
      engine: yamlpath
      key: $.releases[?(@.name == "jenkins-agents" || @.name == "jenkins-agents-bom")].version
    scmid: default
```  
 
the target files: 
```
releases:
  - name: jenkins-agents
    namespace: jenkins-agents
    chart: jenkins-infra/jenkins-kubernetes-agents
    version: 1.0.0
    values:
      - "../config/jenkins-kubernetes-agents_ci.jenkins.io_cijioagents1.yaml"
  - name: jenkins-agents-bom
    namespace: jenkins-agents-bom
    chart: jenkins-infra/jenkins-kubernetes-agents
    version: 1.0.0
    values:
      - "../config/jenkins-kubernetes-agents_ci.jenkins.io_cijioagents1-bom.yaml"
```

and 

```
releases:
  - name: jenkins-agents
    namespace: jenkins-agents
    chart: jenkins-infra/jenkins-kubernetes-agents
    version: 1.0.1
    values:
      - "../config/jenkins-kubernetes-agents_ci.jenkins.io_cijioagents2.yaml"
  - name: jenkins-agents-bom
    namespace: jenkins-agents-bom
    chart: jenkins-infra/jenkins-kubernetes-agents
    version: 1.0.1
    values:
      - "../config/jenkins-kubernetes-agents_ci.jenkins.io_cijioagents2-bom.yaml"
```

so `cijioagents2` is uptodate to 1.1.0 and `cijioagents1` is not as still to 1.0.1
2 releases impacted on each file hence the key selector with or `key: $.releases[?(@.name == "jenkins-agents" || @.name == "jenkins-agents-bom")].version`

the updatecli apply does the update, it's just the change display that misses the spot !

### Environment

```markdown
- OS: Ubuntu 22.04 / macos
- updatecli: v0.92.0
```

### Pipeline Graph

```mermaid
```
