### ISSUE TITLE
[yaml] error when the "file" key is an URL

### ISSUE THREAD

**Issue by dduportal** [updatecli/updatecli#357]
**Describe the bug**

As per the documentation (https://www.updatecli.io/docs/resources/yaml/#_file) the attribute `file` of YAML resource can be either a file path, or an "URL"-like (with a prefix scheme).

But the URL-like values are resulting on errors, at least on a YAML source.

**To Reproduce**

The following snippet fails when for both `file://` and `https://` URL schemes:

```yaml
---
title: Show a set of yaml resources as a generic example
sources:
  default:
    kind: yaml
    spec:
      file: examples/values.yaml
      key: "github.user"
  fromExplicitFile:
    kind: yaml
    spec:
      file: file://examples/values.yaml
      key: "github.user"
  fromUrl:
    kind: yaml
    spec:
      file: https://raw.githubusercontent.com/updatecli/updatecli/dc90759914718beee17101c693911088cfbf6deb/examples/values.yaml
      key: "github.user"
```

```shell
#####################################################
# SHOW A SET OF YAML RESOURCES AS A GENERIC EXAMPLE #
#####################################################


SOURCES
=======

fromUrl
-------
ERROR: ✗ open /Users/dadou/workspace/updatecli/updatecli/https:/raw.githubusercontent.com/updatecli/updatecli/dc90759914718beee17101c693911088cfbf6deb/examples/values.yaml: no such file or directory

fromExplicitFile
----------------
ERROR: ✗ open /Users/dadou/workspace/updatecli/updatecli/file:/examples/values.yaml: no such file or directory

default
-------
✔ Value 'olblak' found for key github.user in the yaml file examples/values.yaml
```

**Expected behavior**

- I would expect the case with `file://` to work as expected (e.g. the scheme prefix should be removed)
- For the URL like, I'm not sure if it should be supported, or not. WDYT @olblak ?

**Screenshots**
N.A.

**Version (please complete the following information):**
 - OS: macOS
 - Version 0.13.1

**Additional context**
N.A.
