### ISSUE TITLE
[yaml] condition with a source input value fails to validate

### ISSUE THREAD

**Issue by dduportal** [updatecli/updatecli#358]
**Describe the bug**

When using a yaml condition without the attribute `value` defined, the conditions fails even if the input source value matches the value of the specified YAML key.

The documentation at https://www.updatecli.io/docs/resources/yaml does not allow to conclude if it should work or not.

**To Reproduce**

```yaml
# test.yaml
github:
  user: asterix
```

```yaml
# updatecli.yaml
title: Check a YAML file
sources:
  default:
    kind: yaml
    spec:
      file: test.yaml
      key: "github.user"
conditions:
  checkGithubUsername:
    kind: yaml
    sourceID: default
    spec:
      file: test.yaml
      key: "github.user"
``` 

```shell
# ..
#####################
# CHECK A YAML FILE #
#####################


SOURCES
=======

default
-------
✔ Value 'asterix' found for key github.user in the yaml file test.yaml


CONDITIONS:
===========

checkGithubUsername
-------------------
✗ Key 'github.user', from file 'test.yaml', is incorrectly set to asterix and should be '

✗ condition not met, skipping pipeline

=============================
# ...
```

**Expected behavior**

```shell
SOURCES
=======

default
-------
✔ Value 'asterix' found for key github.user in the yaml file test.yaml


CONDITIONS:
===========

checkGithubUsername
-------------------
✔ Key 'github.user', from file 'test.yaml', is correctly set to 'asterix'

=============================
```

**Screenshots**
N.A.

**Version (please complete the following information):**
 - OS: macOs
 - Version 0.13.1

**Additional context**
N.A.
