### ISSUE TITLE
[yaml] attribute 'value' is ignored by targets

### ISSUE THREAD

**Issue by dduportal** [updatecli/updatecli#359]
**Describe the bug**

With a target of kind `yaml`, specifying the attribute `value` as no effect. The input source value is always used.

**To Reproduce**

```yaml
# test.yaml
github:
  user: olblak
  repository: charts
```

```yaml
---
title: Show a set of yaml resources as a generic example
sources:
  getGithubUser:
    kind: yaml
    spec:
      file: test.yaml
      key: "github.user"
targets:
  setGitHubRepository:
    kind: yaml
    spec:
      file: test.yaml
      key: "github.repository"
      value: "charts"
```

```shell
# ...
SOURCES
=======

getGithubUser
-------------
✔ Value 'olblak' found for key github.user in the yaml file test.yaml


TARGETS
========

setGitHubRepository
-------------------

**Dry Run enabled**

✔ Key 'github.repository', from file 'test.yaml', was updated from 'charts' to 'olblak'

=============================
# ...
```

**Expected behavior**

I expect that the target sets the specified key to the specified content, instead of the one from the default source value.

e.g.

```shell
# ...
SOURCES
=======

getGithubUser
-------------
✔ Value 'olblak' found for key github.user in the yaml file test.yaml


TARGETS
========

setGitHubRepository
-------------------

**Dry Run enabled**

✔ Key 'github.repository', from file 'test.yaml', is already set to 'charts'

=============================
# ...
```
```

**Screenshots**
N.A.

**Version (please complete the following information):**
 - OS: macOS
 - Version 0.13.1

**Additional context**
N.A.
