### ISSUE TITLE
Feature Request: don't output binary (file-source)

### ISSUE THREAD

**Issue by till** [updatecli/updatecli#3636]
### Is your feature request related to a problem?

It would be nice if updatecli would not output binary file content.

I am running the following workflow:

```yaml
sources:
  getRelease:
    kind: githubrelease
    transformers:
      - trimPrefix: 'v'
    spec:
      token: "{{ requiredEnv .github.token }}"
      owner: paketo-community
      repository: go-generate
      assert: "*.cnb"
      versionFilter:
        kind: latest
  getAsset:
    kind: file
    dependson:
      - getRelease
    spec:
      file: https://github.com/paketo-community/go-generate/releases/download/v{{ source "getRelease" }}/go-generate-{{ source "getRelease" }}.cnb

targets:
  publish:
    sourceid: getRelease
    kind: shell
    spec:
      command: |
        export version={{ source `getRelease` }}
        skopeo copy \
        "docker-archive:./go-generate-${version}.cnb" \
        "docker://registry/buildpacks/go-generate:${version}"
```

### Solution you'd like

No output when the content is a binary blob.

### Anything else?

Ref: https://github.com/orgs/updatecli/discussions/3635#discussioncomment-11912639
