### ISSUE TITLE
Updatecli Fails to Retrieve OCI Helm Chart Versions from Public ECR Registry

### ISSUE THREAD

**Issue by jayfranco999** [updatecli/updatecli#3648]
### Is there an existing issue for this?

- [x] I have searched the existing issues

## Problem Description:

(Ref: https://github.com/jenkins-infra/helpdesk/issues/4504)

When attempting to track the Karpenter Helm chart version using updatecli, an authentication/credential error occurs preventing version retrieval. The specific error message is:

```
ERROR: ✗ unable to list versions for OCI Helm chart public.ecr.aws/karpenter/karpenter: error getting credentials - err: signal: killed, out: ``
```

As suggested by @dduportal , a potential workaround involves logging out of the Helm registry before performing an unauthenticated pull:

```
helm registry logout public.ecr.aws
```

### Specific Technical Constraints:

The Jenkins `updatecli` pipeline library's current implementation (in updatecli.groovy) presents challenges:

- The updatecli() function runs within a node() block
- No direct mechanism to inject pre-command steps
- Limited context for modifying credential or registry handling

### Possible Root Causes:

Updatecli CLI might have underlying issues with Helm chart credential retrieval
Complex authentication flow for public ECR repositories
Potential interaction between Helm, AWS credentials, and updatecli

### Expected Behavior

To retrieve the latest helmchart version from Public ECR Registry (i.e 1.1.x)

### Environment

```markdown
- OS:
- updatecli:
```

### Pipeline Graph

```mermaid
```

**Comment by olblak** [comment]
@jayfranco999 Would you have an Updatecli manifest that I could use to reproduce?

**Comment by jayfranco999** [comment]
Thanks for the response @olblak,

This was the manifest I was trying to run

```
---
name: Bump `karpenter` helm release version

scms:
  default:
    kind: github
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: "{{ .github.owner }}"
      repository: "{{ .github.repository }}"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      branch: "{{ .github.branch }}"

sources:

  lastChartVersion:
    name: Karpenter AWS Provider Helm Chart Latest Version
    kind: helmchart
    spec:
      url: oci://public.ecr.aws/karpenter
      name: karpenter
```

Which gave me the following authentication error

```
ERROR: ✗ unable to list versions for OCI Helm chart public.ecr.aws/karpenter/karpenter: error getting credentials - err: signal: killed, out: ``
```

I was able to work around this locally by using another source `logoutPublicECR` to preliminarily logout of the ecr registry which worked.

```
sources:
  logoutPublicECR:
    name: Logout from public ECR registry via Helm CLI
    kind: shell
    spec:
      command: |
        docker logout public.ecr.aws

  lastChartVersion:
    name: Karpenter AWS Provider Helm Chart Latest Version
    dependson:
      - logoutPublicECR
    kind: helmchart
    spec:
      url: oci://public.ecr.aws/karpenter
      name: karpenter
      versionfilter:
        kind: semver
        strict: true
```
