### ISSUE TITLE
[docker] condition fails when using another registry than the DockerHub

### ISSUE THREAD

**Issue by dduportal** [updatecli/updatecli#365]
**Describe the bug**

It seems that using another Docker registry than the defauklt dockerhub is always failing the condition of kind "docker"

**To Reproduce**

This snippet always fail:

```yaml
title: "Bump jx-release-version version on shared library resources"
sources:
  lastVersion:
    kind: githubRelease
    name: Get the latest jx-release-version version
    spec:
      owner: "jenkins-x-plugins"
      repository: "jx-release-version"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      versionFilter:
        kind: semver
conditions:
  checkIfDockerImageIsPublished:
    name: "Check if the Docker Image is published"
    kind: dockerImage
    spec:
      hostname: 'ghcr.io'
      image: 'jenkins-x/jx-release-version'
 ```

**Expected behavior**
The condition should pass

**Screenshots**
N.A.

**Version (please complete the following information):**

- OS: macOS
- Version 0.14.0

**Additional context**
N.A.

**Comment by olblak** [comment]
Thanks for reporting this, ghcr should be working but it requires a token.
We are probably just missing the right error message

**Comment by dduportal** [comment]
Good point, thanks (I did not read the documentation correctly).

Trying with the token is giving the following error though:

```text
CONDITIONS:
===========

checkIfDockerImageIsPublished
-----------------------------
ERROR: illegal base64 data at input byte 3

✗ condition not met, skipping pipeline
```

I guess there is something in the code that does not support the GitHub token format 😅

```
      token: 'ghp_XXXXXXXXXX' # Input byte 3 is `_`...
```

**Comment by olblak** [comment]
No the github token alone used to be working at some point. The documentation on [www.updatecli.io](https://www.updatecli.io/docs/resources/docker_image/#_dockerhub) must  be updated.
The ghcr token format is now the same as the other registries. You can fetch it from your .docker/config.json

Or something like `echo -n 0 "$GITHUB_ACTOR:$GITHUB_TOKEN" | base64`

-> https://github.com/updatecli/updatecli/pull/246

I detected that issue with integration tests :trollface:

**Comment by dduportal** [comment]
I can't make it work, could you help me?

- My couple username + token works as expected. The command below works as expected (answers HTTP/200 with a temporary token, which mean this token is allowed for this image:

```shell
curl -u "$GITHUB_ACTOR:$GITHUB_TOKEN" https://ghcr.io/token\?scope\=repository:updatecli/updatecli:pull
```

- The command `echo -n 0 "$GITHUB_ACTOR:$GITHUB_TOKEN"` is not valid: it adds a leading `0` and a space separator in the string:

```shell
$ echo -n 0 "$GITHUB_ACTOR:$GITHUB_TOKEN"
0 jenkins-infra-bot:ghp_XXXXX
```

- Whatever encoded value I'm using (`export UPDATECLI_GHCR_TOKEN="$(echo -n "$GITHUB_ACTOR:$GITHUB_TOKEN" | base64)"` or `export UPDATECLI_GHCR_TOKEN="$(echo -n 0 "$GITHUB_ACTOR:$GITHUB_TOKEN" | base64)"`), `updatecli` always fails the condition with this message:

```text
$ export UPDATECLI_GHCR_TOKEN="$(echo -n "$GITHUB_ACTOR:$GITHUB_TOKEN" | base64)"
$ updatecli diff <...>
# ...
CONDITIONS:
===========

checkIfDockerImageIsPublished
-----------------------------
ERROR: something went wrong while login to dockerhub

✗ condition not met, skipping pipeline

=============================
```

with manifest

```yaml
# ...
conditions:
  checkIfDockerImageIsPublished:
    name: "Check if the Docker Image is published"
    kind: dockerImage
    spec:
      hostname: "ghcr.io"
      image: "updatecli/updatecli"
      token: '{{ requiredEnv "UPDATECLI_GHCR_TOKEN" }}'
```

**Comment by dduportal** [comment]
Oh found a working case: the `hostname` is not needed at all (is it deprecated?). When removing it and setting the `image` field to the full image name, then it works \o/

**Comment by dduportal** [comment]
ok, no need to encode the token:

```
conditions:
  checkIfDockerImageIsPublished:
    name: "Check if the Docker Image is published"
    kind: dockerImage
    spec:
      image: "ghcr.io/updatecli/updatecli"
      username: "{{ .github.username }}"
      password: "{{ requiredEnv .github.token }}"
```

seems to work as expected \o/
