### ISSUE TITLE
Autodiscovery preccomit not working if default branch of remote hook is not main

### ISSUE THREAD

**Issue by rromiccw** [updatecli/updatecli#3717]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

When using autodiscovery for my pre-commit hooks it fails for ones that **dont** have **main** as default branch but rather **master** branch.

**For those Im getting an error like this:**

```
############################################################
# BUMP "HTTPS://GITHUB.COM/HADOLINT/HADOLINT" REPO VERSION #
############################################################

source: source#https://github.com/hadolint/hadolint
-------------------------------------------
DEBUG: checkout git branch "main", based on "main"
DEBUG: new branch "main" doesn't exist, creating it from branch "main"

ERROR: something went wrong in "target#.pre-commit-config.yaml" : update pipeline: template: cfg:84:77: executing "cfg" at <source "https://github.com/hadolint/hadolint">: error calling source: parent source "https://github.com/hadolint/hadolint" failed

Pipeline "Bump \"https://github.com/hadolint/hadolint\" repo version" failed
Skipping due to:
        something went wrong during target execution

```

For example if **main** is **default branch** of remote origin it works as expected:

```
###########################################################
# BUMP "HTTPS://GITHUB.COM/RHYSD/ACTIONLINT" REPO VERSION #
###########################################################

source: source#https://github.com/rhysd/actionlint
------------------------------------------
DEBUG: checkout git branch "main", based on "main"
Searching for version matching pattern "v1.7.4 || >1.7 < 2"
✔ Git tag "v1.7.4" found matching pattern "v1.7.4 || >1.7 < 2" of kind "semver"
DEBUG: empty changelog found for the source

target: target#.pre-commit-config.yaml

```

### Expected Behavior

I would expect that crawler respects default branch for remote origins and checkout them and not use only main by default (or to have fallback solution to specify some other branch as part of the configuration).

### Steps To Reproduce

**My updatecli configuration:**

```
name: "Bump minor version of tools in .tool-versions"
pipelineid: tools-minor

actions:
    defaul:
        title: 'deps(ci): bump tools with latest minor versions'
        kind: github/pullrequest
        spec:
            usetitleforautomerge: true
            automerge: false
            labels:
                - upgrade
                - tools
                - minor
        scmid: default

scms:
    default:
        kind: github
        spec:
            branch: {{ env `BRANCH` | default `master` }}
            owner: '{{ requiredEnv "GITHUB_OWNER" }}'
            repository: '{{ requiredEnv "GITHUB_REPO" }}'
            token: '{{ requiredEnv "GITHUB_TOKEN" }}'
            user: '{{ requiredEnv "GITHUB_AUTHOR" }}'
            username: '{{ requiredEnv "GITHUB_AUTHOR" }}'
            url: 'github.com'
            force: true
            commitmessage:
              type: "deps"
              scope: "ci"
              hidecredit: true

autodiscovery:
  scmid: default
  crawlers:
    precommit:
      versionfilter:
        kind: semver
        pattern: minoronly
```

**pre-commit config:**
```
---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args:
          - --unsafe
      - id: check-json
      - id: check-added-large-files
      - id: no-commit-to-branch
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-case-conflict
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.23.2
    hooks:
      - id: gitleaks
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        types:
          - file
          - yaml
        args: [--no-warnings, -c=.yamllint]

  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.4
    hooks:
      - id: actionlint

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.97.0
    hooks:
      - id: terraform_fmt
        args:
          - --args=-no-color
          - --args=-diff
          - --args=-write=false
      - id: terraform_docs
        args:
          - --args=--config=.terraform-docs.yml
          - --hook-config=--create-file-if-not-exist=true
        exclude: .terraform/
      - id: terraform_tflint
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
        exclude: (\.archived|archived|\.terraform)

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shfmt
        args:
          - -l
          - -i
          - "2"
          - -ci
          - -sr
          - -w
      - id: shellcheck

```

### Environment

```markdown
- OS: macOS 
- updatecli: v0.93.0
```

### Pipeline Graph

```mermaid
```

### Anything else?

As a temporary workaround I can specify for each pre-commit hook its own source and target for it, but would expect that autodiscovery works out of the box :)
