### ISSUE TITLE
[yaml] Target with a key not found does not reports as a failure

### ISSUE THREAD

**Issue by dduportal** [updatecli/updatecli#379]
**Describe the bug**

The execution of a YAML target prints an error message `cannot find key <...> from file <...>` but the final report is not showing the target as failed.

**To Reproduce**

```yaml
title: Bump wiki docker image version
sources:
  latestRelease:
    kind: githubRelease
    name: "Get latest jenkins-infra/docker-confluence-data release"
    spec:
      name: Get jenkins-infra/docker-confluence-data latest version
      owner: "jenkins-infra"
      repository: "docker-confluence-data"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
conditions:
  docker:
    name: "Test jenkinsciinfra/wiki:<latest_version> docker image tag"
    kind: dockerImage
    spec:
      image: "jenkinsciinfra/wiki"
targets:
  imageTag:
    name: "Update wiki docker image tag"
    kind: yaml
    spec:
      file: "config/wiki.yaml"
      key: "image.tag"
    scm:
      github:
        user: "{{ .github.user }}"
        email: "{{ .github.email }}"
        owner: "{{ .github.owner }}"
        repository: "{{ .github.repository }}"
        token: "{{ requiredEnv .github.token }}"
        username: "{{ .github.username }}"
        branch: "{{ .github.branch }}"
```

```text
TARGETS
========

imageTag
--------
✗ cannot find key 'image.tog' from file 'config/wiki.yaml'

=============================

REPORTS:


✔ WIKI.YAML:
        Sources:
                ✔ [latestRelease] Get latest jenkins-infra/docker-confluence-data release(githubRelease)
        Condition:
                ✔ [docker] Test jenkinsciinfra/wiki:<latest_version> docker image tag(dockerImage)
        Target:
                ✔ [imageTag]  Update wiki docker image tag(yaml)
```

**Expected behavior**

I would expect the error to be reported

**Screenshots**
N.A.

**Version (please complete the following information):**

- OS: macOS and Linux Ubuntu 20.04 (both amd64)
- Version 0.14.1

**Additional context**

The error at https://github.com/updatecli/updatecli/blob/c9b06f4da1a32b847d4e718369389a14e3921520/pkg/core/engine/target/main.go#L238 is always `nil` which is why the report is never aware. 

I assume the bug is in the yaml target implementation: I'm working on this direction.
