### ISSUE TITLE
git directory: repository does not exist

### ISSUE THREAD

**Issue by softlion** [updatecli/updatecli#3800]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

I have a simple config to update a value in a yaml file. Nothing difficult.  
When adding the scm to create a PR on github, updatecli fails with this message:

```
ERROR: something went wrong in "target#updateValues" : something went wrong in target "updateValues" : 
"opening \"/tmp/updatecli/github/owner/repo\" git directory: repository does not exist"
```

That happens with both the docker version of updatecli and the github action's version of updatecli (ie: when run in a github action using updatecli/updatecli-action@v2)

I retried with more debug infos:
```
SCM repository retrieved: 1
DEBUG: cloning git repository: https://github.com/owner/repo.git in /tmp/updatecli/github/owner/repo
ERROR: failed cloning GitHub repository "https://github.com/owner/repo.git"
ERROR: err - cloning: authentication required: Repository not found.
        It appears that a password has been specified without a username, could it be related?
```

I verified the token using the gh command line (github cli) and it worked.

```
echo "token" | gh auth login --with-token
gh repo clone owner/repo
```

So I'm not sure what I did wrong.

### Expected Behavior

no error

### Steps To Reproduce

```yaml
scms:
  default:
    kind: github
    spec:
      owner: "owner"
      repository: "repo"
      branch: "..."
      token: '{{ requiredEnv "UPDATECLI_GITHUB_TOKEN" }}'
      user: "..."
      email: "..."

sources:
  latestDockerDigest:
    kind: dockerdigest
    name: "..."
    spec:
      image: "..."
      tag: "latest"
      architecture: "amd64"

targets:
  updateValues:
    name: "name"
    scmid: default
    kind: yaml
    spec:
      file: "xxx.yaml"
      key: "$.image.tag"
```

### Environment

```markdown
- OS: tested on docker (official updatecli) and inside github action (official updatecli action)
- updatecli: latest docker / github action
```

**Comment by softlion** [comment]
I was able to make this github kind work.

"username" is mandatory.

I'm use an auth token: username should be optional.

**Comment by olblak** [comment]
Thanks for the issue, you are not the first person to stumble on this, so I quickly check what we can do, and apparently the fix is really easy.

If a token is defined but not the username, then we can set the username  to "oauth2"
I was able to make it working with the following example

```
scms:
  default:
    kind: github
    spec:
      owner: olblak
      repository: fleet-lab
      username: oauth2
      token: '{{ requiredEnv "UPDATECLI_GITHUB_TOKEN" }}'
      branch: main

sources:
  default:
    kind: file
    scmid: default
    spec:
      file: README.md

  kubectl:
    kind: githubRelease
    spec:
      owner: "updatecli"
      repository: "udash"
      token: '{{ requiredEnv "UPDATECLI_GITHUB_TOKEN" }}'
      username: "oauth2"
      versionFilter:
        kind: semver
```

The code should be modified in https://github.com/updatecli/updatecli/blob/7eaf7ed3f8b6c5d877cb240b5833c8a8a18d0da5/pkg/plugins/scms/github/main.go#L197
