### ISSUE TITLE
target ENV for Dockerfile is adding the new value instead of replacing the old one

### ISSUE THREAD

**Issue by lemeurherve** [updatecli/updatecli#390]
**Describe the bug**
Using an ENV keyword on a dockerfile type target, I've noticed the new value is added before the previous value instead of replacing it:
> 🐋 On (Docker)file "/var/folders/z6/xykmq_m902n_7v4j8sxhzkdm0000gn/T/updatecli/jenkins-infra/docker-packer/Dockerfile":
> ✔ The line #3, matched by the keyword "ENV" and the matcher "WINDOWS_UPDATE_VERSION", is changed from "ENV WINDOWS_UPDATE_VERSION 0.10.1" to "ENV WINDOWS_UPDATE_VERSION=v0.14.0 0.10.1".

**To Reproduce**
On the https://github.com/jenkins-infra/jenkins-packer repository, try this updatecli manifest:
```
title: Bump Packer Windows Update Provisioner plugin version
sources:
  latestRelease:
    kind: githubRelease
    name: Get latest rgl/packer-plugin-windows-update version
    spec:
      owner: "rgl"
      repository: "packer-plugin-windows-update"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"

# No condition here as we're downloading the plugin from github directly (no docker image involved)
targets:
  updateReleaseInDockerfile:
    name: "Update the version of the Packer Windows Update Provisioner plugin in the Dockerfile"
    kind: dockerfile
    spec:
      file: Dockerfile
      instruction:
        keyword: "ENV"
        matcher: "WINDOWS_UPDATE_VERSION"
    scm:
      github:
        user: "{{ .github.user }}"
        email: "{{ .github.email }}"
        owner: "{{ .github.owner }}"
        repository: "{{ .github.repository }}"
        token: "{{ requiredEnv .github.token }}"
        username: "{{ .github.username }}"
        branch: "{{ .github.branch }}"
```

For reference, here is the Dockerfile:
```
FROM hashicorp/packer:1.6.5

ENV WINDOWS_UPDATE_VERSION 0.10.1

ADD https://github.com/rgl/packer-provisioner-windows-update/releases/download/v${WINDOWS_UPDATE_VERSION}/packer-provisioner-windows-update_${WINDOWS_UPDATE_VERSION}_checksums.txt ./
ADD https://github.com/rgl/packer-provisioner-windows-update/releases/download/v${WINDOWS_UPDATE_VERSION}/packer-provisioner-windows-update_${WINDOWS_UPDATE_VERSION}_linux_amd64.tar.gz ./

RUN sed -i '/.*linux_amd64.tar.gz/!d' packer-provisioner-windows-update_${WINDOWS_UPDATE_VERSION}_checksums.txt
RUN sha256sum -cs packer-provisioner-windows-update_${WINDOWS_UPDATE_VERSION}_checksums.txt

RUN tar xvfz packer-provisioner-windows-update_${WINDOWS_UPDATE_VERSION}_linux_amd64.tar.gz -C /bin && \
    rm -f packer-provisioner-windows-update_${WINDOWS_UPDATE_VERSION}_linux_amd64.tar.gz && \
    chmod a+x /bin/packer-provisioner-windows-update

```

I've also tried to replace in the Dockerfile `ENV WINDOWS_UPDATE_VERSION 0.10.1` to `ENV WINDOWS_UPDATE_VERSION=0.10.1`, same error.

**Expected behavior**
The ENV value is replaced:
> 🐋 On (Docker)file "/var/folders/z6/xykmq_m902n_7v4j8sxhzkdm0000gn/T/updatecli/jenkins-infra/docker-packer/Dockerfile":
> ✔ The line #3, matched by the keyword "ENV" and the matcher "WINDOWS_UPDATE_VERSION", is changed from "ENV WINDOWS_UPDATE_VERSION 0.10.1" to "ENV WINDOWS_UPDATE_VERSION=v0.14.0".

**Version (please complete the following information):**
- OS: MacOS
- Version: 0.15.0
