### ISSUE TITLE
condition dockerImage with a digest as source returns "not found on DockerHub"

### ISSUE THREAD

**Issue by lemeurherve** [updatecli/updatecli#391]
**Describe the bug**
When retrieving a digest in source, the condition `dockerImage` always fails to find the corresponding docker image on docker hub.

**To Reproduce**
With [the datadog updatecli manifest](https://github.com/jenkins-infra/charts/blob/main/updatecli/updatecli.d/docker-images/datadog.yaml) as example for a source retrieving a digest, add a condition to it in order to have this final manifest:
```
title: Bump datadog docker image digest
sources:
  latestDigest:
    kind: dockerDigest
    name: "Get jenkinsciinfra/datadog:latest docker image digest"
    spec:
      image: "jenkinsciinfra/datadog"
      tag: "latest"
# no condition to test docker image availability as we're using a digest from docker hub
conditions:
  checkDockerImagePublished:
    name: "Is latest jenkinsciinfra/datadog docker image published"
    kind: dockerImage
    spec:
      image: "jenkinsciinfra/datadog@sha256"
```
Here is the output of `updatecli diff`:
```
SOURCES
=======

latestDigest
------------
✔ Digest 'e56ac356bac9f18478591d003a862583fc03d4c67119234eed9895f6d11e5a5a' found for docker image jenkinsciinfra/datadog:latest available from Docker Registry
Remark: Do not forget to add @sha256 after your the docker image name
Example: jenkinsciinfra/datadog@sha256:e56ac356bac9f18478591d003a862583fc03d4c67119234eed9895f6d11e5a5a


CONDITIONS:
===========

checkDockerImagePublished
-------------------------
ERROR: jenkinsciinfra/datadog@sha256:e56ac356bac9f18478591d003a862583fc03d4c67119234eed9895f6d11e5a5a not found on DockerHub

✗ condition not met, skipping pipeline
```
Note that manually pulling the image works as expected:  
`docker pull jenkinsciinfra/datadog@sha256:e56ac356bac9f18478591d003a862583fc03d4c67119234eed9895f6d11e5a5a`

**Expected behavior**
The conditions passes and check the presence of the image in docker hub

**Version**
- OS: MacOS
- Version: 0.14.1 & 0.15.0
