### ISSUE TITLE
Feature Request: New source type "Amazon EKS Add On Version"

### ISSUE THREAD

**Issue by dduportal** [updatecli/updatecli#3944]
### Is your feature request related to a problem?

We are managing an Amazon EKS cluster in which we pin the addons versions.
The version are tracked using an updatecli manifest with a "shell" source running an `aws eks describe-addon-versions --kubernetes-version=1.XX <...>` like command:

- https://github.com/jenkins-infra/terraform-aws-sponsorship/blob/main/updatecli/updatecli.d/eks-aws-ebs-csi-driver.yaml
- https://github.com/jenkins-infra/terraform-aws-sponsorship/blob/main/updatecli/updatecli.d/eks-coredns.yaml
- https://github.com/jenkins-infra/terraform-aws-sponsorship/blob/main/updatecli/updatecli.d/eks-kube-proxy.yaml
- https://github.com/jenkins-infra/terraform-aws-sponsorship/blob/main/updatecli/updatecli.d/eks-vpc-cni.yaml

It works but required a lot of custom AWS credential managements, along with flag parsing, etc..

### Solution you'd like

In the same way as the [Amazon AMI](https://www.updatecli.io/docs/plugins/resource/aws_ami/) resource, a native source of type "Amazon EKS AddOn" would make thing smoother:

```yaml
source:
  getVPCCNIVersion:
    kind: aws/eksaddon
    spec:
      region: "us-east-2"
      kubernetesversion: {{ source "getKubernetesVersion" }}
      addon: "vpc-cni
```

### Anything else?

We could even think about autodiscovery with terraform
