### ISSUE TITLE
Comments in target yaml break format 

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#40]
**Describe the bug**
Comments in target yaml break format 

```
credentials: |
    credentials:
        system:
            #${ENV}
            domainCredentials:
```
becomes
```
credentials: "credentials:\n  system:\n    \n    #${ENV}\n    domainCredentials:\n    
```

**Expected behavior**
Target yaml keeps its formatting

**Additional context**
This problem seems to be coming from [go-yamlyaml](https://github.com/go-yaml/yaml/issues/578)

**Workaround** 
Remove comments
