### ISSUE TITLE
Feature Request: Single commit for multiple updates via multiple targets

### ISSUE THREAD

**Issue by pkazi** [updatecli/updatecli#4043]
### Is your feature request related to a problem?

I have a use case to update yaml file with new docker image tag. I have 3 services that  I want to update the tag. In this case, it is creating 3 commits, where as I am looking for only one commit.

### Solution you'd like

A single commit for a given SCM, it can be multiple targets.

**Comment by treezio** [comment]
Maybe using `squash & merge` option (at least in GitHub) as a workaround fits your needs.

**Comment by pkazi** [comment]
I am not using Pull Request way.
This is my scm - 
```
scms:
  default:
    kind: github
    spec:
      commitusingapi: true
      branch: '{{ .scm.branch }}'
      email: '{{ requiredEnv "GITHUB_EMAIL" }}'
      owner: '{{ .scm.owner }}'
      repository: '{{ .scm.repository }}'
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      user: '{{ requiredEnv "GITHUB_USER" }}'
      username: '{{ requiredEnv "GITHUB_USER" }}'
      workingBranch: false
      force: true
```

My workflow is I need to update 3 docker image tags in my GitOps repo's values.yaml file. instead of 3 different commits to main branch, how to have only 1 commit for all3 updates ?
