### ISSUE TITLE
Feature request: update all charts of an helmfile without having to create a manifest of each of them

### ISSUE THREAD

**Issue by lemeurherve** [updatecli/updatecli#409]
**Is your feature request related to a problem?**
To update the different charts of an helmfile, we need to create an updatecli manifest for each of them.
We also need to keep track of which of them are covered by an updatecli manifest.

**Describe the solution you'd like**
Ability to specify once to updatecli we want to check/update all helm charts of an helmfile.

Proposed format, with the introduction of `helmfile` kind:
````yaml
title: "Bump helm charts versions of publick8s"
sources:
  default:
    kind: helmfile
    spec:
      # either a local path
      file: clusters/publick8s.yaml
      # or a public url
      url: https://github.com/jenkins-infra/charts/blob/main/clusters/publick8s.yaml
targets:
  updateChartsVersions:
    name: "Update all charts versions"
    kind: helmfile
    spec:
      file: clusters/publick8s.yaml
    scm:
      github:
        user: "{{ .github.user }}"
        email: "{{ .github.email }}"
        owner: "{{ .github.owner }}"
        repository: "{{ .github.repository }}"
        token: "{{ requiredEnv .github.token }}"
        username: "{{ .github.username }}"
        branch: "{{ .github.branch }}"
````

**Describe alternatives you've considered**

N/A

**Additional context**

To update the charts used in [these two helmfiles](https://github.com/jenkins-infra/charts/tree/main/clusters), we have all these updatecli manifests: https://github.com/jenkins-infra/charts/tree/main/updatecli/updatecli.d/charts
All of them are similar, and could be IMO factored in one manifest for these helm charts version update. (This is not the case for the [docker image versions](https://github.com/jenkins-infra/charts/tree/main/updatecli/updatecli.d/docker-images) bump, as we need to search info in different places)

**Comment by olblak** [comment]
Now that the [autodiscovery](https://github.com/updatecli/updatecli/issues/761) is ready, I can have a look to this issue if needed.
Considering that there is no way to clearly identify Helmfile configuration, I am not considering the helmfile crawler to be running by default. Instead we'll need to enable it using a configuration.

So proposed Updatecli manifest
```
# A scm configuration can be specified so Updatecli browse the git repository content.
scms:
    default:
        kind: github
        spec:
        # ...
pullrequests:
    default:
       kind: github
       spec:
       # ....

autodiscovery:
     # Optional configuration to specified the scm configuration used in generated manifest
     scmid: 
     # Optional configuration to specified the pullrequest configuration used in generated manifest
     pullrequestid: 

     crawlers:
         helmfile:
            # default false
            enabled: true

            # Optional, mutually exclusive with only
            ignore:
              - path: <specifies path to ignore>

            # Optional, mutually exclusive with ignore
            only:
              - path: <only explore this path>

            # OptionDefault scm directory or local if nothing specified
            rootdir: <override directory to analyze>
```

The rule would be 
If we find a yaml file with the following content

```
repositories:
    - name: example
      url: https://mychart

releases:
    - chart: example/mychart
      version: 1.0.0
```

Then we generate the manifest

```
title: "Bump {{ helmChart Name }} Helm Chart Version"

# if `scmid` is specified in autodisccovery configuration
scms:
  {{ scmid }}:
    kind: github
    spec:
      {{ scmid spec }}

sources:
  {{ chartName }}:
    name: Get latest {{ chartName }} version
    kind: helmchart
    spec:
      url: {{ chartRepositoryUrl }}
      name: {{ chartName }}

conditions:
  # Extra protection in case the target file changed between the detection and apply
  {{ chartName }}:
    name: "Ensure {{ chartName }} chart is specified"
    kind: yaml
    scmid: default
    spec:
      file: {{ filename }}
      key: {{ identified_key }}
      value: {{ repositoryNAme }}/{{ chartName }

targets:
  {{ chartName }}:
    name: "Update {{ chartName }} chart version"
    kind: yaml
    scmid: default
    spec:
      file: {{ filename }}
      key: {{ identified_key }}

# If pullrequestid is specified in autodiscovery configuration`
pullrequests:
  default:
    kind: github
    scmid: {{ scmID }}
    spec:
      labels:
        - dependencies
        - accountapp

```
