### ISSUE TITLE
scms ID "" referenced by the action id "mr" does not exist

### ISSUE THREAD

**Issue by alikhil** [updatecli/updatecli#4169]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

+++++++++++
+ PREPARE +
+++++++++++

Loading Pipeline "updatecli.yaml"

SCM repository retrieved: 1

++++++++++++++++++
+ AUTO DISCOVERY +
++++++++++++++++++

++++++++++++++++++
+ UPDATECLI.YAML +
++++++++++++++++++

HELM
=====
Manifest detected: 12

---

=> Total manifest detected: 12

ERROR: Error(s) happened while generating Updatecli pipeline manifest
ERROR: "Bump dependency \"argo-cd\" for Helm chart \"argocd\"" - scms ID "" referenced by the action id "mr" does not exist
ERROR: Error(s) happened while generating Updatecli pipeline manifest
ERROR: "Bump dependency \"argo-cd\" for Helm chart \"argocd\"" - scms ID "" referenced by the action id "mr" does not exist
ERROR: "Bump dependency \"cert-manager\" for Helm chart \"cert-manager\"" - scms ID "" referenced by the action id "mr" does not exist
ERROR: Error(s) happened while generating Updatecli pipeline manifest
ERROR: "Bump dependency \"argo-cd\" for Helm chart \"argocd\"" - scms ID "" referenced by the action id "mr" does not exist
ERROR: "Bump dependency \"cert-manager\" for Helm chart \"cert-manager\"" - scms ID "" referenced by the action id "mr" does not exist
...MORE ERRORS like this...

++++++++++++++++++
+ UPDATECLI.YAML +
++++++++++++++++++

name: UPDATECLI.YAML
pipelineid: 16dc32d2752e350fa15d80c273069b5387f30e7dc1a888974dc63bcbdc6d8ceb
autodiscovery:
    crawlers:
        helm:
            ignorecontainer: true
    scmid: gitlab
    actionid: mr
    groupby: ""
actions:
    mr:
        title: 'feat: update helm chart dependencies with updatecli'
        kind: gitlab/mergerequest
        scmid: gitlab
scms:
    gitlab:
        kind: gitlab
        spec:
            url: https://gitlab.domain.com
            owner: technology
            repository: techops/kubernetes/charts
            branch: main
            username: alikhil
            token: token
            email: myemail@mail.com
        disabled: false
version: v0.94.1-next

### Expected Behavior

If I run the same configuration in version `0.92.0` it works! Or If I change config by renaming scm and action to `default` it works again:
```yaml
scms:
  default:
    kind: gitlab
    spec:
      url: https://gitlab.domain.com
      owner: technology
      repository: techops/kubernetes/charts
      branch: main
      username: alikhil
      token: token
      email: myemail@mail.com

autodiscovery:
  scmid: default
  actionid: default
  crawlers:
    helm:
      ignorecontainer: true

actions:
  default:
    title: "feat: update helm chart dependencies with updatecli"
    kind: gitlab/mergerequest
    scmid: default
```

### Steps To Reproduce

1. With latest version or v0.94.1
2. With the following config:
```yaml
scms:
  gitlab:
    kind: gitlab
    spec:
      url: https://gitlab.domain.com
      owner: technology
      repository: techops/kubernetes/charts
      branch: main
      username: alikhil
      token: token
      email: myemail@mail.com

autodiscovery:
  scmid: gitlab
  actionid: mr
  crawlers:
    helm:
      ignorecontainer: true

actions:
  mr:
    title: "feat: update helm chart dependencies with updatecli"
    kind: gitlab/mergerequest
    scmid: gitlab
```
3. Run `updatecli manifest show`

### Environment

```markdown
- OS: Mac OS
- updatecli: v0.94.1
```

### Pipeline Graph

```mermaid
```

### Anything else?

I guess this bug is result of these two commits:
- https://github.com/updatecli/updatecli/commit/79482d68cd82cf40bf8ea3ab150920eea85a8d63
- https://github.com/updatecli/updatecli/commit/e99a29e3bb9d98ee64e4596345b7c5ead18cda79
