### ISSUE TITLE
Templated values are not rendered for pull request titles

### ISSUE THREAD

**Issue by lemeurherve** [updatecli/updatecli#440]
**Is your feature request related to a problem?**

Not a problem, just nitpicking...

**Describe the solution you'd like**

I'd like to be able to use templated values in the `title` field, to live long and prosper.

Example:
```
title: "Bump `accountapp` helm chart version to {{ source `lastChartVersion` }}"
sources:
  lastChartVersion:
    kind: helmChart
    spec:
      url: https://jenkins-infra.github.io/helm-charts
      name: accountapp
```

**Describe alternatives you've considered**

N/A

**Additional context**

N/A
