### ISSUE TITLE
Pull Request does not check for existence of specified target items

### ISSUE THREAD

**Issue by dduportal** [updatecli/updatecli#442]
**Describe the bug**

If you specify `target`s that does not exist to a `pullrequest` block, then updatecli fails when trying to open the pull request with the error `reference not found`
 
**Steps to Reproduce**

With this manifest `example.yaml`:

```yml
title: Bump Golang Version

scms:
  default:
    kind: github
    spec:
      user: updatecli
      email: me@olblak.com
      owner: updatecli
      repository: updatecli
      token: 'SuperSecretToken'
      branch: main

sources:
  latestVersion:
    name: Get Latest Version
    kind: shell
    spec:
      command: echo 1.0.0

targets:
  release-sandbox:
    name: 'Update last version'
    sourceID: latestVersion
    kind: shell
    spec:
      command: echo
    scmID: default

pullrequests:
  default:
    title: 'PR Title Here'
    kind: github
    scmID: default
    targets:
      - foo
```

With the command

```shell
updatecli diff --config example.yaml
```

No error is shown.

**Expected behavior**

This pipeline should fail its validation

**Screenshots**
N.A.

**Version**

- OS: all
- Updatecli version: 0.17.2

**Additional context**
N.A.
