### ISSUE TITLE
Pull Requests: if no target is specified, then use them all

### ISSUE THREAD

**Issue by dduportal** [updatecli/updatecli#445]
**Is your feature request related to a problem?**

Maintaining multiple manifests is a pain: having less configuration would help.

The new pullrequest object is hard to maintain: the list of targets need to be updated to reflect existing target ids: it's not really sustainable.

**Describe the solution you'd like**

```yml
pullrequests:
  default:
    title: '[updatecli] Bump Golang version to {{ source "latestGoVersion" }}'
    kind: github
    scmID: default
    targets:
      - release-sandbox
      - release
      - workflowgo
      - go.mod
    spec:
      labels:
        - chore
```

should have the same effect as

```yml
pullrequests:
  default:
    title: '[updatecli] Bump Golang version to {{ source "latestGoVersion" }}'
    kind: github
    scmID: default
    spec:
      labels:
        - chore
```

=> The manifests where only a subset of all the targets are specified are edge cases.

**Describe alternatives you've considered**
N.C.

**Additional context**
N.C.
