### ISSUE TITLE
Pull Request should automatically defines their kind and scm id based on targets

### ISSUE THREAD

**Issue by dduportal** [updatecli/updatecli#446]
**Is your feature request related to a problem?**

Maintaining multiple manifests is a pain: having less configuration would help.

I would like to avoid repeating the SCM ID in targets, and to avoid specifying a kind of pull request since it must be the same as the scm object it relates to.

**Describe the solution you'd like**

```yml
title: Bump Golang Version

scms:
  default:
    kind: github
    spec:
      user: updatecli
      email: me@olblak.com
      owner: updatecli
      repository: updatecli
      token: '{{ requiredEnv "UPDATECLI_GITHUB_TOKEN" }}'
      username: '{{ requiredEnv "UPDATECLI_GITHUB_ACTOR" }}'
      branch: main

# ... sources and conditions

## The 4 targets below HAVE an implicit SCM ID defined, because the pull request object says so
targets:
  release-sandbox:
    name: '[release.yaml] Update Golang version to {{ source "latestGoVersion" }}'
    sourceID: latestGoVersion
    kind: yaml
    spec:
      file: .github/workflows/release.yaml
      key: jobs.build.steps[3].with.go-version
  release:
    name: '[release-sandbox.yaml] Update Golang version to {{ source "latestGoVersion" }}'
    sourceID: latestGoVersion
    kind: yaml
    spec:
      file: .github/workflows/release-sandbox.yaml
      key: jobs.build.steps[3].with.go-version
  workflowgo:
    name: '[release.yaml] Update Golang version to {{ source "latestGoVersion" }}'
    kind: yaml
    sourceID: latestGoVersion
    spec:
      file: .github/workflows/go.yaml
      key: jobs.build.steps[0].with.go-version
  go.mod:
    name: '[go.mod] Update Golang version to {{ source "latestGoVersion" }}'
    sourceID: gomod
    kind: file
    spec:
      file: go.mod

pullrequests:
  default:
    title: '[updatecli] Bump Golang version to {{ source "latestGoVersion" }}'
    ## No kind object
    scmID: default
    # Explicitly defined targets inherits the SCM ID of the pullrequest
    targets:
      - release-sandbox
      - release
      - workflowgo
      - go.mod
    spec:
      labels:
        - chore
```

**Describe alternatives you've considered**

**Additional context**
