### ISSUE TITLE
Comment in yaml target doesn't apply

### ISSUE THREAD

**Issue by gionn** [updatecli/updatecli#4490]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Adding `comment` attribute to a `yaml` target doesn't have any effect.

### Expected Behavior

any provided values as `comment` should be added as an inline comment as per docs:
https://www.updatecli.io/docs/plugins/resource/yaml/#_parameters

### Steps To Reproduce

```yml
name: Update AMI

sources:
  src_ami:
    kind: aws/ami
    spec:
      filters:
        - name: "name"
          values: "RHEL-9.5.0_HVM-*"

targets:
  moleculeYml:
    kind: yaml
    sourceid: src_ami
    spec:
      file: "molecule/opensearch/vars.yml"
      key: "$.MOLECULE_IT_IMAGE_ID"
      comment: "RHEL-9.5.0_HVM-*"
```

### Environment

```markdown
Application:    0.95.1
Golang     :    1.24.1 linux/amd64
Build Time :    2025-03-12T12:27:50Z
```

### Pipeline Graph

```mermaid
```

**Comment by olblak** [comment]
Ho, you are right
We introduced this parameter in the context of GitHub action update, we implemented it for the yamlpath engine but not for the default one.

```
sources:
  default:
    kind: shell
    spec:
      command: echo 99

targets:
  comment:
    kind: yaml
    spec:
      engine: yamlpath
      file: /tmp/test.yaml
      key: '$.user.age'
      comment: "almost"
```
