### ISSUE TITLE
YAML parsing seems to erroneously distinguish quoted and non-quoted version strings

### ISSUE THREAD

**Issue by jcmcken** [updatecli/updatecli#4510]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

For example, if I have a YAML that looks like:

```yaml
version: "4.3.1"
```

If I run an ``updatecli`` manifest like:

```yaml
name: foo
sources:
  current:
    kind: "yaml"
    spec:
      file:
        file: "path/to/file"
        key: "$.version"
    transformers:
    - semverinc: "minor"
```

I get an error ``wrong semantic version input: "\"4.3.1\""``

### Expected Behavior

Every YAML parser I've used treats ``"4.3.1"`` and ``4.3.1`` as strings, so it's not clear what distinction ``updatecli`` is making. 

### Steps To Reproduce

See the example in the 'current behavior' description

### Environment

```markdown
- OS: Rocky Linux release 9.5. (Blue Onyx) -- a RHEL9 clone

- updatecli:


Application: 0.95.0
Golang:      1.24.1 linux/amd64
Build Time:  2025-03-11T16:30:40Z
```

### Pipeline Graph

```mermaid
graph TD
    source#current(["current (yaml)"])
```

### Anything else?

This issue may be similar to what I posted in [this discussion](https://github.com/orgs/updatecli/discussions/4491), but with this config I'm not using any templating.

**Comment by olblak** [comment]
Mmmh interesting bug.
It seems to affect the default yaml parser we use on Updatecli

```
sources:
  goccy:
    kind: yaml
    spec:
      file: /tmp/test.yaml
      key: "$.version"
    transformers:
      - semverinc: "minor"
  goyaml:
    kind: yaml
    spec:
      file: /tmp/test.yaml
      key: "$.version"
      engine: yamlpath
    transformers:
      - semverinc: "minor"
```

and

```
version: "4.3.1"
```

```
source: source#goccy
------------
✔ value "\"4.3.1\"" found for key "$.version" in the yaml file "/tmp/test.yaml"
[transformers]
ERROR: ✔ wrong semantic version input: "\"4.3.1\""

source: source#goyaml
-------------
✔ value "4.3.1" found for key "$.version" in the yaml file "/tmp/test.yaml"
[transformers]
✔ Result correctly transformed from "4.3.1" to "4.4.0"

ERROR: something went wrong in "source#goccy" : wrong semantic version input: "\"4.3.1\""
```

In the Golang ecosystem, there are two popular Golang library `https://github.com/go-yaml/yaml` and `https://github.com/goccy/go-yaml`, both have pros & cons, we switched to the goccy one, as we find it better maintained, but we kept the go-yaml one for specific scenarios

We may need to open a bug on `https://github.com/goccy/go-yaml`
