### ISSUE TITLE
Feature Request (helmchart plugin): allow multiple changes for a single target

### ISSUE THREAD

**Issue by dduportal** [updatecli/updatecli#463]
### Is your feature request related to a problem?

If a manifest changes 2 distinct values on a single helmchart, it is annoying (but not blocking) that the helm chart's version is bumped twice.

Example Manifest (with 2 targets: one for each value)

```yaml
title: Bump `ldap` images versions

scms:
  default:
    kind: github
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: "{{ .github.owner }}"
      repository: "{{ .github.repository }}"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      branch: "{{ .github.branch }}"

sources:
  crond:
    kind: dockerDigest
    name: "Get jenkinsciinfra/ldap:cron-latest docker image digest"
    spec:
      image: "jenkinsciinfra/ldap"
      tag: "cron-latest"
  slapd:
    kind: dockerDigest
    name: Get jenkinsciinfra/ldap:latest docker image digest
    spec:
      image: "jenkinsciinfra/ldap"
      tag: "latest"

targets:
  updateChartCrond:
    name: Update jenkins-wiki-exporter helm chart
    kind: helmChart
    sourceID: crond
    spec:
      name: charts/ldap
      key: image.crond.tag
      versionincrement: patch
    scmID: default
  updateChartSlapd:
    name: Update jenkins-wiki-exporter helm chart
    kind: helmChart
    sourceID: slapd
    spec:
      name: charts/ldap
      key: image.slapd.tag
      versionincrement: patch
    scmID: default

pullrequests:
  default:
    kind: github
    scmID: default
    targets:
      - updateChartCrond
      - updateChartSlapd
    spec:
      labels:
        - dependencies
        - ldap
        - crond
        - slapd
```

This manifest produces [a PR with the following change](https://github.com/jenkins-infra/helm-charts/pull/84/files):

```diff
- version: 0.1.3
+ version: 0.1.5
```

### Solution you'd like

The `helmchart` provider is specifically allowing to bump the version of an helm chart.
The ability to "batch" a set of changes to a single chart, with only 1 bump, would make it a bit more practial.

Example of a manifest with a proposed new syntax (compliant with the previous one of course!):

```yaml
title: Bump `ldap` images versions

scms:
  default:
    kind: github
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: "{{ .github.owner }}"
      repository: "{{ .github.repository }}"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      branch: "{{ .github.branch }}"

sources:
  crond:
    kind: dockerDigest
    name: "Get jenkinsciinfra/ldap:cron-latest docker image digest"
    spec:
      image: "jenkinsciinfra/ldap"
      tag: "cron-latest"
  slapd:
    kind: dockerDigest
    name: Get jenkinsciinfra/ldap:latest docker image digest
    spec:
      image: "jenkinsciinfra/ldap"
      tag: "latest"

targets:
  updateChart:
    name: Update jenkins-wiki-exporter helm chart
    kind: helmChart
    sourceID: crond
    spec:
      name: charts/ldap
      changes:
        - key: image.crond.tag
          sourceID: crond
        - key: image.slapd.tag
          sourceID: slapd
      versionincrement: patch
    scmID: default

pullrequests:
  default:
    kind: github
    scmID: default
    targets:
      - updateChart
    spec:
      labels:
        - dependencies
        - ldap
        - crond
        - slapd
```

### Alternatives you've considered

N.A.

### Anything else?

Not sure how to deal with the mandatory `sourceID` at the target level: I guess a message to the user explaining that it's ignored would suffice.

**Comment by lemeurherve** [comment]
I would reserve the introduction of `changes` for the [`actions`](https://github.com/updatecli/updatecli/issues/465) instead.

**Comment by lemeurherve** [comment]
> I would reserve the introduction of `changes` for the [`actions`](https://github.com/updatecli/updatecli/issues/465) instead.

Maybe `destinations` here?

**Comment by dduportal** [comment]
> I would reserve the introduction of changes for the actions instead.

Fair point. 

> Maybe destinations here?

Destination does not convey the full meaning, as each element of the proposed array has a key, but also a value.

Not sure, maybe "elements" ? "edits" ? "helmValues" ?

**Comment by lemeurherve** [comment]
WDYT about "keys"?

```yaml
targets:
  updateChart:
    name: Update jenkins-wiki-exporter helm chart
    kind: helmChart
    sourceID: crond
    spec:
      name: charts/ldap
      keys:
        - key: image.crond.tag
          sourceID: crond
        - key: image.slapd.tag
          sourceID: slapd
      versionincrement: patch
    scmID: default
```
