### ISSUE TITLE
Feature Request: Composite Targets

### ISSUE THREAD

**Issue by dduportal** [updatecli/updatecli#464]
### Is your feature request related to a problem?

It's about targets, but could be generalized to other resources (sources/conditions).

The idea is to allow "grouping" a set of targets that would look almost the same, into a single meaningful change ("commit") (e.g. 1 commit).

As for today, we have either a set of targets in a manifest (e.g. 1 "change/commit" per target), or a set of manifests (but in this case the source is duplicated.

### Solution you'd like

Allowing to define a "composite" target, e.g. a target composed of "sub targets" would allow simpler use case while keeping meaningful attributes factorized.

That would be providing an array of maps instead of a map to the `spec`.

Example: a set of files that would be modified with different patterns matching but the same source input:

```yaml
targets:
  updateAllNginx:
    name: Update all nginx services
    kind: file
    sourceID: nginxVersion
    spec:
      - file: "config.properties"
        matchPattern: "whatever/"
      - file: "config-2.ini"
        matchPattern: "whatever/"
```

### Alternatives you've considered

This feature request a bit different than something like #435:

- It does not depend on a specific provider (so no specific logic to rewrite/implement for each plugin)
- It improves the expressivity of the updatecli syntax to allow new use cases
