### ISSUE TITLE
Error `no Git tag found matching pattern \"latest\"` with gitTag resources

### ISSUE THREAD

**Issue by dduportal** [updatecli/updatecli#467]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- If you run the current example at `examples/updatecli.generic/gitTag.yaml`, it only errors for every gittag resource
- Example pre-0.17.0 (from documentation) does not work either
- When updating to post-0.17.0 scm syntax, the error keep happening

### Steps To Reproduce

- Pre 0.17.0 (from website):

```yaml
title: "Test new gitTag resource"
sources:
  git:
    name: Get Latest updatecli test
    kind: gitTag
    spec:
      url: "https://github.com/updatecli/updatecli.git"
      branch: "main"
```

```shell
$ updatecli diff --config examples/updatecli.generic/gitTag.yaml

+++++++++++
+ PREPARE +
+++++++++++

Loading Pipeline "examples/updatecli.generic/gitTag.yaml"
Repository retrieved: 0

++++++++++++
+ PIPELINE +
++++++++++++

############################
# TEST NEW GITTAG RESOURCE #
############################

SOURCES
=======
git
---
WARNING: no git tag message specified
Searching for version matching pattern "latest"
✗ No Git Tag found matching pattern "latest"
ERROR: ✗ no Git tag found matching pattern "latest"
Pipeline "Test new gitTag resource" failed
Skipping due to:
        "sources stage:\t\"no Git tag found matching pattern \\\"latest\\\"\""
sources stage:  "no Git tag found matching pattern \"latest\""

=============================
REPORTS:

✗ GITTAG.YAML:
        Sources:
                ✗ [git] Get Latest updatecli test(gitTag)
        Target:

Run Summary
===========
Pipeline(s) run:
  * Changed:    0
  * Failed:     1
  * Skipped:    0
  * Succeeded:  0
  * Total:      1
ERROR: ✗ 1 over 1 pipeline failed
ERROR: command failed
```

* Same with "updated" syntax:

```yaml
title: "Test new gitTag resource"

scms:
  updatecli:
    kind: git
    spec:
      url: "https://github.com/updatecli/updatecli.git"
      branch: "main"

sources:
  git:
    name: Get Latest updatecli test
    kind: gitTag
    scmID: updatecli
```

```shell
updatecli diff --config examples/updatecli.generic/gitTag.yaml 

+++++++++++
+ PREPARE +
+++++++++++

Loading Pipeline "examples/updatecli.generic/gitTag.yaml"
Repository retrieved: 1


++++++++++++
+ PIPELINE +
++++++++++++



############################
# TEST NEW GITTAG RESOURCE #
############################


SOURCES
=======

git
---
WARNING: no git tag message specified
Searching for version matching pattern "latest"
✗ No Git Tag found matching pattern "latest"
ERROR: ✗ no Git tag found matching pattern "latest"
Pipeline "Test new gitTag resource" failed
Skipping due to:
        "sources stage:\t\"no Git tag found matching pattern \\\"latest\\\"\""
sources stage:  "no Git tag found matching pattern \"latest\""

=============================

REPORTS:


✗ GITTAG.YAML:
        Sources:
                ✗ [git] Get Latest updatecli test(gitTag)
        Target:



Run Summary
===========
Pipeline(s) run:
  * Changed:    0
  * Failed:     1
  * Skipped:    0
  * Succeeded:  0
  * Total:      1
ERROR: ✗ 1 over 1 pipeline failed
ERROR: command failed
```

### Environment

```markdown
- OS: macOS, Linux
- updatecli: 0.18.2
```

### Anything else?

This is only reporting an issue. I intend to fix this as part of https://github.com/updatecli/updatecli/pull/457 unless you disagree.
