### ISSUE TITLE
The gitTag resource does returns the correct version

### ISSUE THREAD

**Issue by dduportal** [updatecli/updatecli#469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The gittag does not return the latest tag, but another.
It seems related to a sorting issue (the returned tag are always the "latest" on on lexicographic order).

### Expected Behavior

Example with the updatecli GitHub repository: it returns `v0.9.0` while `v0.18.2` is expected (when writing these lines).

### Steps To Reproduce

```yaml
title: "Test new gitTag resource"

scms:
  updatecli:
    kind: git
    spec:
      url: "https://github.com/updatecli/updatecli.git"
      branch: "main"

sources:
  git:
    name: Get Latest updatecli test
    kind: gitTag
    scmID: updatecli
```

### Environment

```markdown
- OS: macOS, Linux
- updatecli: 0.18.2
```

### Anything else?

This is only reporting an issue. I intend to fix this as part of #457 unless you disagree.
