### ISSUE TITLE
Feature Request: Shell 'actions' or creating a commit without pushing

### ISSUE THREAD

**Issue by btrepp** [updatecli/updatecli#4820]
### Is your feature request related to a problem?

Hi,

I was trying to refactor around having the updatecli tool use git format-email, and then perhaps a SMTP action to send this to a mailing list after.

I got pretty close with targets

```
  patch:
    name: Create patch
    kind: shell
    dependson: [release]
    scmid: environment
    dependsonchange: true
    disablesourceinput: true
    spec:
      command: "git format-patch -n HEAD^"
```

However even though this depends on a yaml step that is cloning a SCM, and I think applying the change, there isn't any commits.

Possibly the order of creating a commit comes after the targets stages?. If so it would be awesome if a 'shell' action could exist, allowing uses to use shell commands for any custom forges/processes that aren't currently supported SCMs/actions?
