### ISSUE TITLE
github scm: invalid auth method

### ISSUE THREAD

**Issue by omissis** [updatecli/updatecli#4823]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

I am trying to configure updatecli to update my repository [](https://github.com/mecha-hq/images). 
For some reason I cannot understand, the tool is failing with the following error:

```
ERROR: failed cloning GitHub repository "https://github.com/mecha-hq/images.git"
ERROR: err - cloning: invalid auth method

```
This is the minimal configuration with which I can reproduce the error:

```
name: update mecha-hq/images versions
scms:
  mecha_images:
    kind: github
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: mecha-hq
      repository: images
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      username: "{{ .github.username }}"
      branch: main
actions:
  update-deps:
    kind: github/pullrequest
    scmid: mecha_images
    spec:
      automerge: false
      mergemethod: squash
      description: update mecha-hq/images version
      labels:
        - dependencies
        - mecha
      title: "deps: update mecha-hq/images version"
```

the command I am using is:

```
updatecli diff --config example_images.yaml --values example_values.yaml --debug
```

I checked all the template variables and they are correctly injected. 

Also, **if I try to run with `repository: shellbits` instead of `repository: images`, everything works fine**.

**Both repositories are public.**

I am not sure what to look into anymore.

Thank you in advance for any pointer!

### Expected Behavior

The mecha-hq/images repository gets cloned without auth errors

### Steps To Reproduce

1. expand the attached zip file
2. fill in the values in the example_values.yaml file
3. export your GITHUB_TOKEN in your shell
4. run: updatecli diff --config example_images.yaml --values example_values.yaml --debug

[example.zip](https://github.com/user-attachments/files/19727111/example.zip)

### Environment

```markdown
Local
- OS: CachyOS, kernel 6.14.0-4-cachyos
- updatecli: 0.97.0

Github action
- https://github.com/mecha-hq/images/actions/runs/14432911239/job/40469869186
```

### Pipeline Graph

doesn't work

### Anything else?

command output:

```
+++++++++++
+ PREPARE +
+++++++++++

Loading Pipeline "example_images.yaml"
DEBUG: pipelineid undefined, we'll try to generate one
DEBUG: using pipeline name to generate the pipelineid

SCM repository retrieved: 1
DEBUG: cloning git repository: https://github.com/mecha-hq/images.git in /tmp/updatecli/github/mecha-hq/images
Enumerating objects: 628, done.
Counting objects: 100% (261/261), done.
Compressing objects: 100% (128/128), done.
Total 628 (delta 151), reused 181 (delta 114), pack-reused 367 (from 2)
ERROR: failed cloning GitHub repository "https://github.com/mecha-hq/images.git"
ERROR: err - cloning: invalid auth method


++++++++++++++++++
+ AUTO DISCOVERY +
++++++++++++++++++



++++++++++++
+ PIPELINE +
++++++++++++



###################################
# UPDATE MECHA-HQ/IMAGES VERSIONS #
###################################


ACTIONS
========

DEBUG: No target found for pipeline "update mecha-hq/images versions", skipping depends on action

=============================

SUMMARY:



✔ update mecha-hq/images versions:

Run Summary
===========
Pipeline(s) run:
  * Changed:    0
  * Failed:     0
  * Skipped:    0
  * Succeeded:  1
  * Total:      1
```

**Comment by olblak** [comment]
Mmmh interesting, I can reproduce it, and you are right using a different public GitHub repository works

**Comment by olblak** [comment]
Got it, as usual the problem is the git submodule specified on that repository.
By default, updatecli tries to clone git submodules which you can disable with  `submodules` set to `false`

```
name: update mecha-hq/images versions
scms:
  mecha_images:
    kind: github
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: mecha-hq
      repository: images
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      username: "{{ .github.username }}"
      branch: main
      submodules: false
```

Git submodules are often confusing with Updatecli and I always wonder if It should  be disabled by default
