### ISSUE TITLE
YAML parsing with go-yaml sometimes mangles unrelated objects in array

### ISSUE THREAD

**Issue by viccuad** [updatecli/updatecli#4837]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

When using a YAML target on the form:

```yaml
targets:
  updateMetadataAnnotationVersion:
    name: Update metadata.yml with new version
    kind: yaml
    scmid: "policy-repo"
    sourceid: newestGitHubDraftReleaseVersion
    disableconditions: true
    spec:
      searchpattern: true
      file: "metadata.y*ml"
      key: "$.annotations.'io.kubewarden.policy.version'"
```

The YAML parser, in addition to correctly editing that key, mangles an unrelated element string in an unrelated array, under `rules[].resources[]`.

This does not happen all the times, though.

### Expected Behavior

The YAML parser only edits the instructed key.

### Steps To Reproduce

Run the following policy (see `testdata/` for an example):
https://github.com/kubewarden/automation/tree/main/updatecli/policies/open-release-pr

### Environment

```markdown
- OS: 1.24.1 linux/amd64
- updatecli: 0.97.0
```

### Pipeline Graph

```mermaid
graph TD
    target#updateCargoTomlVersion("Update Cargo.toml, Cargo.lock with new version (shell)")
    source#newestGitHubDraftReleaseVersion(["Extract version from newest GitHub draft release from release drafter (githubrelease)"])
    source#newestGitHubDraftReleaseVersion --> target#updateCargoTomlVersion
    source#newestGitHubDraftReleaseVersion --> target#updateMetadataAnnotationVersion
    target#updateMetadataAnnotationVersion("Update metadata.yml with new version (yaml)")
    source#newestReleaseTagVersion(["Extract newest tag from newest GitHub release (githubrelease)"])
    condition#checkCargoTomlExists{"Check if Cargo.toml exists (file)"}
    condition#checkCargoTomlExists --> target#updateCargoTomlVersion
```

### Anything else?

See [here](https://github.com/kubewarden/do-not-expose-admission-controller-webhook-services-policy/pull/14) for more info.

**Comment by viccuad** [comment]
Another example: https://github.com/kubewarden/do-not-expose-admission-controller-webhook-services-policy/pull/22/commits/bb7c8c57bc8bee487cc5efb85c58806eec5aba07

**Comment by olblak** [comment]
@viccuad Another option could be to use the yamlpath engine

```
targets:
  updateMetadataAnnotationVersion:
    name: Update metadata.yml with new version
    kind: yaml
    scmid: "policy-repo"
    sourceid: newestGitHubDraftReleaseVersion
    disableconditions: true
    spec:
      engine: yamlpath
      searchpattern: true
      file: "metadata.y*ml"
      key: "$.annotations.'io.kubewarden.policy.version'"
```

The key value is probably wrong, I don't have the time to test it
