### ISSUE TITLE
Feature Request: Force quotes on a string

### ISSUE THREAD

**Issue by omissis** [updatecli/updatecli#4855]
### Is your feature request related to a problem?

I have a few cases where the yaml output removes strings from a value that I would like to avoid.
For example, I have some softwares that do not respect semver, and where the version looks like `0.8`. Yaml believes that is a number, and other processes downstream break because of this.

I also had issues with fields valued as `@local dist/tools/checkmake/0.2.2/packages`, as the library removed the quotes, but the leading `@` broke the yaml, I will see if I can reproduce this issue, too.

### Solution you'd like

maybe having a new `finalizers` property that allow to do one last round of changes after the yaml value has been generated, such as `forceQuotes`, eg:

```
targets:
  melange-yaml-1:
    name: Bump file-lint version
    kind: yaml
    sourceid: file-lint
    scmid: mecha-images
    spec:
      key: $.package.version
      file: tools/file-lint/melange.yaml
    finalizers:
        forceQuotes:
            enable: true
            style: single
```

### Alternatives you've considered

I tried playing with the transformers, but they are too early in the pipeline I believe

### Anything else?

Maybe there are some go-yaml configs that can be exposed instead?

**Comment by olblak** [comment]
I took a quick look and there are a few things you could try.

1. Using the YAML engine "yamlpath" based on  github.com/go-yaml/yaml
2. Using go templating
3. Using transformers

I don't think adding a new parameter would make things easier 

```
sources:
  default:
    name: Get 0.8
    kind: shell
    spec:
      command: echo 0.8

targets:
  a:
    kind: yaml
    spec:
      file: /tmp/values.yaml
      key: $.a
  b:
    kind: yaml
    spec:
      engine: yamlpath
      file: /tmp/values.yaml
      key: $.b
  c:
    kind: yaml
    spec:
      file: /tmp/values.yaml
      key: $.c
    transformers:
      - addprefix: '"'
      - addsuffix: '"'
  d:
    kind: yaml
    spec:
      engine: yamlpath
      file: /tmp/values.yaml
      key: $.d
    transformers:
      - addprefix: '"'
      - addsuffix: '"'
  e:
    kind: yaml
    disablesourceinput: true
    spec:
      file: /tmp/values.yaml
      key: $.e
      value: '{{ source "default" }}'

```
