### ISSUE TITLE
Feature Request: `quote` and `unquote` transformers

### ISSUE THREAD

**Issue by loispostula** [updatecli/updatecli#4869]
### Is your feature request related to a problem?

We sometime needs to resort to do such transformation:
```yaml
    transformers:
      - addprefix: '"'
      - addsuffix: '"'
```
or 
```yaml
    transformers:
      - trimprefix: '"'
      - trimsuffix: '"'
```

### Solution you'd like

Let's consolidate into a `quote` and `unquote` transformer that performs both operations atomically, improving both performance and code clarity.
