### ISSUE TITLE
Feature Request: Support Automerge for GitHub Pullrequest 

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#488]
### Is your feature request related to a problem?

Using Github PullRequest workflow is useful to get reviews and to trigger GitHub action jobs.
Sometimes we are only interested by the GitHub Action, so if tests are passing then we can safely merge the change which reduce alert fatigue for safe dependency update
 
It would be useful to automatically merge Pull Request on git repository with a lot of testing place.

### Solution you'd like

I would like to assign "auto-merge" to pullrequest created by updatecli such as in the following example 

```
pullrequests:
  helm-charts:
    kind: "github"
    scmID: "helm-charts"
    targets:
      - "helm-charts"
    spec:
      automerge: true
      labels:
        - "dependencies"
```

### Anything else?

It seems to be possible now using the Graphql API
-> https://docs.github.com/en/graphql/reference/mutations#enablepullrequestautomerge
