### ISSUE TITLE
Feature Request: Implement the source "DockerImage"

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#512]
### Is your feature request related to a problem?

I am facing a situation where the source of truth of a version is defined on a docker registry.

I am looking for a way to retrieve the latest docker image tag matching a version such as semantic versioning or regex.
At the moment we have the condition "dockerImage" which allows to test if a docker image tag exist on a docker repository.
Naturally I would use the same resource kind

### Solution you'd like

I would like to reuse the same approach than for the dockerImage condition but with the versionFilter as well to retrieve the latest docker image tag matching a version pattern.
But I am 

**Default**: Retrieve the newest docker image tag
```
    name: "Docker Image Published on Registry"
    kind: dockerImage
    spec:
      image: "updatecli/updatecli"
```

**Semver**: Retrieve the latest version matching pattern 
```
    name: "Docker Image Published on Registry"
    kind: dockerImage
    spec:
      image: "updatecli/updatecli"
      versionFilter:
          kind: semver
          pattern: "~0"
```
**Regex**: Retrieve the latest version matching regex pattern
```
    name: "Docker Image Published on Registry"
    kind: dockerImage
    spec:
      image: "updatecli/updatecli"
      versionFilter:
          kind: regex
          pattern: "0.(\d*)$"
```

### Alternatives you've considered

I have been wondering using a different resource kind than "dockerImage"
