### ISSUE TITLE
error calling source: key not defined in configuration, ArgoCD Autodiscovery multiple sources per application.yaml

### ISSUE THREAD

**Issue by paltaa** [updatecli/updatecli#5410]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Hey, about 4 months ago these errors started appearing:

```
ERROR: Pipeline "deps(helm): bump Helm chart \"aws-load-balancer-controller\" in ArgoCD manifest \"helm/dev/alb-ingress-controller/application.yaml\"" failed to update: template: cfg:5:46: executing "cfg" at <source "go">: error calling source: key not defined in configuration
ERROR: Pipeline "deps(helm): bump Helm chart \"argo-cd\" in ArgoCD manifest \"helm/dev/argocd/application.yaml\"" failed to update: template: cfg:5:46: executing "cfg" at <source "go">: error calling source: key not defined in configuration
```
This is my updatecli config and my github action:

```
# updatecli.d/default.yaml
name: Argocd Autodiscovery

# TODO: should add another pipeline with different labels for production upgrades
autodiscovery:
  # We want one PR per dependency
  groupby: individual
  actionid: default
  # scmid is applied to all crawlers
  scmid: default
  crawlers:
    argocd:
      # To ignore specific path
      ignore:
        # Ignore manifest match path "dev/*.yaml"
        - path: helm/prod/*/application.yaml

        - path: helm/*/*/application.yaml
          charts:
            "grafana-dashboards": ""
            "pacifier-patrol": ""
            "monotron": ""
        # Ignore any helm chart repository named "https://redacted.private"
        - repositories:
            - "https://redacted.private"

        # # Ignore any Helm chart named "kubewarden-crds" in manifest path "dev/*.yaml"
        # - path: dev/*.yaml
        #   charts:
        #     "kubewarden-crds": ""
      # Only accepts the same rule than ignore
      only:
       - path: helm/dev/*/application.yaml
      
scms:
  default:
    kind: github
    spec:
      owner: redacted
      username: redacted
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      repository: gitops
      branch: "main"
    
actions:
    default:
        kind: "github/pullrequest"
        spec:
            labels:
                - "dependencies"
            mergemethod: "squash"
        scmid: "default"

```

And github action:

```
name: updatecli
on:
#   release:
  workflow_dispatch:
#   push:
    # branches: [main]
#   pull_request:
#     branches: [main]
  schedule:
    # Run the first day of every month
    - cron: "0 0 1 * *"

permissions: {}

jobs:
  updatecli:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0

      - name: "Setup updatecli"
        uses: "updatecli/updatecli-action@v2"
        
      - name: "Run updatecli in dryrun"
        run: "updatecli diff --values ./updatecli.d/default.yaml"
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}

      - name: "Run updatecli"
        if: github.ref == 'refs/heads/main'
        run: "updatecli apply  --values ./updatecli.d/default.yaml"
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}
```

Any ides on what might be wrong here? Using ArgoCD Autodiscovery with some applications using multiple sources

Github Action workflow run summary:
```
Run Summary
===========
Pipeline(s) run:
  * Changed:	0
  * Failed:	28
  * Skipped:	0
  * Succeeded:	38
  * Total:	66

ERROR: ✗ 28 over 66 pipeline failed
ERROR: command failed: 28 over 66 pipeline failed
```

### Expected Behavior

Pipeline should run green and update the chart versions

### Steps To Reproduce

In description

### Environment

```markdown
- OS: Github actions ubuntu
- updatecli: actions v2
```

### Pipeline Graph

```mermaid
```
