### ISSUE TITLE
Resource File is failing when used with scmID

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The following example:

```
scms:
  scenario-1:
    kind: git
    spec:
      url: "git@github.com:updatecli/updatecli.git"
      branch: "main"

sources:
  scenario-1:
    name: "Scenario 1"
    kind: file
    scmID: scenario-1
    spec:
      file: README.md
      line: 1

```

fails with error message

```
################
# TEST GIT SCM #
################


SOURCES
=======
Validating "GIT.YAML"

default
-------
ERROR: ✗ open README.md: no such file or directory

```

### Expected Behavior

It should correctly find the FILE from the temporary location like for condition and targets

### Steps To Reproduce

Just run updatecli 

### Environment

```markdown
- OS:
- updatecli:
```
