### ISSUE TITLE
Unsupported response type from the registry quay.io: Content-Type "application/vnd.docker.distribution.manifest.v1+json" is either deprecated or unknown by updatecli.

### ISSUE THREAD

**Issue by nmasse-itix** [updatecli/updatecli#605]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Output of **updatecli diff**:

```

+++++++++++
+ PREPARE +
+++++++++++

Loading Pipeline "./updatecli.yaml"

SCM repository retrieved: 0


++++++++++++
+ PIPELINE +
++++++++++++



##################
# UPDATECLI.YAML #
##################


SOURCES
=======

tic-tsdb
--------
⚠ No GitHub Release found. As fallback Looking at published git tags
Searching for version matching pattern "latest"
✔ Github Release version "v0.0.2" found matching pattern "latest"


CHANGELOG:
----------

Release published on the 0001-01-01 00:00:00 +0000 UTC at the url https://github.com/nmasse-itix/tic-tsdb/releases/tag/untagged-b8b1342ec55f853329ce

Released v0.0.2


CONDITIONS:
===========

tic-tsdb
--------
WARNING: No username and/or password specified: trying to retrieve a token as anonymous user might not be supported or could impact the rate limiting on your network.
ERROR: Unsupported response type from the registry quay.io: Content-Type "application/vnd.docker.distribution.manifest.v1+json" is either deprecated or unknown by updatecli.

✗ condition not met, skipping pipeline

=============================

REPORTS:


- UPDATECLI.YAML:
        Sources:
                ✔ [tic-tsdb]  (kind: githubRelease)
        Condition:
                ✗ [tic-tsdb]  (kind: dockerImage)
        Target:
                - [tic-tsdb]  (kind: file)



Run Summary
===========
Pipeline(s) run:
  * Changed:    0
  * Failed:     0
  * Skipped:    1
  * Succeeded:  0
  * Total:      1
```

### Expected Behavior

updatecli should tell it will update the file **version.txt** with the latest available version (v0.0.2).

### Steps To Reproduce

1. Create **updatecli.yaml** with :

```yaml
sources:
  tic-tsdb:
    kind: githubRelease
    spec:
      owner: nmasse-itix
      repository: tic-tsdb
      token: REDACTED
conditions:
  tic-tsdb:
    kind: dockerImage
    sourceID: tic-tsdb
    spec:
      hostname: quay.io
      image: quay.io/itix/tic-tsdb
      architecture: amd64
targets:
  tic-tsdb:
    kind: file
    sourceID: tic-tsdb
    spec:
      file: version.txt
```

2. run **updatecli diff**

### Environment

```markdown
- OS: Fedora 35
- updatecli: both v0.22.3 and main branch were tried
```

### Anything else?

Oddly, this is the only image on which I get this error. 

If I try this pipeline instead:

```yaml
sources:
  photo-bot:
    kind: githubRelease
    spec:
      owner: nmasse-itix
      repository: Telegram-Photo-Album-Bot
      token: REDACTED
conditions:
  photo-bot:
    kind: dockerImage
    sourceID: photo-bot
    spec:
      hostname: quay.io
      image: quay.io/itix/photo-bot
      architecture: amd64
targets:
  photo-bot:
    kind: file
    sourceID: photo-bot
    spec:
      file: version.txt
```

It works !

```

+++++++++++
+ PREPARE +
+++++++++++

Loading Pipeline "./updatecli.yaml"

SCM repository retrieved: 0


++++++++++++
+ PIPELINE +
++++++++++++



##################
# UPDATECLI.YAML #
##################


SOURCES
=======

photo-bot
---------
Searching for version matching pattern "latest"
✔ Github Release version "1.0.6" found matching pattern "latest"


CHANGELOG:
----------

Release published on the 2021-12-14 17:51:50 +0000 UTC at the url https://github.com/nmasse-itix/Telegram-Photo-Album-Bot/releases/tag/1.0.6

Released 1.0.6


CONDITIONS:
===========

photo-bot
---------
WARNING: No username and/or password specified: trying to retrieve a token as anonymous user might not be supported or could impact the rate limiting on your network.
✔ The Docker image quay.io/itix/photo-bot:1.0.6 exists and is available.


TARGETS
========

photo-bot
---------

**Dry Run enabled**

⚠ File content for "version.txt", updated. 

--- version.txt
+++ version.txt
@@ -1 +1 @@
+1.0.6
\ No newline at end of file


=============================

REPORTS:


⚠ UPDATECLI.YAML:
        Sources:
                ✔ [photo-bot]  (kind: githubRelease)
        Condition:
                ✔ [photo-bot]  (kind: dockerImage)
        Target:
                ⚠ [photo-bot]  (kind: file)



Run Summary
===========
Pipeline(s) run:
  * Changed:    1
  * Failed:     0
  * Skipped:    0
  * Succeeded:  0
  * Total:      1
```

The outputs of curl commands are consistent with what updatecli sees:

```
$ curl -D - -s -H "Accept: application/vnd.docker.distribution.manifest.v2+json" -H "Accept: application/vnd.docker.distribution.manifest.list.v2+json" https://quay.io/v2/itix/photo-bot/manifests/1.0.6 |grep ^content-type
content-type: application/vnd.docker.distribution.manifest.list.v2+json

$ curl -D - -s -H "Accept: application/vnd.docker.distribution.manifest.v2+json" -H "Accept: application/vnd.docker.distribution.manifest.list.v2+json" https://quay.io/v2/itix/tic-tsdb/manifests/v0.0.2 |grep ^content-type
content-type: application/vnd.docker.distribution.manifest.v1+json
```

Is there an upcoming breaking change that is being A/B tested on quay.io ? I don't know... 

Any clue ?
