### ISSUE TITLE
[updatecli 0.23.x] failing to open pull request + no error reported globally

### ISSUE THREAD

**Issue by dduportal** [updatecli/updatecli#632]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

With updatecli 0.23.0 and 0.23.1, we have errors when trying to open a pull request, with the error `ERROR: 1 target(s) (updateChartVersion) failed for pullrequest "default"`.

Besides this failure, the execution of updatecli does NOT fail and does NOT report the failure, which makes it hard to detect.

### Expected Behavior

Can't be sure of the root cause error, but we have to fix updatecli so that, at least, it reports the failure, and eventually give details on the failure.

### Steps To Reproduce

* Any manifest at https://github.com/jenkins-infra/kubernetes-management/tree/56ff776b83f8677e16f8e8c9d422c7d3a7205a1f/updatecli/updatecli.d

  * In particular (a simple one):

```yaml
title: Bump aws-node-termination-handler helm chart version

scms:
  default:
    kind: github
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: "{{ .github.owner }}"
      repository: "{{ .github.repository }}"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      branch: "{{ .github.branch }}"

sources:
  lastChartVersion:
    kind: helmChart
    spec:
      url: https://aws.github.io/eks-charts
      name: aws-node-termination-handler

targets:
  updateChartVersion:
    name: "eks/aws-node-termination-handler Helm Chart"
    kind: file
    scmid: default
    spec:
      file: clusters/cik8s.yaml
      matchpattern: 'chart: eks\/aws-node-termination-handler((\r\n|\r|\n)(\s+))version: .*'
      replacepattern: 'chart: eks/aws-node-termination-handler${1}version: {{ source "lastChartVersion" }}'

pullrequests:
  default:
    kind: github
    scmid: default
    targets:
      - updateChartVersion
    spec:
      labels:
        - dependencies
        - aws-node-termination
```

* Executing the diff works as expected and succeeds to report expected change + PR:

```shell
updatecli diff --values updatecli/values.yaml --config updatecli/updatecli.d/charts/aws-node-termination-handler.yaml


+++++++++++
+ PREPARE +
+++++++++++

Loading Pipeline "updatecli/updatecli.d/charts/aws-node-termination-handler.yaml"

SCM repository retrieved: 1


++++++++++++
+ PIPELINE +
++++++++++++



########################################################
# BUMP AWS-NODE-TERMINATION-HANDLER HELM CHART VERSION #
########################################################


SOURCES
=======

lastChartVersion
----------------
✔ Helm Chart 'aws-node-termination-handler' version '0.18.1' is found from repository https://aws.github.io/eks-charts

Remark: We couldn't identify a way to automatically retrieve changelog information.
Please use following information to take informed decision

Helm Chart: aws-node-termination-handler
A Helm chart for the AWS Node Termination Handler.
Project Home: https://github.com/aws/eks-charts
Require Kubernetes Version: &gt;= 1.16-0
Version created on the 2022-04-07 17:03:20.030632404 &#43;0000 UTC

Sources:

* https://github.com/aws/aws-node-termination-handler/

* https://github.com/aws/eks-charts/



URL:

* https://aws.github.io/eks-charts/aws-node-termination-handler-0.18.1.tgz




CHANGELOG:
----------

Remark: We couldn't identify a way to automatically retrieve changelog information.
Please use following information to take informed decision

Helm Chart: aws-node-termination-handler
A Helm chart for the AWS Node Termination Handler.
Project Home: https://github.com/aws/eks-charts
Require Kubernetes Version: &gt;= 1.16-0
Version created on the 2022-04-07 17:03:20.030632404 &#43;0000 UTC

Sources:

* https://github.com/aws/aws-node-termination-handler/

* https://github.com/aws/eks-charts/



URL:

* https://aws.github.io/eks-charts/aws-node-termination-handler-0.18.1.tgz





TARGETS
========

updateChartVersion
------------------

**Dry Run enabled**

⚠ updated the [dry run] content of the file "/var/folders/2s/09szbrgn22l2tcvxz1_k34g40000gn/T/updatecli/jenkins-infra/kubernetes-management/clusters/cik8s.yaml"

--- /var/folders/2s/09szbrgn22l2tcvxz1_k34g40000gn/T/updatecli/jenkins-infra/kubernetes-management/clusters/cik8s.yaml
+++ /var/folders/2s/09szbrgn22l2tcvxz1_k34g40000gn/T/updatecli/jenkins-infra/kubernetes-management/clusters/cik8s.yaml
@@ -51,6 +51,6 @@
   - name: aws-node-termination-handler
     namespace: eks
     chart: eks/aws-node-termination-handler
-    version: 0.18.0
+    version: 0.18.1
     values:
       - "../config/ext_aws-node-termination-handler.yaml"



PULL REQUESTS
=============

[Dry Run] A pull request with kind "github" and title "[updatecli] Bump aws-node-termination-handler helm chart version" is expected.

=============================

REPORTS:


⚠ AWS-NODE-TERMINATION-HANDLER.YAML:
        Sources:
                ✔ [lastChartVersion]  (kind: helmChart)
        Target:
                ⚠ [updateChartVersion] eks/aws-node-termination-handler Helm Chart (kind: file)



Run Summary
===========
Pipeline(s) run:
  * Changed:    1
  * Failed:     0
  * Skipped:    0
  * Succeeded:  0
  * Total:      1
 
```

* Applying the change fails at the Pull Request level, despite being reported as success:

```shell
updatecli apply --values updatecli/values.yaml --config updatecli/updatecli.d/charts/aws-node-termination-handler.yaml


+++++++++++
+ PREPARE +
+++++++++++

Loading Pipeline "updatecli/updatecli.d/charts/aws-node-termination-handler.yaml"

SCM repository retrieved: 1


++++++++++++
+ PIPELINE +
++++++++++++



########################################################
# BUMP AWS-NODE-TERMINATION-HANDLER HELM CHART VERSION #
########################################################


SOURCES
=======

lastChartVersion
----------------
✔ Helm Chart 'aws-node-termination-handler' version '0.18.1' is found from repository https://aws.github.io/eks-charts

Remark: We couldn't identify a way to automatically retrieve changelog information.
Please use following information to take informed decision

Helm Chart: aws-node-termination-handler
A Helm chart for the AWS Node Termination Handler.
Project Home: https://github.com/aws/eks-charts
Require Kubernetes Version: &gt;= 1.16-0
Version created on the 2022-04-07 17:03:20.030632404 &#43;0000 UTC

Sources:

* https://github.com/aws/aws-node-termination-handler/

* https://github.com/aws/eks-charts/



URL:

* https://aws.github.io/eks-charts/aws-node-termination-handler-0.18.1.tgz




CHANGELOG:
----------

Remark: We couldn't identify a way to automatically retrieve changelog information.
Please use following information to take informed decision

Helm Chart: aws-node-termination-handler
A Helm chart for the AWS Node Termination Handler.
Project Home: https://github.com/aws/eks-charts
Require Kubernetes Version: &gt;= 1.16-0
Version created on the 2022-04-07 17:03:20.030632404 &#43;0000 UTC

Sources:

* https://github.com/aws/aws-node-termination-handler/

* https://github.com/aws/eks-charts/



URL:

* https://aws.github.io/eks-charts/aws-node-termination-handler-0.18.1.tgz





TARGETS
========

updateChartVersion
------------------
⚠ updated the content of the file "/var/folders/2s/09szbrgn22l2tcvxz1_k34g40000gn/T/updatecli/jenkins-infra/kubernetes-management/clusters/cik8s.yaml"

--- /var/folders/2s/09szbrgn22l2tcvxz1_k34g40000gn/T/updatecli/jenkins-infra/kubernetes-management/clusters/cik8s.yaml
+++ /var/folders/2s/09szbrgn22l2tcvxz1_k34g40000gn/T/updatecli/jenkins-infra/kubernetes-management/clusters/cik8s.yaml
@@ -51,6 +51,6 @@
   - name: aws-node-termination-handler
     namespace: eks
     chart: eks/aws-node-termination-handler
-    version: 0.18.0
+    version: 0.18.1
     values:
       - "../config/ext_aws-node-termination-handler.yaml"

no changed file to commit


PULL REQUESTS
=============

ERROR: 1 target(s) (updateChartVersion) failed for pullrequest "default"

=============================

REPORTS:


✔ AWS-NODE-TERMINATION-HANDLER.YAML:
        Sources:
                ✔ [lastChartVersion]  (kind: helmChart)
        Target:
                ✗ [updateChartVersion] eks/aws-node-termination-handler Helm Chart (kind: file)



Run Summary
===========
Pipeline(s) run:
  * Changed:    0
  * Failed:     0
  * Skipped:    0
  * Succeeded:  1
  * Total:      1
```

### Environment

```markdown
- OS: macOS, Ubuntu 20.04
- updatecli: 0.23.0, 0.23.1
```
