### ISSUE TITLE
Cannot execute pwsh as shell commands

### ISSUE THREAD

**Issue by jetersen** [updatecli/updatecli#660]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
TARGETS
========

default
-------

**Dry Run enabled**

The shell 🐚 command "pwsh -File ./updatecli/updatecli.d/test.ps1 2.344" exited on error (exit code 64) with the following output:
----

Usage: pwsh[.exe] [-Login] [[-File] <filePath> [args]]
                  [-Command { - | <script-block> [-args <arg-array>]
                                | <string> [<CommandParameters>] } ]
                  [-ConfigurationName <string>] [-CustomPipeName <string>]
                  [-EncodedCommand <Base64EncodedCommand>]
                  [-ExecutionPolicy <ExecutionPolicy>] [-InputFormat {Text | XML}]
                  [-Interactive] [-MTA] [-NoExit] [-NoLogo] [-NonInteractive] [-NoProfile]
                  [-OutputFormat {Text | XML}] [-SettingsFile <filePath>] [-SSHServerMode] [-STA]
                  [-Version] [-WindowStyle <style>] [-WorkingDirectory <directoryPath>]

       pwsh[.exe] -h | -Help | -? | /?

PowerShell Online Help https://aka.ms/powershell-docs

All parameters are case-insensitive.
----

command stderr output was:
----
The argument './updatecli/updatecli.d/test.ps1' is not recognized as the name of a script file. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

----
ERROR: Something went wrong in target "default" :
ERROR: Shell command exited on error.
```

### Expected Behavior

Runs the powershell script 😅 

### Steps To Reproduce

```
---
scms:
  github:
    kind: github
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: "{{ .github.owner }}"
      repository: "{{ .github.repository }}"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      branch: "{{ .github.branch }}"

sources:
  jenkinsWeekly:
    name: Get Last Jenkins Weekly Version
    kind: jenkins
    spec:
      release: weekly
      github:
        token: "{{ requiredEnv .github.token }}"
        username: "{{ .github.username }}"
conditions:
  jenkinsWeekly:
    name: Test if Jenkins weekly published
    kind: maven
    spec:
      url: "repo.jenkins-ci.org"
      repository: "releases"
      groupid: "org.jenkins-ci.main"
      artifactid: "jenkins-war"
targets:
  default:
    name: 'Update weekly version'
    sourceid: jenkinsWeekly
    kind: shell
    spec:
      command: pwsh -File ./updatecli/updatecli.d/test.ps1
    scmid: github
```

### Environment

```markdown
OS: Ubuntu 20.04
updatecli: v0.23.2
```

### Anything else?

I would like to use powershell as it has a decent way of interacting with XML while #336 #371 is still WIP

**Comment by olblak** [comment]
interesting, did you try running  updatecli with the flag `--clean=false` such `updatecli diff --config <you manifest> --clean=false --debug`

The goal is to not delete the git repository from `/tmp/updatecli` then check if you correctly have the script ./updatecli/updatecli.d/test.ps1, on the branch from that repository

**Comment by dduportal** [comment]
That definitively looks like a bug to me. I was never able to test updatecli on a Windows machine so can't be sure.

Given how I found hard to execute shell command with Go on Linux, I really do not trust my code on that area :D

**Comment by olblak** [comment]
but in this case, @jetersen mentioned that he was on Ubuntu

**Comment by jetersen** [comment]
Again my confusion is that updatecli for the shell command uses the tmp folder as a working directory. 
Which is quite confusing when developing a new script that has not been committed.

Maybe we need an option to run on the current git clone that assumes dry run.
So you can test the updatecli behavior.

**Comment by olblak** [comment]
> Again my confusion is that updatecli for the shell command uses the tmp folder as a working directory.

You are not the first one to find this behavior confusing.
We've been discussing about it a lot with @dduportal on how to improve the user experience.

Up to now, relying on a temporary directory make things safer.
**But** it's really annoying as we can't easily test manifest that modify files which are not yet available on the remote environment. At least, without commenting all the scm stuff.

The biggest challenge comes from the fact that a manifest can have multiple scm configuration that may have nothing to do with the local repository.

**Comment by olblak** [comment]
> Maybe we need an option to run on the current git clone that assumes dry run.
> So you can test the updatecli behavior.

That's part of @dduportal refactoring with https://github.com/updatecli/updatecli/issues/465

```
## New flag that ensures that the target is applied locally but the "actions" are not applied
$ updatecli apply --config manifest.yaml --values values.yaml --no-actions # Or --actions=false
```

You may send him a beer or two to motivate him ;)

**Comment by jetersen** [comment]
> You may send him a beer or two to motivate him ;)

@dduportal has not setup his GitHub sponsor 😅

**Comment by dduportal** [comment]
> > You may send him a beer or two to motivate him ;)
> 
> @dduportal has not setup his GitHub sponsor 😅

I'm the Internet Explorer of the open source: Just realizing what GitHub Sponsor exists and what is it :D

**Comment by jetersen** [comment]
I think we can close this issue and link to #465 

I have verified I am able to perform powershell scripts over here: https://github.com/jenkinsci/bom/pull/1279

FYI updatecli and the powershell script is really useful for managing pinned version.

**Comment by olblak** [comment]
> FYI updatecli and the powershell script is really useful for managing pinned version.

I think that could be a great story to publish on www.updatecli.io :) 
and a great learning experience for me

**Comment by jetersen** [comment]
Would be a better story if #754 was there! Cause right now pwsh terminal relies on process environment variables inheritance and basically I have problems accessing curl and java as well as getting the correct path to the jenkins plugin manager jar. 😓

**Comment by jetersen** [comment]
My solution ended up being simple: https://github.com/jenkinsci/bom/blob/72a2154456b19142082e63d7195b4e82a3848dcf/updatecli/generate-manifests.ps1#L118

```yaml
targets:
  jenkins:
    kind: shell
    spec:
	  command: pwsh -NoProfile -File {{ requiredEnv "GITHUB_WORKSPACE" }}/updatecli/update-jenkins.ps1
```
