### ISSUE TITLE
Feature Request: Allow disabling Helm chart version increment

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#691]
### Is your feature request related to a problem?

I am facing a situation where we want to rely on chart releaser to bump the Helm chart version but  I am still looking for the metadata such as appVersion.

### Solution you'd like

We already have a key `versionincrement` to configure how the version should be incremented. 
I would like to add "none" to the accepted values such as 

```
  noVersionInc: 
    name: Test Chart Update
    scmid: default
    kind: helmchart
    spec:
      name: chart/epinio
      file: Chart.yaml
      appversion: true
      key:  dependencies[2].version
      versionincrement: none
```

### Alternatives you've considered

I considered adding a new boolean field such as `disableversionincrement` but I think it's better to reuse `versionincrement`
