### ISSUE TITLE
Source gittag without valid scmid should trigger an error

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If no scmid is provided then running `updatecli diff --debug` show something like 

```
jenkinsgitTag
-------------
ERROR: ✗ no tag found
Pipeline "Update myfile" failed
Skipping due to:
        sources stage:  "no tag found"
```

### Expected Behavior

I would expect an error like 

```
Source "sourceID" failed due to no valid scm id "scmid" 
```

### Steps To Reproduce

```
name: Update myfile

scms:
  updatecli:
    kind: git
    spec:
      url: https://github.com/updatecli/updatecli.git
      branch: main

sources:
  jenkinsgitTag:
    name: Retrieve latest updatecli tag
    scmid: updatecli
    kind: gittag
```

### Environment

```markdown
- OS: opensuse
- updatecli: v0.25.0
```
