### ISSUE TITLE
[file resource] condition reports empty file list

### ISSUE THREAD

**Issue by dduportal** [updatecli/updatecli#709]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
CONDITIONS:
===========

testVersionInTestHarness
------------------------
✔ Content of the file "tests/asciidoctor.bats" matched the pattern "(?m:^ALPINE_VERSION=.*)"
✔ Condition on file [] passed
```

=> The line `Condition on file [] passed` is misleading as it's also written when there is an error.

### Expected Behavior

```
CONDITIONS:
===========

testVersionInTestHarness
------------------------
✔ Content of the file "tests/asciidoctor.bats" matched the pattern "(?m:^ALPINE_VERSION=.*)"
✔ Condition on file 'README.adoc' passed
```

### Steps To Reproduce

```yaml
title: "Bump Alpine Linux Version"

scms:
  default:
    kind: github
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: "{{ requiredEnv .github.owner }}"
      repository: "{{ requiredEnv .github.repository }}"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      branch: "{{ .github.branch }}"

sources:
  latestVersion:
    kind: githubrelease
    name: "Get the latest Alpine Linux version"
    spec:
      owner: "alpinelinux"
      repository: "aports" # Its release process follows Alpine's
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      versionfilter:
        kind: semver
        pattern: "~3.15"
    transformers:
      - trimprefix: "v"

conditions:
  testVersionInReadme:
    name: "Does the README.adoc have a variable ALPINE_VERSION"
    kind: file
    disablesourceinput: true
    spec:
      file: README.adoc
      matchpattern: "(?m:^:ALPINE_VERSION:.*)"
```

### Environment

```markdown
- OS: macOS, Ubuntu 22.04
- updatecli: 0.25.0
```
