### ISSUE TITLE
[file resource] targets: templatized strings with double quotes are considered syntax error

### ISSUE THREAD

**Issue by dduportal** [updatecli/updatecli#710]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```console
$ updatecli diff --values updatecli/values.yaml --config updatecli/updatecli.d/asciidoctor-bibtex.yml


+++++++++++
+ PREPARE +
+++++++++++

Loading Pipeline "updatecli/updatecli.d/asciidoctor-bibtex.yml"
ERROR: failed loading pipeline(s)
        * "updatecli/updatecli.d/asciidoctor-bibtex.yml" - yaml: line 34: did not find expected key
ERROR: ✗ no valid pipeline found
ERROR: command failed
```

### Expected Behavior

- Expected output that should not depend on type of quotes:

```console
updatecli diff --values updatecli/values.yaml --config updatecli/updatecli.d/asciidoctor-bibtex.yml


+++++++++++
+ PREPARE +
+++++++++++

Loading Pipeline "updatecli/updatecli.d/asciidoctor-bibtex.yml"

SCM repository retrieved: 1


++++++++++++
+ PIPELINE +
++++++++++++



###################################
# BUMP ASCIIDOCTOR-BIBTEX VERSION #
###################################


SOURCES
=======

latestVersion
-------------
Searching for version matching pattern "latest"
✔ Github Release version "v0.8.0" found matching pattern "latest"


CHANGELOG:
----------

Release published on the 2020-07-04 09:10:00 +0000 UTC at the url https://github.com/asciidoctor/asciidoctor-bibtex/releases/tag/v0.8.0

## Summary

This release is a continuous improvement of  0.7.

## Distribution

This release is published through [Ruby Gems](https://rubygems.org/gems/asciidoctor-bibtex)

## Enhancements

- Upgrade bibtex-ruby dependency

## Fixed Bugs

- Fix handling of texts to avoid ghost footnotes


TARGETS
========

updateReadme
------------

**Dry Run enabled**

✔ Content from file "README.adoc" already up to date
✔ All contents from 'file' and 'files' combined already up to date

=============================

REPORTS:


✔ ASCIIDOCTOR-BIBTEX.YML:
        Sources:
                ✔ [latestVersion] Get the latest Asciidoctor-Bibtex version (kind: githubrelease)
        Target:
                ✔ [updateReadme] Update the key ASCIIDOCTOR_BIBTEX_VERSION in the README.adoc file (kind: file)



Run Summary
===========
Pipeline(s) run:
  * Changed:    0
  * Failed:     0
  * Skipped:    0
  * Succeeded:  1
  * Total:      1
```

- Eventually an error telling me to not use double quotes in my YAML if using a template

### Steps To Reproduce

```yaml
---
title: "Bump Asciidoctor-Bibtex version"

scms:
  default:
    kind: github
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: "{{ requiredEnv .github.owner }}"
      repository: "{{ requiredEnv .github.repository }}"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      branch: "{{ .github.branch }}"

sources:
  latestVersion:
    kind: githubrelease
    name: "Get the latest Asciidoctor-Bibtex version"
    spec:
      owner: "asciidoctor"
      repository: "asciidoctor-bibtex"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      versionfilter:
        kind: latest
    transformers:
      - trimprefix: "v"

targets:
  updateReadme:
    name: "Update the key ASCIIDOCTOR_BIBTEX_VERSION in the README.adoc file"
    kind: file
    spec:
      file: README.adoc
      matchpattern: "(?m:^:ASCIIDOCTOR_BIBTEX_VERSION:.*)"
      content: ":ASCIIDOCTOR_BIBTEX_VERSION: {{ source `latestVersion` }}"
```

### Environment

```markdown
- OS: macOS, Ubuntu 22.04
- updatecli: 0.25.0
```
