### ISSUE TITLE
dockerImage underline within vscode with a hint to use Valid values: "dockerdigest"

### ISSUE THREAD

**Issue by smerle33** [updatecli/updatecli#714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

With this template : 

```
title: Bump Jenkinsfile_k8s for updatecli `hashicorp-tools` docker image version to lastest image release

scms:
  default:
    kind: github
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: "{{ .github.owner }}"
      repository: "{{ .github.repository }}"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      branch: "{{ .github.branch }}"

sources:
  dockerHashicorpToolsImageVersion:
    kind: githubRelease
    spec:
      owner: "jenkins-infra"
      repository: "docker-hashicorp-tools"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"

conditions:
  checkIfDockerImageIsPublished:
    name: "Check if the Docker Image is published"
    kind: dockerImage
    spec:
      image: "jenkinsciinfra/hashicorp-tools"
      architecture: amd64

targets:
  updateJenkinsfile:
    name: Update jenkinsfile_k8s file in groovy code
    kind: file
    spec:
      file: ./Jenkinsfile_k8s
      # Please note that the patterns are specified as "block scalars" (>) - https://yaml-multiline.info/ - with the last endline trimmed (-) to avoid tedious escaping of simple quotes
      matchpattern: >-
        'jenkinsciinfra/hashicorp-tools:(.*)'
      replacepattern: >-
        'jenkinsciinfra/hashicorp-tools:{{ source `dockerHashicorpToolsImageVersion` }}'
    scmid: default

pullrequests:
  default:
    kind: github
    scmid: default
    targets:
      - updateJenkinsfile
    spec:
      labels:
        - dependencies
        - hashicorp-tools
```

under VSCODE STUDIO, I got some words underline to convert to lowercase, which is fine, but I also got 
`kind: dockerImage`

with the hint : 
```
Updatecli
Source: config.json

Value is not accepted. Valid values: "dockerdigest".yaml-schema: Updatecli(1)
```

### Expected Behavior

I would expect a hint with the lowercase

### Environment

```markdown
- OS:
- updatecli:
```
