### ISSUE TITLE
Feature Request: Add SCM gittea support

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#737]
### Is your feature request related to a problem?

I would like to use updatecli to automate files stored on gittea repositories

### Solution you'd like

```
scms:
  default:
    kind: gittea
    spec:
      user: updatecli
      email: me@olblak.com
      owner: updatecli
      repository: updatecli
      token: '{{ requiredEnv "UPDATECLI_GITHUB_TOKEN" }}'
      username: '{{ requiredEnv "UPDATECLI_GITHUB_ACTOR" }}'
      branch: main
```
