### ISSUE TITLE
Shell resource don't inherit environment variable

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#749]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Scripts called by the shell resource only have access to the environment variable `DRY_RUN`. More context from the two following links

```
	// If Env is nil, the new process uses the current process's
	// environment.
```
=>  https://pkg.go.dev/os/exec#Cmd

But it's set to 
```
Env: []string{fmt.Sprintf("DRY_RUN=%v", dryRun)},
```
=> https://github.com/updatecli/updatecli/blob/main/pkg/plugins/resources/shell/target.go#L40

For example in the context of Github Action we need to inherit the updated env `PATH` based on cached tool so we can use custom command in script s. 

### Expected Behavior

This manifest https://github.com/epinio/docs/blob/main/.github/workflows/updatecli.yml should be working by using the command 

```
act workflow_dispatch -j updatecli --env "UPDATECLI_GITHUB_TOKEN=xxx" --env "UPDATECLI_GITHUB_ACTOR=yyy"
```

### Environment

```markdown
- OS: linux
- updatecli: 0.27.0
```

### Anything else?

I don't see any reason to not inherit all environment variable from the updatecli process, so I would retrieve all of them from `os.Environment` then append `DRY_RUN`

Also I am wondering if we shouldn't replace `DRY_RUN` by `UPDATECLI_DRY_RUN` to reduce the risk of collision

**Comment by olblak** [comment]
> The initial intent was to avoid exposing an enviornmental variable with a secret credential to the underlying shell script, as updatecli often might leak value unencrypted.

This worry as well, what do you think to have by default few standard variable such as `PATH` and then adding a new setting named `allowedEnvironment` so we could filter such as 

```
  docusaurus:
    kind: shell
    name: "Set latest docusaurus version"
    scmid: default
    sourceid: epinioSubVersion
    spec:
      # epinio source value is automatically added to the command as a parameter
      command: "./updatecli/scripts/docusaurus.sh"
      environments:
          - name: "PATH"
            inherited: true
          - name: "CUSTOM_VARIABLE"
            value: "custom_value"
```

The settings would be 

```
type environments struct {
      // name defines the environment variable name
      Name string
      // value defines the environment variable value for a specific name
      Value string
      // inherit defines if the default value is retrieve from the Updatecli process
      Inherit bool
 }
```
