### ISSUE TITLE
Feature Request: Automate Helm Chart Update

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#761]
### Is your feature request related to a problem?

Up to now we used Updatecli to define tailored update scenarios. I am now looking to automatically detected those common scenarios. 
One of them is:

1. Search recursively all Chart.yaml in a specific directory/git repository
2. Identify all chart dependencies 
3. Generate appropriate Updatecli manifest and then run them right away 

```
name: <chart_name>-<dependency_name>
sources:
    <dependency_name>:
        name: Get latest "<dependency_name>" Helm Chart Version
        kind: helmchart
        spec:
            name: <dependency_name>
            url: <dependency_url>
conditions:
    <dependency_name>:
        name: Ensure dependency "<dependency_name>" is specified
        kind: yaml
        spec:
            file: .chart/<chart_name>/Chart.yaml
            key: dependencies[2].name
            value: <dependency_name>
        disablesourceinput: true
targets:
    <dependency_name>:
        name: Bump chart dependency "<dependency_name>" in Chart "<chart_name>"
        kind: helmchart
        spec:
            file: Chart.yaml
            key: dependencies[2].version
            name: chart/<dependency_name>
            versionincrement: minor
        sourceid: <dependency_name>
```

### Solution you'd like

I would like to be able to run the following command 

```
# Updatecli should be able to identify helm chart 
updatecli diff

#Updatecli should be able to apply helm chart update
updatecli apply
```

The flag `--disable-auto` would disable the `auto-guessing` feature

### Anything else?

For a more global discussion https://github.com/updatecli/updatecli/discussions/755
The auto feature would also greatly benefit from https://github.com/updatecli/updatecli/issues/716

**Comment by lemeurherve** [comment]
Related: https://github.com/updatecli/updatecli/issues/409

**Comment by olblak** [comment]
> Related: #409



> Related: #409

I am getting there :)

**Comment by olblak** [comment]
Now that the [autodiscovery](https://github.com/updatecli/updatecli/issues/761) is ready, I can have a look to this issue if needed.
Considering that there is no way to clearly identify Helmfile configuration, I am not considering the helmfile crawler to be running by default. Instead we'll need to enable it using a configuration.

So proposed Updatecli manifest
```
# A scm configuration can be specified so Updatecli browse the git repository content.
scms:
    default:
        kind: github
        spec:
        # ...
pullrequests:
    default:
       kind: github
       spec:
       # ....

autodiscovery:
     # Optional configuration to specified the scm configuration used in generated manifest
     scmid: 
     # Optional configuration to specified the pullrequest configuration used in generated manifest
     pullrequestid: 

     crawlers:
         helmfile:
            # default false
            enabled: true

            # Optional, mutually exclusive with only
            ignore:
              - path: <specifies path to ignore>

            # Optional, mutually exclusive with ignore
            only:
              - path: <only explore this path>

            # OptionDefault scm directory or local if nothing specified
            rootdir: <override directory to analyze>
```

The rule would be 
If we find a yaml file with the following content

```
repositories:
    - name: example
      url: https://mychart

releases:
    - chart: example/mychart
      version: 1.0.0
```

Then we generate the manifest

```
title: "Bump {{ helmChart Name }} Helm Chart Version"

# if `scmid` is specified in autodisccovery configuration
scms:
  {{ scmid }}:
    kind: github
    spec:
      {{ scmid spec }}

sources:
  {{ chartName }}:
    name: Get latest {{ chartName }} version
    kind: helmchart
    spec:
      url: {{ chartRepositoryUrl }}
      name: {{ chartName }}

conditions:
  # Extra protection in case the target file changed between the detection and apply
  {{ chartName }}:
    name: "Ensure {{ chartName }} chart is specified"
    kind: yaml
    scmid: default
    spec:
      file: {{ filename }}
      key: {{ identified_key }}
      value: {{ repositoryNAme }}/{{ chartName }

targets:
  {{ chartName }}:
    name: "Update {{ chartName }} chart version"
    kind: yaml
    scmid: default
    spec:
      file: {{ filename }}
      key: {{ identified_key }}

# If pullrequestid is specified in autodiscovery configuration`
pullrequests:
  default:
    kind: github
    scmid: {{ scmID }}
    spec:
      labels:
        - dependencies
        - accountapp

```
