### ISSUE TITLE
Feature Request: Allow for single generic manifest 

### ISSUE THREAD

**Issue by hoshsadiq** [updatecli/updatecli#765]
### Is your feature request related to a problem?

We have a monorepo with many terraform workspaces that refer to a git repo as a module. It would be nice to be able to create a single manifest that will upgrade based by just indiscriminately upgrading that tag it's referring to.

In my use case, I have a single repo that contains terraform modules and each module is tagged separated, e.g.:

```
$ git tag -l
service_a/1.0.0
service_a/1.0.1
service_b/1.1.0
service_b/1.2.0
```

Then we have the main terraform repo that has e.g. the following two workspaces:
```
# workspaces/service_a/main.tf
module "mymod" {
    source = "git@github.com:myorg/tfmodules//service_a?ref=service_a/1.0.0"
}


# workspaces/service_b/main.tf
module "mymod" {
    source = "git@github.com:myorg/tfmodules//service_b?ref=service_b/1.1.0"
}
```

Currently the only way to upgrade both of those is to have two separate manifests where the source is as follows:
```
# workspaces/service_a/aupdatecli.yaml
sources:
  tfModules:
    kind: gittag
    scmid: tfModules
    spec:
      versionfilter:
        kind: regex
        pattern: "service_a/.*"


# workspaces/service_b/aupdatecli.yaml
sources:
  tfModules:
    kind: gittag
    scmid: tfModules
    spec:
      versionfilter:
        kind: regex
        pattern: "service_b/.*"
```

If you don't have the manifest separated, the file `service_a/main.tf` will be upgraded to `service_b/1.1.0`, where it should only be upgraded to `service_a/1.0.1`.

Having multiple files is probably fine if your repo has a few workspaces, but starts getting out of control when you have too many.

### Solution you'd like

[Renovate](https://docs.renovatebot.com/modules/versioning/#regular-expression-versioning) manages this use case using the capture groups.

You can define a capture group called `compatibility` which will ensure that any new version matches that. So the regex `(?P<compatibility>.*/).*` will match different for each of the above tf files. For the first one, it will match essentially group `service_a/*` but won't include `service_b/*`.

Ideally I want to have single manifest that can I point to and it will upgrade all the files it finds.

### Alternatives you've considered

N/A.

### Anything else?

I tried to implement the `compatibility` capture group, but it seems update cli would need some significant refactoring.
