### ISSUE TITLE
SCM cache get cleaned every time

### ISSUE THREAD

**Issue by gionn** [updatecli/updatecli#788]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After adding different scms, I noticed that running updatecli was taking more and more time and network usage is always high (20 MB/s)

A workaround to make updatecli running fast again is by adding an explicit `directory` config:

```yml
scms:
  myRepo:
    kind: git
    spec:
        url: https://github.com/myorg/myrepo.git
        branch: master
        directory: /tmp/myrepo
```

I checked $TMPDIR/updatecli contents between updatecli execution and it looks like all the git repos get wiped at the end of updatecli execution

### Expected Behavior

updatecli should be fast on the following runs involving multiple git repos

### Environment

```markdown
- OS: MacOS 12.4
- updatecli: v0.29.0
```
