### ISSUE TITLE
Semantic Version filter drop "v" prefix

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#803]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When parsing version using semantic version, updatecli drop the v prefix such as 

```
######################
# BUMP VENOM VERSION #
######################


SOURCES
=======

latestVersion
-------------
Searching for version matching pattern "*"
✔ Github Release version "1.0.1" found matching pattern "*"
```

### Expected Behavior

It should return 

```
######################
# BUMP VENOM VERSION #
######################


SOURCES
=======

latestVersion
-------------
Searching for version matching pattern "*"
✔ Github Release version "v1.0.1" found matching pattern "*"

```

### Steps To Reproduce

`updatecli diff --confeig updatecli/updatecli.d/venom.yaml `

### Environment

```markdown
- OS: linux
- updatecli: v0.29.0
```

**Comment by hervelemeur** [comment]
Note, we're using semver filter specially for dripping this "v" in some cases

**Comment by dduportal** [comment]
> ### Is there an existing issue for this?
> 
>     * [x]  I have searched the existing issues
> 
> 
> ### Current Behavior
> 
> When parsing version using semantic version, updatecli drop the v prefix such as
> 
> ```
> ######################
> # BUMP VENOM VERSION #
> ######################
> 
> 
> SOURCES
> =======
> 
> latestVersion
> -------------
> Searching for version matching pattern "*"
> ✔ Github Release version "1.0.1" found matching pattern "*"
> ```
> 
> ### Expected Behavior
> 
> It should return
> 
> ```
> ######################
> # BUMP VENOM VERSION #
> ######################
> 
> 
> SOURCES
> =======
> 
> latestVersion
> -------------
> Searching for version matching pattern "*"
> ✔ Github Release version "v1.0.1" found matching pattern "*"
> ```
> 
> ### Steps To Reproduce
> 
> `updatecli diff --confeig updatecli/updatecli.d/venom.yaml `
> ### Environment
> 
> ```gfm
> - OS: linux
> - updatecli: v0.29.0
> ```
> 
> ### Anything else?
> 
> _No response_

I've always thought it was expected ?

**Comment by olblak** [comment]
It wasn't initially intended and to be honest I thought it was more a technical limitation of the semver library that we are using.
I am open to suggestion here

**Comment by olblak** [comment]
> Note, we're using semver filter specially for dropping this "v" in some cases

I think it would be better to use the transformers `trimprefix`

**Comment by hervelemeur** [comment]
Sure, that was just a note, it won't be difficult to fix :)

![](https://imgs.xkcd.com/comics/workflow_2x.png)

**Comment by olblak** [comment]
I am going to move forward with this issue as it's a blocker for my autodiscovery :)

**Comment by dduportal** [comment]
> I am going to move forward with this issue as it's a blocker for my autodiscovery :)

Ping @hervelemeur we'll have to block updates of updatecli: as soon as this PR is merged, almost all our manifests will be broken :'(

**Comment by dduportal** [comment]
@olblak I'm not really a huge fan of this change. Could you describe the "blocker" (it's not obvious on first sight)

**Comment by hervelemeur** [comment]
As I see it, either it's a breaking change, or either a flag (disabled by defaut) is added to allow this behavior change.

**Comment by olblak** [comment]
> @olblak I'm not really a huge fan of this change. Could you describe the "blocker" (it's not obvious on first sight)

 I'll take some time tomorrow to answer and I'll hold on 0.30.0 release until we find an agreement

**Comment by olblak** [comment]
The reason why I started thinking about this issue is, now that I am working on "autodiscovery" feature. I need to be able to retrieve an information from a source in a reliable way. And, sometimes I need to be able to transform that information.
In the context of Updatecli we have the "source" concept which allows us to retrieve an information and we have the "transformer" concept which allow us to change that information.

As a reminder the autodiscovery parses specific files to generate Updatecli manifest based on what it could detect.

So let's take the following docker-compoose.yaml example

```
version: '2.2'

services:
    mariadb:
      image: ghcr.io/epinio/epinio-server:v0.3.6
      expose:
        - "3306"
```

The generated manifest looks something like

```
title: Get latest epinio-server docker image
sources:
    mariadb:
        image: ghcr.io/epinio/epinio-server
        versionfilter:
            kind: semver
targets:
    docker-compose:
        kind: yaml
        disablesourceinput: true
        spec:
            file:: docker-compose.yaml
            key: services["mariadb"].image
            value: ghcr.io/epinio/epinio-server:{{ source "mariadb" }}

```

I want to retrieve the latest available tag for the mariadb docker image, if we use the parsed version (which drop the v), then we would end up in a broken docker-compose file as the tag retrieved would be 1.1.0 instead of "v1.1.0".
As I said the source information must be reliable.

In this case the transformer is pretty useless because we wouldn't automatically know if we need to add a "v" or not. That the goal of the source to tell me the real value.

Differently said, considering that the source information is supposed to retrieve the correct version, I would expect the dockerimage tag "v1.1.0" to be returned

This PR  https://github.com/updatecli/updatecli/pull/802/files

Is changing the behavior for the resources "gitea/*","githubrelease","gittag" to align with the dockerimage behavior.
Is this PR critical for now? Well not as much as dockerimage but I think it would be better to be consistent and more we wait and more manifests will need to be updated.

To me the biggest concern is changing the "githubrelease" behavior as it means that I also have to change manifest in quite few places.

I see different outcome

**Option 1**

As Herve suggested, I introduce a new flag "originalversion" set to false by default. such as

```
targets:
  goWorkflow:
    name: 'Bump Venom version to {{ source "latestVersion" }}'
    kind: file
    spec:
      file: .github/workflows/go.yaml
      matchpattern: 'VENOM_VERSION: .*'
      content: 'VENOM_VERSION: {{ source `latestVersion` }}'
      originalversion: false
    scmid: default
```

if set to false we display a warning message such as

> WARNING: The semantic version values retrieved from githubrelease will soon stop dropping the "v" if one specified in the github release tag. Please adapt your manifest to this new behavior and then set `originalVersion` to true to validate that you are manifest is compatible with the new behavior. 

Then in a future release, we'll officially switch to the new behavior and then remove the parameter "originalVersion"  when it's not needed anymore.

This warning will only be displayed for "gittag" and "githubreleas" as those two resources are the only one being affected by this change. the "dockerimage" and "gitea/*" haven't be released yet.

**Option 2**

We don't change the githubrelease and gittag behavior and we start seeing a different behavior between older and newer plugins.

**Option 3**

I am totally wrong, and I am now in a local optimum.

**Comment by olblak** [comment]
I am reopening this issue as it appears we need more discussions.
I stand ready to revert this https://github.com/updatecli/updatecli/pull/802 pullrequest or implement anotther one

**Comment by dduportal** [comment]
Thanks for the explanations and the work on this. i'm a bit late to the party, but I got some points (happy to discuss it in direct):

- Your audit of the problem (the source should be the "real string" and not transformed) is absolutly true. I initially slowed down in order to get a migration path that would not break manifests on the next version. But the goal is a good one (I want to acknowledge that :) ).

- Considering the long term goal of "source is the real string found on the remote system such as the GitHub release or Git tag":
  - The default for semver should be *without* the `v`. The rationale is that the official semantic version clearly states that the `v` prefix is not valid: https://semver.org/#is-v123-a-semantic-version. That would make the behavior less eratic (e.g. not changing the source as your request)
  - However, since the usage of the prefix `v` is quite common, we could introduce an attribute to the semver versionFilter to include the `v` prefix in the research. By doing so, the user would *explicitly* enable the behavior (and the source would keep the `v`)

  - For instance with ovh/venom, by default, should not return any version because there is not strict semantic version in the release list:
    
    ```yaml
      sources:
        latestVersion:
          name: Get latest Venom release
          kind: githubrelease
          spec:
            owner: ovh
            repository: venom
            versionfilter:
              kind: semver
    ```

  - But end suer could enable the tolerated behavior with the following:

    ```yaml
      sources:
        latestVersion:
          name: Get latest Venom release
          kind: githubrelease
          spec:
            owner: ovh
            repository: venom
            versionfilter:
              kind: semver
              addprefix: "v"
    ### latestVersion == v1.0.1 
    ```

**Comment by dduportal** [comment]
About the proposed attribute `keeporiginalversion`, if we consider the "prefix v not dropped if present in the found tags" that I understand is on the main branch (and ready to ship for 0.30.0):

```yaml
targets:
  goWorkflow:
    name: 'Bump Venom version to {{ source "latestVersion" }}'
    kind: file
    spec:
      file: .github/workflows/go.yaml
      matchpattern: 'VENOM_VERSION: .*'
      content: 'VENOM_VERSION: {{ source `latestVersion` }}'
      originalversion: false
    scmid: default
```

I don't see the difference with doing:

```yaml
targets:
  goWorkflow:
    name: 'Bump Venom version to {{ source "latestVersion" }}'
    kind: file
    sourceid: latestVersion
    transformers:
      - addprefix: "v"
    spec:
      file: .github/workflows/go.yaml
      matchpattern: 'VENOM_VERSION: .*'
      content: 'VENOM_VERSION: {{ source `latestVersion` }}'
    scmid: default
```

Did I miss something?
