### ISSUE TITLE
Feature Request: Add OCI registry support to helm resource

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#811]
### Is your feature request related to a problem?

Helm now support OCI registry as a way to store helm package.
Considering that Updatecli already support OCI registry in the dockerimage resource. I should be straightforward to add OCI registry support to the helm chart as well

### Solution you'd like

```
sources:
  kubed:
    name: "Get Latest Helm Chart version"
    kind: "helmchart"
    spec:
      url: "oci://localhost:5000/helm-charts/mychart"
```

So if url start with "oci//" then we know we are facing an oci registry

### Anything else?

https://helm.sh/docs/topics/registries/
