### ISSUE TITLE
Cannot get repo from enterprise github

### ISSUE THREAD

**Issue by gerardsegarra** [updatecli/updatecli#854]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm trying to configure an enterprise version of github and it keeps giving the error:
`ERROR: err - authentication required` and
`something went wrong in target "external-secrets" : "repository does not exist"`.

I've tried giving more permissions to the PAT, but from the documentation it's not clear what permissions should the PAT have or the format of the username.

### Steps To Reproduce

```
---
title: "Bump external-secrets version"
# Define git repository configuration to know where to push changes
scms:
  default:
    kind: "github"
    spec:
      # user: "{{ .github.team.user }}"
      # email: "{{ .github.team.email }}"
      owner: "{{ .github.team.owner }}"
      repository: "{{ .github.team.repository }}"
      token: "{{ requiredEnv .github.team.token }}"
      username: "{{ .github.team.username }}"
      # branch: "{{ .github.team.branch }}"
      url: "{{ .github.team.url }}"

# Defines where we get source values
sources:
  external-secrets:
    name: Get latest "external-secrets" Helm Chart Version
    kind: helmchart
    spec:
        name: external-secrets
        url: https://charts.external-secrets.io

targets:
  external-secrets:
    name: "External secrets"
    kind: "helmchart"
    scmid: "default"
    sourceid: "external-secrets"
    spec:
      file: apps/values.yaml
      key: external_secrets.source.targetRevision
      name: owner/repo
      versionincrement: minor
```

Run `updatecli diff --config updatecli/updatecli.d --values updatecli/values.yaml --debug`

And the out put says
```
SCM repository retrieved: 1
ERROR: err - authentication required
```

But running `git clone https://USERNAME:PAT_TOKEN@github.x_company.com/owner/repo` works.

### Environment

```markdown
- OS: macos 12
- updatecli: 0.33.0
```

### Anything else?

Thank you all in advance :D
