### ISSUE TITLE
Dynamic PR title isn't updated

### ISSUE THREAD

**Issue by lemeurherve** [updatecli/updatecli#866]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When setting a `pullrequest.title` with a dynamic value like the source, the initial title isn't changed while the PR body is updated.

Ex: https://github.com/jenkins-infra/kubernetes-management/pull/2870
<img width="887" alt="image" src="https://user-images.githubusercontent.com/91831478/189953667-b90259e6-7f03-4d32-a0c8-14bc1dd41b25.png">

### Expected Behavior

The PR title is updated on every pull request update.

### Steps To Reproduce

Example manifest: https://github.com/jenkins-infra/kubernetes-management/blob/06efa37c1f9d3349f28b9c6e0eb3611d8422aebe/updatecli/updatecli.d/charts/artifact-caching-proxy.yaml

```yaml
title: "Bump `artifact-caching-proxy` helm chart version"

scms:
  default:
    kind: github
    spec:
      user: "{{ .github.user }}"
      email: "{{ .github.email }}"
      owner: "{{ .github.owner }}"
      repository: "{{ .github.repository }}"
      token: "{{ requiredEnv .github.token }}"
      username: "{{ .github.username }}"
      branch: "{{ .github.branch }}"

sources:
  lastChartVersion:
    kind: helmchart
    spec:
      url: https://jenkins-infra.github.io/helm-charts
      name: artifact-caching-proxy

targets:
  updateChartVersion:
    name: "Update the chart version for artifact-caching-proxy"
    kind: file
    scmid: default
    spec:
      files:
        # TODO:
        # - clusters/cik8s.yaml
        - clusters/doks.yaml
        - clusters/prodpublick8s.yaml
      matchpattern: 'chart: jenkins-infra\/artifact-caching-proxy((\r\n|\r|\n)(\s+))version: .*'
      replacepattern: 'chart: jenkins-infra/artifact-caching-proxy${1}version: {{ source "lastChartVersion" }}'

pullrequests:
  default:
    kind: github
    scmid: default
    title: Bump `artifact-caching-proxy` helm chart version to {{ source `lastChartVersion` }}
    targets:
      - updateChartVersion
    spec:
      labels:
        - dependencies
        - artifact-caching-proxy
```

### Environment

```markdown
- OS: infra.ci.jenkins.io
- updatecli: v0.33.0
```
