### ISSUE TITLE
updatecli is messing with indents 😓

### ISSUE THREAD

**Issue by jetersen** [updatecli/updatecli#89]
**Describe the bug**
after a `updatecli apply` it messes with indents on a list.

**To Reproduce**

`updatecli.d/argocd.tpl`
```yaml
source:
  kind: githubRelease
  spec:
    owner: "argoproj"
    repository: "argo-cd"
    token: "{{ requiredEnv .github.token }}"
    username: "{{ .github.user }}"
    version: "latest"
targets:
  argocd:
    name: argo-cd
    kind: yaml
    prefix: https://github.com/argoproj/argo-cd/manifests/cluster-install?ref=
    spec:
      file: argocd/kustomization.yaml
      key: bases[0]
    scm:
      github:
        user: "{{ .github.user }}"
        email: "{{ .github.email }}"
        owner: "owner"
        repository: "repo"
        token: "{{ requiredEnv .github.token }}"
        username: "{{ .github.username }}"
        branch: "master"
```
`argocd/kustomization.yaml`
```yaml
bases:
- https://github.com/argoproj/argo-cd/manifests/cluster-install?ref=v1.6.1
resources:
- certificate.yaml
- argocd-ingress-webhook.yaml
- appprojects/core-services.yaml
- appprojects/env-proxy.yaml
- appprojects/system-services.yaml
patches:
- argocd-service.yaml
- argocd-cm.yaml
- argocd-rbac-cm.yaml
```

**Expected behavior**
only the bases line is updated without touching indents as we are trying to follow a style.

**Screenshots**
![image](https://user-images.githubusercontent.com/1661688/90513316-b9965000-e15f-11ea-8644-6254b81598ae.png)

**Version (please complete the following information):**
 - OS: linux
 - Version v0.0.20
