### ISSUE TITLE
Uwanted changes applied to YAML targets

### ISSUE THREAD

**Issue by jamiezieziula** [updatecli/updatecli#903]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I run `updatecli apply` it works mostly as expected. However, it is performing some amount of linting functionality on my `yaml` files.  Specifically:
- it is removing top level `---` from my files
- removes double spaces between code and comments
- removes subsequent manifests if my yaml file contains more than one

### Expected Behavior

I wouldn't expect any linting behavior to be applied, or the ability to disable it.

### Steps To Reproduce

run `updatecli apply` with the following updatecli manifest.yaml specified:
```
sources:
  istio-gateway:
    kind: helmchart
    spec:
      url: "https://istio-release.storage.googleapis.com/charts"
      name: "gateway"
      version: "1.*.*"
    sourceid: istio-gateway
conditions: {}
targets:
  gateway:
    name: bump chart dependencies
    kind: yaml
    spec:
      file: "gateway.yaml"
      key: "spec.chart.spec.version"
    sourceid: istio-gateway
```
on the below istio manifest file.  The dashes & secondary manifest will be removed.
```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gateway
  namespace: istio-ingress
spec:
  interval: 5m
  chart:
    spec:
      chart: gateway
      version: 1.15.0
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      interval: 5m
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway
  namespace: istio-ingress
spec:
  selector:
    istio: gateway
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - "*"
      tls:
        credentialName: tls
        mode: SIMPLE
```

### Environment

```markdown
- OS: Mac Monterey & ubuntu-latest in GitHub Actions
- updatecli: 0.34.0
```
