### ISSUE TITLE
Accessing yaml keys with `.` in the name fails

### ISSUE THREAD

**Issue by jamiezieziula** [updatecli/updatecli#904]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I would like to be able to access a `key` in a `yaml` target that contains periods - i.e. 
```
key: "spec.values.labels.service.istio.io/canonical-revision"
```
but this throws an error:
```
ERROR: something went wrong in target "helm-chart-label" : "✗ cannot find key 'spec.values.labels.service.istio.io/canonical-revision' from file 'gateway.yaml'"
```

I tried several other options trying to escape the periods but nothing seems to work:
```
"spec.values.labels.service.istio.io/canonical-revision"
"spec.values.labels.'service.istio.io/canonical-revision'"
"spec.values.labels.service\.istio\.io/canonical-revision"
```

### Expected Behavior

I should be able to pass label names or other strings to the yaml key 

### Steps To Reproduce

updatecli manifest file
```
targets:
  helm-chart-label:
    name: bump chart dependencies
    kind: yaml
    spec:
      file: "gateway.yaml"
      key: "spec.values.labels.service.istio.io/canonical-revision"
    sourceid: gateway
```
gateway.yaml
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gateway
spec:
  values:
    labels:
      service.istio.io/canonical-revision: "1.15.0"
```

### Environment

```markdown
- OS: 12.3.1
- updatecli: v0.34.0
```

**Comment by olblak** [comment]
Thanks for reporting this, it's indeed a valid usecase and I would expect `"spec.values.labels.service\.istio\.io/canonical-revision"` to work. I'll have a look

**Comment by olblak** [comment]
While doing some validation before releasing the current fix, the following snippet works

```
targets:
  helm-chart-label:
    name: bump chart dependencies
    kind: yaml
    disablesourceinput: true
    spec:
      file: "/tmp/gateway.yaml"
      key: 'spec\.values\.labels\.service\.istio\.io/canonical-revision'
      value: "test"

```

But it's important to notice that for the escaping to work in Updatecli the yaml value must be single quote otherwise the escaping charactere is used to escape yaml special characters
