### ISSUE TITLE
Unable to create separate branches/PRs for different targets/scms/PRs

### ISSUE THREAD

**Issue by JayDoubleu** [updatecli/updatecli#914]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Updatecli will push each target changes as commits into a single branch and open single pull request.

### Expected Behavior

Updatecli should push each target changes as single commit into a separate branch and open a pull request for each of the targets.

### Steps To Reproduce

1. `git clone git@github.com:JayDoubleu/updatecli_pr_test.git`
2. `cd updatecli_pr_test`
3. `export UPDATECLI_GITHUB_ACTOR="xxx"`
4. `export UPDATECLI_GITHUB_TOKEN="ghp_xxx"`
5. `updatecli apply --debug updatecli.yaml --clean --debug`

### Environment

```markdown
- OS: golang 1.19.1 linux/amd64
- updatecli: 0.33.3
```

**Comment by olblak** [comment]
Thanks for the reporting this issue, your feedback is very valuable.
We are currently thinking about refactoring the SCM part but I must admit we don't have any ETA
We gathered our thoughts in https://github.com/updatecli/updatecli/issues/465

For now , we use one manifest per pipeline such as in [updatecli.d](https://github.com/updatecli/updatecli/tree/main/updatecli/updatecli.d)

**Comment by alexagriffith** [comment]
just ran into this issue - would be great to have this feature

**Comment by alexagriffith** [comment]
any suggested workaround that doesn't involved many files? I have a list of about 20 version bumps I do in one repo for a YAML file to deploy clusters - its not very helpful for me to have one PR for many updates, I need them to be separate because they need to be merged one at a time

**Comment by alexagriffith** [comment]
> 

this is at the top of your .tpl? or is this a bash file that generates multiple tpl files?

**Comment by alexagriffith** [comment]
> 

can you show me what your bash script looks like? that would help me a lot. thank you for helping me on this!

**Comment by olblak** [comment]
Thanks @JayDoubleu for sharing your workaround. As far as I know, at the moment it's the only one that I am aware of. So using something like 

```
name: Example
pipelineid: '{{ requiredEnv "CURRENT_ITER_ENVIRONMENT" }}'
scms:
   ...
sources:
   ...
```

Then you could have a bash script such as 

```
  export CURRENT_ITER_ENVIRONMENT=xxx
  updatecli apply --config updatecli.d/manifest.yaml

  export CURRENT_ITER_ENVIRONMENT=yyy
  updatecli apply --config updatecli.d/manifest.yaml 

# Or a bash loop if a lot of variables
```
I saw some project, where they leverage GitHub Action matrix to execute the same updatecli command with different environment variable value.

> this is at the top of your .tpl? or is this a bash file that generates multiple tpl files?

Assuming your .tpl is still a valid yaml file  then I would suggest switching to a `.yaml` or `.yml` extension and put the manifest in the directory named "updatecli.d" you'll get validation and auto-completion for free from any IDE that support jsonschema store such as vscode or goland.

> It's incredibly ugly so I also can't wait for this to be addressed.

Lately I have been exploring different approach to solve a few of the current scm UX issues.

But to solve this particular problem, I am thinking of the following approaches:

**One actions per change** 

This approach is the one envisioned on https://github.com/updatecli/updatecli/issues?q=is%3Aissue+is%3Aopen+actions
 
Having to write one action per target will probably be very lengthy. I must admit we are moving slowly on that area due to various reason but mainly lack of time.

**pipelineby**

Adding a new parameter at the same level than `pipelineid` that would allow to group subpipeline based on criteria. 
The criteria that I can think of are `all`,`source`,`target` where:
*  `all` is the current behavior. One per pipeline
* `target` would mean one sub pipeline per target definition
* `source` would mean one sub-pipeline per source definition.

such as:
```
name: My pipeline example
pipelineid: xxx
# Pipelineby could accept one of ["all","source","target"]
pipelineby: target
sources:
  ...
targets:
  ...
```

this approach could be implemented with limited effort and could be compatible with the multiple action scenarios"


**Allow global definition**
https://github.com/updatecli/updatecli/issues/430

I did several POC but I have some concern by the complexity of maintaining and debugging pipeline using global setting. For larger project, I think I would prefer working on adding support for Cluelang which has a better composition approach.

**Comment by alexagriffith** [comment]
awesome thanks - one thing I did for now was keep the tpl and wrote a bash script that creates a new file per PR I want and  prepends the set the values to the tpl file and renames it according the the values. 

for example my bash script inserts 
```
{{ $name := "a" }}
{{ $phase := "b" }}
{{ $stier := "c" }}
{{ $ttier := "d" }}
```

at the top of the tpl file and renames the file based on name, etc values. so that also seems to work. The tpl template inserts the values based on the prepended lines. I iterate over my list of values, it creates ~40 files which is a lot but at least I get the output I want now. 

for example, my bash file is like 

```
for n in ${!appNames[@]}; do
  for s in ${!sourceTiers[@]}; do 
    VARS=$(cat <<-END
{{ \$name := "${appNames[$n]}" }}
{{ \$phase := "app" }}
{{ \$stier := "${sourceTiers[$s]}" }}
{{ \$ttier := "${targetTiers[$s]}" }}
)
    echo "$VARS"  > $templateDir/${appNames[$n]}-app-${targetTiers[$s]}.tpl
    cat update-templates/deploy-configs.tpl >> deploy-configs/${appNames[$n]}-app-${targetTiers[$s]}.tpl
  done 
done
```


thanks for sharing your solutions as well and helping me out!

**Comment by olblak** [comment]
I am currently wondering the relation between between scm, target, and action 

At the moment, one pipeline must have one action per scm. We can have different pipeline if same action is bound to multiple scm such as
```mermaid
flowchart LR
    scma -.-> targeta
    sourcea -.-> targeta
    scmb --> targetb
    sourcea --> targetb
    targeta -.-> actiona
    targetb --> actiona
```
dotted link is one pipeline 
plain link is the second pipeline

The reason is the working branch named is generated by the pipelineID, and we can only have one pipelineID per manifest but nothing prevent us to have the same working branch from different git repositories, hence why the diagram would work

To be able to have different pipeline based on the scm, I could expose a new parameter directly from the action which would default to pipelineid.

```mermaid
flowchart LR
    scma -.-> targeta
    sourcea -.-> targeta
    scmb --> targetb
    sourcea --> targetb
    targeta -.-> actiona
    targetb --> actionb

```

**Comment by olblak** [comment]
While I didn't make major progress on this issue, I want to share a workaround using go template loop with a map or array specified via a values.yaml file

Example

Assuming we want to run `updatecli apply --values values.yaml --config manifest.tpl`

<details><summary>values.yaml</summary>

```
apps:
  redis:
    image: redis
    tagfilter: '^(\d*).(\d*)-alpine$'

  mariadb:
    image: mariadb
    versionfilter:
      kind: semver
      pattern: '*' 

  nextcloud:
    image: nextcloud
    versionfilter:
      kind: semver

  keycloak:
    image: quay.io/keycloak/keycloak
    versionfilter:
      kind: semver

  postgresql:
    image: postgres
    tagfilter: '^(\d*).(\d*)$'
    versionfilter:
      kind: semver

  rabbitmq:
    image: rabbitmq
    tagfilter: '^(\d*)\.(\d*)\.(\d*)-management$'
    versionfilter:
      kind: semver
      # for the semver constraint to work, we must explicitely mention
      # that we want to include pre-release using the pattern >=0.0.0-0
      pattern: '>=0.0.0-0'
```

</details>

<details><summary>manifest.tpl</summary>

```
{{ $github := .github }}

{{ range $id, $app := .apps }}
---
name: 'Bump container {{ $id }} tag'
pipelineid: apps
sources:
  default:
    name: Get latest tag for {{ $app.image }}
    kind: dockerimage
    spec:
      image: '{{ $app.image }}' 
      {{ if $app.tagfilter }}
      tagfilter: '{{ $app.tagfilter }}' 
      {{ end }}
      {{ if $app.versionfilter }}
      versionfilter:
        kind: '{{ $app.versionfilter.kind }}' 
        {{ if $app.versionfilter.pattern }}
        pattern: '{{ $app.versionfilter.pattern }}' 
        {{ end }}
      {{ end }}

targets:
  manifest:
    name: 'Update {{ $id }} /manifest.yaml'
    kind: yaml
    scmid: kubernetes-marketplace
    spec:
      file: '{{ $id }}/manifest.yaml'
      key: $.version
  
  app:
    name: 'Update {{ $app.dir }}/app.yaml'
    kind: file
    scmid: kubernetes-marketplace
    spec:
      file: '{{ $id }}/app.yaml'
      matchpattern: 'image: {{ $app.image }}:(.*)'
      replacepattern: 'image: {{ $app.image }}:{{ source "default" }}' 

# Define git repository configuration to know where to push changes
# Values are templated and provided via the values.yaml so we can easily 
# adapt to the repository owner.
scms:
  kubernetes-marketplace:
    kind: "github"
    spec:
      user: "{{ $github.user }}" 
      email: "{{ $github.email }}" 
      owner: "{{ $github.owner }}" 
      repository: "{{ $github.repository }}" 
      branch: "{{ $github.branch }}" 
      username: '{{ requiredEnv "UPDATECLI_GITHUB_ACTOR" }}' 
      token: '{{ requiredEnv "UPDATECLI_GITHUB_TOKEN" }}' 

actions:  
  kubernetes-marketplace:
    kind: "github/pullrequest"
    scmid: kubernetes-marketplace
    spec:
      usetitleforautomerge: true
      mergemethod: squash
      labels:
        - enhancement 
{{ end }}

```

</details>

Go template will use the apps variable defined in the values.yaml to generate one pipeline for each app
