### ISSUE TITLE
Runtime error if a pullrequest is specified without target

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#920]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If a pullrequest is specified but no target exist using the same scmid than the pullrequest, then Updatecli retuns an runtime error

```
PULL REQUESTS
=============

panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/updatecli/updatecli/pkg/core/pipeline.(*Pipeline).RunPullRequests(0xc000e2c160)
	/home/runner/work/updatecli/updatecli/pkg/core/pipeline/pullRequests.go:53 +0x197a
github.com/updatecli/updatecli/pkg/core/pipeline.(*Pipeline).Run(0xc000e2c160)
	/home/runner/work/updatecli/updatecli/pkg/core/pipeline/main.go:234 +0x3ce
github.com/updatecli/updatecli/pkg/core/engine.(*Engine).Run(0x445d600)
	/home/runner/work/updatecli/updatecli/pkg/core/engine/main.go:250 +0x57c
github.com/updatecli/updatecli/cmd.run({0x2866d94?, 0x0?})
	/home/runner/work/updatecli/updatecli/cmd/root.go:109 +0x17f
github.com/updatecli/updatecli/cmd.glob..func2(0x4413a20?, {0x286708c?, 0x4?, 0x4?})
	/home/runner/work/updatecli/updatecli/cmd/diff.go:29 +0x10a
github.com/spf13/cobra.(*Command).execute(0x4413a20, {0xc0002c4f00, 0x4, 0x4})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0x4413020)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/updatecli/updatecli/cmd.Execute()
	/home/runner/work/updatecli/updatecli/cmd/root.go:42 +0x65
main.main()
	/home/runner/work/updatecli/updatecli/main.go:8 +0x17
[1]    3751 exit 2     updatecli diff --config updatecli/updatecli.d/github-action.yaml --values 
```

This error was generated by this manifest

```
name: Get Updatecli GitHub Action Information

scms:
  github-action:
    kind: git
    spec:
      url: https://github.com/updatecli/updatecli-action.git
      branch: v2

  default:
    kind: github
    spec:
        branch: "{{ .scms.default.branch}}"
        email: "{{ .scms.default.email}}"
        owner: "{{ .scms.default.owner}}"
        repository: "{{ .scms.default.repository}}"
        token: '{{ requiredEnv "UPDATECLI_GITHUB_TOKEN" }}'
        user: "{{ .scms.default.user }}"
        username: '{{ requiredEnv "UPDATECLI_GITHUB_ACTOR" }}'
    disabled: false

sources:
  currentValue:
    name: Get Latest Updatecli used by Github Action Version
    kind: yaml
    spec:
      file: action.yaml
      key: inputs.version.default
    scmid: github-action

  expectedValue:
    name: Get Latest Updatecli Version
    kind: githubrelease
    spec:
      owner: Updatecli
      repository: updatecli
      username: '{{ requiredEnv "UPDATECLI_GITHUB_ACTOR" }}'
      token: '{{ requiredEnv "UPDATECLI_GITHUB_TOKEN" }}'

targets:
  currentVersion:
    name: Ensure Data.json is up to date with currentValue
    kind: json
    # scmid: default
    sourceid: currentValue
    spec:
      file: public/data.json
      key: ".projects.(.name=Updatecli).apps.(.name=Github Action).currentValue"

  expectedVersion:
    name: Ensure Data.json is up to date with expectedValue
    kind: json
    # scmid: default
    sourceid: expectedValue
    spec:
      file: public/data.json
      key: ".projects.(.name=Updatecli).apps.(.name=Github Action).expectedValue"

pullrequests:
  default:
    title: '[updatecli] Update Github Action information'
    kind: github
    spec:
      automerge: true
      labels:
        - skip-changelog
    scmid: default
```

### Expected Behavior

This [line](https://github.com/updatecli/updatecli/blob/da79486a36088036e7d970f86720d598cd5b2085/pkg/core/pipeline/pullRequests.go#L24) should detects if `relatedTargets` is an empty array, then it continue to the next loop iteration.

### Environment

```markdown
- OS: linux
- updatecli: 0.35.1
```
