### ISSUE TITLE
command execution doesn't seem to work for complex commands

### ISSUE THREAD

**Issue by JayDoubleu** [updatecli/updatecli#942]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Command either doesn't execute properly or executes in an odd way

### Expected Behavior

Complex commands should execute properly

### Steps To Reproduce

```
version: 0.33.3

sources:
  latestVersion:
    kind: shell
    name: Get latest version
    spec:
      command: >-
        curl -s https://api.github.com/repos/updatecli/updatecli/releases | grep tag_name | cut -d "\"" -f 4| sort -V | tail -n1
      versionfilter:
        kind: semver
    transformers:
      - findsubmatch:
          pattern: v((\d+\.)?(\d+))?(\*|\.\d+)
          captureindex: 1
```

Output:

```
+ PIPELINE +
++++++++++++



#############
# TEST.YAML #
#############


SOURCES
=======

latestVersion
-------------
The shell 🐚 command "curl -s https://api.github.com/repos/updatecli/updatecli/releases | grep tag_name | cut -d \"\\\"\" -f 4| sort -V | tail -n1" ran successfully with the following output:
----
curl 7.79.1 (x86_64-redhat-linux-gnu) libcurl/7.79.1 OpenSSL/1.1.1n-fips zlib/1.2.11 brotli/1.0.9 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.45.1 OpenLDAP/2.4.59
Release-Date: 2021-09-22
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
----

⚠ empty source returned

=============================

REPORTS:


- TEST.YAML:
        Source:
                ⚠ [latestVersion] Get latest version (kind: shell)
```

### Environment

```markdown
- OS:
- updatecli:
```

**Comment by olblak** [comment]
Thanks for opening this issue as it triggered use cases that I didn't think about initially.

First, you are right that the shell resource could be improved. Meanwhile, the way we usually go, is to put all the logic in a script and then call the script from updatecli like [here](https://github.com/updatecli/updatecli/blob/main/updatecli/updatecli.d/golang.yaml#L23L30)

Secondly it seems that you need to manipulate a remote json file, so you could have something like 

```
sources:
  latestVersion:
    kind: json
    name: Get latest version
    spec:
      file: https://api.github.com/repos/updatecli/updatecli/releases
      key: '.[0].tag_name'
    transformers:
      - findsubmatch:
          pattern: v((\d+\.)?(\d+))?(\*|\.\d+)
          captureindex: 1
```
The Json resource relies on Dasel which provide some advanced query mechanism, more on https://daseldocs.tomwright.me/selectors/search

The first element of the array is the latest release but of course the risk in your case would be someone releasing something not semver compliant. 🤷🏾 
So I could easily imagine a manifest like 
```
  # Not working at this time
  semverVersion:
    kind: json
    name: Get latest version
    spec:
      file: https://api.github.com/repos/updatecli/updatecli/releases
      key: ".[*].tag_name"
      multiple: true
      versionfilter:
        kind: semver
    transformers:
      - trimPrefix: "v"
```
Where `versionfilter` could be used if `multiple` is set to true
The later scenario could be easily implemented in a hour or two
 combined with the multiple results return from the key ".[*].tag_name" the `versionfilter` could be super useful.
