### ISSUE TITLE
Feature Request: Allow the xml resource to query multiple elements 

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#945]
### Is your feature request related to a problem?

While discussing in https://github.com/updatecli/updatecli/issues/942

I realized that it would be super nice to be able to query multiple elements at once.
So condition and targets should be able to update multiple element and the source should be able to use versionFilter to apply advanced filtering 

### Solution you'd like

```
sources:
  parentVersion:
    name: Get parent version from pom.xml
    kind: xml 
    spec:
      file: library.xml
      multiple: true
      path: "./bookstore/book[*]/title"

conditions:
  parentVersion:
    name: Check book title 
    kind: xml 
    spec:
      file: library.xml
      multiple: true
      path: "./bookstore/book[*]/title"
      values: bob

targets:
  parentVersion:
    name: Update book title
    kind: xml 
    spec:
      file: library.xml
      multiple: true
      path: "./bookstore/book[*]/title"
      values: bob
```
