### ISSUE TITLE
Feature Request: Support multiple architectures in conditions for Docker images/digest

### ISSUE THREAD

**Issue by dduportal** [updatecli/updatecli#962]
### Is your feature request related to a problem?

- I have a Dockerfile which can be built for multiple architectures (`linux/amd64`, `linux/armd64`, etc.) with a `docker-bake.hcl` file (e.g. building all images with only 1 command:`docker buildx bake ....`).
- I want to track, with updatecli, the tag of the (multi-architecture) base image (`FROM image:<tag>`). With a "source from github -> condition on the docker image -> target on dockerfile).
- I would like to only specify once the condition for my image. Currently it looks like the snippet below:

```yaml
--- 
#...

sources:
  lastVersion:
    # ....

conditions:
    checkDebianDockerImageAmd64:
      kind: dockerimage
      disablesourceinput: true
      spec:
        architecture: amd64
        image: eclipse-temurin
        tag: '{{source "lastVersion" }}-jdk-focal'
    checkDebianDockerImageArm64:
      kind: dockerimage
      disablesourceinput: true
      spec:
        architecture: arm64
        image: eclipse-temurin
        tag: '{{source "lastVersion" }}-jdk-focal'
    checkDebianDockerImages390x:
      kind: dockerimage
      disablesourceinput: true
      spec:
        architecture: s390x
        image: eclipse-temurin
        tag: '{{source "lastVersion" }}-jdk-focal'
    checkDebianDockerImagesArmv7:
      kind: dockerimage

      disablesourceinput: true
      spec:
        architecture: arm/v7
        image: eclipse-temurin
        tag: '{{source "lastVersion" }}-jdk-focal'

# ...
```

### Solution you'd like

New attribute `architectures` which expect a list of string for the conditions on dockerimage and eventually dockerdigest:

```
conditions:
    checkDebianDockerImageAmd64:
      kind: dockerimage
      disablesourceinput: true
      spec:
        architectures:
          - amd64
          - arm64
          - s390x
          - arm/v7
        image: eclipse-temurin
        tag: '{{source "lastVersion" }}-jdk-focal'
```

### Alternatives you've considered

Templating YAML (:'( )
