### ISSUE TITLE
Feature Request: Add docker-compose autodiscovery

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#975]
### Is your feature request related to a problem?

I would like to be able to automatically update the content of my docker compose file

### Solution you'd like

In the context of the autodiscovery feature I want to look for each files matching pattern

* docker-compose.yaml
* docker-compose.*.yaml
* docker-compose.yml
* docker-compose.*.yml

Then for each of them, I am looking for each service image such as 

```
services:
  mongodb:
    image: mongo:6.0.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
```

If an image contains a tag then we generate the following manifest (in memory), before applying it

```
name: Bump "mongo" Docker compose service image version for "testdata/docker-compose.yaml"
pipelineid: 9a35e08be3b34bc912c977b3510a1130
sources:
    mongodb:
        name: Get latest "mongo" Docker Image Tag
        kind: dockerimage
        spec:
            image: mongo
            versionfilter:
                kind: semver
targets:
    mongodb:
        name: Bump "mongo" Docker Image tag for docker compose file "testdata/docker-compose.yaml"
        kind: yaml
        transformers:
            - addprefix: 'mongo:'
        spec:
            file: /home/olblak/Projects/Updatecli/updatecli/pkg/plugins/autodiscovery/dockercompose/testdata/docker-compose.yaml
            key: services.mongodb.image
        sourceid: mongodb
```

I am still annoyed that by default we fallback to versionFilter "semver"
I would like something smarter 

such as using semver only if it's strict semver otherwise using the closest regular expression matching the tag

**Comment by dduportal** [comment]
🤔 could you clarify ? What do you want to update that cannot be done using a yaml resource ?

**Comment by olblak** [comment]
Well I opened this issue a bit in the hurry and I agree I should have detailed it a bit more.
Let's me detail what I am looking for

**Comment by dduportal** [comment]
Thanks for updating the issue @olblak !

> I am still annoyed that by default we fallback to versionFilter "semver"
> I would like something smarter
> such as using semver only if it's strict semver otherwise using the closest regular expression matching the tag

That make a lot of sense!

**Comment by dduportal** [comment]
Some cases that you might meet after the initial implementation:

- (might be more general to the auto-dsicovery) How to exclude a specific item in the docker-compose files found?
- Support of other CPU architectures for Linux
- Support of Windows images
- Case of an image having both `build` and `image`fields (could be excluded or not)

**Comment by olblak** [comment]
Thanks @dduportal for your feedback.

> (might be more general to the auto-dsicovery) How to exclude a specific item in the docker-compose files found?

That's something that bother me for the other autodiscovery plugin as well and I don't think there is a way to make that generic.
Right now I decided to only allow/ignore per path such as 

```
autodiscovery:
  # scmid is applied to all crawlers
  scmid: epinio
  crawlers:
    helm:
      # To ignore specific path
      #ignore:
      #  # - path: <filepath relative to scm repository>
      #  # - path: chart/*
```

I am assuming that I ignore a specific file and whithin that file write manifest.
But we could still improve the situation later one.

> Support of other CPU architectures for Linux
> Support of Windows images

Those information are not provided in the docker compose file, and I can't rely on the machine where we run Updatecli to detect those information, so to be honest I don't know how to handle it.

> Case of an image having both build and imagefields (could be excluded or not)
In my understanding the build image receive a dockerfile so we should implement a dockerfile plugin for autodiscovery

**Comment by dduportal** [comment]
> > (might be more general to the auto-dsicovery) How to exclude a specific item in the docker-compose files found?
> 
> That's something that bother me for the other autodiscovery plugin as well and I don't think there is a way to make that generic. Right now I decided to only allow/ignore per path such as
> 
> ```
> autodiscovery:
>   # scmid is applied to all crawlers
>   scmid: epinio
>   crawlers:
>     helm:
>       # To ignore specific path
>       #ignore:
>       #  # - path: <filepath relative to scm repository>
>       #  # - path: chart/*
> ```
> 
> I am assuming that I ignore a specific file and whithin that file write manifest. But we could still improve the situation later one.

Make sense. But in the case of my docker-compose files that I'm trying to test with this auto-discovery features, the grain is at "service" level. I got 1 service in my `docker-compose.yml` file that I do NOT want updated, of the 3 services.

```yaml
# docker-compose.yml
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    # ...
  jenkins-agent:
    image: jenkins/ssh-agent:jdk17
    # ...

  ## I do not want to update the image of this service
  custom-app:
    image: localhost:5000/myimage@sha256:<whatever>
    # ...
```

WDYT about something like this (based on the snippet you shared):

```yaml
autodiscovery:
# ...
  crawlers:
    docker-compose:
      ignore:
        - path: ./docker-compose.yml
          # Optional
          services:
            - custom-app
```

**Comment by dduportal** [comment]
> > Support of other CPU architectures for Linux
> > Support of Windows images
> 
> Those information are not provided in the docker compose file, and I can't rely on the machine where we run Updatecli to detect those information, so to be honest I don't know how to handle it.

These informations exist in the compose file specification through the `platform`: https://docs.docker.com/compose/compose-file/#platform.
You can assume that it is `linux/amd64` by default but if the service has a `platform` attribute then you have to use it (otherwise it is a bug from user point of view :) ).

**Comment by olblak** [comment]
> These informations exist in the compose file specification through the `platform`: https://docs.docker.com/compose/compose-file/#platform.

Thanks for the information, I'll implement the architecture change but I think at the moment the dockerimage plugin only works for linux and would recquire minor changes in the dockerimage plugin first

**Comment by olblak** [comment]
Regarding your service request, it makes sense to me and I can do the extra mile but I would still wondering on the logical operator.
Could tell me how you understand the following snippet 


```
autodiscovery:
# ...
  crawlers:
    docker-compose:
      ignore:
        - path: ./docker-compose.yml
          services:
            - custom-app
```
```
autodiscovery:
# ...
  crawlers:
    docker-compose:
      ignore:
        - path: ./docker-compose.yml
        - services:
            - custom-app
```
