### ISSUE TITLE
Feature Request: Add versionfilter to target

### ISSUE THREAD

**Issue by olblak** [updatecli/updatecli#976]
### Is your feature request related to a problem?

I would like to be able to only update a target if a version rule is matching. 
For example I would like to only update patch version for target relying on semantic versioning.
Or I would like to assign automerge to pullrequest created by a minor version change.

### Solution you'd like

I would like to only update a target if the new value match in the versionfilter constraint.

```
targets:
  jenkins-wiki-exporter:
    kind: yaml
    spec:
      file: "example.yaml"
      key: "image.tag"
      versionFilter:
        kind: semver
        pattern: "~1.10"
```

### Alternatives you've considered

I have been considering adding new condition to test versionconstraint but I think it will be a bit expressive and would required refactoring

### Anything else?

While I don't have current usecase, I think it could also be implemented for condition too
